- backend/package.json
to allow synchronous zipping of files from problems
> added adm-zip package 

- frontend/require/MTFClient.js
- frontend/require/MTFServer.js
This fixes a bug in grading multiple True/False where the trueAnswer wasn't randomized with the studentAnswer.
> Fix bug in grading multi t/f

- frontend/require/app.js
Fixes loading on case-sensitive filesystems.
> Match case of jsPlumb with file name

- backend/server.js
- frontend/require/QuestionDataModel.js
> Get trueAnswer from qInstance instead of submission. Closes #193.

- doc/faq.md
- doc/writingTests.md
> Document the Reload button

- frontend/require/RetryExamTestInstanceView.html
> Update grade/finish button and modal text.

- frontend/require/RetryExamTestSidebarView.html
> Remove current exam score from sidebar.

- backend/config.js
- backend/logger.js
- backend/server.js
Start splitting up server into multiple files
> Modularize

- frontend/require/QuestionAnswerView.js
- frontend/require/QuestionView.js
- frontend/require/SimpleClient.js
> Expose appModel to AnswerView.

- frontend/require/RetryExamTestInstanceView.html
- frontend/require/RetryExamTestInstanceView.js
> Warn user when submitting with unanswered questions.

- frontend/require/RetryExamTestSidebarView.html
- frontend/require/RetryExamTestSidebarView.js
> Prompt user to finish exam when every question has been answered.

- frontend/require/NavView.html
- frontend/require/NavView.js
> Don't overshoot the viewport

- backend/BasicTestServer.js
- backend/ExamTestServer.js
- backend/GameTestServer.js
- backend/RetryExamTestServer.js
- backend/require-frontend.js
- backend/server.js
This required refactoring all *TestServer.js files to be CommonJS modules instead of AMD modules. In the future, we should limit AMD modules to frontend code only, as AMD modules can only require other
frontend modules and not backend modules, which is severely limiting for backend code.
This also modifies `updateWithSubmission()` to be asynchronous.
Closes #307.
> Disallow multiple submissions for an Exam/Game qInstance.

- backend/server.js
> Remove BAD-ness from server.js.

- backend/server.js
Addresses [this comment](https://github.com/PrairieLearn/PrairieLearn/pull/331/files#r59488430) on #331.
> Allow for existence of clientTemplates without clientFiles.

- frontend/require/MTFClient.js
> Make mtfclient listen to specific class instead of global checkboxes

- frontend/css/local.css
Prevent "Save answer" button from touching the bottom edge of the page
> Better-looking margin for "Save answer" buttons

- v2/sql-loader.js
> Generalize line-splitting

- v2/doc/installing.md
Update the docker commands, as well as remove documentation related to the `/admin` path, since it does not exist.
> Update installing.md for v2

- v2/pages/adminQuestion/adminQuestion.ejs
- v2/pages/adminQuestion/adminQuestion.js
adminQuestion.js : remove renderScore call, and hack submission array to
work with new submission rendering.
adminQuestion.ejs : move submission box below true answer, to match
userInstanceQuestionHomework formatting.
> Fix adminQuestion submission render

- tools/assess-convert.py
Simple assessment conversion script, added into tools directory.
> Assessment conversion script.

- tools/assess-convert.py
> Assessment convert

- doc/clientServerFiles.md
Match those used in the implementation (and those directories not yet implemented).
> Fix serverFiles naming in docs

- doc/docker.md
- doc/installing.md
- doc/uuid.md
Also some various Docker-related-docs updates.
> Detail how to run generate_uuids.py with Docker

- doc/contributing.md
Feel free to merge only the first one :)
> Update contribution docs

- pages/studentInstanceQuestionExam/studentInstanceQuestionExam.js
> Show feedback in exam when open

- pages/instructorAssessment/instructorAssessment.ejs
- pages/instructorAssessment/instructorAssessment.js
- pages/instructorAssessment/instructorAssessment.sql
- public/localscripts/parallel_histograms.js
Did the plotting part of this exercise, but haven't done the CSV yet. Do I need to write code to create the csv file?
> First commit for 402 day by day score plot

- exampleCourse/questions/addVectors/submission.html
- public/localscripts/calculationQuestion/SimpleClient.js
- public/localscripts/questionCalculation.js
This should resolve #589 (and by extension #604 and #605)
> Send feedback to renderSubmission

- doc/externalGrading.md
- exampleCourse/questions/fibonacciEditor/client.js
Forgot to include this in #638. We need unit tests :)
> Fixed file answer key in editor example

- models/index.js
Didn't realize I forgot to push this.
> Adds error checking to file load

- webhooks/grading/grading.js
A temporary fix for the fact that we don't yet have a unified and robust system for handling grading results from both S3 and local jobs.
> Fixed issue with processing failed grading jobs

- exampleCourse/questions/multiplyTwoNumbers/question.html
- question-servers/elements/answer_panel.py
- question-servers/elements/index.js
- question-servers/elements/submission_panel.py
There seems to still be a bug in handlebars templating in freeform questions. See the multiplyTwoNumbers question created in this PR for an example.
> created answer and submission panel

- environments/centos7-base/main.py
- environments/centos7-ocaml/main.py
Switch from blacklisting all environment variables to whitelisting only the ones we want.
There was also a bug that caused docker images to crash while running in a local dev environment because we were assuming that `webhook_url` would always be defined in the `info` context object, which isn't the case in dev mode.
> Use environment variable whitelist for grading process

- exampleCourse/questions/multiplyTwoNumbers/question.html
- exampleCourse/questions/multiplyTwoNumbers/server.py
- exampleCourse/questions/positionTimeGraph/question.html
- question-servers/elements/matrix_input.py
- question-servers/elements/number_input.py
- Display attribute in number_input to enable inline vs block.
- Escape HTML for rendering raw_submitted_answer in number_input.
- Three methods of comparison in number_input.
- Updated examples that use number_input.
- Popovers to provide information about required format in number_input.
- Various bug fixes and improvements to number_input and matrix_input.
> updates to number_input and matrix_input

- question-servers/elements/format.mustache
- question-servers/elements/matrix_input.mustache
- question-servers/elements/matrix_input.py
**NOTE** For templating to work, it is necessary to install [chevron](https://github.com/noahmorrison/chevron), a python implementation of mustache. This can be done with pip.
> added mustache templating to matrix_input element

- pages/studentAssessments/studentAssessments.ejs
> Warns students about PS/PL linkage in exam assessment list

- lib/question.js
This should fix the issues that Elsa and Mariana are having in #747 and #750
> fix broken v2 question links by adding trailing / urls

- database/tables/instance_questions.pg
- exampleCourse/courseInstances/Sp15/assessments/exam1/infoAssessment.json
- lib/question.js
- migrations/077_instance_questions__highest_submission_score__add.sql
- pages/partials/examQuestionAvailablePoints.ejs
- pages/partials/examQuestionAwardedPoints.ejs
- pages/partials/examQuestionHelpAvailablePoints.ejs
- pages/partials/examQuestionHelpAwardedPoints.ejs
- pages/partials/examQuestionHelpBestSubmission.ejs
- pages/partials/examQuestionScore.ejs
- pages/partials/examQuestionStatus.ejs
- pages/partials/question.ejs
- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs
- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.js
- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.sql
- pages/studentInstanceQuestionExam/studentInstanceQuestionExam.ejs
- public/stylesheets/local.css
- sprocs/grading_jobs_insert_internal.sql
- sprocs/grading_jobs_process_external.sql
- sprocs/instance_questions_grade.sql
- sprocs/instance_questions_points.sql
- sprocs/instance_questions_points_exam.sql
- sprocs/instance_questions_points_homework.sql
- sprocs/instance_questions_update_in_grading.sql
- tests/testAccess.js
- tests/testAccess.sql
- tests/testExam.js
- tests/testExam.sql
This does away with the "Finish assessment" and "Grade assessment" buttons on the assessment overview page for Exams. Instead the question pages now have a Grade button.
> Exam grading via question pages, not via assessment page

- environments/centos7-cs225/Dockerfile
This just adds make, clang, and gcc to the `centos7-base` image.
> Add centos7-cs225 Dockerfile

- exampleCourse/infoCourse.json
- exampleCourse/questions/addNumbers/info.json
- exampleCourse/questions/addVectors/info.json
- exampleCourse/questions/ballToss2/info.json
- exampleCourse/questions/customElement/info.json
- exampleCourse/questions/differentiatePolynomial/info.json
- exampleCourse/questions/downloadFile/info.json
- exampleCourse/questions/fibonacciEditor/info.json
- exampleCourse/questions/fibonacciUpload/info.json
- exampleCourse/questions/fibonacciUploadManual/info.json
- exampleCourse/questions/fossilFuelsRadio/info.json
- exampleCourse/questions/functionValueFromPlot/info.json
- exampleCourse/questions/multiplyTwoMatrices/info.json
- exampleCourse/questions/multiplyTwoNumbers/info.json
- exampleCourse/questions/partialCredit1/info.json
- exampleCourse/questions/partialCredit2/info.json
- exampleCourse/questions/partialCredit3/info.json
- exampleCourse/questions/partialCredit4_v2/info.json
- exampleCourse/questions/positionTimeGraph/info.json
To help identify new vs old example question types
> Adds tags for v2 or v3

- database/tables/questions.pg
- elements/pl_external_grader_results/pl_external_grader_results.mustache
- elements/pl_external_grader_results/pl_external_grader_results.py
- exampleCourse/questions/fibonacciEditor/info.json
- lib/config.js
- lib/externalGrader.js
- lib/externalGraderCommon.js
- lib/externalGraderLocal.js
- lib/externalGraderSqs.js
- migrations/084_questions__timeout__add.sql
- schemas/infoQuestion.json
- schemas/serverConfig.json
- sync/fromDisk/questions.js
- sync/fromDisk/questions.sql
- webhooks/grading/grading.js
* Add optional timeouts for external grading timeouts
* Remove dependency on the script inside the Docker images
* Better error display to students
> Add support for external grading timeouts

- elements/pl_checkbox/pl_checkbox.py
- elements/pl_matrix_input/pl_matrix_input.mustache
- elements/pl_matrix_input/pl_matrix_input.py
- elements/pl_multiple_choice/pl_multiple_choice.py
- elements/pl_number_input/pl_number_input.mustache
- elements/pl_number_input/pl_number_input.py
- elements/pl_symbolic_input/pl_symbolic_input.mustache
- elements/pl_symbolic_input/pl_symbolic_input.py
- elements/pl_variable_score/pl_variable_score.py
- exampleCourse/questions/addNumbers/question.html
- exampleCourse/questions/positionTimeGraph/question.html
Elements are now responsible for displaying their own partial scores.
> Eliminate pl variable score

- lib/assessment.js
Guess I never hit this code path while testing 😄
> Fix external grader crash

- ChangeLog.md
- doc/elements.md
- elements/pl_matrix_input/info.json
- elements/pl_matrix_input/pl_matrix_input.mustache
- elements/pl_matrix_input/pl_matrix_input.py
- elements/pl_matrix_output/pl_matrix_output.mustache
- question-servers/freeformPythonLib/prairielearn.py
- tests/testQuestions.js
Students can now submit answers to `pl_matrix_input` elements either in matlab format or in python format. Also added docs and unit tests for `pl_matrix_input`, which have been missing until now.
> Add support for python in pl_matrix_input

- lib/externalGraderCommon.js
> Remove null bytes from grading results

- ChangeLog.md
- elements/pl_external_grader_results/pl_external_grader_results.py
- elements/pl_figure/pl_figure.py
- elements/pl_file_editor/pl_file_editor.py
- elements/pl_file_preview/pl_file_preview.py
- elements/pl_file_upload/pl_file_upload.py
- elements/pl_matrix_input/pl_matrix_input.py
- elements/pl_matrix_output/pl_matrix_output.py
- elements/pl_number_input/pl_number_input.py
- elements/pl_symbolic_input/pl_symbolic_input.py
> Use UTF-8 when reading element templates

- ChangeLog.md
- pages/partials/assessmentScorePanel.ejs
> Truncate assessment score to 2 decimals

- ChangeLog.md
- elements/pl_matrix_input/pl_matrix_input.mustache
- elements/pl_matrix_input/pl_matrix_input.py
- pages/courseOverview/courseOverview.ejs
- pages/instructorAssessmentInstance/instructorAssessmentInstance.ejs
- pages/instructorAssessments/instructorAssessments.ejs
- pages/studentAssessmentExam/studentAssessmentExam.ejs
- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs
- pages/studentAssessments/studentAssessments.ejs
- public/stylesheets/local.css
A few more small improvements
* Use badges instead of button styles when showing colored assessment labels
* Fix a broken popover in `pl_matrix_input`
> More BS4 fixes

- ChangeLog.md
- elements/pl_file_preview/pl_file_preview.mustache
- pages/partials/question.ejs
- pages/partials/submission.ejs
- public/stylesheets/local.css
Fixes #976. Also collapses all but the most recent submission by default to draw attention to the latest submission.
> Question card style updates

- .travis.yml
- ChangeLog.md
- tools/verify-changelog.sh
CI won't run without a PR, so I'm just going to work out the kinks here.
> Add CI check for a modified changelog

- ChangeLog.md
- elements/pl_file_upload/pl_file_upload.mustache
Minor nitpick that I noticed while testing external grading 🙂
> Fix styling of pl_file_upload element

- .travis.yml
- ChangeLog.md
Using method from https://docs.travis-ci.com/user/pull-requests/
> Only run changelog verifier on pull request builds

- ChangeLog.md
- elements/pl_threejs/pl_threejs.py
Fix bug that showed the body at the submitted position and not the correct position in the answer panel. Oops!
> Fix threejs answer bug

- doc/uuid.md
Emphasis issue w.r.t `courseInformation`.
> Improve notes on UUID changes

- ChangeLog.md
- doc/contributing.md
- elements/pl_matrix_input/pl_matrix_input.py
- exampleCourse/questions/addBinary/question.html
- exampleCourse/questions/addBinary/server.py
- tests/testQuestions.js
* Add a number of existing questions to the unit tests.
* Fix a small bug in `pl_matrix_input` test.
* Fix a small bug in `addBinary` question.
* Add changelog rules to docs.
* Rewrite changelog to conform to rules.
> Add questions to test

- environments/centos7-cs225/Dockerfile
Added valgrind to the docker image.
> Updated dockerfile for CS 225 Docker Image

- ChangeLog.md
- pages/partials/navbar.ejs
- pages/partials/navbarCourse.ejs
- pages/partials/navbarInstructor.ejs
- pages/partials/navbarPlain.ejs
- pages/partials/navbarStudent.ejs
- Refactors duplicate code out to `navbar.ejs`
- Fixes role and mode display for instructors
- Allows deep linking from assessment or question when switching modes, where possible
Closes #1040
> Navbar improvements

- ChangeLog.md
- cron/sendExternalGraderStats.js
- sprocs/grading_jobs_stats_day.sql
fixes PrairieLearn/PrairieGrader#25
> fix external grader stats by splitting out received_at

- exampleCourse/infoCourse.json
> Minor typo

- exampleCourse/serverFilesCourse/python_autograder/pltest.py
would add a changelog to avoid build failure if I knew how
> Typo in comment

- ChangeLog.md
- cron/index.js
- cron/index.sql
- database/tables/cron_jobs.pg
- database/tables/named_locks.pg
- lib/named-locks.js
- lib/named-locks.sql
- migrations/107_named_locks__create.sql
- migrations/108_cron_jobs__create.sql
- migrations/index.js
- sprocs/index.js
- sync/syncFromDisk.js
> Add locking to enable multi-server deployments

- ChangeLog.md
- pages/partials/submissionInfoModal.ejs
> fix render when exernally-gradable submission is not yet graded

- ChangeLog.md
- doc/howToLearnNames.md
- lib/data-files.js
- lib/externalGraderCommon.js
- lib/question.js
- tests/helperQuestion.js
- tests/testAccess.js
- tools/external-grading-load-test/main.js
- tools/load-test.js
I ran `grep -rHn "new Buffer"` and changed each instance outside the `node_modules` folder (I think(?) these others will get cleaned up whenever the module versions are updated).
Fixes #1168
> Change "new Buffer(" to "Buffer.from("

- ChangeLog.md
- exampleCourse/courseInstances/Sp15/assessments/exam1/infoAssessment.json
- middlewares/studentAssessmentAccess.js
- pages/authPassword/authPassword.ejs
- pages/authPassword/authPassword.js
- pages/studentAssessmentExam/studentAssessmentExam.ejs
- pages/studentAssessmentExam/studentAssessmentExam.js
- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs
- server.js
- tests/testAccess.js
- Protect all assessment pages with a password (stored in a cookie)
- Add option to "Finish exam" on password protected assessment overview page
- Disable viewing of closed assessment, even with password
> Assessment password revamp

- ChangeLog.md
- exampleCourse/courseInstances/Sp15/assessments/passwordexam/infoAssessment.json
- middlewares/studentAssessmentAccess.ejs
- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs
- server.js
Should have been only SEB and password protected exams.
Adds an example course exam with a password.
> Fixes "Finish exam" button showing up in all exams

- ChangeLog.md
- doc/PrairieDraw.md
- doc/course.md
- doc/elements.md
- elements/pl-prairiedraw-figure/info.json
- elements/pl-prairiedraw-figure/pl-prairiedraw-figure.mustache
- elements/pl-prairiedraw-figure/pl-prairiedraw-figure.py
- exampleCourse/infoCourse.json
- exampleCourse/questions/examplePrairieDrawFigure/PDelementDemo.js
- exampleCourse/questions/examplePrairieDrawFigure/info.json
- exampleCourse/questions/examplePrairieDrawFigure/mysteryShape.js
- exampleCourse/questions/examplePrairieDrawFigure/question.html
- exampleCourse/questions/examplePrairieDrawFigure/server.py
This is an incomplete list of drawing functions available to PrairieDraw users, mainly written for the TAM 2XX summer development staff.
> Add (incomplete) PrairieDraw documentation

- ChangeLog.md
- middlewares/selectAndAuthzAssessment.js
- middlewares/selectAndAuthzAssessmentInstance.js
- middlewares/selectAndAuthzInstanceQuestion.js
- middlewares/selectAndAuthzInstructorQuestion.js
- tests/testAccess.js
I ran into this error again recently, so might as well PR and make it more descriptive.
Closes #1221
> [Ready to merge] Access denied error rather than "Incorrect row count"

- ChangeLog.md
- lib/cache.js
> Fix cache callback when cache is disabled

- ChangeLog.md
- environments/centos7-plbase/Dockerfile
- package-lock.json
- package.json
Make `npm audit` happy with the vulnerability status of our dependencies. The banner in GitHub is an effective prod to action, I guess.
Also absorbed into the Docker environment what I usually do when developing locally with docker - give the root user superuser access to the database.
> Package updates and docker postgres config change

- ChangeLog.md
- doc/elements.md
Adding documentation for the attribute `placeholder` in `pl-string-input`
> edit element documentation

- ChangeLog.md
- environments/centos7-python/requirements.txt
Figured this out in the office hours
> Add Pillow for CS357

- ChangeLog.md
- public/javascripts/PrairieDraw.js
Very silly bug :-(
Just added an if statement to check against division by zero.
Closes #1262
> fixed function to avoid division by zero

- ChangeLog.md
- lib/course-db.js
- package-lock.json
- tests/testLoadCourse.js
- tests/testLoadCourse/brokenCourse/courseInstances/Fa18/assessments/quiz1/placeholder.txt
- tests/testLoadCourse/brokenCourse/courseInstances/Fa18/infoCourseInstance.json
- tests/testLoadCourse/brokenCourse/infoCourse.json
- tests/testLoadCourse/brokenCourse/questions/basicV3/question.html
Adds JS validation of assessment and question files based on `lib/course-db:checkInfoValid`
Adds allowAccess startDate and endDate checking (closes #684)
Fixes return logic bugs in loops
Adds tests for these conditions
> Assessment and question JSON validation

- ChangeLog.md
- doc/faq.md
> Add section on common pl errors to FAQ

- ChangeLog.md
- environments/centos7-plbase/Dockerfile
- environments/centos7-plbase/python-requirements.txt
- environments/centos7-python/Dockerfile
- environments/centos7-python/requirements.txt
> Add GraphViz dependency to Python, CentOS

- ChangeLog.md
- package-lock.json
- package.json
This resolves the automated warnings from GitHub and npm about vulnerabilities in our dependencies.
> Fix vulnerabilities

- ChangeLog.md
- doc/devElements.md
I've made updates to this doc page for elements, in particular about the dependencies property, based on the schemas. Can someone please check that it's correct?
> Update doc for element dependencies

- ChangeLog.md
- elements/pl-checkbox/pl-checkbox.py
> Warn if pl-checkbox partial-credit-method is set but partial-credit is disabled

- ChangeLog.md
- cron/sendExternalGraderDeadLetters.js
> Fix dead letter cron job for async v3

- ChangeLog.md
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.ejs
Initially reported by @mfsilva22 in Slack.
> Correct wording on assessment download options associated with points.

- ChangeLog.md
- lib/python-caller-trampoline.py
> Fix KeyboardInterrupt errors when Ctrl-C'ing

- ChangeLog.md
- doc/elements.md
- elements/pl-hide-in-panel/info.json
- elements/pl-hide-in-panel/pl-hide-in-panel.py
- exampleCourse/courseInstances/Sp15/assessments/plelementexamples/infoAssessment.json
- exampleCourse/questions/examplesMatrixComponentInput/question.html
- exampleCourse/questions/examplesPanels/info.json
- exampleCourse/questions/examplesPanels/question.html
- exampleCourse/questions/examplesVariableOutput/question.html
- tests/testQuestions.js
> Add <pl-hide-in-panel> element.

- ChangeLog.md
- Dockerfile
- environments/centos7-plbase/Dockerfile
- lib/externalGrader.js
A few small changes to help troubleshooting Windows and docker external grading.
> external grading stack traces and docker debugging

- ChangeLog.md
- environments/centos7-plbase/python-requirements.txt
> Add tzlocal as a python library under core

- environments/centos7-plbase/r-requirements.R
add R package kableExtra for much easier html table creation
> add R package kableExtra

- ChangeLog.md
- graders/python/Dockerfile
- graders/python/requirements.txt
Adding:
- `scikit-image`
- `scikit-learn`
- `requests`
- `folium`
- `colormath`
- `nltk`
- `beautifulsoup4`
- `bokeh`
> Add libraries for CS199 Data Science w/ Python external grader

- lib/cache.js
- lib/externalGrader.js
- lib/externalGraderLocal.js
- lib/externalGraderResults.js
- lib/externalGradingSocket.js
- lib/json-load.js
- lib/ltiOutcomes.js
- lib/redis.js
> Fix logging that uses a plain JavaScript object

- ChangeLog.md
- tests/index.js
- tests/testLti.js
- tests/testLti.sql
Adds a few tests to make sure LTI works as expected
> Add LTI tests

- ChangeLog.md
- server.js
> Increase size limit for uploading form data

- news_items/002_in_browser_editing/index.html
> Fix news item to remove easy question deletion

- question-servers/freeform.js
- server.js
> Fix course element script access for instructors

- ChangeLog.md
- pages/instructorGradebook/instructorGradebook.ejs
- pages/instructorQuestionStatistics/instructorQuestionStatistics.ejs
This PR fixes the gradebook and question statistics download links.
Fixes #2005 
Fixes #2057
> Fix csv links

- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql
- pages/instructorAssessments/instructorAssessments.sql
- sprocs/base64_safe_decode.sql
- sprocs/index.js
> Fix file downloads that have invalid base64 contents

- pages/instructorAssessmentQuestionStatistics/instructorAssessmentQuestionStatistics.ejs
- pages/instructorAssessmentQuestionStatistics/instructorAssessmentQuestionStatistics.js
- pages/instructorAssessmentQuestionStatistics/instructorAssessmentQuestionStatistics.sql
- pages/instructorQuestionStatistics/instructorQuestionStatistics.ejs
- pages/instructorQuestionStatistics/instructorQuestionStatistics.js
- pages/instructorQuestionStatistics/instructorQuestionStatistics.sql
- sprocs/assessment_questions_calculate_stats.sql
> Add QID to question stats CSVs and standardize columns

- doc/installing.md
Webstore is sort of hard to navigate, so this should just make the setup process easier at HackIllinois.
> Made direct link to the webstore for Win10 Edu

- pages/news_items/news_items.ejs
- pages/partials/navbar.ejs
Changed the span class for news-items in the navbar and new-items to use badge-primary instead of badge-danger.
> Changed news notifications from danger to primary in navbar (#2907 #2102)

- pages/instructorQuestions/instructorQuestions.ejs
- pages/instructorQuestions/instructorQuestions.sql
- pages/partials/question.ejs
- pages/partials/types.ejs
> Version Selecting with color, issue #2106

- tools/converters/smart-physics/smartphysics-to-pl.py
This is slightly hacky but hopefully can be a good starting point for a more complete converter.
> Added a smartphysics to prairielearn converter.

- pages/authCallbackShib/authCallbackShib.js
> Throw a more user-friendly shibboleth error

- pages/partials/questionFooter.ejs
> Fix buggy float behavior via flexbox

- doc/accessControl.md
Updated example case for a timeLimMin and close duration startDate and endDate.
> Docs: Clarify remote exam configuration

- ChangeLog.md
- exampleCourse/questions/demoRandomPlot/server.py
Upgrades the underlying matplotlib code to use appropriate subplot functions.
Close #2209
> Fix demoRandomPlot question

- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs
> Fix title placement in time expired modal

- doc/accessControl.md
- doc/remoteExams.md
- mkdocs.yml
> Add access rule examples for remote exams

- pages/partials/submissionStatus.ejs
> Clarify ungradable error message

- ChangeLog.md
- pages/partials/questionFooter.ejs
This change (from PR #2187) broke repeated submissions to externally graded questions. I'm reverting for now until we can fix it properly.
> Revert grade button double-click fix (3e7d6807)

- api/v1/endpoints/courseInstanceAssessmentInstances/index.js
- api/v1/endpoints/queries.sql
- doc/api.md
- tests/testApi.js
- tools/api_download.py
> Augment read-only API to fetch instance_question data for assessment_instance

- doc/remoteExams.md
> Fix remote exam docs to clarify auto-close behavior

- tools/question_converters/randexam/randexam2pl2.py
This PR updates the randexam python question converter script to output v3 question types.
> randexam converter updated to v3 questions

- pages/administratorQuery/administratorQuery.ejs
- pages/administratorQuery/administratorQuery.js
See #2348
This PR changes the SQL query page to use server-side highlighting with the copy of `highlight.js` in `node_modules`.
> Change to server-side SQL highlighting

- docs/externalGrading.md
PR documents PowerShell-specific commands, quirks, and errors.
Resolves #2236 
Resolves #1714
> Add clarification to external grading docs on Windows PowerShell dev

- elements/pl-code/pl-code.py
The updates to syntax highlighting broke Mariana's questions because Markdown is called `md` in Pygments as opposed to `markdown` in hljs.  It seems we can match languages based on "shortnames" (filenames, aliases, etc.) as well as their longer class names. Markdown looks like the only one with this weird issue (https://pygments.org/docs/lexers/), but hopefully this will prevent problems in the future.
> Be more forgiving with language names in pl-code

- api/v1/endpoints/courseInstanceAssessments/index.js
- api/v1/endpoints/queries.sql
- docs/api.md
- tests/testApi.js
- tools/api_download.py
Added api call for an assessment's assessment_access_rules.
> Added api call to get assessment_access_rules

- pages/partials/submissionInfoModal.ejs
> Fix course instance reference for instructor submission info

- sprocs/users_randomly_generate.sql
Fixes an array offset NULL error, and retries when duplicating an existing uid
> Bug fix for sprocs/users_randomly_generate()

- package.json
cc @astrosticks @trombonekenny
> Add .sql and remove .ejs from nodemon watch list

- elements/pl-integer-input/pl-integer-input.mustache
- elements/pl-matrix-component-input/pl-matrix-component-input.mustache
- elements/pl-matrix-input/pl-matrix-input.mustache
- elements/pl-number-input/pl-number-input.mustache
- elements/pl-string-input/pl-string-input.mustache
- elements/pl-symbolic-input/pl-symbolic-input.mustache
> Change input labels to be unescaped

- database/tables/workspaces.pg
- migrations/174_workspaces__create.sql
- migrations/177_workspaces_state__alter.sql
@mwest1066, should the state machine be `NOT NULL`?
> Change `workspaces.state` to be NOT NULL

- docs/dev-guide.md
> Add documentation on how to run individual tests

- pages/partials/questionFooter.ejs
> Fix alignment of manual grading footnote

- docs/dev-guide.md
> Add developer docs on how to add JSON properties

- pages/instructorQuestionPreview/instructorQuestionPreview.ejs
> Fix instructor preview "Student view placeholder" color

- database/tables/variants.pg
- database/tables/workspaces.pg
- migrations/179_variants_workspace_id__add.sql
> Reverse variants-workspaces FK direction

- exampleCourse/courseInstances/Sp15/assessments/exam03-bestPracticesPublic/infoAssessment.json
Exam 3 is a copy of exam 1, but available to the public instead of CBTF only.
> Create public exam 3 in exampleCourse

- lib/course-db.js
Add a new default set named "Worksheet".
> added new Set for worksheets

- docs/elements.md
> Fixing section links

- lib/question.js
Removes `/pl/[garbage]` from `workspaceUrl`.
> Remove urlPrefix from workspaceUrl

- docs/workshop/lesson1.md
Adding one more example to the documentation, to match the questions in XC 101 (#PR 2711)
> additional example to lesson 1

- admin_queries/select_or_insert_user.json
- admin_queries/select_or_insert_user.sql
> Add admin query to insert users

- exampleCourse/questions/demo/workspace/workspace/starter_code.c
- exampleCourse/questions/demo/workspace/workspace/starter_code.h
Add `workspace/starter_code.h` and `workspace/starter_code.c`
> Add boilerplate dir to workspace demo

- exampleCourse/questions/demo/studentFaces/question.html
- exampleCourse/questions/demo/studentFaces/server.py
- exampleCourse/questions/demo/studentNames/server.py
- question-servers/freeform.js
Fixes #2701 
Fixes the `demo/studentFaces` question to use `pl-figure` instead of hard coded urls and image tags.
Also adds `client_files_course_path` to `data['options']` so we don't have to do path trickery in the Python.
> Fix demo faces question

- pages/home/home.ejs
> Fix homepage spacing issues

- docs/elements.md
- elements/pl-dropdown/pl-dropdown.mustache
- elements/pl-dropdown/pl-dropdown.py
Fixes #2756 
The question panel will now show a previous submission and correct/incorrect badge.
> Fix dropdown rendering on question panel

- docs/contributing.md
Since this step is no longer required.
> remove section on "Updating the ChangeLog" in CONTRIBUTING.md

- .gitignore
- docker/start_workspace.sh
Starts dual-pane tmux with PL server in left pane and host server in right pane. Uses `/PrairieLearn/.tmux.conf` if exists.
> Add workspace launcher to docker scripts

- lib/workspace.js
- lib/workspace.sql
- workspace_host/interface.js
- workspace_host/interface.sql
For new `interface` servers:
For new containers:
> Update workspace hosts to use database

- package-lock.json
- package.json
- workspace_host/interface.js
This branch is based on workspace-async-cleanup
> Fully functioning auto syncing system

- docs/manualGrading.md
Hope this isn't overkill, just trying to make it clear how things work
> Add workspace info to manualGrading docs

- pages/workspace/workspace.ejs
- pages/workspace/workspace.js
> Add workspace reboot confirmation dialog

- cron/stopStaleWorkspaces.js
- database/tables/workspaces.pg
- lib/workspace.js
- migrations/200_workspaces__message__add.sql
- pages/workspace/workspace.ejs
- pages/workspace/workspace.js
- public/stylesheets/workspace.css
- sprocs/index.js
- sprocs/workspaces_message_update.sql
- sprocs/workspaces_state_update.sql
- workspace_host/interface.js
> Update workspace status indicator with more detailed info

- Dockerfile
Added new zip dirs to the `Dockerfile`. Leaving the rest of the transition for part 2.
> Add new workspace zip dirs to Dockerfile

- docs/workspaces/index.md
- elements/pl-workspace/pl-workspace.py
- lib/question.js
- lib/question.sql
> Add workspace grading validation for required files

- docs/admin/workspaceAutoscaling.md
- mkdocs.yml
Documents all the possible config values that can be set in the db
> Add documentation for autoscaling settings

- pages/home/home.ejs
- public/stylesheets/home.css
Resolves #2920 
* if content doesn't already fill screen
* if content already fills screen
> Update authenticated footer

- workspace_host/interface.js
Not sure this will address all the weirdness on prod, but this bug is at least part of it.
> Fix workspace S3 path

- pages/instructorRequestCourse/instructorRequestCourse.ejs
> Add TA disclaimer to course request page

- docs/workspaces/index.md
> Add workspace docs on question directory structure

- server.js
In theory this should fix #2936, but I wasn't able to get the bug to occur locally
> Fix workspace proxy uncaught error

- cron/workspacesTransition.js
- cron/workspacesTransition.sql
> Fix recording of workspace host termination

- pages/studentAssessments/studentAssessments.ejs
- pages/studentGradebook/studentGradebook.ejs
- pages/studentGradebook/studentGradebook.sql
Just a small cosmetic change. Helps to remember how you got the grade that you did.
Also added an aria label "Group work" to these icons.
> Adding icon for groupwork to student gradebook

- workspace_host/interface.js
> Add chown hook to workspace host initial unzip

- admin_queries/config_delete.json
- admin_queries/config_delete.sql
- admin_queries/config_select.json
- admin_queries/config_select.sql
- admin_queries/config_upsert.json
- admin_queries/config_upsert.sql
- admin_queries/workspace_hosts.json
- admin_queries/workspace_hosts.sql
- admin_queries/workspace_hosts_all_unhealthy.json
- admin_queries/workspace_hosts_all_unhealthy.sql
- admin_queries/workspace_hosts_update_state.json
- admin_queries/workspace_hosts_update_state.sql
- admin_queries/workspaces.json
- admin_queries/workspaces.sql
- cron/workspacesTransition.sql
- database/tables/workspace_hosts.pg
- migrations/213_workspace_hosts__state__terminated_at__create_index.sql
- workspace_host/interface.sql
I might need to add a couple of indexes to speed these queries up.
> Add admin queries for workspaces

- lib/aws.js
- lib/config.js
- lib/workspace.js
- tsconfig.json
- workspace_host/interface.js
PR #2938 partially fixed the S3 path by adding `-<workspace_version>`.
This PR fully fixes the path by also adding `/current`.
> Fix S3 path for workspace push even more

- lib/workspace.js
- workspace_host/interface.js
This is related to #2985 but doesn't fix it. Hopefully it will give us
more information about what's going wrong in that case.
> Fix workspace launch error reporting

- pages/home/home.ejs
> Fix button margins in home page contrib block

- sprocs/workspace_hosts_recapture_draining.sql
From #2935:
To return a count from an UPDATE we need to put the UPDATE into a CTE (WITH clause). Given this, it might be simpler to also make `found_draining_hosts` another CTE before the UPDATE, instead of using temporary tables.
> Refactor recaptured_hosts count using CTEs

- lib/config.js
- lib/local-cache.js
- server.js
- tests/helperServer.js
Caches `questions.workspace_url_rewrite` to address DB load issues.
> Add local cache for workspace urlRewrite query

- lib/workspace.js
- workspace_host/interface.js
Probably not strictly necessary, but just for completeness.
> Add missing version modifier to workspace zip files

- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs
> Fix missing "Finish assessment" button

- docs/course.md
> Add docs about assessment set ordering

- testCourse/courseInstances/Sp15/assessments/exam1-automaticTestSuite/infoAssessment.json
> Fix typo in testCourse exam text

- workspace_host/interface.js
Splitting this out of #3071 to help streamline review.
This bug is affecting courses with bigger `initial.zip` files because the pipe closes before everything gets extracted, e.g.:
`Sep 15 20:36:15 ip-10-0-0-20.us-east-2.compute.internal node[4195]: error: Error for workspace_id=5511: Error: ENOENT: no such file or directory, chown '/jobs/workspace-b2af8b8e-7890-4092-9fe6-997b0ba4bc73/pics/Picture18.png'`
---
_Originally posted by @tdy in https://github.com/PrairieLearn/PrairieLearn/pull/3071#discussion_r487578857_:
I believe this comment from the `unzipper` author confirms that the basic async iterator won't work for our use case (parallel or not). From https://github.com/ZJONSSON/node-unzipper/issues/138#issuecomment-506376795:
> The problem is that the pipe chain finishes when the zip …
> Fix workspace initial unzip

- pages/courseSyncs/courseSyncs.ejs
> Fix singular/plural label for docker image sync

- docs/assessment.md
- lib/group-update.js
- pages/instructorAssessmentGroups/instructorAssessmentGroups.ejs
- tests/testGroupStudent.js
Fixes #3076
Will always use "group" in all group work related stuffs
> [Group Work] Inconsistent use of "team" instead of "group"

- pages/studentAssessmentHomework/studentAssessmentHomework.js
- pages/studentAssessmentHomework/studentAssessmentHomework.sql
> [Group Work] Rewrite create group

- docs/externalGrading.md
- docs/installing.md
- docs/workspaces/index.md
> Added documentation for running PL from WSL2 image.

- pages/instructorIssues/instructorIssues.ejs
- pages/partials/question.ejs
> Escaped issue description in mailto link.

- admin_queries/courses_with_chunks.json
- admin_queries/courses_with_chunks.sql
- admin_queries/courses_without_chunks.json
- admin_queries/courses_without_chunks.sql
- lib/chunks.js
- lib/chunks.sql
- pages/administratorJobSequence/administratorJobSequence.ejs
- pages/administratorJobSequence/administratorJobSequence.js
- pages/administratorOverview/administratorOverview.js
- pages/editError/editError.js
Fixes up the chunk generation code that @mwest1066 wrote into a working state on staging (which basically worked as-is, so kudos)
Also adds some chunk admin queries so that we can see which courses have chunks generated.
Resolves #3280
> Allow admins to force generate course chunks

- news_items/021_c_grader/index.html
- news_items/021_c_grader/info.json
@jonatanschroeder can you fill in something for the "features" part of this? Feel free to edit anything else as well.
This will need to be merged after #3205 so we can fill in the example question URL from the live website.
> Add news item for new C autograder

- pages/instructorFileEditor/instructorFileEditor.js
- pages/shared/syncHelpers.js
> Always create course chunks regardless of JSON errors

- docs/faq.md
Forgot to update the FAQ in https://github.com/PrairieLearn/PrairieLearn/pull/2587
> Update FAQ for Docker Toolbox deprecation

- pages/clientFilesAssessment/clientFilesAssessment.js
- pages/clientFilesCourse/clientFilesCourse.js
- pages/clientFilesCourseInstance/clientFilesCourseInstance.js
- pages/clientFilesQuestion/clientFilesQuestion.js
> Fix client files access when no filename provided

- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js
- sprocs/groups_uid_list.sql
> Fixes array_agg call in groups_uid_list sproc.

- sprocs/instance_questions_update_score.sql
In file upload, if new grade is uploaded, set the submission to gradable.
> Set submission to gradable if grade uploaded.

- sprocs/instance_questions_update_score.sql
> Set instance question to complete when new grade is uploaded.

- docs/assessment.md
- lib/question.js
- pages/partials/newVariantInfo.ejs
- pages/partials/questionFooter.ejs
- tests/helperQuestion.js
Doesn't solve fully #3551 but is a workaround for questions with single variant.
> Add tries left in Grade button for exams

- environments/plbase/plbase-install.sh
Adding library `dvipng` (this will allow using latex fonts when creating dynamic plots using pl-figure
> install dvipng library

- graders/python/requirements.txt
Adding [this library](https://pypi.org/project/automata-lib/) to facilitate the creation of coding problems involving DFAs and NFAs.
> Python autograder: Add automata-lib

- pages/instructorAssessmentAccess/instructorAssessmentAccess.ejs
- pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- pages/instructorAssessmentSettings/instructorAssessmentSettings.ejs
Change the name of some of the header bars in Instructor Assessment pages. 
Closes #3657
> easy name changes

- tools/verify_course_repo.js
There is currently no built-in script aiming to verify course repositories on an CI machine. This commit adds a new script that can be execute directly in docker with the following command:
docker run -it -v $(pwd):/course prairielearn/prairielearn node /PrairieLearn/tools/verify_course_repo.js
The script prints nothing if the course repo is valid, and prints errors and returns with an exit code of 1 if there are any errors.
To setup CI for a course repo:
1. Make install docker is installed on the CI machine.
2. Execute command:
docker run -it -v $(pwd):/course prairielearn/prairielearn node /PrairieLearn/tools/verify_course_repo.js
> add script verify_course_repo.js

- elements/pl-drawing/mechanicsObjects.js
> Fix all black pl-drawing shapes

- LICENSE
I have no idea what's supposed to go in these fields, but I figured I'd at least put something.
> Fill placeholder fields in LICENSE

- docs/elements.md
- elements/pl-integer-input/pl-integer-input.mustache
- elements/pl-integer-input/pl-integer-input.py
- exampleCourse/questions/element/integerInput/question.html
- exampleCourse/questions/element/integerInput/server.py
- question-servers/freeformPythonLib/prairielearn.py
This allows hex, binary, octal and other non-trivial bases for integers.
> Add option for pl-integer-input to be provided in a non-10 base

- server.js
If we jump early to the error page (e.g., authentication failures) then `res.locals.asset_path()` and `res.locals.node_modules_asset_path()` wouldn't be defined yet. This causes an error because the error page includes `pages/partials/head.ejs` which calls both of these functions.
> Fix missing asset_path() on error page

- lib/aws.js
Also reduce the log level from `info` to `verbose` to avoid spamming syslog.
> Fix logging for buffer upload to S3

- elements/pl-dropdown/pl-dropdown.mustache
- elements/pl-dropdown/pl-dropdown.py
> Fix pl-dropdown badge in case of save without grade

- middlewares/authzCourseInstance.sql
- pages/instructorCourseAdminInstances/instructorCourseAdminInstances.sql
- sprocs/authz_course_instance.sql
- sprocs/course_instances_instructor_can_view.sql
> Fix auto-enrollment while opening unrelated queries

- pages/instructorAssessmentManualGrading/instructorAssessmentManualGrading.ejs
- pages/instructorAssessmentManualGrading/instructorAssessmentManualGrading.js
- pages/instructorAssessmentManualGrading/instructorAssessmentManualGrading.sql
- pages/instructorAssessmentQuestionManualGrading/instructorAssessmentQuestionManualGrading.ejs
- pages/instructorAssessmentQuestionManualGrading/instructorAssessmentQuestionManualGrading.js
- pages/instructorAssessmentQuestionManualGrading/instructorAssessmentQuestionManualGrading.sql
- server.js
> Revisions to manual grading submission views

- lib/config.js
- lib/github.js
Fixes `null` branches for newly generated courses by looking up the branch that was created on GitHub
> Fix null "branch" field for generated courses

- pages/partials/questionFooter.ejs
> Add points for current and future attempts in question footer

- sprocs/assessment_instances_select_log.sql
> Add group log events to assessment instance log view

- lib/score-upload.js
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js
- sprocs/instance_questions_update_score.sql
- tests/testInstructorAssessmentDownloads.js
> Add safeguard to ensure submission uploads match the UID

- lib/assessment.js
- lib/assessment.sql
- pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- pages/instructorAssessmentInstances/instructorAssessmentInstances.js
> Add Grade All button

- docs/question.md
data["partial_scores"] is a dictionary containing score and weight, not a number.
> Fixed bug in example code

- exampleCourse/questions/demo/calculation/question.html
Changes to pl-input for the default question generated by "Add new question"
> Change pl-input for default question

- Makefile
- package-lock.json
- package.json
- pages/studentSEBConfig/studentSEBConfig.js
To use `depcheck`, run:
```
make depcheck
```
> Add depcheck for checking whether npm dependencies are really used

- package-lock.json
- package.json
This replaces #4530 which was outdated by other package changes. It was easier to recreate this PR from scratch than to try and rebase the existing one.
> Remove unused csv package

- prairielib/lib/sql-db.js
> Fix typo in unused function name

- elements/pl-checkbox/pl-checkbox.py
> Fix checkbox unit testing bug

- pages/instructorAssessmentInstances/instructorAssessmentInstancesClientJS.ejs
- pages/instructorGradebook/instructorGradebook.ejs
- pages/partials/assessment.ejs
I'm open to suggestions about tweaks in UI (e.g., different button order, different title).
> Add filter in gradebook and students page to list only Students

- .github/workflows/image-prairielearn.yml
- .github/workflows/images.yml
- tools/check_path_modified.sh
Includes multi-arch builds to support ARM64/M1, following on from #4622
> Add GitHub action to publish prairielearn/* docker images

- pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- pages/instructorAssessmentInstances/instructorAssessmentInstancesClientJS.ejs
- pages/instructorGradebook/instructorGradebook.ejs
- pages/instructorQuestions/instructorQuestions.ejs
> UI tweaks to questions, gradebook and students tables

- pages/instructorGradebook/instructorGradebook.sql
> Show students in gradebook page even if there are no assessments

- docs/faq.md
This is a temporary workaround until #4701 is implemented.
> Add FAQ entry describing local templates

- pages/instructorAssessmentGroups/instructorAssessmentGroups.ejs
> Fix group page for non-group assessments

- exampleCourse/questions/demo/autograder/c/salesTax/info.json
> Fix reference to C autograder image

- sprocs/assessment_instances_select_log.sql
> Review assessment instance log order

- elements/pl-file-preview/pl-file-preview.mustache
- elements/pl-file-preview/pl-file-preview.py
- elements/pl-file-upload/pl-file-upload.js
Resolves #4350 
Resolves #1133
Also partially addresses #3159 (for images)
> File upload/preview: show images and clearer message when file is binary

- graders/r/Dockerfile
- graders/r/r_autograder/pltest.R
- graders/r/r_autograder/run.sh
This should complete the setup for the R autograder
> Copy autograder interface files into position

- workspaces/rstudio/Dockerfile
`sqlite3` is a command line tool that UIUC STAT 447 uses, others may find it useful as well.
> adding SQLite3 to RStudio workspace

- workspaces/desktop/pre-install.sh
Another thing I forgot to add in my last PR. Some students may expect nano to be in the terminal.
> adding nano to desktop build

- docs/course.md
I think this explanation belongs here. Edited the example shown also.
> Add note about useNewQuestionRenderer in course config doc

- elements/pl-order-blocks/pl-order-blocks.js
- elements/pl-order-blocks/pl-order-blocks.mustache
- elements/pl-order-blocks/pl-order-blocks.py
> Encapsulate and format JavaScript for pl-order-blocks element

- pages/instructorQuestionManualGrading/instructorQuestionManualGrading.js
- pages/partials/instructorGradingPanel.ejs
- sprocs/instance_question_select_manual_grading_objects.sql
Instructors should be able to specify points OR percentage (previously they could only do it by percentage).
> Add Points Input Box to Manual Grading Page

- pages/instructorAssessmentQuestionManualGrading/instructorAssessmentQuestionManualGrading.ejs
- pages/instructorAssessmentQuestionManualGrading/instructorAssessmentQuestionManualGrading.js
- pages/instructorAssessmentQuestionManualGrading/instructorAssessmentQuestionManualGrading.sql
- pages/instructorQuestionManualGrading/instructorQuestionManualGrading.js
- pages/instructorQuestionManualGrading/instructorQuestionManualGradingNextInstanceQuestion.js
- pages/instructorQuestionManualGrading/instructorQuestionManualGradingNextInstanceQuestion.sql
- server.js
Fixes https://github.com/PrairieLearn/PrairieLearn/issues/5091
> Manual grading: return questions in  order when selecting 'next'

- tools/build-image-if-needed.sh
- tools/check_path_modified.sh
> fix: Build changed images on master

- lib/question.js
- sprocs/variants_insert.sql
- sprocs/variants_select.sql
> fix: Validate variant in query against question

- pages/instructorGradebook/instructorGradebook.ejs
Resolves #5483 
Also limits the rendered size of UIN if it's too long (Resolves #5408).
> Allow UIN, Name and Role to be hidden in gradebook

- pages/enroll/enroll.js
- pages/enroll/enroll.sql
- pages/enroll/lti.ejs
- pages/instructorInstanceAdminLti/instructorInstanceAdminLti.ejs
- Explains in the error message how LTI students can see more courses.
- Adds a warning on the instructor LTI screens to check with PL admins before using
> Fix enrollment error message for LTI students

- graders/r/Dockerfile
This PR updates the set of packages in the R autograder, and was prepared by @daviddalpiaz and myself.  I ran the Docker build locally, so it should not create any sort of surprises or hickups when you merge.  
Any questions, please just hit us up here or on Slack.
> Updated package set for R autograder (thanks, @daviddalpiaz)

- elements/pl-dropdown/pl-dropdown.mustache
- elements/pl-dropdown/pl-dropdown.py
- elements/pl-file-editor/pl-file-editor.js
- elements/pl-file-editor/pl-file-editor.mustache
- elements/pl-file-editor/pl-file-editor.py
- elements/pl-file-upload/pl-file-upload.mustache
- elements/pl-file-upload/pl-file-upload.py
- elements/pl-rich-text-editor/pl-rich-text-editor.py
Addresses part of #5540, in particular for pl-dropdown, pl-rich-text-editor, pl-file-editor and pl-file-upload.
> Disable elements when new answers are no longer allowed

- migrations/252_instance_questions__requires_manual_grading__update.sql
I tested the `WITH ranked_submissions` CTE from [migrations/252] on the production DB and it took about an hour and used over 200 GB of disk space to page out the CTE results. This PR speeds this up about 50x by a combination of:
1. Early restriction to questions with `grading_method = 'Manual'` (this is only a small fraction of questions).
2. Restriction to instance questions modified this semester (a small fraction of instance questions).
3. Avoiding the use of `s.*` in a CTE, which selects the `submitted_answer` and pages it to disk, including a lot of large base64-encoded python notebooks.
I also used DISTINCT with ORDER BY, rather than the window function, but I'm not sure whether this is any faster.
I believe that this PR doesn't change the result of the migration (except the date …
> fix: Speed up migration 252 for manual grading

- lib/score-upload.js
- middlewares/selectAndAuthzInstanceQuestion.sql
- pages/instructorAssessmentInstance/instructorAssessmentInstance.js
- pages/instructorAssessmentInstance/instructorAssessmentInstance.sql
- pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.ejs
- pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.js
- pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.sql
- pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ejs
- pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.js
- pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.sql
- pages/partials/editQuestionPointsForm.ejs
- pages/partials/editQuestionScorePercForm.ejs
- pages/partials/instructorGradingPanel.ejs
- sprocs/instance_questions_update_score.sql
This PR introduces logic to identify cases where two different graders provide conflicting scores to the same instance question.
> Manual grading: identify conflicting scores

- pages/instructorQuestions/instructorQuestions.ejs
- pages/instructorQuestions/instructorQuestions.sql
Resolves: #4825 
Resolves: #5398 
Grading method and external grading image added as hidden-by-default columns. Also adds a "none" option to the assessment columns.
> feat: Add grading method and image to question page

- api/v1/endpoints/courseInstanceAssessmentInstances/index.js
- api/v1/endpoints/courseInstanceAssessments/index.js
- api/v1/endpoints/courseInstanceSubmissions/index.js
- api/v1/endpoints/queries.sql
- api/v1/error.js
- api/v1/index.js
This PR improves the authorization that we perform for various API routes. Shoutout to @dwang for identifying these issues!
> fix: Improve API authorization

- pages/instructorAssessmentManualGrading/assessment/assessment.sql
Manual grading landing page for an assessment is pretty slow in production. This query change hopefully improves the performance of related queries.
> Improve performance of manual grading assessment page

- grader_host/index.js
This will hopefully improve our ability to diagnose the issue documented in #5669.
> chore: Add more logging to external grader host

- lib/assessment.js
> typo: LIT -> LTI

- elements/pl-order-blocks/pl-order-blocks.css
fix #4955
Also fix the entire thing being off-center
> pl-order-blocks: improve margins and reflow

- elements/pl-order-blocks/pl-order-blocks.js
- elements/pl-order-blocks/pl-order-blocks.mustache
> pl-order-blocks: handle spaces in answers-name

- lib/question.js
- sprocs/grading_jobs_update_after_grading.sql
Fixes #5671 from @nwalters512 troubleshooting
> fix regression for LTI grading

- lib/config.js
- workspace_host/interface.js
Provides the variables to address #5373
> Add config variables for workspace containers

- pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- pages/instructorAssessmentInstances/instructorAssessmentInstances.sql
- sprocs/group_info.sql
> feat: Add group user names as hidden column in assessment instances page

- pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- pages/instructorAssessmentInstances/instructorAssessmentInstancesClientJS.ejs
- Fix an issue with delete group assessments not showing the group name and member UIDs
Sample:
#5885
> Fix bug in delete group assessment instance

- docs/c-grader/index.md
> docs: Fix reference to external grader results for C grader

- lib/chunks.js
- sync/course-db.js
- sync/syncFromDisk.js
- tools/verify_course_repo.js
This PR removes some leftover, unused code from #1640.
> Remove unused syncing function

- graders/c/README.md
- graders/java/README.md
- graders/python/README.md
This should help to improve the discoverability of the documentation for each grader image.
> Link to documentation from grader image READMEs

- docs/java-grader/index.md
- docs/python-grader/index.md
> Fix pl-external-grader-results references in docs

- README.md
The readme was a bit out of date with broken badges and such. I also added a link to https://www.prairielearn.com.
> Update README with latest information

- schemas/schemas/serverConfig.json
Followup to #6024 - I neglected to add this value to the schema for the server config!
> Add disabled as an allowed value for workersExecutionMode

- graders/c/cgrader/cgrader.py
This PR allows a test using the C grader to separate calls for compilation and linking. This allows:
* More fine-tuned flags between different C files or between compilation and linking;
* Special processing of object files (e.g., using `objcopy` to replace a symbol name);
* Using the same object code in multiple executables.
Existing tests should behave mostly the same way as usual, but setting the `exec_file` argument to `None` would cause the linker to be skipped. A new method was created to link objects separately.
Doc updates pending.
> C grader: Allow compiler and linker calls to be split

- CODEOWNERS
Thanks @SethPoulsen for committing to own this element!
> Add Seth as codeowner for pl-order-blocks

- CODEOWNERS
Thanks @jonatanschroeder for maintaining these 🎉
> Add Jonatan as codeowner of various things

- lib/editors.js
- pages/instructorFileEditor/instructorFileEditor.js
- pages/shared/syncHelpers.js
> Use correct branch name when performing git operations

- lib/question.js
- pages/studentInstanceQuestionExam/studentInstanceQuestionExam.ejs
- pages/studentInstanceQuestionHomework/studentInstanceQuestionHomework.ejs
> Remove unused YouTube video rendering code

- middlewares/selectAndValidateWorkspace.js
- middlewares/selectAndValidateWorkspace.sql
- server.js
This should clean up our logs a bit.
> Don't proxy workspace traffic if workspace is not running

- .github/workflows/main.yml
See the GitHub docs for more details: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
> Limit CI workflow concurrency

- pages/instructorAssessmentInstances/instructorAssessmentInstancesClientJS.ejs
Resolves #4811, resolves #5663.
> Add shortcut to re-open assessment instance

- .changeset/poor-frogs-burn.md
I've installed https://github.com/apps/changeset-bot so that I don't forget about this in the future.
> Add changeset for recent version bumps

- pages/instructorAssessmentSettings/instructorAssessmentSettings.ejs
- pages/instructorAssessmentSettings/instructorAssessmentSettings.js
- pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.ejs
- pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.js
Can be useful for in-class worksheets if instructor shows the code on the screen.
> feat: Add QR code to assessment student link

- lib/code-caller/index.js
- package.json
- python/zygote.py
- yarn.lock
Lifting these out of #6304. I ultimately decided not to proceed with the "wait for workers to be ready" approach", but there were still a few things from that PR that I'd like to land.
> Code caller container improvements

- pages/partials/submission.ejs
Submitting a minor change to the text of the manual feedback panel to make it a bit 'friendlier'
"Grader Feedback" ---> "Feedback from the Course Team"
Let me know if there is anywhere else I need to change.
> Minor change to the text of the manual feedback panel

- lib/groups.sql
- pages/partials/studentGroupControls.ejs
- pages/shared/groupWorkInfoContainer.ejs
Resolves #6353. Resolves #6344.
> Display group size limits and partner names to students

- pages/partials/mathjax.ejs
> Enable MathJax contextual menu

- docs/elements.md
- docs/python-grader/index.md
- docs/question.md
- exampleCourse/questions/demo/custom/elementHiddenTag/question.html
> Remove remaining instances of self-closing elements

- pages/authLogin/authLogin.ejs
Noticed this while testing locally.
> Fix login page when not running in enterprise mode

- pages/workspace/workspace.ejs
My editor pointed these out to me!
> Fix HTML syntax on workspace page

- pages/instructorAssessments/instructorAssessments.js
> Fix instructor assessments CSV download by providing missing param

- sprocs/sync_assessment_modules.sql
- sprocs/sync_assessment_sets.sql
- sprocs/sync_course_tags.sql
- sprocs/sync_topics.sql
- tests/sync/util.js
> Rename instances of courseInfo.json to infoCourse.json

- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js
- pages/instructorAssessmentInstance/instructorAssessmentInstance.js
- pages/instructorAssessmentQuestionStatistics/instructorAssessmentQuestionStatistics.js
- pages/instructorAssessmentStatistics/instructorAssessmentStatistics.js
- pages/instructorAssessments/instructorAssessments.js
- pages/instructorGradebook/instructorGradebook.js
- pages/instructorQuestionStatistics/instructorQuestionStatistics.js
This keeps these errors out of Sentry.
> Use 404 status code for unknown file downloads

- docs/manualGrading.md
- exampleCourse/courseInstances/SectionA/assessments/homework/manualGrading/infoAssessment.json
- lib/question.js
- pages/instructorAssessmentQuestionStatistics/instructorAssessmentQuestionStatistics.ejs
- pages/instructorAssessmentQuestions/instructorAssessmentQuestions.ejs
- pages/partials/questionScorePanel.ejs
- pages/partials/submissionStatus.ejs
- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs
- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.js
- pages/studentAssessmentInstanceHomework/studentAssessmentInstanceHomework.js
- sprocs/variants_select_submission_for_grading.sql
- testCourse/courseInstances/Sp15/assessments/hw9-internalExternalManual/infoAssessment.json
- tests/gradingMethods.test.js
> Handle questions with no points as auto-grading

- workspace_host/interface.js
Our workspace code will happily handle many types of errors. Unfortunately, it wasn't logging them out, which made it difficult to tell what was actually happening when errors *were* encountered. This PR updates the workspace host code to actually log out pretty much every error we could encounter.
> Log workspace errors

- api/v1/endpoints/queries.sql
> fix: Submissions API support for group assessments

- elements/pl-file-editor/pl-file-editor.py
- elements/pl-rich-text-editor/pl-rich-text-editor.py
> Avoid duplication of file content in submitted answers

- docs/assessment.md
Admin-merging before CI was done finally came back to bite me 😂
> Fix formatting in docs/assessment.md

- lib/node-metrics.js
> Fix Node CPU metric calculation

- elements/pl-order-blocks/dag_checker.py
- elements/pl-order-blocks/dag_checker_test.py
> fix: pl-order-blocks crashing in rare circumstances

- executor.js
- lib/code-caller/code-caller-container.js
- lib/code-caller/code-caller-native.js
- lib/code-caller/index.js
- lib/config.js
We're optimistic that increasing the ping timeout will resolve #6618.
> Make code caller ping timeout configurable

- elements/pl-symbolic-input/pl-symbolic-input.py
- pyrightconfig.json
- python/python_helper_sympy_test.py
- tests/exampleCourseQuestions.test.js
Fix test for sympy element. Adds unit tests to internal sympy helper functions to ensure functionality is preserved before a refactor in a later pull request.
> Improve tests for SymPy helpers and pl-symbolic-input

- cron/index.js
This caught a few issues with our OTel instrumentation! 🎉
> Add type checking to cronjobs index

- database/tables/time_series.pg
- migrations/20221122001508_time_series__date__add_index.sql
This will need to be merged and deployed before #6649.
> Create index for the date column of time_series

- pages/authCallbackLti/authCallbackLti.js
The main issue here was a missing `return` within the `if (is_instructor)` block. I opted to invert the condition and error early.
Using a global variable for `redirUrl` is weird; I eliminated that.
> Fix LTI auth callback linking

- pages/home/home.js
> Unconditionally show example courses to admins

- lib/score-upload.js
- pages/instructorAssessmentInstance/instructorAssessmentInstance.js
- pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.js
- pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.js
- sprocs/instance_questions_update_score.sql
> fix: Force assessment ID check for manual score updates

- lib/opsbot.js
This PR removes some outdated code and terminology from our opsbot utils.
> Remove unused opsbot code

- middlewares/authzCourseOrInstance.js
- middlewares/authzCourseOrInstance.sql
- pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ejs
> Display institution on course settings page

- docs/elements.md
Resolves #6969. Also fixed broken links and ordering inconsistency with hidden hints documentation.
> Fix position of pl-file-preview in element docs

- Makefile
- docker/init.sh
- workspace_host/nodemon.json
I'm open to tweaks in the watch list and general config, but I'd really appreciate the ability to restart the workspace automatically on related changes.
> Add support for nodemon in workspace host

- graders/java/JUnitAutograder.java
- graders/java/autograder.sh
As discussed on Slack. Further details withheld from public discussion.
> Java grader: replace command line arguments with parameters file

- lib/databaseDescribe.js
- lib/databaseDiff.js
- tests/database.test.js
- tests/issues.test.js
- tests/lti.test.js
- tools/pg-describe.js
- tools/pg-diff.js
Before this PR, there were 159 files using `ERR\(...\)`. With that as a proxy for usage of callback functions, I figure if I can rewrite 1-3 files a day to use async/await instead of callbacks, we're at most 6 months away from getting rid of callback code entirely 🎉
> Rewrite some tests and database utils with async/await

- docs/workspaces/index.md
Proposed command was missing the course, as the other versions.
> docs: Fix command for PowerShell using workspaces

- lib/chunks.js
- tests/chunks.test.js
- tests/chunks.test.sql
See inline descriptions of the problem and the fix.
> Fix bug when question is renamed to a subdirectory of itself

- exampleCourse/courseInstances/SectionA/assessments/exam/activeAccessRestriction/infoAssessment.json
- pages/instructorCourseAdminStaff/instructorCourseAdminStaff.js
> Typo: "acccess"

- ee/cron/workspaceHostLoads.js
- sprocs/workspace_loads_current.sql
See inline comment for description.
Fixes https://github.com/PrairieLearnInc/sysconf/issues/804.
> Exclude unhealthy hosts from workspace load computations

- lib/question.js
#7112 changed the query for issue counts, but didn't change the variable used in the log.
> fix: Incorrect variable used in logging

- lib/issues.js
This was a regression introduced accidentally in #7113.
> Correctly capture course error data from error object

- pages/partials/questionFooter.ejs
> Round remaining available points in question footer

- question-servers/freeform.js
I noticed both of these while working on #7128. Regardless of what happens with that PR, I wanted to get these in.
> Freeform question bug fixes

- .github/workflows/cla.yml
> Upgrade cla-assistant Action to latest version

- package.json
- question-servers/freeform.js
- yarn.lock
This should reduce synchronous thread-blocking work in prod. Note that the value of the cache key will change, so we'll temporarily get zero cache hits.
Benchmark:
```
cpu: Apple M1 Max
runtime: node v18.12.0 (arm64-darwin)
benchmark                                  time (avg)             (min … max)       p75       p99      p995
----------------------------------------------------------------------------- -----------------------------
• big strings
----------------------------------------------------------------------------- -----------------------------
JSON.stringify + crypto.subtle.digest   68.53 ms/iter   (66.05 ms … 71.24 ms)  70.27 ms  71.24 ms  71.24 ms
JSON.stringify + crypto.createHash      61.59 ms/iter   (59.49 ms … 66.89 ms)  62.03 ms  66.89 ms  66.89 ms
object-hash …
```
> Use object-hash to speed up cache key computation

- lib/config.js
- workspace_host/interface.js
I forgot to remove these in #6983.
> Remove unused workspace config

- pages/administratorAdmins/administratorAdmins.html.js
- pages/administratorAdmins/administratorAdmins.js
- pages/administratorAdmins/administratorAdmins.sql
I forgot to do this as part of #2378.
> Don't query for question render stats on admins page

- .changeset/curvy-peas-divide.md
- packages/postgres/README.md
- packages/postgres/src/pool.ts
See updated `README.md` for an example use case.
> Return result from runInTransactionAsync

- pages/administratorAdmins/administratorAdmins.js
Local testing of #7178 didn't reveal any issues because there was only one admin locally 🤦
> Allow multiple rows for administrator query

- grader_host/lib/config.js
- grader_host/lib/lifecycle.js
- grader_host/lib/load.js
- grader_host/lib/pullImages.js
My find/replace in #7197 didn't take into account the fact that the grader has a separate special logger 🤦
> Fix grader host logging

- grader_host/lib/config.js
- grader_host/lib/lifecycle.js
- grader_host/lib/load.js
- grader_host/lib/pullImages.js
#7208 was still not quite right. We need TypeScript so bad here!
> Don't destructure require of grader host logger

- cron/workspaceHostTransitions.js
> Add timeout to workspace host health check

- .github/workflows/combine-prs.yml
As recommended by @jonatanschroeder on Slack. This may help us deal with Dependabot PRs.
> Add combine-prs GitHub Actions workflow

- lib/aws.js
As discussed on Slack, and based on discussion in https://github.com/aws/aws-sdk-js/issues/4354#issuecomment-1450660391.
> Suppress AWS maintenance mode message

- docs/assessment.md
- pages/partials/attachFilePanel.ejs
- pages/partials/studentAssessmentInstanceRowLabel.ejs
- tests/activeAccessRestriction.test.js
Changed the UI to provide more clarity on the purpose of attached files.
> Rename attached files to personal notes for clarity

- database/tables/page_view_logs.pg
- migrations/20230309000047_page_view_logs__panel_count__drop.sql
> Drop panel count columns from page_view_logs table

- database/tables/audit_logs.pg
- database/tables/groups.pg
- migrations/20230308213204_audit_logs__group_id__drop_index.sql
> Drop group_id foreign key constraint from audit_logs

- .changeset/five-hornets-happen.md
- .github/workflows/release.yml
- packages/error/src/index.test.ts
- packages/error/src/index.ts
This only came to my attention when I tried to install this package into PrairieTest, which is fully written in TypeScript.
> Make data argument optional in @prairielearn/error make()

- .github/workflows/release.yml
This should speed up releases a bit.
> Enable caching for release workflow

- cron/workspaceHostTransitions.js
- cron/workspaceHostTransitions.sql
- lib/workspace.sql
This may give us better visibility into cases where workspaces launch twice.
> Add workspace log when terminating hosts

- docs/elements.md
Follow-up in docs on https://github.com/PrairieLearn/PrairieLearn/issues/7322
> Update `pl-graph` docs

- lib/assessment.sql
- lib/workspace.sql
- packages/prettier-plugin-sql/package.json
- yarn.lock
Pulls in my changes from https://github.com/sql-formatter-org/sql-formatter/pull/574.
> Update sql-formatter to get FOR UPDATE support

- .github/workflows/release.yml
- package.json
See note here: https://github.com/changesets/action/issues/170#issuecomment-1477095373
> Fix changeset versioning

- lib/question.js
- middlewares/authzCourseOrInstance.js
- package.json
- packages/docker-utils/package.json
- packages/docker-utils/src/index.ts
- pages/courseSyncs/courseSyncs.js
- pages/instructorEffectiveUser/instructorEffectiveUser.ejs
- pages/instructorEffectiveUser/instructorEffectiveUser.js
- pages/instructorIssues/instructorIssues.js
- yarn.lock
Resolves #7163, replaces the use of moment.js with equivalent functions in date-fns.js.
Also resolves #4684.
> Replace moment with date-fns

- lib/chunks.js
- lib/courseUtil.js
- lib/editors.js
- lib/file-store.js
- lib/github.js
- lib/server-jobs.js
- pages/instructorFileEditor/instructorFileEditor.js
- pages/instructorLoadFromDisk/instructorLoadFromDisk.js
- pages/shared/syncHelpers.js
> Log all created/updated/deleted chunks after sync

- docs/elements.md
- elements/pl-graph/pl-graph.py
Adds an attribute to hide warnings raised by `pl-graph` during rendering.
> feat: `pl-graph` show warnings flag

- server.js
These are all covered by the middleware that runs for the entire `/pl/course_instance/:course_instance_id/instance_question/:instance_question_id` route prefix.
https://github.com/PrairieLearn/PrairieLearn/blob/ed27bcfa732e8a8e1ff6833a06499a34fa85d7bf/server.js#L1335-L1341
> Remove unnecessary auth checks

- yarn.lock
Followup to #7497. I really need to make `yarn dedupe` part of CI...
> Deduplicate dependencies

- elements/pl-external-grader-results/pl-external-grader-results.py
> Show external grader test results with zero points as gray

- package.json
- yarn.lock
> Bump @prairielearn/html to 3.0.0

- cron/workspaceHostTransitions.js
- pages/workspaceLogs/workspaceLogs.js
- tsconfig.json
- workspace_host/interface.js
- workspace_host/lib/docker.js
- workspace_host/lib/docker.test.js
Doing this so I can have more confidence when refactoring the workspace host config.
> Typecheck workspace host

- cron/workspaceHostTransitions.js
- package.json
- packages/aws-imds/package.json
- packages/compiled-assets/package.json
- packages/config/package.json
- packages/csv/package.json
- packages/docker-utils/package.json
- packages/error/package.json
- packages/html-ejs/package.json
- packages/html/package.json
- packages/logger/package.json
- packages/migrations/package.json
- packages/named-locks/package.json
- packages/opentelemetry/package.json
- packages/path-utils/package.json
- packages/postgres-tools/package.json
- packages/postgres/package.json
- packages/prettier-plugin-sql/package.json
- packages/sanitize/package.json
- packages/sentry/package.json
- packages/signed-token/package.json
- packages/workspace-utils/package.json
- pages/workspaceLogs/workspaceLogs.js
- tests/helperDb.js
- tests/mocha-hooks.mjs
- yarn.lock
I'm lifting these bumps out of #7572.
> Upgrade typescript and @types/node

- .github/workflows/images.yml
See inline comment for more details.
> Don't build linux/arm64 variant of prairielearn/prairielearn image

- package.json
- tests/helperServer.js
- yarn.lock
Tiny cleanup for something I noticed while reviewing all dependencies on another branch.
> Replace delay package with native setTimeout promise

- elements/pl-threejs/OrbitControls.js
- elements/pl-threejs/STLLoader.js
- elements/pl-threejs/info.json
- elements/pl-threejs/pl-threejs.js
- elements/pl-threejs/pl-threejs.mustache
- pages/partials/issueActionButtons.ejs
- tests/assets.test.js
This element has been broken in a few ways for a while now:
- The entire element didn't render because files were moved around in the `three` package.
- Once that was fixed, the motion toggles didn't work, and the motion buttons displayed a missing icon error.
This PR fixes both these issues. It also adds new tests for element assets to prevent future regressions.
> Fix pl-threejs element

- .changeset/config.json
We don't currently want to version these apps (though it's an interesting possibility).
> Ignore apps in changesets config

- apps/prairielearn/src/lib/config.js
> Allow x-auth for authType in config

- apps/prairielearn/src/lib/assets.ts
I'm doing this ahead of starting work on #7704.
> Convert assets lib to TypeScript

- apps/prairielearn/src/lib/features/manager.ts
- apps/prairielearn/src/tests/features.test.ts
> Type-checking of feature names

- apps/grader-host/src/index.js
- apps/grader-host/src/lib/pullImages.js
- apps/prairielearn/package.json
- apps/prairielearn/src/lib/code-caller/code-caller-container.js
- apps/prairielearn/src/pages/shared/syncHelpers.js
- apps/workspace-host/src/interface.js
- packages/aws-imds/package.json
- packages/config/package.json
- packages/docker-utils/package.json
- packages/docker-utils/src/index.ts
- yarn.lock
> Use v3 of AWS SDK in docker-utils package

- apps/prairielearn/src/cron/autoFinishExams.ts
- apps/prairielearn/src/cron/cleanTimeSeries.ts
- apps/prairielearn/src/cron/index.js
- apps/prairielearn/src/cron/workspaceHostTransitions.ts
- apps/prairielearn/src/cron/workspaceTimeoutStop.ts
I only converted the jobs that were already being type-checked with `// @ts-check`; I haven't touched the others yet.
> Convert typechecked cron jobs to TypeScript

- apps/grader-host/package.json
- apps/grader-host/src/index.js
- apps/grader-host/src/lib/config.js
- apps/grader-host/src/lib/receiveFromQueue.js
- apps/grader-host/src/tests/receiveFromQueue.test.js
- apps/grader-host/tsconfig.json
- apps/prairielearn/package.json
- apps/prairielearn/src/cron/sendExternalGraderDeadLetters.js
- apps/prairielearn/src/lib/externalGraderResults.js
- apps/prairielearn/src/lib/externalGraderSqs.js
- yarn.lock
I tested this end-to-end in our staging environment, and external grading is still working well!
Part of #7727.
> Use v3 AWS SDK to interact with SQS

- apps/prairielearn/src/pages/authLogin/authLogin.ts
- apps/prairielearn/src/server.js
Separating this from #7738 to retain Git history.
> Convert authLogin page to TypeScript

- apps/prairielearn/package.json
- apps/prairielearn/src/cron/externalGraderLoad.js
- apps/prairielearn/src/cron/sendExternalGraderDeadLetters.js
- apps/prairielearn/src/cron/serverLoad.js
- apps/prairielearn/src/cron/serverUsage.js
- apps/prairielearn/src/cron/workspaceHostTransitions.ts
- apps/prairielearn/src/ee/cron/chunksHostAutoScaling.ts
- apps/prairielearn/src/ee/cron/workspaceHostLoads.ts
- apps/prairielearn/src/lib/aws.js
- apps/prairielearn/src/lib/chunks.ts
- apps/prairielearn/src/lib/externalGraderResults.js
- apps/prairielearn/src/lib/externalGraderSqs.js
- apps/prairielearn/src/lib/lifecycle-hooks.js
- apps/prairielearn/src/lib/node-metrics.js
- apps/prairielearn/src/pages/courseSyncs/courseSyncs.js
- apps/prairielearn/src/pages/instructorGradingJob/instructorGradingJob.js
- apps/prairielearn/src/pages/shared/syncHelpers.js
- apps/prairielearn/src/pages/workspaceLogs/workspaceLogs.js
- apps/prairielearn/src/server.js
- apps/prairielearn/src/tests/helperServer.js
- yarn.lock
I'd recommend reviewing with whitespace changes hidden.
> Convert PL to AWS SDK v3 with codemod

- apps/prairielearn/src/pages/shared/syncHelpers.js
> Fix course syncing

- apps/prairielearn/src/lib/chunks.ts
- apps/prairielearn/src/lib/server-jobs.ts
This also includes a small refactor of the new server jobs code. See inline comment for more details.
> Use new server jobs in chunks lib

- apps/prairielearn/src/middlewares/selectAndAuthzInstanceQuestion.sql
- apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.ejs
- apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ejs
> Update page titles for manual grading pages

- apps/prairielearn/src/middlewares/authn.js
This resolves some nuisance errors that were occasionally being reported to Sentry when someone or something tried to access a workspace container route while unauthenticated. `req.path` was `/` in the `authn` middleware mounted on the workspace proxy route, which triggered the "allow people to access the homepage without auth" case.
Note that we didn't fail open here; we still correctly failed the authentication process later in the request lifecycle.
> Redirect to homepage for unauthenticated workspace proxy requests

- apps/prairielearn/elements/pl-big-o-input/big_o_utils.py
- apps/prairielearn/elements/pl-big-o-input/big_o_utils_test.py
See title, resolves #7573. Tested locally and seems to work, but hard to tell if this will fix the problem without testing on a live server. Should merge after the semester ends.
> Add simplify to big O grading

- apps/prairielearn/src/pages/administratorCourses/administratorCourses.ejs
> Show institution timezone on admin page

- apps/prairielearn/elements/pl-xss-safe/pl-xss-safe.py
- pyproject.toml
See title, basic type annotations for this element.
> style: `pl-xss-safe` type annotations

- apps/prairielearn/src/migrations/20230531211528__config__drop.sql
- database/tables/config.pg
> Drop config table

- apps/prairielearn/package.json
- yarn.lock
> Remove unused delay dependency

- apps/prairielearn/src/question-servers/freeform.js
Based on discussion with @eliotwrobson in #7909. Resolves #5372.
> Add paths to option object in call to file()

- apps/prairielearn/elements/pl-big-o-input/big_o_utils.py
- apps/prairielearn/elements/pl-big-o-input/big_o_utils_test.py
- apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py
- apps/prairielearn/python/python_helper_sympy.py
See title, slight changes to the backend of the BigO grader to give unconditional correct feedback in more cases. Small API additions to the sympy code, but will not break any existing code (did not have to modify any sympy test cases).
> feat: More flexibility in BigO grading

- apps/prairielearn/python/prairielearn.py
> fix: f-string typo fix

- apps/prairielearn/src/sync/course-db.js
- apps/prairielearn/src/tests/sync/assessmentsSync.test.js
Closes #773. See note on that issue about the safety of this change (tl;dr it is very safe).
> Validate that assessment question points are non-increasing

- exampleCourse/questions/element/bigOInput/question.html
> fix: Added variable to big-O examples

- apps/prairielearn/src/lib/editors.js
- packages/error/src/index.test.ts
- packages/error/src/index.ts
I'd recommend reviewing with whitespace changes hidden.
> Rewrite editors with async/await writing

- apps/prairielearn/src/migrations/20230612165721_feature_grants__type__drop.sql
- database/tables/feature_grants.pg
Cleanup following the deployment of #7801.
> Drop type column from feature_grants table

- apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.py
> pl-order-blocks: fix unordered grading mode

- .changeset/ninety-mails-tie.md
- apps/prairielearn/assets/scripts/question.ts
- apps/prairielearn/package.json
- packages/browser-utils/README.md
- packages/browser-utils/package.json
- packages/browser-utils/src/encode-data.ts
- packages/browser-utils/src/index.ts
- packages/browser-utils/src/on-document-ready.ts
- packages/browser-utils/src/parse-html.ts
- packages/browser-utils/tsconfig.json
- packages/html/package.json
- yarn.lock
These have been extracted from PrairieTest so that we can use them in PrairieLearn as well.
> Introduce @prairielearn/browser-utils package

- apps/prairielearn/src/lib/chunks.ts
This PR fixes a situation where someone could trigger rate limiting of IMDS credential acquisition by modifying a sufficiently large number of questions in a single sync. By sharing a client, we should limit ourselves to only a single attempt to get credentials per chunk update, which should be much less likely to be rate limited.
> Use a single S3 client when uploading chunks

- apps/prairielearn/src/lib/server-jobs.ts
- apps/prairielearn/src/tests/serverJobs.test.ts
I'm lifting this out of #8007 because I need it for another PR.
> Add fail() method to server jobs

- apps/prairielearn/elements/pl-drawing/pl-drawing.mustache
- apps/prairielearn/src/pages/partials/examQuestionAvailablePoints.ejs
- apps/prairielearn/src/pages/partials/examQuestionHelpAvailablePoints.ejs
- apps/prairielearn/src/pages/partials/examQuestionHelpAwardedPoints.ejs
- apps/prairielearn/src/pages/partials/examQuestionHelpBestSubmission.ejs
> Fix markup for popovers triggered by focus

- apps/prairielearn/src/lib/instructorFiles.js
- apps/prairielearn/src/middlewares/authzCourseOrInstance.js
- apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.js
I can across these while starting work on institution administrators. Using `html` will result in improved and more robust formatting.
> Use html tagged template literal to construct error info

- docs/elements.md
Some incorrect types in a table in the docs.
> docs: Small doc fixes

- .changeset/unlucky-chicken-brush.md
- packages/browser-utils/README.md
- packages/browser-utils/src/index.ts
- packages/browser-utils/src/template-from-attributes.ts
Lifting this over from PrairieTest, where it's been very useful.
> Add templateFromAttributes function to browser-utils package

- .eslintrc.js
- apps/prairielearn/elements/pl-drawing/mechanicsObjects.js
- apps/prairielearn/elements/pl-drawing/pl-drawing.js
- apps/prairielearn/elements/pl-file-preview/pl-file-preview.js
- apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js
- apps/prairielearn/elements/pl-threejs/STLLoader.js
- apps/prairielearn/elements/pl-threejs/pl-threejs.js
- apps/prairielearn/src/lib/chunks.ts
- apps/prairielearn/src/tests/courseElementExtension.test.js
- apps/prairielearn/src/tests/enroll.test.ts
- apps/prairielearn/src/tests/fileEditor.test.js
- package.json
- packages/flash/src/index.ts
- packages/html/src/index.ts
- packages/postgres-tools/src/diff.ts
- packages/postgres/src/pool.ts
- yarn.lock
I fixed all the rule violations with the exception of `@typescript-eslint/no-dynamic-delete`, which I just disabled for the time being.
> Upgrade to typescript-eslint v6

- apps/prairielearn/assets/scripts/question.ts
> Fix submission info button when submission loaded dynamically

- apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.js
This was manifesting as failed syncs.
> Fix instructor file editor course hash

- apps/prairielearn/src/migrations/20230720173159_audit_logs__enrollment_id__add.sql
- database/tables/audit_logs.pg
> Add enrollment_id column to audit_logs table

- apps/prairielearn/assets/scripts/administratorFeaturesClient.ts
- apps/prairielearn/assets/scripts/lib/htmx.ts
- apps/prairielearn/assets/scripts/lib/morphdom.ts
- apps/prairielearn/assets/scripts/tsconfig.json
- apps/prairielearn/package.json
- apps/prairielearn/src/components/Modal.html.ts
- apps/prairielearn/src/lib/features/index.ts
- apps/prairielearn/src/lib/features/manager.sql
- apps/prairielearn/src/lib/features/manager.ts
- apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts
- apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.sql
- apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.ts
- apps/prairielearn/src/tests/accessibility/index.test.js
- yarn.lock
This will make it easier for admins to manage which features are assigned in which contexts.
> Implement in-browser editing of feature grants

- apps/prairielearn/src/middlewares/authzCourseOrInstance.js
A continuation of #8207. This work will make upcoming changes to auto-enrollment much easier to implement since we can use standard control flow.
Can be reviewed commit-by-commit. I'd recommend hiding whitespace on the diff.
> Refactor rest of authzCourseOrInstance

- apps/prairielearn/elements/pl-integer-input/pl-integer-input.mustache
- apps/prairielearn/elements/pl-integer-input/pl-integer-input.py
See title, simplifies mustache template and output behaves identically.
> style: Removed rounded right from integer input element.

- .github/workflows/main.yml
- apps/prairielearn/src/tests/manualGrading.test.js
Despite the fact that CI was green on https://github.com/PrairieLearn/PrairieLearn/pull/8280, we had failing tests, which became evident on master. I don't know why CI didn't catch this on the branch 😕
> Fix tests failing from deleted file

- graders/c/requirements.txt
These updates match the ones found by dependabot, and match those in plbase.
> Upgrade C grader Python dependencies

- apps/prairielearn/src/lib/markdown.js
- apps/prairielearn/src/tests/markdown.test.js
> Allow markdown tag to be empty

- docs/dev-guide.md
- docs/installingNative.md
- docs/running-in-production/setup.md
> Fix references to 'node server' command

- apps/prairielearn/package.json
- apps/prairielearn/src/question-servers/freeform.js
- apps/prairielearn/src/tests/api.test.js
- apps/prairielearn/src/tests/groupExam.test.ts
- apps/prairielearn/src/tests/manualGrading.test.js
- yarn.lock
This upgrade was previously avoided in #1458, but it seems the issues there may have been resolved in later versions. This also resolves  https://github.com/PrairieLearn/PrairieLearn/security/dependabot/19.
> Upgrade cheerio to 1.0.0 RC12

- apps/prairielearn/src/ee/pages/studentCourseInstanceUpgrade/studentCourseInstanceUpgrade.html.ts
So that our friends in Canada know how much things actually cost!
> Show USD label for prices

- apps/prairielearn/src/tests/manualGrading.test.ts
This is mostly a way to get more familiar with typescript.
> Translate manual grading test script to typescript

- apps/prairielearn/src/lib/code-caller/code-caller-container.js
- apps/prairielearn/src/question-servers/calculation-inprocess.js
- apps/prairielearn/src/question-servers/calculation-subprocess.js
- apps/prairielearn/src/question-servers/calculation.js
There were three separate issues here. See inline comments for more details.
> Fix calculation subprocess execution

- apps/prairielearn/src/lib/question.js
- apps/prairielearn/src/question-servers/calculation-inprocess.js
- apps/prairielearn/src/question-servers/calculation.js
Three separate issues were preventing v2 generated files from working correctly. See inline comments for details.
> Fix issues with v2 question generated files

- apps/prairielearn/src/tests/zoneGradingExam.test.js
- apps/prairielearn/src/tests/zoneGradingHomework.test.js
Makes a little more progress towards #4976.
> Use fetch API for zone grading tests

- docs/elements.md
- exampleCourse/questions/element/template/question.html
> docs: Incorrect attributes in element doc

- apps/prairielearn/python/colors.py
- package.json
- yarn.lock
Typechecking will fail until @eliotwrobson can push a fix to this branch.
> Upgrade pyright

- apps/prairielearn/src/pages/authLogout/authLogout.ts
- apps/prairielearn/src/server.js
Follows other logout work in #8446
> Convert logout to TypeScript

- apps/prairielearn/src/tests/helperQuestion.ts
> Rename helperQuestion to typescript

- apps/prairielearn/src/lib/opsbot.ts
> Convert opsbot script to typescript

- apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts
@mfsilva22 pointed out that "None" isn't a remotely good description of what that option actually does.
> Improve labels on admin feature flags modal

- .changeset/bright-dots-tickle.md
- packages/opentelemetry/src/index.ts
This is needed for some work in PrairieTest.
> Export TraceFlags from OpenTelemetry package

- apps/prairielearn/src/lib/externalGrader.sql
> Fix External Grading for Shared Questions

- apps/prairielearn/src/pages/authLogout/authLogout.ts
We could refactor this cookie delete into the session package as a library call, if we wanted to, but it seems straightforward enough to hard code it here.
> fix: remove session on logout

- .github/workflows/images.yml
As discussed in office hours last week.
> Tag all Docker images with Git SHA

- apps/prairielearn/python/python_helper_sympy.py
- apps/prairielearn/python/python_helper_sympy_test.py
See title, adds unicode decoding to the symbolic input parser along with tests.
> feat: Unicode decoding for symbolic parser

- apps/prairielearn/src/lib/externalGradingSocket.js
- apps/prairielearn/src/lib/question.js
> Fix reference to encoded data in values retrieved via web socket

- apps/prairielearn/python/prairielearn.py
- apps/prairielearn/python/python_helper_sympy.py
See title, adds helper function to resolve #8627
> fix: Add unidecode to integer input

- apps/prairielearn/package.json
- apps/prairielearn/src/lib/cache.ts
- apps/prairielearn/src/lib/socket-server.js
- apps/prairielearn/src/lib/workspace.js
- apps/workspace-host/package.json
- apps/workspace-host/src/interface.js
- apps/workspace-host/src/lib/config.js
- apps/workspace-host/src/lib/socket-server.js
- packages/workspace-utils/package.json
- packages/workspace-utils/src/index.ts
- yarn.lock
> Completely replace node-redis with ioredis

- packages/postgres/README.md
Documents the functions introduced in #7741. Closes #8659.
> Document new Postgres functions with Zod validation

- apps/prairielearn/src/pages/administratorAdmins/administratorAdmins.html.ts
- apps/prairielearn/src/pages/administratorAdmins/administratorAdmins.ts
- apps/prairielearn/src/server.js
Administrator admins page was already written without EJS. This commit converts the page to typescript. Work was done during a paired programming session with Nathan on Zoom.
> Modernize administrator admins page

- apps/prairielearn/elements/pl-integer-input/pl-integer-input.py
Fixes a minor bug where the integer input element escapes student input twice. Also, somewhat simplifies the python controller file by reducing the number of file reads.
> fix: Integer input escaping and file simplification

- apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.js
- apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.js
We are adding a flash message for course instance and assessment copy operations. Closes #8206.
> Add flash message to copy operations

- apps/prairielearn/src/lib/node-metrics.ts
This will allow us to pick up the changes from https://github.com/aws/aws-sdk-js-v3/pull/5356. We need to add an `as const` to the `metrics` array for string values to appear in the resulting type.
> Convert node-metrics to TypeScript

- docs/assessment.md
- docs/dev-guide.md
- docs/docker.md
- docs/getStarted.md
- docs/installing.md
- docs/installingLocal.md
- docs/running-in-production/admin-user.md
- docs/running-in-production/docker-compose.md
- docs/workshop/lesson2.md
Indented code blocks in the markdown docs where the code should be inside an indented section. I have updated all of the locations mentioned by @jonatanschroeder in #8199. Closes #8199.
> Indent code blocks in documentation

- .changeset/cuddly-berries-carry.md
- packages/session/src/index.test.ts
- packages/session/src/index.ts
> Allow session cookie to have an explicit domain

- apps/prairielearn/elements/pl-string-input/pl-string-input.mustache
- apps/prairielearn/elements/pl-string-input/pl-string-input.py
- exampleCourse/questions/element/stringInput/question.html
See title. Consistency changes were fairly minimal.
> feat: String input consistency

- apps/prairielearn/assets/scripts/navbarClient.ts
As suggested by @jonatanschroeder here: https://github.com/PrairieLearn/PrairieLearn/pull/8704#discussion_r1376937846. This will make consistently applying a domain in #8403 easier.
> Use same attributes for all navbar cookies

- apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.js
User must have student data viewer permission to see an assessment instance's log and data.
> Ensure proper permissions in assessment instance log page

- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/migrations/20231101173307_rubric_items__number__change_type.sql
- database/tables/rubric_items.pg
Follow-up to https://github.com/PrairieLearn/PrairieLearn/pull/8777#discussion_r1379314657. Once #8777 is merged, should also include a change in the db-types schema.
> Change type of rubric items order column

- apps/prairielearn/src/lib/manualGrading.sql
- apps/prairielearn/src/lib/manualGrading.ts
> Convert manual grading lib to typescript

- apps/grader-host/package.json
- apps/prairielearn/package.json
- apps/workspace-host/package.json
- yarn.lock
Picks up the changes from https://github.com/caolan/async/pull/1920.
> Upgrade to latest version of async library

- apps/prairielearn/src/lib/manualGrading.ts
- apps/prairielearn/src/pages/partials/editQuestionPointsForm.ejs
- apps/prairielearn/src/pages/partials/editQuestionScorePercForm.ejs
Upload already handles this. Manual grading instance questions as well.
> Add validation of score/points format in manual grading

- apps/prairielearn/src/lib/question.js
- apps/prairielearn/src/question-servers/freeform.js
Captures and displays durations of various question operations in question test jobs. The output looks like this:
Closes #8822.
> Collect duration statistics during question testing

- apps/prairielearn/src/lib/externalGrader.ts
- apps/prairielearn/src/lib/externalGraderLocal.js
- apps/prairielearn/src/lib/externalGraderSqs.js
> Convert externalGrader library to typescript

- apps/prairielearn/assets/scripts/institutionAdminCourseInstanceClient.ts
- apps/prairielearn/assets/scripts/institutionAdminGeneralClient.ts
- apps/prairielearn/assets/scripts/instructorInstanceAdminBillingClient.ts
- apps/prairielearn/assets/scripts/lib/countdown.ts
- apps/prairielearn/assets/scripts/lib/mathjax.ts
- apps/prairielearn/assets/scripts/navbarClient.ts
- apps/prairielearn/assets/scripts/question.ts
- apps/prairielearn/assets/scripts/studentCourseInstanceUpgradeClient.ts
- apps/prairielearn/assets/scripts/tsconfig.json
- apps/prairielearn/assets/scripts/workspaceClient.ts
- apps/prairielearn/src/ee/lib/billing/components/InstructorInstanceAdminBillingForm.html.ts
This is a best practice, and it will also be required for Zod to work correctly for client-side data parsing/validation.
> Enable strict typechecking for assets scripts

- apps/prairielearn/src/pages/instructorIssues/instructorIssues.js
I'll be making some changes to this page in another PR soon; I wanted to refactor it to async/await ahead of time. I'm deliberately choosing not to convert to TypeScript, rewrite in ESM, or make any other changes at this time.
> Refactor instructor issues page to async/await

- apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.js
Similar to #8839. As with that PR, I'm deliberately choosing not to convert to TypeScript, rewrite in ESM, or make any other changes at this time.
> Refactor instructor course admin staff page to use async/await

- docs/faq.md
The previous wording caused some confusion; hopefully this is clearer.
> Improve student assessment access FAQ

- apps/prairielearn/src/pages/instructorQuestionPreview/instructorQuestionPreview.js
An async function with a callback argument is very obviously broken!
> Fix instructor issue reporting error handling

- apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ejs
As requested here: https://github.com/PrairieLearn/PrairieLearn/pull/8602#issuecomment-1811085303
> Change color of public sharing button

- Makefile
- apps/prairielearn/src/migrations/20231116005437_drop_mongodb_columns.sql
- database/tables/assessment_instances.pg
- database/tables/submissions.pg
- database/tables/variants.pg
> Drop unused columns left over from MongoDB migration

- apps/prairielearn/src/lib/externalGradingSocket.js
- apps/prairielearn/src/lib/github.js
- apps/prairielearn/src/lib/id.js
- apps/prairielearn/src/lib/load.js
- apps/prairielearn/src/lib/markdown.js
- apps/prairielearn/src/lib/paginate.js
- apps/prairielearn/src/lib/questionPreview.js
- apps/prairielearn/src/lib/require-frontend.js
- apps/prairielearn/src/lib/uri-util.js
This PR is part of the larger modernization efforts. This PR intends to add type checking to any files that do not already include `//@ts-check` but are touched by #8871.
> Add type checking to pl lib files

- apps/prairielearn/assets/scripts/workspaceClient.ts
- apps/prairielearn/src/lib/workspace.js
Follows up on #8807 to enforce authentication for workspace sockets.
> Enable authentication for workspace sockets

- exampleCourse/questions/demo/randomFakeData/server.py
I observed a test failure on https://github.com/PrairieLearn/PrairieLearn/actions/runs/7026483117/job/19119289551 caused by the same name ("Angela Adams") being selected twice. It's crazy it witness such an unlikely event actually happening!
By using a set to construct names, we ensure uniqueness, just like with birthdays.
> Ensure uniqueness of random data

- apps/prairielearn/src/admin_queries/generate_assessment_instances.sql
- apps/prairielearn/src/admin_queries/generate_assessment_instances_group.sql
> Fix admin queries that create assessment instances

- apps/prairielearn/elements/pl-dataframe/pl-dataframe.py
See title, resolves #8915 by changing function calls.
> fix: Avoid deprecation warnings in `pl-dataframe` element

- pyproject.toml
As suggested here: https://github.com/PrairieLearn/PrairieLearn/pull/8920#discussion_r1409940712
> Configure Pyright to report unnecessary ignore comments

- apps/prairielearn/src/lib/github.js
Unsurprisingly, when something went wrong during repo creation, we blew through our rate limit polling 10 times per second. This PR makes a few improvements to this process:
- Poll only once per second; these jobs don't need to run _that_ fast.
- If we get an error other than a 404, immediately abort.
- Poll for at most 30 seconds.
- Mark the job as a whole as failed if an error is encountered.
This still needs to be tested once we're no longer being rate-limited.
> Improve polling for GitHub repository creation

- apps/prairielearn/src/lib/github.js
AFAICT it makes more sense to send these logs to the job itself instead of the process output.
> Log repo creation progress to job

- apps/prairielearn/src/lib/assessment.sql
- apps/prairielearn/src/lib/question-render.js
- apps/prairielearn/src/lib/question-testing.js
- apps/prairielearn/src/lib/question-variant.js
- apps/prairielearn/src/migrations/20231201011351_variants__client_fingerprint_id__add.sql
- apps/prairielearn/src/sprocs/variants_insert.sql
- database/tables/client_fingerprints.pg
- database/tables/variants.pg
> Add client_fingerprint_id to variants

- apps/prairielearn/src/components/QuestionsTable.html.ts
> Fix visibility of assessments column in questions page

- apps/prairielearn/src/tests/sprocs/check_assessment_access.test.js
- apps/prairielearn/src/tests/sprocs/check_course_instance_access.test.js
- apps/prairielearn/src/tests/sprocs/ip_to_mode.test.js
- apps/prairielearn/src/tests/sync/assessmentSetsSync.test.js
- apps/prairielearn/src/tests/sync/initialSync.test.js
- apps/prairielearn/src/tests/sync/util.js
Some mechanical refactoring ahead of ESM conversions.
> Refactor some tests to use type checking and async/await

- apps/prairielearn/package.json
- apps/prairielearn/src/ee/auth/lti13/lti13Auth.ts
- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/tests/helperClient.ts
- apps/prairielearn/src/tests/lti13.test.ts
- yarn.lock
This PR implements end-to-end testing of LTI 1.3 authentication being introduced in #8855. It also happens to test the creation and configuration of LTI 1.3 instances.
> LTI 1.3 authentication testing

- apps/prairielearn/src/pages/submissionFile/submissionFile.js
- apps/prairielearn/src/server.js
- apps/prairielearn/src/tests/accessibility/index.test.js
> Enable submission file endpoint on public question previews

- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.js
- apps/prairielearn/src/server.js
> instructorRequestCourse page to ESM

- apps/prairielearn/src/question-servers/index.ts
Precursor to the work in #9069, with minimal changes in the file, so that rename is tracked in the history. The actual types will be set in #9069, to be merged after this one is merged to master.
> Rename question-servers main file to Typescript

- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.ejs
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.js
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.sql
More modernization work. Converted to queryRow[s] and Zod checking.
> Convert instructorRequestCourse page to parsed SQL

- apps/prairielearn/src/lib/grading.js
- apps/prairielearn/src/lib/question-testing.js
- apps/prairielearn/src/question-servers/index.ts
Follow-up to #9069. Adds types to the data parameter for the callback functions for question servers.
> Add return data types for question server functions

- apps/prairielearn/src/pages/administratorCourses/administratorCourses.ejs
- apps/prairielearn/src/pages/administratorCourses/courseUpdateColumn.ejs
Small quality-of-life improvement for admins.
> Add links to institution/course on admin courses page

- apps/prairielearn/src/lib/grading.ts
- apps/prairielearn/src/question-servers/index.ts
> Convert grading library to typescript

- apps/prairielearn/src/pages/administratorCourses/administratorCourses.ejs
This was accidentally removed while resolving merge conflicts in #2378.
> Restore branch editing on admin courses page

- apps/prairielearn/src/lib/assessment.sql
- apps/prairielearn/src/lib/assessment.ts
- apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.js
This PR intends to add client fingerprint data to the assessment instance event log CSV file. In the first iteration of this, I have added the client fingerprint number and IP address to the CSV file. Please review and let me know of any improvements that can be made or other client fingerprint data you would like to see included. 
This feature has been requested and seeks to address one of the additional features to be implemented from #8924.
> Add client fingerprint number and IP address to CSV file

- apps/prairielearn/src/lib/workspace.ts
> Convert workspace library to typescript

- apps/prairielearn/src/pages/partials/questionFooter.ejs
Extracted from #9106 to make review easier. The two versions of the footer (freeform vs v2) are almost identical, but with minor changes.
> Deduplicate code in question footer partial

- apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.js
- apps/prairielearn/src/pages/instructorCourseAdminTags/instructorCourseAdminTags.js
- apps/prairielearn/src/pages/instructorCourseAdminTopics/instructorCourseAdminTopics.js
- apps/prairielearn/src/pages/instructorEffectiveUser/instructorEffectiveUser.js
- apps/prairielearn/src/pages/instructorFileDownload/instructorFileDownload.js
- apps/prairielearn/src/pages/instructorFileTransfer/instructorFileTransfer.js
- apps/prairielearn/src/pages/instructorInstanceAdminAccess/instructorInstanceAdminAccess.js
- apps/prairielearn/src/pages/instructorInstanceAdminLti/instructorInstanceAdminLti.js
- apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.js
- apps/prairielearn/src/pages/instructorIssues/instructorIssues.js
- apps/prairielearn/src/pages/instructorJobSequence/instructorJobSequence.js
- apps/prairielearn/src/pages/instructorQuestionStatistics/instructorQuestionStatistics.js
- apps/prairielearn/src/pages/news_item/news_item.js
- apps/prairielearn/src/pages/news_items/news_items.js
This PR seeks to add type checking to several of the instructor pages as well as `news_item.js` and `news_items.js`. This PR is part of the larger modernization efforts. As part of that effort, this PR intentionally only adds type checking and fixes any errors identified by TypeScript. Other steps towards modernizing these pages will come in subsequent PRs.
> Add TS Check

- yarn.lock
Resolves https://github.com/PrairieLearn/PrairieLearn/security/dependabot/153.
> Bump follow-redirects to 1.15.4

- apps/prairielearn/src/ee/auth/lti13/lti13Auth.html.ts
- apps/prairielearn/src/ee/auth/lti13/lti13Auth.ts
- apps/prairielearn/src/ee/pages/institutionAdminLti13/institutionAdminLti13.html.ts
- apps/prairielearn/src/ee/pages/institutionAdminLti13/institutionAdminLti13.ts
- apps/prairielearn/src/ee/pages/lti13Instance/lti13Instance.ts
> LTI 1.3 auth debugging and bug fixes

- apps/prairielearn/src/pages/administratorNetworks/administratorNetworks.js
- apps/prairielearn/src/pages/authPassword/authPassword.js
- apps/prairielearn/src/pages/editError/editError.js
- apps/prairielearn/src/pages/home/home.js
- apps/prairielearn/src/pages/studentAssessmentInstanceFile/studentAssessmentInstanceFile.js
- apps/prairielearn/src/pages/studentAssessmentInstanceTimeRemaining/studentAssessmentInstanceTimeRemaining.js
- apps/prairielearn/src/pages/studentAssessments/studentAssessments.js
- apps/prairielearn/src/pages/studentGradebook/studentGradebook.js
This PR is part of the larger modernization process and intends to add type checking to several pages that do not already do so. This will allow for further modernization efforts to these files in forthcoming PRs.
> Add ts-check to pages

- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/migrations/20240111010531_groups__group_config_id__not_null.sql
- database/tables/groups.pg
Like #8919, but for the `groups` table.
> Make groups.group_config_id NOT NULL

- apps/prairielearn/src/ee/models/enrollment.ts
This fixes an issue that one of our courses using student billing was facing.
Consider the following scenario:
- A course instance has a limit of 20 enrollments.
- 20 students enroll.
- The instructor enables student billing.
- A 21st student pays and tries to enroll.
With our old limit checking, we'd see that the course has hit 20/20 enrollments and block the 21st (paid) user from enrolling. Now, we'll allow it.
Note that this was only a problem when none of the original free students tried to access the course after student billing was enabled. If they did, they'd be prompted to pay, and after paying, they'd be counted as a paid user for enrollment limit calculations and thus we'd only count 19/20 free enrollments and everything would work fine from that point.
> Fix enrollment limits for paid users

- apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ts
> Convert manual grading instance question page to TS

- apps/prairielearn/src/lib/question-testing.js
These functions were already using async.series, so many of the changes were already partially done.
> Convert question-testing library functions to async

- apps/prairielearn/src/models/workspace.sql
- apps/prairielearn/src/models/workspace.ts
- apps/prairielearn/src/pages/workspace/workspace.html.js
- apps/prairielearn/src/pages/workspace/workspace.js
Closes #9227. I also updated the visual style of the label too, including replacing "PL" with "PrairieLearn" (since we don't really refer to ourselves as "PL" in our official docs or product).
For student exam:
For student homework:
For instructor preview:
> Add question link to workspace navbar

- apps/prairielearn/src/lib/question-testing.ts
> Convert question testing library to Typescript

- apps/prairielearn/src/lib/course.ts
> Add missing directory argument to git restore command

- apps/prairielearn/src/tests/access.test.ts
- apps/prairielearn/src/tests/homework.test.ts
- apps/prairielearn/src/tests/instructorQuestions.test.ts
- apps/prairielearn/src/tests/zoneGradingExam.test.ts
- apps/prairielearn/src/tests/zoneGradingHomework.test.ts
Getting us one step closer to nuking `async-stacktrace`...
> Convert some tests to async query functions

- apps/prairielearn/src/lib/groups.ts
- apps/prairielearn/src/tests/instructorAssessmentGroups.test.ts
Resolves #9297. Also adds a test to ensure this is possible again in the future.
> Restore ability to add instructors to assessment groups

- .github/workflows/main.yml
- .github/workflows/release.yml
> Update Node version in CI configuration

- apps/prairielearn/src/lib/assessment.sql
- apps/prairielearn/src/lib/groups.sql
- apps/prairielearn/src/migrations/20240131192701_group_logs__roles__add.sql
- database/tables/group_logs.pg
> Add roles to group logs

- graders/python/Dockerfile
- graders/python/install.sh
As discussed on Slack, this is highly unlikely to break for anyone not doing horrible and contrived things with Python.
> Use Amazon Linux 2023 for Python grader image

- apps/prairielearn/src/pages/authCallbackLti/authCallbackLti.js
- apps/prairielearn/src/tests/lti.test.ts
This was done primarily with the goal of fixing broken nonce checking; see inline comment for more details. However, that was easiest to do by just rewriting all the code to use `async`/`await`, which I did. I also took the opportunity to improve the HTTP status codes used here.
Best reviewed with whitespace changes hidden.
> Refactor authCallbackLti

- apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.js
This PR intends to convert callback functions to `async/await` in the instructorCourseAdminSettingsPage. This is part of the larger modernization efforts and future PRs will convert this page to TypeScript.
> Convert course settings page to async/await

- apps/prairielearn/src/pages/instructorIssues/instructorIssues.ejs
- docs/saml.md
- exampleCourse/infoCourse.json
- exampleCourse/questions/demo/autograder/ansiOutput/info.json
- exampleCourse/questions/element/graph/info.json
- exampleCourse/questions/element/markdown/info.json
- testCourse/infoCourse.json
I noticed that my Illinois email was actually part of the issues UI 😬 I decided to remove all references to my old Illinois NetID while I was cleaning that up.
> Remove all references to nwalter2

- apps/prairielearn/src/pages/administratorInstitutions/administratorInstitutions.sql
This uses the same sort order as PrairieTest.
> Sort institution list alphabetically

- exampleCourse/questions/demo/autograder/python/randomFunctionName/question.html
one of the randomized parameters was mentioned in text html, but had "params" missing
> fixed question.html

- apps/prairielearn/src/sync/infofile.ts
> Update types in infofile library for sync

- graders/python/requirements.txt
- images/plbase/python-requirements.txt
- workspaces/jupyterlab-python/requirements.txt
As requested by @ffund on Slack.
> Install seaborn in all Python environments

- apps/prairielearn/src/models/institution.sql
> Sort when selecting all institutions

- apps/prairielearn/src/server.js
- packages/opentelemetry/package.json
- packages/opentelemetry/src/init.ts
- yarn.lock
My editor flagged some of these functions as deprecated. This PR replaces them with their recommended replacements.
> Replace usage of deprecated OpenTelemetry functionality

- apps/prairielearn/src/models/course-permissions.sql
- apps/prairielearn/src/models/course-permissions.ts
Resolves #9452. This is one possible approach, I'm open to alternatives.
> Change course permission delete process to accept arrays

- apps/prairielearn/src/cron/index.js
Best reviewed with whitespace changes hidden.
> Convert cron job executor to ESM

- apps/prairielearn/src/cron/index.js
- apps/prairielearn/src/tests/cron.test.ts
Depends on #9481. Best reviewed with whitespace changes hidden.
> Use async/await for cron jobs

- apps/prairielearn/src/news_items/index.js
- apps/prairielearn/src/server.js
- apps/prairielearn/src/tests/accessibility/index.test.ts
- apps/prairielearn/src/tests/newsItems.test.ts
> Fix news item lock contention

- .changeset/calm-garlics-hear.md
- apps/prairielearn/src/lib/course.ts
- apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.js
- packages/migrations/src/batched-migrations/batched-migrations-runner.ts
- packages/named-locks/README.md
- packages/named-locks/src/index.ts
As discussed here: https://github.com/PrairieLearn/PrairieLearn/pull/9475#discussion_r1506867150
Depends on #9480.
> Simplify named locks

- apps/prairielearn/src/pages/instructorIssues/instructorIssues.js
- apps/prairielearn/src/pages/instructorIssues/instructorIssues.sql
Fixes errors introduced in #9472.
> Fix issue closing

- apps/prairielearn/elements/pl-multiple-choice/info.json
- apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.mustache
- apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.py
- apps/prairielearn/package.json
- docs/elements.md
- exampleCourse/questions/element/multipleChoice/question.html
- exampleCourse/questions/element/multipleChoice/serverFilesQuestion/sky-color.json
- exampleCourse/questions/workshop/Lesson5_example2/question.html
- pyproject.toml
- yarn.lock
This reverts commit 63c5d012324f126934c920c38abdd7beae77be44. Discussed on Slack with @nwalters512. Will re-merge once deploy issues are resolved.
> Revert "refactor: Multiple choice rework (#8903)"

- apps/prairielearn/src/lib/editors.js
- apps/prairielearn/src/tests/courseEditor.test.sql
- apps/prairielearn/src/tests/courseEditor.test.ts
- apps/prairielearn/src/tests/fileEditor.test.sql
- apps/prairielearn/src/tests/fileEditor.test.ts
This mirrors a similar safety check here:
https://github.com/PrairieLearn/PrairieLearn/blob/61115813fe0484c22284e27c5770e7b2e64b5338/apps/prairielearn/src/lib/course.ts#L94-L97
> Assert defined course branch and repository in file editor

- apps/prairielearn/src/lib/server-jobs.ts
As we prepare to deploy syncing changes, this should give us a little more information.
> Log timing information for processes in server jobs

- apps/prairielearn/src/sprocs/sync_course_instances.sql
- apps/prairielearn/src/sprocs/sync_questions.sql
- apps/prairielearn/src/sync/course-db.ts
- apps/prairielearn/src/sync/fromDisk/assessmentModules.ts
- apps/prairielearn/src/sync/fromDisk/assessmentSets.ts
- apps/prairielearn/src/sync/fromDisk/assessments.ts
- apps/prairielearn/src/sync/fromDisk/courseInfo.ts
- apps/prairielearn/src/sync/fromDisk/courseInstances.ts
- apps/prairielearn/src/sync/fromDisk/questions.ts
- apps/prairielearn/src/sync/fromDisk/tags.ts
- apps/prairielearn/src/sync/fromDisk/topics.ts
All these files were already type-checked, so this was a pretty straightforward conversion.
> Convert syncing code to TypeScript

- apps/prairielearn/src/sync/course-db.ts
- apps/prairielearn/src/sync/fromDisk/assessments.js
- apps/prairielearn/src/sync/fromDisk/assessments.ts
- apps/prairielearn/src/sync/syncFromDisk.ts
- apps/prairielearn/src/tests/sync/assessmentsSync.test.sql
- apps/prairielearn/src/tests/sync/assessmentsSync.test.ts
This is being done ahead of #9586 to avoid significant user-facing impact. See comment thread here: https://github.com/PrairieLearn/PrairieLearn/pull/9586#discussion_r1524024563
> Don't check exam UUIDs for inaccessible course instances

- apps/prairielearn/src/components/CourseRequestsTable.html.ts
- apps/prairielearn/src/lib/course-request.sql
- apps/prairielearn/src/lib/course-request.ts
- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/migrations/20240307213407_course_requests__referral_source__add.sql
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.html.ts
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.sql
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.ts
- database/tables/course_requests.pg
Predefined option selected:
"Other" option shows a text input:
Updated "Course Requests" table:
> Add referral source to course request page

- apps/prairielearn/src/lib/regrading.js
- apps/prairielearn/src/pages/instructorAssessmentRegrading/instructorAssessmentRegrading.js
Convert regrading process to async and to use the new server jobs library.
> Convert regrading process to async

- docker/start_s3rver.sh
Shell scripts are hard, and I didn't sufficiently test my changes from #9584.
> Fix start_s3rver script

- apps/prairielearn/src/ee/auth/azure/index.ts
- apps/prairielearn/src/pages/authLoginOAuth2/authLoginOAuth2.js
I'm doing this ahead of our upcoming work to collect emails during user authentication.
These match the scopes that we use for Google auth:
https://github.com/PrairieLearn/PrairieLearn/blob/ad9329a2c44c10d9bfdf18f6eb5c0bbb991901e0/apps/prairielearn/src/pages/authLoginOAuth2/authLoginOAuth2.js#L29
> Request user email from Azure

- apps/prairielearn/src/lib/db-types.ts
Jonatan pointed out that I missed this in #9615.
> Remove role column from EnrollmentSchema

- apps/prairielearn/src/lib/copy-question.ts
Resolves #9619. Both cases would cause error if the copy were to be performed.
(Review ignoring whitespaces)
> Remove source and example courses from copy target list

- packages/workspace-utils/src/index.ts
We've seen a low rate of failures related to this in production. This change should let the disk usage computation run more reliably.
> Fix TOCTOU bug in workspace disk usage computation

- exampleCourse/questions/demo/workspace/desktop/question.html
This is mostly for consistency and to allow easier testing of results. Other workspace demo questions already include this.
> Add file preview to example question for desktop workspace

- .changeset/eighty-badgers-grin.md
- apps/prairielearn/src/lib/editors.js
- apps/prairielearn/src/lib/instructorFiles.js
- apps/prairielearn/src/middlewares/authzCourseOrInstance.js
- packages/error/package.json
- packages/error/src/index.ts
- yarn.lock
The main change that had to be made here was figuring out how to make TypeScript happy with attaching "info" to errors. I opted to introduce a new `AugmentedError` class that I hope will eventually take the place of all our `makeWith...` error utilities.
> Turn on typechecking for authzCourseOrInstance

- apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.html.ts
- apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- apps/prairielearn/src/pages/instructorAssessmentQuestions/instructorAssessmentQuestions.ejs
> Only show actions dropdown if permissions allow actions

- apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.js
- apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.sql
- newCourse/courseInstances/New_1/infoCourseInstance.json
This PR intends to convert the `instructorAssessmentSettings` page from callback functions to `async/await` and to use Zod-validated queries.
> Convert Assessment Settings page to async

- apps/prairielearn/src/lib/authn.js
- apps/prairielearn/src/lib/redirect.ts
- apps/prairielearn/src/middlewares/autoEnroll.ts
- apps/prairielearn/src/models/enrollment.ts
- apps/prairielearn/src/pages/enroll/enroll.ts
- apps/prairielearn/src/server.js
As discussed on Slack. See inline comment for motivation. I adapted two functions to use this new functionality, and I think it makes them much nicer to reason about!
> Add support for throwing redirects

- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/pages/userSettings/userSettings.html.ts
- apps/prairielearn/src/pages/userSettings/userSettings.ts
This ensures students can't use access tokens to smuggle information into or out of secure testing facilities.
> Forbid access token viewing/creation in exam mode

- docs/question.md
This should hopefully make things clearer for folks who aren't yet familiar with the exact behavior of Exam-type assessments.
> Clarify how singleVariant questions work on Exam assessments

- apps/prairielearn/src/components/CourseRequestsTable.html.ts
> Add step to confirm denial of course requests

- apps/prairielearn/src/lib/editors.js
- apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ts
- apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.js
- apps/prairielearn/src/tests/instructorCourseAdminSettings.test.ts
I recommend reviewing with whitespace changes hidden.
> Refactor instructor file editor to use async/await

- apps/grader-host/package.json
- apps/grader-host/src/index.js
- apps/grader-host/src/lib/config.ts
- apps/grader-host/src/lib/healthCheck.js
- apps/grader-host/src/lib/lifecycle.js
- apps/grader-host/src/lib/load.js
- apps/grader-host/src/lib/logger.js
- apps/grader-host/src/lib/pullImages.js
- apps/grader-host/src/lib/receiveFromQueue.js
- apps/grader-host/src/lib/timeReporter.js
- apps/grader-host/src/tests/receiveFromQueue.test.js
- tools/cjs-to-esm-candidates.mjs
- yarn.lock
I also added `// @ts-check` as I went.
I tested a build of this in our staging environment, and everything appears to work correctly!
> Convert grader-host to ESM

- apps/prairielearn/src/middlewares/selectAndAuthzAssessment.js
- apps/prairielearn/src/server.js
Lifting this out of #9103 to minimize changes there.
> Convert selectAndAuthzAssessment to async/await

- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/pages/instructorAssessmentRegrading/instructorAssessmentRegrading.js
- apps/prairielearn/src/pages/instructorAssessmentUploads/instructorAssessmentUploads.js
This PR intends to convert the `instructorAssessmentRegrading` and `instructorAssessmentUploads` pages to async as well as use Zod-validated queries.
> Convert instructor assessment regrading and upload pages to async

- apps/prairielearn/src/lib/assessment.ts
- apps/prairielearn/src/lib/aws.js
- apps/prairielearn/src/lib/chunks.ts
- apps/prairielearn/src/lib/externalGrader.ts
- apps/prairielearn/src/lib/file-store.js
- apps/prairielearn/src/lib/github.js
- apps/prairielearn/src/lib/ltiOutcomes.js
- apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.js
- apps/prairielearn/src/tests/helperQuestion.ts
Also removes unused callback-based variants of functions.
> Remove unnecessary Async suffixes from function names

- apps/prairielearn/src/lib/course.ts
- apps/prairielearn/src/pages/instructorGradebook/instructorGradebook.js
Also removed last instance of the callback version of `checkBelongs`. Since this name was ambiguous and needed to be renamed anyway, I also gave it a more meaningful name.
> Convert instructor gradebook to async

- apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js
> Typeset formulas in rubric items on update of rubric settings

- apps/prairielearn/src/pages/instructorEffectiveUser/instructorEffectiveUser.js
- apps/prairielearn/src/pages/instructorFileDownload/instructorFileDownload.js
- apps/prairielearn/src/pages/instructorInstanceAdminAccess/instructorInstanceAdminAccess.js
This PR intends to convert more pages to async/await and use Zod-validated queries where applicable.
> Convert more instructor pages to async/await

- apps/prairielearn/src/pages/instructorCourseAdminInstances/instructorCourseAdminInstances.js
- apps/prairielearn/src/pages/instructorCourseAdminSets/instructorCourseAdminSets.js
- apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.js
- apps/prairielearn/src/pages/instructorCourseAdminTags/instructorCourseAdminTags.js
- apps/prairielearn/src/pages/instructorCourseAdminTopics/instructorCourseAdminTopics.js
This PR intends to convert the remaining `instructorCourseAdmin` pages to use async/await and Zod-validated queries where applicable.
> Convert instructor course admin pages to async

- .changeset/bright-bats-act.md
- packages/cache/README.md
- packages/cache/src/index.ts
I noticed some room for improvement here while working on my native ESM branch.
> Refine @prairielearn/cache package

- apps/prairielearn/src/sprocs/sync_assessments.sql
Closes #9836. This won't take effect until courses re-sync.
A fun fact: we currently pretty much always sort assessments by three columns when selecting them, for instance:
https://github.com/PrairieLearn/PrairieLearn/blob/e88d079812180315e2ce90d8605fdffbe01a8185/apps/prairielearn/src/middlewares/selectAssessments.sql#L15-L18
However, from what I can see, the `id` column will never be used, because `order_by` will always contain fully unique values, and so we'll never fall back to ordering on the `id`. AFAICT this is a relic of when we used to sort by `assessments.number` directly: https://github.com/PrairieLearn/PrairieLearn/commit/8cebe15ab7bd63ef2f3493027d2550ad2105a522.
I'm sort of inclined to go through the codebase and remove `assessments.id` as a fallback ordering for …
> Ensure stable ordering of assessments

- .codecov.yml
This issue was helpfully pointed out by someone from Codecov on https://github.com/codecov/feedback/issues/386.
> Fix Codecov status configuration

- apps/prairielearn/src/sync/course-db.ts
- tools/verify_course_repo.mjs
Extracted from #9883. This script had not been updated when the signature of loadFullCourse was updated in #9315.
Best reviewed with hiding space changes.
> Fix verify_course_repo script in tools

- apps/prairielearn/src/lib/externalGraderCommon.test.ts
- apps/prairielearn/src/lib/externalGraderCommon.ts
> Convert external grader common library to TS

- apps/prairielearn/src/lib/uri-util.test.ts
- apps/prairielearn/src/lib/uri-util.ts
> Convert URI util library to typescript

- apps/prairielearn/src/lib/editors.ts
This refactor takes the file editor another step away from being a big ball of mutable class properties. This also makes it easier for TypeScript to ensure correct behavior: it won't catch missing assignments to `this.commitMessage` or `this.pathsToAdd`, but it will catch missing or invalid returned objects.
> Return git paths and commit message from file editor write() function

- apps/prairielearn/src/cron/serverUsage.ts
- apps/prairielearn/src/lib/editors.ts
- apps/prairielearn/src/lib/workspace.ts
- apps/prairielearn/src/middlewares/clientFingerprint.ts
- apps/prairielearn/src/tests/permissions/effectiveUser.test.ts
- apps/prairielearn/src/tests/sync/assessmentsSync.test.ts
- packages/postgres-tools/src/describe.ts
- packages/postgres-tools/src/diff.ts
Super minor cleanup. These comments aren't required in `.ts` files.
> Remove unnecessary ts-check comments

- docs/questionSharing.md
Standardize header capitalization within this file and make it consistent with other docs.
> Fix capitalization in question sharing doc headers

- apps/prairielearn/src/lib/copy-question.ts
> Point copy question links to new endpoint

- apps/prairielearn/src/pages/studentAssessments/studentAssessments.ts
- apps/prairielearn/src/pages/studentGradebook/studentGradebook.ts
Follow-up to recent changes to these pages.
> Convert student assessments and gradebook to typescript

- apps/prairielearn/src/pages/legacyQuestionFile/legacyQuestionFile.js
Seems like we don't have tests for this page, so this wasn't caught in #9841.
> Fix unused SQL parameter in legacyQuestionFile page

- apps/workspace-host/package.json
- apps/workspace-host/src/interface.js
- yarn.lock
Best reviewed with whitespace changes hidden.
> Remove remaining callbacks from workspace-host

- apps/prairielearn/src/server.js
deploy after #9918, replaces #9919
> Remove old copy template question endpoint

- package.json
- yarn.lock
Closes https://github.com/PrairieLearn/PrairieLearn/issues/9987
See discussion on the issue. I may be off the mark here or this may have other bad side effects for how yarn is set up for the project as a whole, so I anticipate this PR might need to be closed without merging, but I was curious to see if the CI would succeed or if the image size would be impacted.
> Add node-gyp to yarn explicitly

- apps/prairielearn/package.json
- apps/prairielearn/src/ee/auth/saml/router.ts
- apps/prairielearn/src/pages/instructorInstanceAdminLti/instructorInstanceAdminLti.js
- apps/prairielearn/src/tests/courseEditor.test.sql
- apps/prairielearn/src/tests/courseEditor.test.ts
- apps/prairielearn/src/tests/exam.test.ts
- apps/prairielearn/src/tests/fileEditor.test.sql
- apps/prairielearn/src/tests/fileEditor.test.ts
- apps/prairielearn/src/tests/groupScoreAndSync.test.ts
- apps/prairielearn/src/tests/groupStudent.test.ts
- apps/prairielearn/src/tests/helperServer.ts
- apps/prairielearn/src/types/async-stacktrace.d.ts
- yarn.lock
This leaves just three files in `apps/grader-host` that use `async-stacktrace` 🎉 
I recommend reviewing this with whitespace changes hidden.
> Remove last usages of async-stacktrace from PrairieLearn app

- apps/prairielearn/src/sprocs/sync_topics.sql
> Fix function call in `sync_topics.sql`

- apps/prairielearn/src/pages/studentAssessment/studentAssessment.html.ts
> Fix reference to studentAssessmentClient script

- apps/prairielearn/package.json
- yarn.lock
Resolves https://github.com/PrairieLearn/PrairieLearn/security/dependabot/173.
> Bump ws to 7.5.11 in all sub-dependencies

- apps/prairielearn/elements/pl-drawing/pl-drawing.js
- apps/prairielearn/elements/pl-drawing/pl-drawing.py
> Update `pl-drawing` to respect `data["editable"]`

- apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts
- apps/prairielearn/elements/pl-dropdown/pl-dropdown.mustache
- apps/prairielearn/elements/pl-matching/pl-matching.mustache
- apps/prairielearn/src/components/CourseRequestsTable.html.ts
- apps/prairielearn/src/components/QuestionContainer.html.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionGeneral/administratorInstitutionGeneral.html.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionLti13/administratorInstitutionLti13.html.ts
- apps/prairielearn/src/pages/administratorCourses/administratorCourses.html.ts
- apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts
- apps/prairielearn/src/pages/administratorInstitutions/administratorInstitutions.html.ts
- apps/prairielearn/src/pages/instructorAssessmentGroups/instructorAssessmentGroups.html.ts
- apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.html.ts
- apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.html.ts
- apps/prairielearn/src/pages/instructorEffectiveUser/instructorEffectiveUser.ejs
- apps/prairielearn/src/pages/instructorInstanceAdminLti/instructorInstanceAdminLti.ejs
- apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts
Having this class in place will allow for an easier upgrade to Bootstrap 5.
https://getbootstrap.com/docs/4.6/components/forms/#select-menu
> Use Bootstrap custom-select class for all select elements

- apps/prairielearn/src/pages/studentAssessmentInstanceTimeRemaining/studentAssessmentInstanceTimeRemaining.js
This is a precursor to converting this file to TS.
> Update time remaining router to use modern conventions

- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.ts
> Remove unused parameter from course request query

- apps/prairielearn/src/pages/authCallbackOAuth2/authCallbackOAuth2.ts
- apps/prairielearn/src/pages/authCallbackShib/authCallbackShib.ts
- apps/prairielearn/src/pages/authLoginOAuth2/authLoginOAuth2.ts
- apps/prairielearn/src/pages/clientFilesAssessment/clientFilesAssessment.ts
- apps/prairielearn/src/pages/clientFilesCourse/clientFilesCourse.ts
- apps/prairielearn/src/pages/clientFilesCourseInstance/clientFilesCourseInstance.ts
- apps/prairielearn/src/pages/clientFilesQuestion/clientFilesQuestion.ts
- apps/prairielearn/src/pages/elementExtensionFiles/elementExtensionFiles.ts
- apps/prairielearn/src/pages/elementFiles/elementFiles.ts
- apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts
- apps/prairielearn/src/pages/instructorFileDownload/instructorFileDownload.ts
- apps/prairielearn/src/pages/studentAssessmentInstanceTimeRemaining/studentAssessmentInstanceTimeRemaining.ts
- apps/prairielearn/src/pages/submissionFile/submissionFile.ts
These are router pages that don't link to separate EJS/HTML.TS files for rendering.
> Convert more router files to Typescript

- apps/prairielearn/package.json
- apps/prairielearn/src/lib/markdown.test.ts
- apps/prairielearn/src/lib/markdown.ts
- yarn.lock
Starting point to implementing https://github.com/PrairieLearn/PrairieLearn/issues/6480#issuecomment-2195169680. A future PR can convert some relevant parts of this functionality to a package.
> Convert markdown lib to Typescript

- apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.html.ts
- apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.sql
- apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.ts
The accessibility changes here (adding two missing labels for form inputs) will be necessary for CI to pass on #10098.
While I was here, I ended up refactoring things to better match our conventions.
> Improve accessibility of instructor sharing settings

- apps/prairielearn/src/pages/partials/navbar.ejs
> Fix undefined mode listing in public question page

- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.html.ts
Before:
After:
This will help things look nicer with the updated Bootstrap 5 styles.
> Improve display of checkboxes on course request form

- exampleCourse/courseInstances/SectionA/assessments/gallery/questions/infoAssessment.json
> Fix text of question gallery assessment

- apps/prairielearn/src/lib/editors.ts
> Drop tags when adding/copying template questions

- apps/prairielearn/assets/scripts/instructorGradebookClient.ts
- apps/prairielearn/assets/scripts/lib/questionsTable.js
- apps/prairielearn/src/components/AssessmentBadge.html.ts
- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/pages/instructorAssessmentQuestions/instructorAssessmentQuestions.html.ts
- apps/prairielearn/src/pages/instructorIssues/instructorIssues.html.ts
- apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts
- apps/prairielearn/src/pages/partials/assessment.ejs
- apps/prairielearn/src/pages/partials/assessments.ejs
Also converted a few places that were not using the partial itself but had the same construct.
> Convert assessment badge partial into component

- .git-blame-ignore-revs
- .prettierignore
> Configure Prettier to auto-format test/example course JSON

- apps/prairielearn/package.json
- apps/prairielearn/src/api/v1/index.js
- apps/prairielearn/src/lib/config.ts
- apps/prairielearn/src/lib/sentry.ts
- apps/prairielearn/src/server.js
- apps/workspace-host/src/interface.js
- packages/sentry/package.json
- packages/sentry/src/index.ts
- yarn.lock
We've just experienced some memory leak issues in production, and our hypothesis is that this is Sentry's fault. We're going to downgrade to confirm.
> Downgrade Sentry to v7

- apps/prairielearn/src/pages/studentAssessmentInstanceFile/studentAssessmentInstanceFile.js
- apps/prairielearn/src/pages/studentAssessmentInstanceFile/studentAssessmentInstanceFile.sql
Page was not converted to TS to ensure rename history is maintained.
> Modernize student assessment instance file route

- apps/prairielearn/src/ee/auth/saml/router.html.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionCourse/administratorInstitutionCourse.html.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionCourseInstance/administratorInstitutionCourseInstance.html.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionCourses/administratorInstitutionCourses.html.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionGeneral/administratorInstitutionGeneral.html.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionLti13/administratorInstitutionLti13.html.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionSaml/administratorInstitutionSaml.html.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionSso/administratorInstitutionSso.html.ts
- apps/prairielearn/src/ee/pages/institutionAdminAdmins/institutionAdminAdmins.html.ts
- apps/prairielearn/src/ee/pages/institutionAdminCourses/institutionAdminCourses.html.ts
- apps/prairielearn/src/ee/pages/instructorInstanceAdminBilling/instructorInstanceAdminBilling.html.ts
- apps/prairielearn/src/ee/pages/instructorInstanceAdminLti13/instructorInstanceAdminLti13.html.ts
- apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.html.ts
- apps/prairielearn/src/ee/pages/studentCourseInstanceUpgrade/studentCourseInstanceUpgrade.html.ts
- apps/prairielearn/src/ee/pages/terms/terms.html.ts
- apps/prairielearn/src/pages/authPassword/authPassword.html.ts
- apps/prairielearn/src/pages/home/home.html.ts
- apps/prairielearn/src/pages/workspace/workspace.html.ts
> Add missing "content" ID to main regions

- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.html.ts
- apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.sql
- apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.ts
- apps/prairielearn/src/tests/fileEditor.test.ts
> Introduce stronger types to file editor page

- apps/prairielearn/src/lib/question-testing.ts
Resolves #2087. I couldn't find any other reference to a similar name.
> Fix reference to errors/issues page

- graders/c/requirements.txt
- graders/python/requirements.txt
- images/plbase/python-requirements.txt
- workspaces/jupyterlab-python/requirements.txt
Skipped major versions:
* numpy
* pyarrow
* sphinx
> Bump all Python minor/patch packages

- docs/question.md
This was reported by Armando on Slack.
> Fix typo in question documentation

- apps/prairielearn/assets/scripts/application.ts
- apps/prairielearn/assets/scripts/behaviors/tooltip.ts
- apps/prairielearn/assets/scripts/instructorAssessmentManualGradingAssessmentQuestionClient.ts
- apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js
- apps/prairielearn/assets/scripts/instructorQuestionSettingsClient.ts
- apps/prairielearn/package.json
- apps/prairielearn/src/components/HeadContents.html.ts
- apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessment/assessment.html.ts
- apps/prairielearn/src/pages/instructorIssues/instructorIssues.html.ts
- yarn.lock
This is in the same spirit as #10394.
> Globally initialize tooltips

- apps/prairielearn/src/lib/config.ts
- apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.html.ts
This was added in #3132, but I see no reason this would ever be necessary. @mwest1066 @nicknytko do you have any context to offer here?
> Remove personal notes config option

- apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts
Fixes #10262: allows sort by fingerpring changes.
Fixes #10263: search by UID/name/role in group assessments (a custom search had to be used due to limitations in bootstrap-table).
Fixes #10264: escapes name, UID, UIN, assessment instance link text.
> Fix sort, escape and search in assessment students page

- apps/prairielearn/src/server.js
- docs/assessment.md
It's pretty common to get questions regarding functionality of assessment types, so I created a table that summarizes the differences between the different types. The differences were found by searching the code for functionality that depends on the assessment type.
> Docs: summarize difference between assessment types

- apps/prairielearn/assets/scripts/workspaceClient.ts
- apps/prairielearn/src/pages/workspace/workspace.html.ts
The main goal of this PR was to improve the color contrast between the text and the navbar background.
Bootstrap 4:
Bootstrap 5:
I also made a few other tweaks, explained below.
> Improve workspace navbar

- workspaces/rstudio/Dockerfile
This PR is the same as #10451, but it'll get an auto-published preview image since I'm the one who opened the PR.
> Upgrade workspace-rstudio to rstudio 4.4.1

- apps/prairielearn/assets/scripts/enrollClient.ts
- apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.html.ts
- apps/prairielearn/src/pages/enroll/enroll.html.ts
The only modal I didn't update was the [rubric settings modal](https://github.com/PrairieLearn/PrairieLearn/blob/master/apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/rubricSettingsModal.html.ts), which uses some custom classes/styling that I didn't want to figure out.
> Use Modal component wherever possible

- apps/prairielearn/assets/scripts/behaviors/bootstrap-compat.ts
Folks were using this in their questions for YouTube embeds and the like, so we need to support this when Bootstrap 5 styles are enabled.
> Add forward compatibility for Bootstrap 4 embed-responsive utiliies

- .github/dependabot.yml
We're still waiting for https://github.com/twbs/bootstrap/pull/38725 to be released.
> Ignore Bootstrap in Dependabot config

- apps/prairielearn/src/lib/grading.ts
This tripped me up while reading this code; figured I'd try to save the next person to read this from confusion.
> Add comment explaining tricky part of submission insertion

- apps/prairielearn/src/lib/code-caller/index.js
- apps/prairielearn/src/server.js
This will complement the CloudWatch metrics.
> Add OTel metrics for code caller pool

- apps/prairielearn/public/stylesheets/local.css
Tiny enhancement for keyboard users.
> Show "Go home" text when navbar link is focused

- apps/prairielearn/assets/scripts/instructorAssessmentManualGradingAssessmentQuestionClient.ts
- apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js
Tested under both Bootstrap 4 and Bootstrap 5. Closes #10584.
> Fix manual grading conflict modals

- packages/run/.mocharc.cjs
- packages/run/README.md
- packages/run/package.json
- packages/run/src/index.test.ts
- packages/run/src/index.ts
- packages/run/tsconfig.json
- yarn.lock
As first proposed here: https://github.com/PrairieLearn/PrairieLearn/pull/10532#discussion_r1727954710
Hopefully you buy the rationale for this being a package! This is obviously a trivial piece of code, but I think having the blog post as context wherever the function is is really important since it's not 100% clear why this should exist at first glance.
> Introduce run function

- apps/prairielearn/src/pages/workspace/workspace.html.ts
Ensures button text and icon have the same text color.
Tested in Bootstrap 4 and 5.
> Consistent icon color in workspace modal buttons

- testCourse/courseInstances/Sp15/assessments/hw2-miscProblems/infoAssessment.json
> fix: Expiring access rule in a test

- apps/prairielearn/package.json
- apps/prairielearn/src/server.js
- yarn.lock
In the latest version, the ESM distribution of Pyroscope is working as expected.
> Use ESM for Pyroscope

- apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.html.ts
- apps/prairielearn/src/tests/fileEditor.test.ts
This PR intends to lay the foundation for added functionality to the instructor assessment settings page. This PR uses art from the course settings and question settings pages to use a narrower card with input fields. This also adds a form which will be utilized in a subsequent PR for editing the assessment settings.
> Update instructor assessment settings page

- apps/prairielearn/src/components/PersonalNotesPanel.html.ts
This was called out as a potential accessibility improvement in UMich's accessibility review.
> Include file name in personal notes delete button label

- apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts
- apps/prairielearn/assets/scripts/instructorGradebookClient.ts
- apps/prairielearn/src/components/QuestionContainer.html.ts
- apps/prairielearn/src/components/StudentAccessRulesPopover.html.ts
- apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.html.ts
- apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessment/assessment.html.ts
Continuation of #10671; the regex I used in that PR to identify buttons missing an explicit style missed some cases.
> Add ghost styling to more buttons

- apps/prairielearn/assets/scripts/instructorAssessmentSettingsClient.ts
- apps/prairielearn/assets/scripts/lib/saveButtonEnabling.ts
- apps/prairielearn/src/lib/prettier.ts
- apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.html.ts
- apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.sql
- apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.ts
- apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ts
- apps/prairielearn/src/tests/courseEditor.test.ts
- apps/prairielearn/src/tests/instructorAssessmentSettings.test.sql
- apps/prairielearn/src/tests/instructorAssessmentSettings.test.ts
This PR intends to add the functionality of editing assessment settings in the browser. This PR uses the recently introduced form in the `instructorAssessmentSettings` page to update `infoAssessment.json` and the assessment TID.
> Assessment settings editor

- apps/prairielearn/assets/scripts/instructorQuestionSettingsClient.ts
- apps/prairielearn/src/lib/editors.ts
- apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts
- apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts
- apps/prairielearn/src/tests/courseEditor.test.ts
- apps/prairielearn/src/tests/instructorQuestionSettings.test.sql
- apps/prairielearn/src/tests/instructorQuestionSettings.test.ts
This PR intends to add editing of the question `info.json` from the `instructorQuestionSettings` page. This PR is a first step in this project of bringing settings editing to this page. The intention here is to add the editing class to the post route and add the ability to edit just the "title" and "QID". Further editing will be implemented in subsequent PRs.
> Question Settings Editor

- apps/prairielearn/src/components/Scorebar.html.ts
- apps/prairielearn/src/pages/studentAssessments/studentAssessments.html.ts
> Center scorebar on student assessments page

- apps/prairielearn/src/sync/fromDisk/questions.ts
> Fix syncing of shareSourcePublicly

- apps/prairielearn/src/sync/course-db.ts
> Fix conditionals in JSON sharing validation

- apps/prairielearn/src/components/QuestionContainer.html.ts
- apps/prairielearn/src/lib/copy-question.ts
- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/pages/instructorCopyPublicQuestion/instructorCopyPublicQuestion.ts
Should not be merged until after #10029 is deployed
> Read new shared_source_publicly column

- docs/python-grader/Makefile
- docs/python-grader/sphinx-docs.md
- graders/python/python_autograder/code_feedback.py
This PR gets the Sphinx-powered autogenerated docs for the Python grader to build again. It also rebuilds the docs with the latest version of Sphinx installed by `images/plbase/python-requirements.txt`.
> Fix and rebuild Sphinx docs for Python grader

- apps/prairielearn/src/tests/sharedQuestionPreview.test.sql
- apps/prairielearn/src/tests/sharedQuestionPreview.test.ts
> Tests for questions with shared source only

- apps/prairielearn/src/migrations/20241029204638_questions__share_publicly_backfill__finalize.ts
merge after https://github.com/PrairieLearn/PrairieLearn/pull/10843 has deployed and completed
> Finalize share publicly backfill

- apps/prairielearn/src/components/QuestionScore.html.ts
This is another component of #10792. It's a prerequisite for testing #10936.
> Decompose question score panel into two components

- apps/prairielearn/assets/scripts/question.ts
- apps/prairielearn/src/components/QuestionContainer.html.ts
This will be testable sometime after #10935 lands. This will be required to support potential backend/frontend mismatches during deployments.
> Update question client script with forwards compatibility

- apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts
- apps/prairielearn/src/ee/pages/instructorAiGenerateQuestion/instructorAiGenerateQuestion.ts
Minor issues involving the wrong things being passed on were causing problems- none of these changes should affect the ui
> Fix sentry issue + python disappearing issue

- apps/prairielearn/src/lib/question-render.sql
- apps/prairielearn/src/lib/question-render.ts
- apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ts
- apps/prairielearn/src/pages/instructorQuestionPreview/instructorQuestionPreview.ts
- apps/prairielearn/src/pages/publicQuestionPreview/publicQuestionPreview.ts
- apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ts
This is the last portion of #10792.
> Render panels with objects from res.locals

- workspaces/xtermjs/src/package.json
- workspaces/xtermjs/src/yarn.lock
Similar to #10990 but for xtermjs workspace.
> Upgrade Express in xtermjs workspace

- .github/workflows/main.yml
We need the `prairielearn/executor` image to be pushed for these commits.
> Build all commits to code freeze branches

- docs/installingNative.md
- graders/python/python_autograder/code_feedback.py
- Adds detailed instructions to native setup guide for MacOS and Linux
Added some "hypermodern" setup steps too ;)
> Add detailed instructions to native setup guide

- graders/python/python_autograder/pl_result.py
Fixup bug reported by Jill Naiman on Slack.
> Change DoNotRunError and UserCodeFailedError

- apps/prairielearn/elements/pl-checkbox/pl-checkbox.py
- apps/prairielearn/elements/pl-variable-score/pl-variable-score.py
- apps/prairielearn/python/zygote.py
- exampleCourse/questions/demo/addHTMLtable/server.py
- graders/python/python_autograder/code_feedback.py
- images/plbase/python-requirements.txt
Splitting this out of #11083 since it requires changes to Python code to comply with updated lint rules.
> Upgrade Ruff to 0.8.6

- apps/prairielearn/elements/pl-workspace/pl-workspace.py
- apps/prairielearn/python/prairielearn.py
- apps/prairielearn/python/python_helper_sympy.py
- images/plbase/python-requirements.txt
- tools/api_download.py
- tools/question_converters/canvas/canvas.py
- tools/question_converters/canvas/quiz2pl.py
Release announcement: https://astral.sh/blog/ruff-v0.9.0
All changes here were from `make format-python`.
> Install Ruff 0.9.1

- apps/prairielearn/python/prairielearn.py
- apps/prairielearn/python/python_helper_sympy.py
- exampleCourse/questions/demo/drawing/simpleTutorial/server.py
- exampleCourse/questions/element/fileEditor/initial_code.py
- exampleCourse/questions/workshop/Lesson5_example2/server.py
- pyproject.toml
- All changes were automated with `ruff check --fix`.
- Clears up `range(0, N)` from #11109
> add PIE, run ruff check --fix

- apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py
- apps/prairielearn/elements/pl-checkbox/pl-checkbox.py
- apps/prairielearn/elements/pl-drawing/elements.py
- apps/prairielearn/elements/pl-drawing/pl-drawing.py
- apps/prairielearn/elements/pl-excalidraw/pl-excalidraw.py
- apps/prairielearn/elements/pl-external-grader-variables/pl-external-grader-variables.py
- apps/prairielearn/elements/pl-integer-input/pl-integer-input.py
- apps/prairielearn/elements/pl-matching/pl-matching.py
- apps/prairielearn/elements/pl-matrix-input/pl-matrix-input.py
- apps/prairielearn/elements/pl-number-input/pl-number-input.py
- apps/prairielearn/elements/pl-order-blocks/dag_checker.py
- apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.py
- apps/prairielearn/elements/pl-symbolic-input/pl-symbolic-input.py
- apps/prairielearn/elements/pl-units-input/pl-units-input.py
- apps/prairielearn/python/prairielearn.py
- apps/prairielearn/python/question_phases.py
- exampleCourse/questions/workshop/Lesson4_example3/server.py
- graders/python/python_autograder/code_feedback.py
- pyproject.toml
https://docs.astral.sh/ruff/rules/collapsible-else-if/
- Simplifies `if...else` into `elif`.
- Changes were completely automated with `ruff check --fix`.
> add PLR5501; ruff check --fix

- apps/prairielearn/elements/pl-big-o-input/big_o_utils_test.py
- apps/prairielearn/elements/pl-code/code_utils_test.py
- apps/prairielearn/elements/pl-number-input/pl_number_input_test.py
- apps/prairielearn/elements/pl-order-blocks/dag_checker_test.py
- apps/prairielearn/elements/pl-units-input/units_utils_test.py
- apps/prairielearn/python/colors_test.py
- apps/prairielearn/python/prairielearn_test.py
- apps/prairielearn/python/python_helper_sympy_test.py
- apps/prairielearn/python/zygote_utils_test.py
- pyproject.toml
- Follows best pytest practices
> Ruff: flake8-pytest-style

- docs/hooks/d2-svg-file.py
- docs/python-grader/sphinx-config/conf.py
- pyproject.toml
- workspaces/jupyterlab-python/jupyter_server_config.py
- workspaces/jupyterlab/jupyter_notebook_config.py
- All Python files are now covered by Ruff
> Ruff: enable ruff on all python files

- apps/prairielearn/src/lib/code-caller/index.ts
- packages/actions-report-image-sizes/tsconfig.json
- packages/postgres/src/index.ts
- packages/sentry/src/index.ts
- packages/session/src/index.ts
- packages/tsconfig/tsconfig.base.json
- packages/tsconfig/tsconfig.package-cjs.json
See https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax.
> Enable verbatimModuleSyntax in TypeScript configs

- apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.html.ts
> Hide sharing token regeneration button for non-owners

- apps/prairielearn/src/ee/lib/lti13.ts
- apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.html.ts
This PR implements my nits from #11040 that weren't resolved as part of that PR.
Updated role display:
> Tweaks to LTI 1.3 linking flow

- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/migrations/20250117000347_variants__variant_seed_nonnull.sql
- database/tables/variants.pg
> Make variants.variant_seed non-null

- apps/prairielearn/elements/pl-matching/pl-matching.py
- pyproject.toml
> pyright: type pl-matching

- apps/prairielearn/python/zygote.py
https://github.com/PrairieLearn/PrairieLearn/pull/11051#discussion_r1924469189
> add comment back

- .github/workflows/main.yml
- .hadolint.yaml
- Dockerfile
- Makefile
Hadolint is a dockerfile linter. https://github.com/hadolint/hadolint
I didn't install in container, just in the actions pipeline
> Add hadolint

- apps/prairielearn/src/server.ts
This code had been gradually converted from callback to async code over time. Now that no callback code is left this can be converted to regular async/await code.
Best reviewed ignoring whitespaces.
> Convert async.series call in server.ts to asynchronous code

- pyproject.toml
After clearing #11243 and #11244 we should enable this to highlight the need to resolve these.
> pyright: turn on info statement

- .vscode/settings.json
> Type hint common JSON files in VSCode

- docs/question.md
See title, credit to @jonatanschroeder
> Enhance docs example for score computation

- graders/python/requirements.txt
- images/plbase/python-requirements.txt
- workspaces/jupyterlab-python/requirements.txt
- workspaces/vscode-python/requirements.txt
Consolidates updates from other Dependabot PRs.
> Upgrade faker and pyarrow

- apps/prairielearn/elements/pl-matching/pl-matching.py
- apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.py
- apps/prairielearn/python/prairielearn/core.py
- apps/prairielearn/python/zygote.py
- docs/hooks/d2-svg-file.py
- graders/python/python_autograder/pl_helpers.py
- pyproject.toml
- Ensure everything is annotated
> ruff: add annotation rule

- apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.py
- apps/prairielearn/elements/pl-dataframe/pl-dataframe.py
- apps/prairielearn/elements/pl-drawing/elements.py
- apps/prairielearn/elements/pl-dropdown/pl-dropdown.py
- apps/prairielearn/elements/pl-excalidraw/pl-excalidraw.py
- apps/prairielearn/elements/pl-matching/pl-matching.py
- apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.py
- apps/prairielearn/elements/pl-overlay/pl-overlay.py
- apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.py
- apps/prairielearn/elements/pl-template/pl-template.py
- apps/prairielearn/python/prairielearn/core.py
- apps/prairielearn/python/prairielearn/internal/check_data.py
- apps/prairielearn/python/prairielearn/internal/traverse.py
- apps/prairielearn/python/prairielearn/sympy_utils.py
- apps/prairielearn/python/test/core_test.py
- exampleCourse/elements/extendable-element/extendable-element.py
- exampleCourse/questions/demo/annotated/engMarkovBrewing/tests/ans.py
- exampleCourse/questions/demo/autograder/c/salesTax/server.py
- exampleCourse/questions/element/dataframe/server.py
- exampleCourse/questions/gallery/multipleChoice/advanced/server.py
- graders/c/cgrader/cgrader.py
- graders/python/python_autograder/pl_result.py
- graders/python/python_autograder/pl_unit_test.py
- images/plbase/python-requirements.txt
- pyproject.toml
- tools/question_converters/canvas/canvas.py
- tools/question_converters/randexam/randexam2pl2.py
- Adds the [Ruff Preview](https://docs.astral.sh/ruff/preview/) flag, which adds some more types of linter checks.
- Upgrades Ruff, which fixes a bug where `FBT001` was not caught in some situations
- There are no code changes, except for formatting + rule ignores.
> Ruff: enable preview rules, bump version

- .coderabbit.yaml
> disable coderabbit summary

- .github/workflows/main.yml
- Makefile
- graders/python/install.sh
- graders/python/post-install.sh
- tools/question-container-debugging.sh
- workspaces/desktop/pl-gosu-helper.sh
- workspaces/desktop/post-install.sh
- workspaces/desktop/pre-install.sh
- workspaces/desktop/start-vnc.sh
- Start linting `.sh` files to catch potential error
- Related: #11221 , #11232
> shellcheck: Add shellcheck linter

- apps/prairielearn/src/lib/db-types.ts
I neglected to do this as part of #11338.
> Update Zod schemas to reflect nullability of tags/topics/modules columns

- docs/installingNative.md
> Clarification around native installation and docker

- apps/prairielearn/src/ee/pages/administratorInstitutionSaml/administratorInstitutionSaml.html.ts
Coderabbit noticed this in another unrelated PR.
> Fix capitalization of aria-describedby attributes

- apps/prairielearn/public/stylesheets/local.css
- apps/prairielearn/src/components/Navbar.html.ts
This PR intends to add focus indicators to buttons that do not have them. This addresses two accessibility issues identified in the report from UIUC (#11360).
> Add focus indicators to buttons

- .codecov.yml
- apps/prairielearn/python/prairielearn/core.py
- apps/prairielearn/python/prairielearn/to_precision.py
- apps/prairielearn/python/test/check_data_test.py
- apps/prairielearn/python/test/colors_test.py
- apps/prairielearn/python/test/core_test.py
- apps/prairielearn/python/test/dummy_extension.py
- apps/prairielearn/python/test/sympy_utils_test.py
- apps/prairielearn/python/test/to_precision_test.py
> prairielearn module test coverage; nan/inf edge case; matlab format

- docs/externalGrading.md
Pulling these over from #11406 in the interest of closing out an open PR.
> Add note about external grading results directory creation

- testCourse/courseInstances/Sp15/assessments/hw10-aiGrading/infoAssessment.json
- testCourse/questions/aiGradingRubrics/README.md
- testCourse/questions/aiGradingRubrics/info.json
- testCourse/questions/aiGradingRubrics/question.html
Things like this will be important for testing #10726.
> Add question/assessment to test AI rubric grading

- apps/prairielearn/src/ee/lib/ai-grading.ts
This PR addresses comments from #10726 that weren't addressed before it was merged.
> Refine AI grading with rubrics

- apps/prairielearn/src/batched-migrations/20250214171608_course_instance_usages__external_grading_jobs__backfill.sql
> Only backfill usage with non-null `grading_received_at`

- contrib/question_converters/canvas/quiz2pl.py
This came up while I was working with Julie to import some Canvas content.
> Strip CSS/JS from questions imported from Canvas

- contrib/question_converters/canvas/canvas.py
- contrib/question_converters/canvas/quiz2pl.py
- pyproject.toml
This PR enables Ruff linting and Pyright checking for `contrib/question_converters/canvas`. As part of this, I removed a bunch of unused functionality from `canvas.py`.
> Typecheck and lint Canvas question converter

- .coderabbit.yaml
> Disable ESLint in CodeRabbit config

- apps/prairielearn/src/ee/pages/institutionAdminAdmins/institutionAdminAdmins.ts
- apps/prairielearn/src/lib/groups.ts
- apps/prairielearn/src/models/user.ts
- apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts
- apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.ts
- apps/prairielearn/src/tests/lti13.test.ts
- apps/prairielearn/src/tests/permissions/institutionAdminAccess.test.ts
With enhanced navigation now available behind a feature flag, we want to make it easy for ourselves to turn it on/off for specific users.
> Add support for configuring feature flags for specific users

- apps/prairielearn/src/components/AssessmentNavigation.html.ts
Resolve comment on https://github.com/PrairieLearn/PrairieLearn/discussions/11550#discussioncomment-12567227.
> Fix target page for assessment switcher on file edit page

- docs/running-in-production/admin-user.md
The sample code is not valid SQL.
> Clarify process for creating administrators

- apps/prairielearn/elements/pl-matrix-component-input/pl-matrix-component-input.py
- apps/prairielearn/elements/pl-matrix-output/pl-matrix-output.py
- apps/prairielearn/elements/pl-python-variable/pl-python-variable.py
- apps/prairielearn/elements/pl-variable-output/pl-variable-output.py
- apps/prairielearn/python/prairielearn/core.py
- apps/prairielearn/python/prairielearn/internal/check_data.py
- docs/requirements.txt
- graders/c/cgrader/cgrader.py
- graders/python/python_autograder/code_feedback.py
- graders/python/python_autograder/pl_result.py
- images/plbase/python-requirements.txt
This is blocked on https://github.com/astral-sh/ruff/issues/16874. We're waiting on https://github.com/astral-sh/ruff/pull/16878 to land.
> Upgrade to Ruff 0.11.2

- apps/prairielearn/src/pages/workspaceLogs/workspaceLogs.ts
> Fix access to workspace logs page

- apps/prairielearn/src/lib/local-cache.ts
- apps/prairielearn/src/tests/helperServer.ts
Noticed this while working on https://github.com/PrairieLearn/PrairieLearn/pull/11665.
> Simplify LocalCache implementation

- .github/workflows/label-prs.yml
> Fix order of labeler

- workspaces/desktop/pre-install.sh
This should reduce the image size and build time a bit.
> Use --no-install-recommends when building workspace-desktop image

- docs/faq.md
This is a common question on Slack, so I added it to the FAQ.
> Add FAQ for sharing files between workspace and tests

- .markdownlint.yml
- Makefile
- SECURITY.md
- apps/prairielearn/src/migrations/README.md
- apps/prairielearn/src/tests/testFileEditor/courseTemplate/README.md
- contrib/question_converters/README.md
- contrib/question_converters/canvas/README.md
- contrib/question_converters/lon-capa/README.md
- contrib/question_converters/lon-capa/zilles-email.md
- contrib/question_converters/randexam/README.md
- contrib/question_converters/smart-physics/README.md
- graders/README.md
- graders/c/README.md
- graders/java/README.md
- graders/python/README.md
- graders/r-previous/README.md
- graders/r/README.md
- graders/r/plr/README.md
- images/executor/README.md
- packages/compiled-assets/README.md
- packages/express-list-endpoints/README.md
- packages/run/README.md
- templateCourse/README.md
- testCourse/questions/aiGradingRubrics/README.md
- workspaces/README.md
- workspaces/desktop/README.md
> Lint all markdown

- .github/workflows/upgrade-containers.yml
> Update package bump frequency

- apps/prairielearn/elements/pl-string-input/pl-string-input.mustache
This slipped through the cracks in #9438.
> Use Bootstrap 5 margin utilities in pl-string-input

- apps/prairielearn/python/prairielearn/conversion_utils.py
- apps/prairielearn/python/prairielearn/extension_utils.py
- apps/prairielearn/python/prairielearn/grading_utils.py
- apps/prairielearn/python/prairielearn/html_utils.py
- apps/prairielearn/python/prairielearn/internal/traverse.py
- apps/prairielearn/python/prairielearn/internal/zygote_utils.py
- apps/prairielearn/python/prairielearn/misc_utils.py
- apps/prairielearn/python/prairielearn/question_utils.py
- apps/prairielearn/python/prairielearn/sympy_utils.py
- docs/assets/extra.css
- docs/scripts/d2_svg_file.py
- docs/scripts/gen_additional_readmes.py
- docs/scripts/gen_python_nav.py
- docs/scripts/jsonschema_details_fix.py
- mkdocs.yml
- pyproject.toml
Note: Builds are currently slow: https://github.com/mkdocstrings/mkdocstrings/issues/756
This PR aims to improve the quality of some docstrings. Unfortunately, we can't enforce this through Ruff yet (https://github.com/astral-sh/ruff/issues/12434).
https://prairielearn--11761.org.readthedocs.build/en/11761/
If you notice any particularly bad docstrings, feel free to comment!
Closes #11373
> Docstrings improvements

- graders/r/Dockerfile
@LinjunHuang86749 and I are experimenting with parsing the syntax tree of R expressions (to properly test unit testing calls) and the CRAN package [lobstr](https://cran.r-project.org/package=lobstr) is of help there.  We already have its dependencies so the next additional to the container should be minimal.
> Add CRAN package 'lobstr' to grader to inspect R expressions

- apps/prairielearn/package.json
- yarn.lock
My fix from https://github.com/twbs/bootstrap/pull/38725 has finally been released 🎉
> Upgrade Bootstrap to 5.3.5

- apps/prairielearn/src/components/SubmissionPanel.html.ts
- apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/rubricInputSection.html.ts
I'm lifting this out of #10506 in the interest of making that diff easier to manage.
I tested locally and things still looked and worked well for me.
> Introduce components for rubric items

- apps/prairielearn/package.json
- yarn.lock
This fixes a Dependabot security alert.
> Upgrade http-proxy-middleware to 3.0.5

- apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/rubricSettingsModal.html.ts
Lifting this out of #10506 for a cleaner diff there.
> Refactor RubricItemRow component

- docs/requirements.txt
- graders/c/requirements.txt
- graders/python/requirements.txt
- images/plbase/python-requirements.txt
- workspaces/jupyterlab-python/requirements.txt
- workspaces/vscode-python/requirements.txt
These are all patch or minor version bumps, shouldn't be anything too interesting to see here.
> Upgrade Python dependencies

- apps/prairielearn/src/schemas/schemas/infoAssessment.json
- apps/prairielearn/src/schemas/schemas/infoQuestion.json
- apps/prairielearn/src/schemas/schemas/questionOptionsCheckbox.json
- apps/prairielearn/src/sync/course-db.ts
- apps/prairielearn/src/sync/fromDisk/assessments.ts
- apps/prairielearn/src/sync/fromDisk/courseInstances.ts
- exampleCourse/courseInstances/SectionA/assessments/gallery/elements/infoAssessment.json
- testCourse/courseInstances/Sp15/assessments/hw9-internalExternalManual/infoAssessment.json
I'm lifting some of these changes out of #11024.
> Minor fixes for and improvements to JSON schemas

- apps/prairielearn/src/tests/sync/assessmentsSync.test.ts
- apps/prairielearn/src/tests/sync/util.ts
These tests reproduced a bug in #11024.
> Add tests for syncing of advanceScorePerc on assessments

- .eslintrc.cjs
- Makefile
- apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.tsx
- apps/prairielearn/assets/scripts/tsconfig.json
- contrib/dump-anonymize.mjs
- scripts/validate-links.mjs
I'm pulling out a few small changes from #10944.
> Minor linting improvements

- graders/python/python_autograder/code_feedback.py
- graders/python/python_autograder/tests/code_feedback_test.py
https://github.com/PrairieLearn/PrairieLearn/pull/9436#discussion_r2050969844 - fast follow
> Add quotes to check_dict

- apps/prairielearn/src/question-servers/calculation-worker.js
- apps/prairielearn/src/question-servers/index.ts
- apps/prairielearn/src/question-servers/types.ts
- apps/prairielearn/src/schemas/infoElementCore.ts
- apps/prairielearn/src/schemas/infoElementCourse.ts
- apps/prairielearn/src/schemas/schemas/infoElementCourse.json
I'm pulling some of the changes out of #11053 for a cleaner diff there.
> Refactor question server types

- apps/prairielearn/src/pages/studentGradebook/studentGradebook.html.ts
- apps/prairielearn/src/pages/studentGradebook/studentGradebook.ts
- apps/prairielearn/src/tests/accessibility/index.test.ts
Closes #10905. While this doesn't do exactly what the issue had proposed, it solves the same goal of giving students access to high-precision scores.
> Add CSV export for student gradebook

- apps/prairielearn/src/question-servers/calculation-subprocess.js
- apps/prairielearn/src/question-servers/calculation-worker.js
- apps/prairielearn/src/question-servers/types.ts
More changes lifted out of #11053.
> More refactoring of question server types

- apps/prairielearn/src/question-servers/freeform.js
- apps/prairielearn/src/question-servers/types.ts
I'm lifting these changes out of #11053.
> Use Zod schemas to parse element JSON files

- apps/prairielearn/src/question-servers/freeform.js
I'm pulling this out of #11053. Once #11826 lands, we can improve the types around this to check our work.
> Refactor how dependencies are tracked for elements

- apps/prairielearn/src/question-servers/freeform.js
> Add types for default freeform question processor

- .coderabbit.yaml
> Disable ruff in coderabbit

- apps/prairielearn/elements/pl-drawing/pl-drawing.mustache
- apps/prairielearn/elements/pl-figure/pl-figure.mustache
These elements are missing it, this change simplifies #11898.
> Add mb-3 to pl-figure and pl-drawing

- .github/workflows/main.yml
Continues from #11909. These comments weren't addressed before merging.
> Clean up after workflow split

- docs/question/accessibility.md
- docs/question/index.md
- mkdocs.yml
> Add instructor-facing docs for question accessibility

- docs/installingNative.md
- I don't think `mise` is a great recommendation, so I removed that 😅 
- Added installation steps for LaTex
> Cleanup native install and add LaTeX installation steps

- Makefile
- eslint.config.mjs
- package.json
- yarn.lock
I noticed a few potential improvements while upgrading PrairieTest to ESLint v9.
> Refine ESLint config

- docs/manualGrading/index.md
Documents the changes done in #11949.
> docs: Add info box about order of instances in manual grading

- apps/prairielearn/src/ee/lib/validateHTML.ts
Lifting this out of https://github.com/PrairieLearn/PrairieLearn/pull/11955#discussion_r2085221876.
> Improve validation of allow-blank attribute for AI question generation

- apps/prairielearn/src/ee/lib/validateHTML.ts
I don't know how, but this made it through the merge queue onto master in #11962. Builds are failing on master and in branches.
> Fix lint issue

- apps/prairielearn/elements/pl-graph/pl-graph.py
- apps/prairielearn/elements/pl-matrix-component-input/pl-matrix-component-input.py
- docs/elements.md
- exampleCourse/questions/element/graph/question.html
- exampleCourse/questions/workshop/Lesson4_example1/server.py
> Fixup minor accessibility, grading, rendering bugs in questions & elements

- apps/prairielearn/assets/scripts/instructorAssessmentManualGradingAssessmentQuestionClient.ts
Discussion in #11884: we don't really need a separate column for indicating AI graded: we just modify the displayed `Graded by` column to AI to indicate AI graded.
> Merge "Graded by" and "Is AI graded" columns on manual grading page

- exampleCourse/questions/demo/annotated/engCircuit/server.py
- exampleCourse/questions/demo/randomDataFrame/server.py
- exampleCourse/questions/demo/randomPlot/server.py
- exampleCourse/questions/element/matrixLatex/server.py
- exampleCourse/questions/element/symbolicInput/server.py
- exampleCourse/questions/template/checkbox/random-prompt/server.py
- exampleCourse/questions/template/matrix-component-input/random-graph/server.py
- pyproject.toml
Alternative to #11931. Rather than adding as many annotations as possible (specifically for `data`), this just enables type checking and then makes the smallest possible changes to make the type checker pass.
> Typecheck example course

- apps/prairielearn/src/schemas/infoAssessment.ts
- apps/prairielearn/src/schemas/schemas/infoAssessment.json
Motivated by a discussion with a confused user on Slack.
> Improve explanation of sharing assessment source publicly

- apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.html.ts
Mostly just to make this consistent with the better way we did things for course instances in #11770
> Minor improvements to UI of public sharing info in assessment settings

- .dependency-cruiser.js
- apps/prairielearn/src/ee/lib/lti13.test.ts
- apps/prairielearn/src/lib/config.ts
- apps/prairielearn/src/tests/chunks.test.ts
- apps/prairielearn/src/tests/fileEditor.test.ts
- apps/prairielearn/src/tests/helperQuestion.ts
- apps/prairielearn/src/tests/sprocs/ip_to_mode.test.ts
- eslint.config.mjs
- packages/compiled-assets/package.json
- packages/express-list-endpoints/package.json
- packages/flash/package.json
- packages/formatter/package.json
- packages/html-ejs/package.json
- packages/html/package.json
- packages/run/package.json
- packages/sanitize/package.json
- packages/session/package.json
- yarn.lock
I'm pulling some of the smaller changes out of #11943 so they can be more easily reviewed. This will leave that PR with mostly mechanical changes from Mocha's API to Vitest's.
> Prepare for Vitest

- docs/dev-guide/guide.md
- docs/dev-guide/quickstart.md
> Update docs from mocha to vitest

- .changeset/dull-clocks-behave.md
- apps/prairielearn/src/lib/config.ts
- apps/prairielearn/src/tests/vitest.testSetup.ts
- packages/config/src/index.ts
Lifting this out of #12034, as this is useful in isolation.
> Reset config before every test

- apps/prairielearn/src/ee/lib/ai-grading/ai-grading-render.ts
- apps/prairielearn/src/question-servers/freeform.ts
I'm lifting this out of #11989.
> Move utilities for rendering questions for AI grading

- docs/contentSharing.md
Docs to match features from #11770
> Add docs for course instance sharing

- docs/assessment/index.md
This PR updates the docs to reference the new feature of custom honor codes from #11953.
> Update docs to include custom honor code

- CONTRIBUTING.md
> Add AI note for contributors

- docs/pl-drawing/index.md
> Update non-responsive images in docs

- apps/prairielearn/src/ee/pages/instructorAiGenerateDrafts/instructorAiGenerateDrafts.ts
- apps/prairielearn/src/server.ts
I noticed these while working on another PR.
> Honor AI question generation feature/enterprise flags

- .changeset/purple-baths-tell.md
- .changeset/slow-nails-try.md
- apps/prairielearn/assets/scripts/behaviors/react-fragments/debug.ts
- apps/prairielearn/assets/scripts/behaviors/react-fragments/index.tsx
- packages/compiled-assets/src/index.ts
- packages/preact-cjs/package.json
- packages/preact-cjs/src/debug.d.ts
- packages/preact-cjs/src/debug.js
- packages/preact-cjs/src/devtools.d.ts
- packages/preact-cjs/src/devtools.js
> Add support for debugging Preact

- apps/prairielearn/package.json
- apps/prairielearn/src/lib/client/nuqs.test.ts
- apps/prairielearn/src/lib/client/nuqs.tsx
- yarn.lock
- Storing tanstack sort table state in the URL
> Add nuqs URL sort helper

- apps/prairielearn/assets/scripts/behaviors/react-fragments/index.tsx
- apps/prairielearn/package.json
- apps/prairielearn/src/lib/preact.tsx
- yarn.lock
- Dates were getting converted to strings implicitly
> Use superjson for preact hydration

- .github/labeler.yml
- .github/title-labeler.yml
- Prevent `debugging` from being picked up
- Add preact label to PRs that add a hydration script
> Add preact/LTI/schema label, fix bug-label

- apps/prairielearn/src/components/SideNav.html.ts
> Highlight Integrations tab when it's active

- .changeset/ready-spiders-grow.md
- packages/formatter/package.json
- packages/formatter/src/date.test.ts
- packages/formatter/src/date.ts
- packages/formatter/src/index.ts
- packages/formatter/src/interval.test.ts
- packages/formatter/src/interval.ts
- yarn.lock
- Tests and code were pulled directly from PrairieTest
> Add date formatting utilities

- apps/prairielearn/src/lib/client/nuqs.test.ts
- apps/prairielearn/src/lib/client/nuqs.tsx
- Pinning only supports customizable left-pinned columns for now 
- Pulled out of #12211
> Add URL serializer for table pinning and visibility state

- eslint.config.mjs
- package.json
- yarn.lock
Related: https://github.com/NickvanDyke/eslint-plugin-react-you-might-not-need-an-effect/issues/21
> Add react-you-might-not-need-an-effect ESLint rules

- apps/prairielearn/assets/scripts/instructorAiGenerateDraftsSampleQuestions.tsx
- apps/prairielearn/src/ee/pages/instructorAiGenerateDrafts/SampleQuestionDemo.tsx
- apps/prairielearn/src/ee/pages/instructorAiGenerateDrafts/aiGeneratedQuestionSamples.ts
Lifting this out of https://github.com/PrairieLearn/PrairieLearn/pull/12369#discussion_r2193541215 for independent discussion.
> Refactor SampleQuestionDemo to avoid useEffect

- apps/prairielearn/src/lib/client/safe-db-types.ts
- Preferred by @mwest1066 in a Slack conversation
> Switch safe-db-types to use pick

- apps/prairielearn/src/components/PageLayout.html.tsx
- apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.html.ts
- apps/prairielearn/src/pages/studentAssessments/studentAssessments.html.ts
- apps/prairielearn/src/pages/studentGradebook/studentGradebook.html.ts
- apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.html.ts
Assessments:
Assessment instance:
instance question
gradebook
> Migrate student pages to use PageLayout

- apps/prairielearn/src/ee/lib/ai-grading/ai-grading.ts
- apps/prairielearn/src/ee/lib/ai-grading/types.ts
Resolves #12365. 
- Used `Async` `mapLimit` to parallelize AI grading requests. 
- Benchmark: for 44 samples on one question involving grading cosine/sine calculations captured with `pl-image-capture`, the previous implementation took about 120 seconds to grade all of them. The implementation in this PR takes 11 seconds.
> Parallelize AI grading

- apps/prairielearn/src/migrations/20250711131327_submissions__grading_method__drop.sql
- database/tables/submissions.pg
> Drop submissions.grading_method column

- apps/prairielearn/assets/scripts/instructorAssessmentManualGradingAssessmentQuestionClient.ts
- apps/prairielearn/src/ee/lib/ai-grading/types.ts
- apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.types.ts
Noticed in #12403 , ~~not tested~~ working
> Add Zod schema for AI Grading, parse on page

- .changeset/hungry-nights-thank.md
- apps/prairielearn/src/ee/lib/ai-grading/ai-grading-util.ts
- apps/prairielearn/src/ee/lib/lti13.ts
- apps/prairielearn/src/ee/models/enrollment.test.ts
- apps/prairielearn/src/ee/pages/administratorInstitutionLti13/administratorInstitutionLti13.ts
- apps/prairielearn/src/lib/editors.ts
- apps/prairielearn/src/lib/file-paths.ts
- apps/prairielearn/src/lib/timezones.ts
- apps/prairielearn/src/models/course.ts
- apps/prairielearn/src/models/institution.ts
- apps/prairielearn/src/models/questions.ts
- apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.ts
- apps/prairielearn/src/pages/authLogin/authLogin.ts
- apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.ts
- apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.ts
- apps/prairielearn/src/pages/instructorAssessmentQuestionStatistics/instructorAssessmentQuestionStatistics.ts
- apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.ts
- apps/prairielearn/src/pages/instructorQuestionStatistics/instructorQuestionStatistics.ts
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.ts
- apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.ts
- apps/prairielearn/src/pages/userSettings/userSettings.ts
- apps/prairielearn/src/tests/activeAccessRestriction.test.ts
- apps/prairielearn/src/tests/chunks.test.ts
- apps/prairielearn/src/tests/groupExam.test.ts
- apps/prairielearn/src/tests/groupExamRolePermissions.test.ts
- apps/prairielearn/src/tests/groupRolePermissions.test.ts
- apps/prairielearn/src/tests/instructorAssessmentGroups.test.ts
- apps/prairielearn/src/tests/instructorBreakVariants.test.ts
- apps/prairielearn/src/tests/sharedQuestionPreview.test.ts
- packages/migrations/src/batched-migrations/batched-migration-runner.ts
> Database query tweaks

- apps/prairielearn/src/ee/models/stripe-checkout-sessions.ts
- apps/prairielearn/src/lib/ltiOutcomes.ts
- apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.ts
- apps/prairielearn/src/pages/submissionFile/submissionFile.ts
- apps/prairielearn/src/tests/helperQuestion.ts
- packages/migrations/src/batched-migrations/batched-migration-runner.test.ts
- packages/postgres-tools/src/describe.ts
A few more changes that I missed in #12499.
> More database query formatting nits

- apps/prairielearn/src/components/JobSequenceResults.tsx
- apps/prairielearn/src/cron/index.ts
- apps/prairielearn/src/ee/lib/ai-grading/ai-grading-stats.ts
Opinionated tweaks in the wake of #12542.
> Tweaks to JSDoc comments

- .github/dependabot.yml
- requirements.txt
Noticed in #12571 , I'm not fully convinced we are using sphinx for anything.
> Remove sphinx

- apps/prairielearn/src/lib/timezones.test.ts
- apps/prairielearn/src/lib/timezones.ts
Pulling out of https://github.com/PrairieLearn/PrairieLearn/pull/12545#discussion_r2258593988.
Tests were authored with the help of GPT 4.1.
> Add tests for formatTimezone function

- apps/prairielearn/src/lib/editors.ts
- contrib/tsconfig.json
- packages/tsconfig/tsconfig.app.json
- packages/tsconfig/tsconfig.package.json
This is meant to complement #12625.
> Refine TypeScript config

- apps/grader-host/src/index.ts
- apps/grader-host/src/lib/config.ts
- apps/grader-host/src/lib/healthCheck.ts
- apps/grader-host/src/lib/lifecycle.ts
- apps/grader-host/src/lib/load.ts
- apps/grader-host/src/lib/receiveFromQueue.test.ts
- apps/prairielearn/src/ee/auth/lti13/lti13Auth.ts
- apps/prairielearn/src/lib/code-caller/code-caller-container.ts
- apps/prairielearn/src/lib/editors.ts
- apps/prairielearn/src/lib/question-variant.ts
- apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.ts
- apps/prairielearn/src/question-servers/calculation-subprocess.ts
- apps/prairielearn/src/question-servers/freeform.ts
- apps/prairielearn/src/question-servers/types.ts
- apps/prairielearn/src/server.ts
- apps/prairielearn/src/tests/permissions/courseAdminAccess.test.ts
- apps/workspace-host/src/interface.ts
- apps/workspace-host/src/lib/docker.ts
- packages/config/src/index.ts
- packages/session/src/index.ts
- packages/tsconfig/tsconfig.app.json
- Caught an interesting type error with `variant.broken_at` and `makeVariant`.
> Make TypeScript settings stricter

- apps/prairielearn/src/lib/db-types.ts
This slipped through review in #12544.
> Delete accidentally-committed comment

- apps/prairielearn/package.json
- yarn.lock
- Updated OpenAI package to support GPT-5 in preparation for #12630.
> Update OpenAI package for GPT-5 support

- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/tests/sync/assessmentsSync.test.ts
- apps/prairielearn/src/tests/sync/courseInstancesSync.test.ts
- apps/prairielearn/src/tests/sync/courseSync.test.ts
- apps/prairielearn/src/tests/sync/initialSync.test.ts
- apps/prairielearn/src/tests/sync/questionsSync.test.ts
- apps/prairielearn/src/tests/sync/tagsTopicsSync.test.ts
- apps/prairielearn/src/tests/sync/util.ts
- Cascaded changes include stricter checks for the outputted values due to type errors
- Mentioned in another PR
> Update all usages of dumpTable to dumpTableWithSchema

- docs/python-grader/reference-docs.md
- mkdocs.yml
> Render classnames in documentation correctly

- apps/prairielearn/src/tests/courseEditor.test.ts
As noted in https://github.com/PrairieLearn/PrairieLearn/pull/12730#discussion_r2305599612.
> Refactor getFiles in course editor tests

- apps/prairielearn/src/ee/pages/instructorInstanceAdminBilling/instructorInstanceAdminBilling.sql
We obviously need to exclude deleted questions here.
> Exclude deleted questions in instructor billing query

- docs/contentSharing.md
- exampleCourse/courseInstances/SectionA/assessments/demo/workspaces/infoAssessment.json
Update sharing docs to match what was implemented in #12184
> Update outdated assessment sharing docs

- apps/prairielearn/src/lib/client/safe-db-types.test.ts
- apps/prairielearn/src/lib/client/safe-db-types.ts
Noticed in #12728 
Missing tests were written by Cursor.
> Add more safe-db-types tests, Institution schema

- .changeset/cold-groups-sit.md
> Bump all packages

- apps/prairielearn/src/pages/instructorInstanceAdminLti/instructorInstanceAdminLti.html.tsx
- apps/prairielearn/src/pages/instructorInstanceAdminLti/instructorInstanceAdminLti.ts
As noted here: https://github.com/PrairieLearn/PrairieLearn/pull/12730#discussion_r2305578368. This makes the Zod query validation actually useful on this page.
Best reviewed with whitespace changes hidden.
> Refactor legacy LTI settings page

- apps/prairielearn/src/middlewares/authzHasCoursePreviewOrInstanceView.tsx
This is a simpler and safer alternative to the changes in #12810.
I did not test this. I just looked at the error on Sentry and thought kind of hard about this 🙂
> Fix auth on workspace container proxy routes

- apps/prairielearn/src/tests/helperClient.ts
Splitting this out of #12725 (see https://github.com/PrairieLearn/PrairieLearn/pull/12725#discussion_r2317046147).
This was tested in #12725.
> Improve CSRF test helpers

- apps/prairielearn/src/models/audit-event.test.ts
- apps/prairielearn/src/models/audit-event.ts
These comments weren't addressed before #12776 was merged.
The tests still pass!
> Clean up audit event tests

- apps/prairielearn/src/lib/assessment.ts
- apps/prairielearn/src/lib/grading.ts
- apps/prairielearn/src/lib/question-testing.ts
As requested by @reteps in https://github.com/PrairieLearn/PrairieLearn/pull/12725#discussion_r2317085689 and https://github.com/PrairieLearn/PrairieLearn/pull/12725#discussion_r2317078219.
N/A, this is a straightforward refactor.
> Use options object for `gradeVariant` function

- apps/prairielearn/src/models/enrollment.sql
- apps/prairielearn/src/models/enrollment.test.ts
- apps/prairielearn/src/models/enrollment.ts
If a user is invited, and visits a course instance, they should be automatically enrolled.
The test suite was written by GPT-5.
A test suite was added that should be sufficient.
> Auto-enroll invited users

- apps/prairielearn/src/lib/client/page-context.test.ts
- apps/prairielearn/src/lib/client/safe-db-types.test.ts
- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/migrations/20250917191818__course_instances__rename_requires_secret_link.sql
- apps/prairielearn/src/migrations/20250917191818__course_instances__self_enrollment_use_enrollment_code__add.sql
- apps/prairielearn/src/migrations/README.md
- apps/prairielearn/src/schemas/infoCourseInstance.ts
- apps/prairielearn/src/schemas/schemas/infoCourseInstance.json
- apps/prairielearn/src/sprocs/sync_course_instances.sql
- apps/prairielearn/src/sync/course-db.ts
- apps/prairielearn/src/sync/fromDisk/courseInstances.ts
- apps/prairielearn/src/tests/sync/courseInstancesSync.test.ts
- database/tables/course_instances.pg
This was discussed in the meeting today as a more accurate descriptor of the behavior this controls. It renames the database and json fields.
None; Hopefully the explanation in migrations/README.md explains what I think this process entails.
> Rename `requiresSecretLink` to `useEnrollmentCode`

- apps/prairielearn/src/lib/db-types.ts
- apps/prairielearn/src/migrations/20250917191819__course_instances__self_enrollment_requires_secret_link__drop.sql
- database/tables/course_instances.pg
This finalizes the work done in #12917 .
None.
> Drop `self_enrollment_requires_secret_link` column

- apps/prairielearn/src/lib/externalGraderCommon.ts
- apps/prairielearn/src/middlewares/authzCourseOrInstance.ts
- apps/prairielearn/src/models/enrollment.ts
- docs/assets/extra.css
I noticed one of these while reviewing a recent PR. I found the remaining with `\}\n\/`.
> Dumb formatting nits

- CODEOWNERS
#13006 was assigned to me only, since I'm a code owner for the only changed file. [Code owner rules](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) specify that, if there are two lines that match the files being changed, only the last one takes precedence, and if multiple owners should be listed they must be in the same line.
Not testing, but should be straightforward.
> Ensure core is assigned to review PRs with other code owners

- .changeset/floppy-spoons-tan.md
- apps/prairielearn/assets/scripts/administratorInstitutionLti13Client.ts
- apps/prairielearn/assets/scripts/behaviors/bootstrap-compat.ts
- apps/prairielearn/assets/scripts/behaviors/popover.ts
- apps/prairielearn/assets/scripts/behaviors/tooltip.ts
- apps/prairielearn/assets/scripts/externalImageCaptureClient.ts
- apps/prairielearn/assets/scripts/instructorAssessmentManualGradingAssessmentQuestionClient.ts
- apps/prairielearn/assets/scripts/instructorGradebookClient.ts
- apps/prairielearn/assets/scripts/instructorRequestCourseClient.ts
- apps/prairielearn/assets/scripts/lib/bootstrap-compat-utils.ts
- apps/prairielearn/assets/scripts/lib/copyContent.ts
- apps/prairielearn/assets/scripts/lib/parallelHistograms.ts
- apps/prairielearn/assets/scripts/lib/questionsTable.tsx
- apps/prairielearn/assets/scripts/lib/scatter.ts
- apps/prairielearn/assets/scripts/question.ts
- apps/prairielearn/assets/scripts/tsconfig.json
- apps/prairielearn/src/components/QuestionsTable.tsx
- apps/prairielearn/src/components/QuestionsTable.types.ts
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.html.ts
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.ts
- apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.types.ts
- eslint.config.mjs
- packages/browser-utils/src/encode-data.ts
This continues work with `no-unnecessary-condition`, helping us write bug-free code.
None.
> Enable `no-unnecessary-condition` over assets
