PrairieLearn/PrairieLearn

- frontend/require/app.js
In 233 this semester, we've had multiple homeworks released on the same day, so sorting by due date does the right thing and sorting by date available does not. The sort still falls back to the date available in case the due date is not provided.
> Sorting tests by due date first and then available date

- backend/server.js
I didn't think it was worth it to update the frontend (see the commit message for reasoning); if you think it's needed, I'll go figure out how frontend things work :).
I'm also not a big fan of hardcoding `Superuser`; would something like `PrairieRole.rankToRole(PrairieRole.SUPERUSER)` (or something else) be better?
> Only prevent changing the role of superusers

- backend/RetryExamTestServer.js
This won't affect existing tests, but any new test instances will show
zone titles.
Closes #290
> Show zone titles in the UI

- backend/server.js
This was a regression caused by e330482 ("split json-load.js and
course-db.js out of server.js"). course-db requires require-frontend,
which sets up the config for requirejs. However, when course-db is
required, config.json hasn't been read yet. As a result, requirejs is
loaded with the default config, which has 'courseDir:
"../exampleCourse"'. This, in turn, breaks course code that uses
"serverCode" and "clientCode".
> Import require-frontend after reading config

- backend/server.js
This essentially will buffer an unlimited amount of data from git, which can be kind-of annoying to scroll through on the UI.
Thoughts on whether it'd be better to truncate after a certain amount of data? An alternative to that would be to have a 'show more' link in the UI.
> Don't crash on large pulls

- Dockerfile
- docker/etc/cont-init.d/01-postgres-init
- docker/etc/services.d/postgresql/run
- docker/etc/services.d/prairielearn/run
This requires not using `with-contenv`, which means that you can't
override PGDATA; however, the container wasn't really designed to do
that anyway.
> Create initial database during build

- v2/exampleCourse/courseInstances/Sp15/assessments/pastsubmissions/info.json
- v2/exampleCourse/courseInstances/Sp15/assessments/v2workingproblems/info.json
- v2/exampleCourse/questions/addVectors/client.js
- v2/exampleCourse/questions/addVectors/info.json
- v2/pages/userInstanceQuestionExam/userInstanceQuestionExam.ejs
- v2/pages/userInstanceQuestionExam/userInstanceQuestionExam.js
- v2/pages/userInstanceQuestionExam/userInstanceQuestionExam.sql
- v2/pages/userInstanceQuestionHomework/userInstanceQuestionHomework.ejs
- v2/pages/userInstanceQuestionHomework/userInstanceQuestionHomework.js
- v2/pages/userInstanceQuestionHomework/userInstanceQuestionHomework.sql
- v2/public/localscripts/calculationQuestion/SimpleClient.js
- v2/public/localscripts/question.js
- v2/public/localscripts/questionCalculation.js
Addresses #255 (and some portion of #29 )
I've left the extra assessment "pastsubmissions" within exampleCourse for testing (the other exams don't load because they include unsupported question types). Once everything checks out, I can make an additional commit to remove the unnecessary assessment.
If you like, I can also combine the two functions in userInstanceQuestionExam.js at lines 84-93 and 95-114, and remove the get_submission BLOCK (lines 11-19) from userInstanceQuestionExam.sql -- getting the most recent submission could be done while getting all the submissions.
> Show all submissions to a question in exam mode

- assessments/homework.sql
- sprocs/assessment_points_homework.sql
This fixes division by zero for homeworks/practice exams when maxPoints is set to zero (no credit), done in the same way as the fix for #509.
> Fix division by zero in non-exam zero maxPoints assignments

- server.js
This adds a handler `/ping` which writes a single byte as a response. This should be placed outside of Shib's paths so an external health checker can make sure that the server is still handling requests without simply hitting Shib and "passing" (and this should already be true in our case).
I chose not to use a webhook, as the line to just do it in `server.js` is shorter than making a separate file and requiring it.
`/ping` with `.` is my personal preference, but this can be modified.
> add /ping health check handler

- exampleCourse/questions/multiplyTwoMatrices/question.html
- exampleCourse/questions/multiplyTwoMatrices/server.py
- exampleCourse/questions/multiplyTwoNumbers/question.html
- exampleCourse/questions/multiplyTwoNumbers/server.py
- exampleCourse/questions/positionTimeGraph/question.html
- question-servers/elements/pl_figure.py
- question-servers/elements/pl_matrix_input.py
- question-servers/elements/pl_matrix_output.py
- question-servers/elements/pl_number_input.py
- question-servers/freeformPythonLib/prairielearn.py
- question-servers/freeformPythonLib/to_precision.py
* In `number_input` and `matrix_input` elements, the correct answer is displayed in a way that better matches the method of comparison (`relabs`, `sigfig`, or `decdig`).
* Also, in element attributes, changes `name` to `params_name`, `answers_name`, or `file_name` as appropriate to be more explicit about the link between HTML and data.
> Format matches comparison method

- doc/installing.md
`docker run` needs both `-i` and `-t` to be killed by Control-C. Add this where appropriate. (Some examples had it, some didn't.)
> Make `docker run` kill-able

- Dockerfile
The current Docker image incurs a pretty large download whenever code changes, as node dependencies are installed after anything is copied over.
In exchange for an added layer, we can pre-copy `requirements.txt` and `package.json` to install dependencies early, then copy the code later. This pattern is shown in the [Dockerfile best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#add-or-copy) page.
Comparing the two images in total (plj is the new version):
```
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
plj                         latest              efab05904bf6        3 minutes ago       1.27GB
prairielearn/prairielearn   latest              e96445423003        3 days ago          1.54GB
```
The …
> Restructure Dockerfile to reduce churn, improve style

- lib/assessment.js
- lib/messageQueue.js
- server.js
- webhooks/grading/grading.js
Sharing code between local dev and production means more consistent behavior, yay!
The one quirk here is there was a cyclical dependency between `assessment.js`, `question.js`, and `messageQueue.js`, which I broke by passing `assessment` to `messageQueue.init`. This could be solved properly by not assigning directly to `module.exports`, but instead assigning to `module.exports.functionNameHere` in all involved modules, but I'm out of time to do that right :)
> Refactor to share results processing code in local dev and production

- elements/pl_file_editor/pl_file_editor.js
- elements/pl_file_editor/pl_file_editor.py
- elements/pl_file_preview/info.json
- elements/pl_file_preview/pl_file_preview.css
- elements/pl_file_preview/pl_file_preview.js
- elements/pl_file_preview/pl_file_preview.mustache
- elements/pl_file_preview/pl_file_preview.py
- elements/pl_file_upload/pl_file_upload.js
- elements/pl_file_upload/pl_file_upload.mustache
- elements/pl_file_upload/pl_file_upload.py
- exampleCourse/questions/fibonacciEditor/question.html
- exampleCourse/questions/fibonacciUpload/question.html
Important changes:
- `pl_file_upload` and `pl_file_editor` now only render in the Question panel. To show the submitted files for a question in a Submission panel, use the new `pl_file_preview` element. This will automatically render and files present in the `_files` submitted answer.
- Support for using any number/combination of `pl_file_upload` and `pl_file_editor` elements on the same page. They will now collaboratively build the `_files` answer and combine any format errors into one array. These files and any errors are displayed by `pl_file_preview`.
> File element improvements

- ChangeLog.md
- elements/pl_file_upload/pl_file_upload.py
A particularly enterprising student could add any files to be uploaded by modifying the json in the hidden input. This strips out any files not present in the `file_names` attribute.
> Fix exploit where students could upload arbitrary files

- pages/authCallbackShib/authCallbackShib.js
Allows specifying a URL path to redirect to after verifying shibboleth auth. i.e.
https://pl-dev.engr.illinois.edu/pl/shibcallback/redirect/pl/course_instance/4/instructor/assessment/10/
Needs testing that it survives the single sign on from shibboleth, even if we don't have an active session on PrairieLearn
Branch is active on pl-dev right now if you want to poke at it.
> Shibboleth redirect path

- elements/pl_external_grader_results/pl_external_grader_results.mustache
- elements/pl_external_grader_results/pl_external_grader_results.py
This ensures that the results display element won't crash if `score` is missing from the results.
> Fix external grading results display when score is missing

- Dockerfile
- requirements.txt
For the CS 126 terminal stuff.
> add pycryptodome for Python cryptography support

- schemas/questionOptionsv3.json
This was missing, so using options in v3 `info.json` files breaks on sync.
> Add options schema for v3 questions

- ChangeLog.md
- elements/pl_symbolic_input/pl_symbolic_input.py
- lib/python_helper_sympy.py
* Move parser to `lib/python_helper_sympy.py`
* Eliminate use of `sympy.sympify`
* Walk AST to convert int and float numbers to sympy equivalents
> Improve symbolic input parsing

- Dockerfile
As per [this image monitoring service,](https://anchore.io/image/dockerhub/prairielearn%2Fprairielearn:latest) we aren't updating the main system, so are missing out on security updates in the docker image we give out (not deployment). It also suggests adding a healthcheck, which can't hurt, and we'll probably use one if/when prod gets deployed as a container.
The update command goes after the yum command to add the extra repos, since the repo packages themselves can have updates (mainly epel-release).
> Add full system update and HEALTHCHECK to Dockerfile

- ChangeLog.md
- elements/pl_matrix_input/pl_matrix_input.py
- elements/pl_number_input/pl_number_input.py
- elements/pl_symbolic_input/pl_symbolic_input.py
- question-servers/freeformPythonLib/prairielearn.py
This is a small update to add `to_json()` and `from_json()` helper functions to `prairielearn.py`, to help instructors with JSON serialization of these types:
* complex number
* real-valued ndarray
* complex-valued ndarray
* sympy expression
* sympy matrix
I did not yet document these helper functions. Existing input elements (`pl_number_input`, `pl_matrix_input`, and `pl_symbolic_input`) support the format created by `to_json()`.
> JSON serialization helper functions

- Dockerfile
The IUS repo bumped to 3.6.3, and either added the `-devel` package or forgot something while packaging.
Fixes docker builds and CI issues.
> Add -devel package for python so pip package installs using gcc don't fail

- ChangeLog.md
- pages/studentInstanceQuestionExam/studentInstanceQuestionExam.ejs
This is a small patch to fix broken popovers in student exam questions.
Popovers in button groups, input groups, and tables need the attribute `data-container="body"` in order to function properly (see [docs](https://getbootstrap.com/docs/3.3/javascript/#popovers)). This attribute is missing in some element code - it will be added in a future patch. The student exam question page was the **only** page that initialized popovers with
`$('[data-toggle="popover"]').popover();`
instead of with
`$('[data-toggle="popover"]').popover({container: 'body'});`
As a consequence, the student exam question page was the **only** page that did **not** specify `'body'` as the default container (doing so would correct for a missing `data-container="body"` attribute).
The reason this bug only showed up …
> Fix broken popovers

- ChangeLog.md
- lib/externalGraderLocal.js
This makes local grading reject results that are larger than 100KB.
> Make local grading consistent with PrairieGrader.

- ChangeLog.md
- elements/pl_symbolic_input/pl_symbolic_input.mustache
- lib/python_helper_sympy.py
fixes #896
We don't want to allow floating-point numbers in symbolic expressions. They cause unpredictable behavior when comparing expressions for equality. Example: `(2*pi)**(0.5)` is parsed as `1.4142135623731*pi**0.5` and is not considered the same as `sqrt(2*pi)` or as `(2*pi)**(1/2)`.
> Disallow floats in symbolic inputs

- pages/instructorGradingJob/instructorGradingJob.ejs
- pages/instructorGradingJob/instructorGradingJob.js
- webhooks/grading/grading.js
- webhooks/grading/grading.sql
For externally graded jobs that are executed on S3, the job's output is no longer cached in the DB. Instead, the instructor grading job page will load the logs from S3 when they're needed. This reuses the existing file download feature. As before, S3 requests are proxied through PrairieLearn to enforce access rules.
> Load external grader output from s3 instead of db

- ChangeLog.md
- elements/pl_number_input/pl_number_input.py
Checks that answer submitted to `<pl_number_input>` is finite, i.e., that it is not `inf` or `nan`. Does not parse or grade a non-finite submitted answer. This is consistent with `<pl_matrix_input>`. Without this fix, `inf` or `nan` would result in a PL error (`Error parsing submission`).
> Number input must be finite

- pages/instructorAssessment/instructorAssessment.ejs
Markup was improperly generated for two of these links, leading to font issues.
> Fix markup issue with assessment reopen and close buttons

- ChangeLog.md
- elements/pl_answer_panel/pl_answer_panel.py
- elements/pl_checkbox/pl_checkbox.py
- elements/pl_external_grader_results/pl_external_grader_results.py
- elements/pl_figure/pl_figure.py
- elements/pl_file_download/pl_file_download.py
- elements/pl_file_editor/pl_file_editor.py
- elements/pl_file_preview/pl_file_preview.py
- elements/pl_file_upload/pl_file_upload.py
- elements/pl_matrix_input/pl_matrix_input.py
- elements/pl_matrix_output/pl_matrix_output.py
- elements/pl_multiple_choice/pl_multiple_choice.py
- elements/pl_number_input/pl_number_input.py
- elements/pl_question_panel/pl_question_panel.py
- elements/pl_submission_panel/pl_submission_panel.py
- elements/pl_symbolic_input/pl_symbolic_input.py
- elements/pl_variable_score/pl_variable_score.py
- exampleCourse/questions/addNumbers/server.py
- lib/python-caller-trampoline.py
Removes the need to return `data` in v3 element and server functions (it was always passed as a mutable argument to these functions). Here is what's done now:
* If nothing is returned, we use the passed (possibly modified) value of `data`.
* If something is returned:
* If it does not differ from what is passed, we use it.
* If it differs from what is passed, we use it, and log an issue.
To deep-compare what is passed with what is returned, we convert each to JSON (sorted) and compare that. We do this because it's a lot easier, and we have to convert at least one of these two things to JSON anyway.
An easy way to test this code is to use the module `copy`. For example:
```
import copy
def generate(data):
data_copy = copy.deepcopy(data)
data_copy['params']['a'] = 10
data['params']['a'] = 5 …
```
> Remove the need to return data in python functions

- lib/python-caller-trampoline.py
It causes no harm but should be removed. Was introduced when debugging the python caller when removing the need to return `data`.
> remove unnecessary line in python caller that was for debugging

- ChangeLog.md
- elements/pl_number_input/pl_number_input.mustache
- elements/pl_number_input/pl_number_input.py
Casts both submitted and true answers as `np.float64` (double-precision floating-point numbers) to avoid a crash when submitted answer is a too-large integer. This crash is caused by an error thrown by `np.allclose(a, b)` - used for grading when the method of comparison is `relabs` - when either `a` or `b` is an integer that cannot be represented as `np.int64`.
Modifies help text to make clear what the upper and lower bounds on the submitted answer are.
This fixes #953.
> Fix pl_number_input bug

- ChangeLog.md
- elements/pl_file_upload/pl_file_upload.css
- elements/pl_file_upload/pl_file_upload.js
- elements/pl_file_upload/pl_file_upload.mustache
The `pl_file_upload` element got broken sometime during the Bootstrap 4 upgrade, and I didn't catch it. This restores everything to working order.
> Fix issues with file upload element

- ChangeLog.md
- doc/elements.md
- elements/pl_threejs/pl_threejs.js
- elements/pl_threejs/pl_threejs.mustache
- elements/pl_threejs/pl_threejs.py
- exampleCourse/questions/rotateObject/info.json
- exampleCourse/questions/rotateObject/question.html
- exampleCourse/questions/rotateObject/server.py
Body-fixed objects can now be translated (as a group) as well as rotated in the `<pl_threejs>` element. Improved UI. Made minor changes to attributes.
> Add translation to threejs

- ChangeLog.md
- elements/pl_threejs/pl_threejs.py
Small emergency bug fix in `pl_threejs`.
The attribute `tol_translation` was being read in two places, `render()` and `grade()`. A different default was being applied in each place. The consequence was that submitted answers were being checked against a stricter tolerance than the student was told.
> Fix tol bug in threejs

- ChangeLog.md
- pages/authCallbackOAuth2/authCallbackOAuth2.js
Trying to log into PrairieLearn using Google raises an error that says `setCredentials is not a function`.
The setCredentials function seems to have been accidentally deleted, so this PR fixes that by assigning the credentials directly. See https://github.com/google/google-api-nodejs-client/issues/869 for more details.
> Assign OAuth credentials directly

- ChangeLog.md
- elements/pl_threejs/pl_threejs.py
Now handles the case when `submitted_answer` exists but is `None`.
This might happen due to an error in transmission of data through the hidden input element (e.g., when course content is being synced at exactly the time of submission). If it happens, students got stuck because `render()` used `submitted_answer` to initialize body and camera pose.
The fixed code checks carefully for `None` and handles this case appropriately.
> Fix none submission bug in plthreejs

- ChangeLog.md
- question-servers/freeformPythonLib/prairielearn.py
The function `prairielearn.string_to_2darray()` was stripping whitespace on either side of "-" and "+" in an effort to reduce parse errors when handling complex number input. Matlab format breaks this feature, because it uses space delimiters. Stripping is now applied only to strings in python format.
> Fix bug in matlab parse

- ChangeLog.md
- environments/centos7-plbase/Dockerfile
- environments/centos7-plbase/r-requirements.R
This PR has components that were split from PR #1023, which tried to solve adding `rpy2` as indicated in #1009. 
In particular, this PR adds _R_ and the _R_ packages dependencies for @stat385uiuc -- which unfortunately take a while to compile as no prebuilt binaries are available on CentOS -- to the `centos-plbase` docker image that was added to #1027
> Add R to centos7-plbase Docker Image

- ChangeLog.md
- database/tables/questions.pg
- lib/externalGraderLocal.js
- lib/externalGraderSqs.js
- migrations/106_questions__external_grading_enable_networking__add.sql
- schemas/infoQuestion.json
- sync/fromDisk/questions.js
- sync/fromDisk/questions.sql
This adds the ability to explicitly enable network access for external grading containers. It still defaults to disabling network access, and should be used only when absolutely necessary or when you're sure that student's can't/won't write networking code.
> External grading network config

- ChangeLog.md
- pages/courseOverview/courseOverview.ejs
I missed this when upgrading to Font Awesome 5...
> Fix Font Awesome icon for editing course roles

- ChangeLog.md
- sprocs/tags_for_question.sql
Was sorting by `id` instead of the `number` field. Found by the HackIllinois graphical editor team.
> Fixes tag display order

- ChangeLog.md
- middlewares/authn.js
- pages/authCallbackAzure/authCallbackAzure.js
- pages/authCallbackOAuth2/authCallbackOAuth2.js
- pages/authCallbackShib/authCallbackShib.js
- server.js
Previously, if you deep linked into something (i.e. `https://pl-dev.engr.illinois.edu/pl/course_instance/39/instructor/assessment/756/`) and were redirected out for authentication, post-login you were sent to `/pl`.
This PR stores the original URL request in a cookie so we can redirect back to it, allowing deep-linking with auth.
> Auth redirect preserves originally requested URL

- ChangeLog.md
- Dockerfile
- docker/start_postgres.sh
- package-lock.json
- package.json
- server.js
PrairieLearn's first run, which does all the migrations, can take a while to run. Since this is visible when starting a docker container, moving that initialization to the Docker build stage makes it quicker to load for the user. On Dave's test box, this saved about 10s on startup with the database pre-migrated in the container.
Adds smarter command line parsing to PL (`yarg-parser`) and `stop` functionality to `docker/start_postgres.sh`
Closes #948
> DB initialization and migrations at Docker build

- ChangeLog.md
- elements/pl_file_upload/pl_file_upload.py
- elements/pl_threejs/pl_threejs.py
- environments/centos7-ocaml/main.py
- exampleCourse/serverFilesCourse/python_autograder/pltest.py
- lib/python-caller-trampoline.py
Adds `allow_nan=False` to all `json.dumps` calls to ensure that (except for repeated names) they produce valid JSON.
Also adds exception handling to `json.dumps` calls in `python-caller-trampoline.py` that displays any object that can't be converted to valid JSON. Doing so makes it much easier to debug problems with server-generated parts of `data`.
Fixes #1072
> Fix invalid json

- ChangeLog.md
- pages/instructorAssessment/instructorAssessment.sql
The `JOIN` means that untagged questions will not appear. A `LEFT JOIN` will just leave the tags column blank for questions without them.
> Fix instructorAssessment page's missing questions

- ChangeLog.md
- lib/question.js
If a question was part of an assessment and issue reporting was enabled, the async panel rerender would crash because `variant` and `__csrf_token` weren't available.
Fixes #1073
> Fix error when rendering question score panel

- ChangeLog.md
- question-servers/freeformPythonLib/prairielearn.py
Formerly, the functions `to_json` and `from_json` in the library `prairielearn.py` made no attempt to preserve the `dtype` of an ndarray. Forgetting about this can cause trouble - for example, the ndarray `array([[1.0]])` with `dtype=np.float64` becomes `array([[1]])` with `dtype=np.int64` after conversion, with consequences that may be hard to debug.
Because these functions are meant to help folks who don't want to understand the details of jsonification, I thought it best to change them to support preservation of `dtype`. This was done by adding a third field `_dtype` to the encoded object when appropriate.
This change is backward-compatible. All previously encoded objects (without `_dtype`) will be recovered by `from_json` as they always were.
> Preserve dtype in json

- ChangeLog.md
- elements/pl_matrix_input/pl_matrix_input.py
- elements/pl_number_input/pl_number_input.py
Displays zero tolerances properly in `pl_matrix_input` and `pl_number_input`. Throws an exception if tolerances are negative.
Fixes #1117.
> Input hint fixes

- ChangeLog.md
- elements/pl_file_editor/pl_file_editor.js
- elements/pl_file_editor/pl_file_editor.mustache
Adds a footer to the editor with a "Restore original file" button that asks you to confirm because this action is potentially destructive.
Fixes #1119.
> Add ability to restore original file in pl_file_editor

- ChangeLog.md
- lib/paginate.js
- pages/instructorAssessment/instructorAssessment.js
- pages/instructorAssessment/instructorAssessment.sql
- pages/instructorAssessments/instructorAssessments.ejs
- pages/instructorAssessments/instructorAssessments.js
- pages/instructorAssessments/instructorAssessments.sql
For some queries (specifically the ones that generate archives of submitted files), the query results are so large that they can't fit in memory. This PR changes to fetching the rows in chunks and streaming the results through the zip archiver so that the total amount of memory in use at any moment remains minimal.
On my machine, this can compress and send ~2Mbps once things get up to speed. I'm able to download a zip of 200,000 files (100K 20B files and 100K 3KB files) in ~2:30.
This also adds an "all file submissions" link to the instructor assessments page; this download utilizes this new chunking+streaming method.
> Improve support for extremely large downloads

- ChangeLog.md
- doc/installingNative.md
- package.json
- Adds doc with a workaround for error on `mcrypt` install (specify the use of python 2).
- Updates required `popper.js` version to `1.14.0`.
> Mcrypt docs fix, popper version update

- ChangeLog.md
- lib/question.sql
- pages/instructorIssues/instructorIssues.ejs
- pages/instructorIssues/instructorIssues.sql
- pages/partials/question.ejs
This PR incorporates the name of the student and a clickable e-mail template into the issue report interface for PL to address #1136. See images below for how the UI changes.
**Old:**
**New** issue information _without_ spaces around e-mail
**New** issue information with spaces around e-mail
**Old:**
**New** issue tracker _without_ spaces around e-mail
**New** issue tracker with spaces around e-mail
Clicking on the e-mail launches the system default webmail client with the to field, subject, and body filled in.
> Show student names on issue reports (close #1136)

- ChangeLog.md
- elements/pl_integer_input/pl_integer_input.mustache
- elements/pl_matrix_input/pl_matrix_input.mustache
- elements/pl_symbolic_input/pl_symbolic_input.mustache
Fixes to a few problems I noticed while testing something else
* `pl_symbolic_input` was using an old`input-group-btn` class; I've updated this to the Bootstrap 4 class.
* Some elements had `aria-describedby` attributes that references non-existent things. This adds the appropriate IDs and updates that attribute to refer to them.
> Fix element styling + aria attributes

- ChangeLog.md
- doc/courseInstance.md
- lib/course-db.js
Currently an empty `assessments` directory syncs correctly, but a missing `assessments` causes syncs to fail. This explicitly checks for the existence of `assessments` and warns if the directory is missing (skipping the sync).
Fixes #999
> Handle missing `assessments` directory on course instance sync

- ChangeLog.md
- public/javascripts/PrairieUtil.js
After package update, the constructor for `clipboard.js` is `ClipboardJS` and not `Clipboard`. Changed one line in `PrairieUtil.js` to the correct form of this constructor, which is used to create a copy button.
Fixes #1203
> Fix copy button

- doc/PrairieDraw.md
The link from the PrairieDraw page to the element list page was incorrect; this fixes it.
> Fix link in PD documentation

- ChangeLog.md
- doc/question.md
- exampleCourse/infoCourse.json
- exampleCourse/questions/chooseMatrices/info.json
- exampleCourse/questions/chooseMatrices/question.html
- exampleCourse/questions/chooseMatrices/server.py
- lib/course-db.js
- package-lock.json
- package.json
- question-servers/freeform.js
- schemas/infoCourse.json
- sync/fromDisk/courseInfo.js
- sync/fromDisk/courseInfo.sql
I told @mfsilva22 I'd have this ready ASAP, but my parents will be in town for the next week, meaning that most of my free time will be family time 🙂this is a continuation of my work from #1188 - it's basically the same code, but leaving the legacy question parsing + rendering in place. The thought is to have the new renderer behind a feature flag so that courses who know what they're doing can opt in while we get our act together re: question migrations.
The remaining thing to be done is to actually add the feature flag. It looks like the `pl_courses` table has an unused column `options` that isn't ever populated during sync, which could probably be used for this purpose. For an example (abbreviated) `infoCourse.json`:
```json
{
"name": "CS 225",
"options": {
"useNewQuestionRenderer": …
```
> New question renderer with feature flag

- ChangeLog.md
- elements/pl-multiple-choice/pl-multiple-choice.py
Two small changes:
* Put feedback (i.e., the badge showing a correct or incorrect answer) inside the `<label>` tags where it belongs.
* When `inline="true"`, put everything inside `<span>` tags instead of inside `<p>` so the result is valid HTML.
> Fix appearance of multiple choice

- ChangeLog.md
- doc/elements.md
- elements/pl-symbolic-input/pl-symbolic-input.mustache
- elements/pl-symbolic-input/pl-symbolic-input.py
The `pl-symbolic-input` element already exists and has worked fine for a long time. I added two optional attributes (`label` and `display`) that mirror other input elements, and added docs.
> Add attributes and doc to pl-symbolic-input

- ChangeLog.md
- doc/elements.md
- elements/pl-code/pl-code.mustache
- elements/pl-code/pl-code.py
- exampleCourse/questions/codeHighlight/question.html
This adds an option to attempt to prevent students from copy/pasting the source code of a `pl-code` element. It disables selection, clicking, and right-clicking on the code. It's still relatively easy to see the source - just going to "View source" on the page and grepping for the code will reveal it. But frankly, I don't care that much 🙂 
Resolves #1224
> Add option to disable selecting on pl-code element

- ChangeLog.md
- elements/pl-symbolic-input/pl-symbolic-input.mustache
- elements/pl-symbolic-input/pl-symbolic-input.py
In `pl-symbolic-input`, it was possible for conversion of the submission string to a sympy expression in `parse()` to complete successfully, but for (re-)conversion of the string equivalent of this expression to an equivalent sympy expression in `grade()` to throw an error.
For example, if a student submitted the expression `sqrt(-1)`, it would parse successfully, but the result would be stored as the string `I`, which would result in an error on `grade()`.
We now round-trip conversion in `parse()` - we convert the string to a sympy expression, convert this expression back to a string, and make sure we can convert the result to a sympy expression again (with the same list of allowable variables and constants). If the reconversion fails, the submission is declared invalid, and appropriate …
> Fix another submission bug in symbolic input element

- ChangeLog.md
- doc/elements.md
- elements/pl-symbolic-input/pl-symbolic-input.mustache
- elements/pl-symbolic-input/pl-symbolic-input.py
- exampleCourse/courseInstances/Sp15/assessments/plelementexamples/infoAssessment.json
- exampleCourse/questions/examplesSymbolicInput/info.json
- exampleCourse/questions/examplesSymbolicInput/question.html
- exampleCourse/questions/examplesSymbolicInput/server.py
- lib/python_helper_sympy.py
- question-servers/freeformPythonLib/prairielearn.py
This time the issue was handling `sympy.E`.
Before, if the submitted answer were to contain something like `exp(1)`, then it would be parsed to `sympy.E`, which would be converted to the string `E`, which - upon the double-check parse - would raise an exception, because `E` wouldn't be in the list of variables (and if it were, that would be even worse).
Now, we handle this properly, by substituting a hidden helper variable for `sympy.E`.
We also handle `sympy.I` properly now, and - as a bonus - add an option to allow symbolic inputs with complex numbers, which wasn't ever allowed before.
> Yet another symbolic input fix (handling E and I)

- ChangeLog.md
- exampleCourse/questions/fibonacciEditor/question.html
- pages/partials/externalGradingLiveUpdate.ejs
- sprocs/grading_job_status.sql
This will close sockets after they're no longer needed, which for us is after the first set of results that we fetch from them. On any given page load, there will be at most one question that needs results fetched, given that we cancel pending jobs when a new one is submitted.
This also checks if any submissions on a page will actually need a socket and doesn't open one if everything is either graded or canceled.
> Better client socket handling on externally graded questions

- ChangeLog.md
- exampleCourse/courseInstances/Sp15/assessments/exam1/infoAssessment.json
https://prairielearn.readthedocs.io/en/latest/assessment/ links to the exampleCourse exam1 as an example of how to add a formula sheet to an assessment, but it was missing. This adds it back.
> Add "text" stanza formula sheet example back

- ChangeLog.md
- elements/pl-string-input/pl-string-input.mustache
- elements/pl-string-input/pl-string-input.py
- exampleCourse/questions/examplesStringInput/question.html
Removes the word "string" as a default placeholder. Creates an attribute `placeholder-text` allowing users to choose their own text. By default, it displays an empty input box.
This PR addresses issue #1276
> String element update

- ChangeLog.md
- pages/partials/questionScorePanel.ejs
We don't have authz data when rendering the score panel async for real-time results. A temp fix is to just disable the exam-specific message.
> Fix render bug with real-time external grader results

- ChangeLog.md
- elements/pl-matrix-component-input/pl-matrix-component-input.css
- elements/pl-matrix-component-input/pl-matrix-component-input.mustache
- elements/pl-matrix-component-input/pl-matrix-component-input.py
- exampleCourse/questions/examplesMatrixInput/question.html
- exampleCourse/questions/examplesMatrixInput/server.py
This adds a scroll bar to the matrix part of the element (not including the label and hint box), and adjusts the size of the entire element.
Added one question to `examplesMatrixInput` that shows a very long row-vector.
This PR also fixes a previous bug (this element does not considering complex numbers, based on the initial implementation, but entering `i` or `j` would break the question, instead of throwing an invalid message.
> scroll bar as auto

- ChangeLog.md
- elements/pl-matrix-component-input/pl-matrix-component-input.py
Setting rowspan equal to the number of rows, Safari dislikes rowspan="0".  Fixes #1312
> fix multi-row matrix input rendering on safari (#1312)

- ChangeLog.md
- elements/pl-figure/pl-figure.mustache
Updates the Bootstrap 3 classes on the `img` tag generated by `pl-figure` to Bootstrap 4 classes of `img-fluid` for responsiveness and `mx-auto d-block` for centering. 
c.f. 
- fluid images: https://getbootstrap.com/docs/4.1/content/images/ 
- centering approach (`text-center` vs. `mx-auto d-block`): https://stackoverflow.com/a/43227280/1345455
> Ensure images are displayed in a responsive manner (close #1322)

- ChangeLog.md
- elements/pl-file-editor/info.json
- package-lock.json
- package.json
This PR changes `<pl-file-editor>` to use a version of the Ace editor from npm. This allows us to keep the source up to date. Using the latest source also fixes some bugs that Ace had in mobile browsers, such as shift and backspace behaving weirdly.
I'm leaving the ace editor in `public/javascripts/ace` for now, as I'm not sure if any courses still rely on it. We can probably check request logs a few months after this is deployed to check if anyone is still accessing them and strip them out of that directory if so.
> Source Ace editor from npm

- ChangeLog.md
- pages/instructorQuestion/instructorQuestion.ejs
The issue link didn't include the QID; now it does 🎉
> Fix issues link on instructor question page

- ChangeLog.md
- elements/pl-code/pl-code.mustache
#1382 accidentally introduced a regression in `pl-code` where HTML entities were being escaped twice. This PR changes the `pl-code` template to use the triple-mustache so that the code is not re-escaped.
> Fix escaping of contents of pl-code block

- ChangeLog.md
- doc/question.md
Typo. The "Edit on GitHub" page header is broken too (links to `docs` instead of `doc`) but I'm not sure where to fix that template.
> Typo: precense -> presence

- ChangeLog.md
- mkdocs.yml
Have to add a line to mkdocs.yml to make the "Edit on GitHub" links point to real pages.
> Fix "Edit on GitHub" links in mkdocs.yml

- ChangeLog.md
- lib/python-caller-trampoline.py
The traceback in the console log generated by a python error (e.g., displayed on the question page or as an issue) had been incorrectly referring to `"<string>"` instead of to the name of the file in which the error was thrown. This has been fixed.
fixes #1408
> Fix python traceback

- ChangeLog.md
- elements/pl-code/pl-code.py
- exampleCourse/questions/examplesAddCodeFromFile/question.html
- exampleCourse/questions/examplesAddCodeFromFile/sample-cd-data.xml
Within this PR, we:
- Ensured that code read in via `source-file-name` in `pl-code` was escaped.
- Added an example of reading in an XML data file (note, `xml` is not a language supported.)
Details in #1420.
> Fix escape of code under pl-code's file input (close #1420)

- ChangeLog.md
- lib/externalGraderLocal.js
By default, Docker doesn't remove any volumes created by a given container. Given that we want our containers to be 100% ephemeral, this changes the local grader to remove volumes when it removes containers after grading is complete. We'll need a corresponding PR for PrairieGrader as well.
> Remove docker volumes when removing local grader containers

- ChangeLog.md
- public/javascripts/PrairieUtil.js
This PR fixes the copy button that appears in `pl-matrix-input` and `pl-matrix-output` elements.
This button was broken on safari. The reason is that safari does not support the Clipboard API (https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API). `PrairieUtil.js` was mistakenly checking for the existence of this Clipboard API when it was trying to check for the existence of `clipboard.js`. There was no consequence on chrome, which does support the Clipboard API.
> Fix clipboardjs copy button

- ChangeLog.md
- doc/elements.md
- elements/pl-checkbox/info.json
- elements/pl-code/info.json
- elements/pl-code/pl-code.css
- elements/pl-code/pl-code.py
- exampleCourse/questions/codeHighlight/question.html
Lets users specify specific lines of code to apply a background highlight to. Users can also specify the color of the background highlight. Here's what that looks like in the example question:
> Highlight specific lines of code in pl-code

- ChangeLog.md
- tools/generate_uuids.py
Fixed a bug in tools/generate_uuid.py that added a uuid for files in the element subdirectory. 
Also added a verbose flag that can be passed as a command line argument to print all the files that were changed by the script to help in debugging.
> Closes generate_uuid bug #1091 and added verbose flag

- ChangeLog.md
- lib/assessment.js
- lib/sanitize-name.js
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js
- pages/instructorAssessmentInstance/instructorAssessmentInstance.js
- pages/instructorAssessmentQuestionStatistics/instructorAssessmentQuestionStatistics.js
- pages/instructorAssessmentStatistics/instructorAssessmentStatistics.js
- pages/instructorAssessments/instructorAssessments.js
- pages/instructorGradebook/instructorGradebook.js
- pages/instructorQuestion/instructorQuestion.ejs
- pages/instructorQuestion/instructorQuestion.js
Course names like "STAT/CS/IS 107" and "TAM 210/211" would have gradebook download links with the `/` character in the link, which would confuse the Express router. This adopts a similar approach to that used in the assessment downloads page and replaces any character not in `[a-zA-Z0-9]` with an underscore.
> Fix gradebook download link for special characters

- ChangeLog.md
- pages/courseSyncs/courseSyncs.js
Changes the sync steps from:
```
git pull --force
```
to 
```
git fetch 
git reset --hard origin/master
```
This change allows for users to rewrite repository history and closes #1258.
> Change sync procedural steps to allow history rewrites (close #1258)

- ChangeLog.md
- pages/instructorQuestion/instructorQuestion.ejs
- pages/instructorQuestion/instructorQuestion.js
Because any button that allows a single person to slow our grading throughput to a crawl is Bad.
> Disable 'Test 100 times' button for externally graded questions

- ChangeLog.md
- lib/externalGraderSqs.js
Now attempts to use the S3 SDK's native multipart streaming upload feature (which defaults to having retries).
> Attempt at S3 fix

- ChangeLog.md
- lib/externalGraderCommon.js
For text files, eagerly decoding the base64 contents to a string was fine. For binary files (tar archives, specifically) that breaks things. We now decode the files into a `Buffer` and write that directly to disk.
> Fix how binary files are handled during external grading

- ChangeLog.md
- elements/pl-code/pl-code.py
hljs has a compatibility issue with pl-code, where a single-line C++ comment can't be parsed correctly if the line is "highlighted" by pl-code and it is not terminated with a newline; the result is that the line following the single-line comment is also marked as a comment by hljs. Inserting a terminating \n on the highlighted line, inside the span, seems to fix this.
GitHub isn't letting me attach an image here but I'll try in a followup.
> Fix hljs syntax highlighting compatibility issue in pl-code.py

- ChangeLog.md
- tools/generate_uuids.py
I encountered this issue recently. The script wasn't matching UUIDs with uppercase letters although it could see the `uuid` property was there, failing with an error message.
> Let generate_uuids.py find uppercase UUIDs

- ChangeLog.md
- pages/enroll/enroll.ejs
Add/remove modal popup will replace the old popover, if enabled. This should have better behavior on some touchscreen devices, as well as offering more verbose warnings about what it means to add/remove a course on PL.
~(There is a toggle in the EJS code, `var useModals=true`, so it's easy to undo this if it seems to cause some unforeseen problems, or if A/B testing is necessary.)~ (Removed popover cruft as per Dave Mussulman's suggestion on Slack.)
The more verbose messages clearly state that add/remove on PL does not register for or drop courses with the University:
> ~Are you sure you want to add this course content to your PrairieLearn account? This does not register you in the actual course. You need to formally register for courses with the University separately.~
> ~Are you sure …
> Adding modal dialogue support to enroll.ejs

- ChangeLog.md
- lib/question.js
Fixes an issue introduced by #1342 where the variant ID was a `Number` on the server but a `String` on the client. This coerces the ID to a `String` when generating a CSRF token for a variant so that it matches what the client sends.
> Fix CSRF checking for external grading live updates

- ChangeLog.md
- elements/pl-number-input/pl-number-input.py
This PR partially fixes the flaky test cases in pl-number-input elements, which didn't take care of comparison options.
🚨Note: this PR only adds test cases concerning different comparison options, but doesn't fix other issues - e.g. lack of complex number tests, lack of randomization in 'correct' and 'invalid' test cases, and incorrect render with respect to rtol and atol, etc.
> Partially fix flaky tests in pl-number-input

- ChangeLog.md
- schemas/schemas/infoQuestion.json
- sync/fromDisk/questions.js
- tests/sync/util.js
Removes remaining references to `externalGradingOptions.files` from question `info.json` files.
Closes #1588
> Remove the deprecated "files" option for external grading

- ChangeLog.md
- pages/partials/question.ejs
Adds `autocomplete="off"` to the v3 question for to disable autocomplete. Fixes #1624.
> Disable autocomplete on v3 questions

- ChangeLog.md
- middlewares/clearCookies.js
- pages/authLogout/authLogout.js
Do not clear the assessment password cookie when visiting the `/pl` homepage, but do clear it when logging out.
Closes #1579
> Assessment password cookie clearing fix

- ChangeLog.md
- sync/fromDisk/tags.js
- sync/fromDisk/topics.js
- tests/sync/questionsSync.js
Previously, we weren't handling duplicates of missing tags/topics appropriately. Now, we dedupe before trying to sync.
This also removes what little support we had for `secondaryTopics` in questions, which was already going to be ripped out in #1640 anyways.
> Fix the syncing of missing tags and topics

- ChangeLog.md
- doc/question.md
The https://prairielearn.readthedocs.io/en/latest/question/ page has a runaway backtick. Hopefully this fixes it.
> Fix documentation formatting

- ChangeLog.md
- sync/fromDisk/topics.js
Fixes #1644 by providing a more detailed error message and aborting sync. This will be fixed more gracefully in #1640.
> Fix handling of duplicate topics in infoCourse.json

- ChangeLog.md
- pages/instructorFileEditor/instructorFileEditor.js
We had the permissions required for file editing set to course “Owner”. I think that we actually want this to be “Editor”? Syncing currently requires “Editor”, which seems to be equivalent to file editing. The levels we have are:
* Viewer — only view, no edit.
* Editor — can edit the course.
* Owner — can edit the course, and can change access permissions of other users.
> Change file edit access to "Editor", down from "Owner"

- ChangeLog.md
- sync/fromDisk/tags.js
- sync/fromDisk/topics.js
By using a `Set` instead of just an object, we can safely handle any property name.
This will also be fixed by #1640 once that's merged, but I want to get this fixed with the current code in the meantime.
Fixes #1651
> Fix tag/topic syncing with builtin JavaScript names

- ChangeLog.md
- exampleCourse/courseInstances/Sp15/assessments/exam5-public/infoAssessment.json
- exampleCourse/courseInstances/Sp15/assessments/exam8-public/infoAssessment.json
- pages/studentAssessmentExam/studentAssessmentExam.ejs
- tests/helperExam.js
- tests/testZoneGradingExam.js
Removes the proctor message from appearing when student is under `mode: "Public"` on `type: "Exam"`. 
Note: This leaves the text present when the following access modes are used in an assessment of `type: "Exam"`: 
- `SEB`
- `Exam` (`Exam` with password)
`type: "Exam"` with `mode: "Public"`
`type: "Exam"` with `mode: "Exam"`
> Restrict proctor message to access modes in CBTF/Secured Environments (close #1649)

- .travis.yml
- ChangeLog.md
- environments/centos7-plbase/Dockerfile
- tools/build-plbase-if-needed.sh
Currently, the `prairielearn/centos7-plbase` image is never rebuilt by Travis because it takes a long time to build and is generally pretty static. However, PRs like #1669 will have failing tests because the new version of the image isn't being used. This PR adds a script run by Travis that will check if any relevant files were changed in the current branch and rebuild the aforementioned image if needed.
> Rebuild centos7-plbase image on CI if needed

- ChangeLog.md
- pages/instructorEffectiveUser/instructorEffectiveUser.ejs
- pages/instructorEffectiveUser/instructorEffectiveUser.js
- server.js
Adds the Express connecting IP address to the authenticated user information shown in the instructor "Change effective user page"
There hasn't been a way for the user (Instructor) to see which IP address they are connecting from. Making that more visible than grepping through server logs will make troubleshooting exam mode network configurations easier.
> Show connecting IP

- ChangeLog.md
- lib/externalGraderCommon.js
This PR fixes a vulnerability that allows an attacker to overwrite arbitrary files on the PL host. Borrows code that @tbretl wrote for in-browser editing.
> Fix external grading vulnerability

- ChangeLog.md
- docker/gen_ssl.sh
- docker/init.sh
- environments/centos7-plbase/Dockerfile
In case we needed `https://localhost:3000` support working with the Docker development containers, this PR adds the package and script support to setup the keys PrairieLearn is expecting. It generates a self-signed localhost key where PrairieLearn is expecting it.
This purposefully doesn't configure PL to use https. That needs a `config.json` `"serverType": "https"` config. But if that config exists, this should take care of everything needed in the container to support that.
My primary use for this is testing LTI endpoints which might balk at insecure connections.
> Add https infrastructure support inside Docker

- ChangeLog.md
- cron/index.js
Turns out I accidentally turned off server load reporting to CloudWatch a month ago.
> Fix disabled server load reporting

- ChangeLog.md
- server.js
#1609 removed Ace assets from `localscripts/calculationQuestion`, but some v2 questions still use them. That PR tried to serve the assets from the legacy URL, but used the wrong path. This PR corrects it to serve them from the right path.
> Fix legacy Ace editor assets

- ChangeLog.md
- pages/partials/navbarStudent.ejs
- pages/studentGradebook/studentGradebook.ejs
- pages/studentGradebook/studentGradebook.js
- pages/studentGradebook/studentGradebook.sql
- server.js
- tests/testHomework.js
Adds a student gradebook page that shows all the assessment instances for the student along with the scores. This ignores access permissions, so it shows the scores for every assessment instance, whether the student has access to see the assessment or not. The main use-case for this is to let students see the scores for their exams, after the exam is over. For this reason, the assessment instances on the gradebook page are not links.
Closes #1452
> Add student gradebook page

- ChangeLog.md
- lib/externalGraderCommon.js
This is an update to #935. That PR failed to fix all cases of NULL
bytes, because NULL bytes might be encoded as "\u0000" in JSON. To fix
this, we process the parsed JSON as a JavaScript object, recursively
searching for strings and replacing NULL bytes in them. We also change
from #935 in that we don't just remove NULL bytes, but rather replace
them with the Unicode replacement character "\uFFFD".
Closes #1270
> Fix external grading results containing NULL bytes

- ChangeLog.md
- middlewares/logResponse.js
- package.json
If you loaded up the docker container and clicked a lot of links in a short amount of time, you probably got a 
```(node:1260) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit```
warning. I traced that back to `middlewares/logResponse` that was adding a `close` event to the response object's underlying socket (`res.socket`) instead of the response itself. HTTP/1.1 will (apparently) share the same socket with multiple requests. At least that's the best of my figuring on why it would trigger so often.
`res.on('close')` should do the same thing (only fire when something happened to the response's underlying connection). I'm not sure if different logging with the …
> Fix MaxListenersExceededWarning

- ChangeLog.md
- lib/markdown.js
- package-lock.json
- package.json
- tests/index.js
- tests/testMarkdown.js
Allows Latex fenced by `$` or `$$` to appear in `<markdown>` tags by allowing it to pass through unmodified to the final HTML document. Adds a bunch of tests to ensure this works (and continues to work) correctly. @coatless let me know if you see any weird potential edge cases not captured in the current tests!
Closes #1742
> Add support for Latex in <markdown> tags

- ChangeLog.md
- database/tables/assessment_sets.pg
- database/tables/assessments.pg
- migrations/151_assessments__assessment_set_id_fkey__alter.sql
The assessments.assessment_set_id foreign key constraint had ON DELETE
SET NULL, but the assessment_set_id column had a NOT NULL constraint.
This makes no sense and gave an error when we deleted courses (and hence
assessment_sets) in the tools/dump_filter.sh script.
> Fix assessments.assessment_set_id delete cascade rule

- ChangeLog.md
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql
In the `_all_files.zip` download, we were incorrectly including rows for
student submissions that had missing files. That is, the question
requires a file upload, but the student made an invalid submission
without a file. We were including this submission row in the SELECT,
resulting in a row with `filename = NULL` and hence a `null` file in the
zip file. To avoid this, we only include submission rows for which the
file is present (`filename IS NOT NULL AND contents IS NOT NULL`).
Closes #1744
> Fix null filenames from missing files in downloads

- ChangeLog.md
- pages/instructorQuestion/instructorQuestion.ejs
We don't support testing of externally-graded questions because we don't
submit the grading jobs for them. We were correctly removing the "Test
100 times" button, but we weren't removing "Test once" for
externally-graded questions. This patch fixes this.
Closes #1748
> Fix to remove test-once button on external questions

- ChangeLog.md
- environments/centos7-plbase/python-requirements.txt
Upgrades the present version of `rpy2` to the latest.
Please hold off on merging until Wednesday, October 16th.
> Bump rpy2 version from 2.9.5 to 3.2.0 (latest)

- ChangeLog.md
- lib/ltiOutcomes.js
- pages/authCallbackLti/authCallbackLti.js
- Added debug to LTI code
- Found a bug where I was passing a Date object instead of String to the `imsx_messageIdentifier` so it wasn't getting populated. Blackboard was throwing HTTP 500 errors at that, even though the online test suites and Coursera didn't seem to care.
> LTI outcomes fix for Blackboard

- ChangeLog.md
- environments/centos7-plbase/r-requirements.R
- Added `checkBuilt = TRUE` to `upgrade.packages()` to enforce recompilation even on minor (x.*.z) versions.
- Moved `update.packages()` before official list
c.f. #1817
> Fix detection of different internals (close #1817)

- ChangeLog.md
- doc/elements.md
Close #1865 thanks to @echuber2.
> Fix use of `data["correct_answers"]` in docs

- ChangeLog.md
- environments/centos7-plbase/r-requirements.R
Adds to `centos7-plbase` the `ucidata` package. This package features data sets from the [UC Irvine's ML repository](https://archive.ics.uci.edu/ml/index.php). 
/cc @daviddalpiaz
> Add the ucidata package to plbase.

- ChangeLog.md
- middlewares/authzCourseInstance.js
- pages/instructorEffectiveUser/instructorEffectiveUser.js
- server.js
Changes to use the built in Express logic to get the client IP `req.ip` when connecting through a proxy. Fixes #1911 where we weren't processing the raw headers properly.
> Change to express 'trust proxy' for client IP parsing

- ChangeLog.md
- server.js
- tests/index.js
- tests/testRedirects.js
Fixes #1968 by copying the original query params to the new URL. Adds tests to avoid future regressions.
I opted to duplicate the redirect code in `server.js` to avoid premature abstraction. If anyone feels strongly about it, I can move it into a helper.
> Fix question variant redirects

- ChangeLog.md
- pages/administratorOverview/administratorDeleteForm.ejs
- pages/administratorOverview/administratorInsertForm.ejs
- pages/administratorOverview/courseDeleteForm.ejs
- pages/administratorOverview/courseInsertForm.ejs
- pages/administratorOverview/courseUpdateColumnForm.ejs
- pages/instructorAssessmentInstance/editQuestionPointsForm.ejs
- pages/instructorAssessmentInstance/editQuestionScorePercForm.ejs
- pages/instructorAssessmentInstance/editTotalPointsForm.ejs
- pages/instructorAssessmentInstance/editTotalScorePercForm.ejs
- pages/instructorCourseAdminAccess/coursePermissionsDeleteForm.ejs
- pages/instructorCourseAdminAccess/coursePermissionsInsertForm.ejs
- pages/instructorCourseAdminAccess/coursePermissionsUpdateRoleForm.ejs
- pages/instructorFileBrowser/instructorFileDeleteForm.ejs
- pages/instructorFileBrowser/instructorFileRenameForm.ejs
- pages/instructorFileBrowser/instructorFileUploadForm.ejs
- pages/instructorQuestionSettings/copyForm.ejs
- pages/instructorQuestionSettings/instructorQuestionSettings.ejs
- pages/partials/attachFileDeleteForm.ejs
- pages/partials/changeIdForm.ejs
- pages/userSettings/tokenDeleteForm.ejs
- pages/userSettings/tokenGenerateForm.ejs
In addition to a couple minor style fixes, this PR right-aligns the "cancel" and "action" buttons that appear in forms that are in popovers (fixes #1978).
> Fix button alignment

- ChangeLog.md
- middlewares/authzCourseInstance.js
- middlewares/authzCourseInstance.sql
- pages/partials/navbar.ejs
- server.js
This PR sets the course permissions `has_course_permission_view`, `has_course_permission_edit`, and `has_course_permission_own` correctly when emulating another user (formerly these were always set to `false`), and leaves the `course_role` alone (formerly, this was set to `None`).
This PR also:
- adds helpful information to the the "Access denied" error page if the effective user does not have access to the current course instance;
- fixes the navbar appearance on this same error page.
**NOTE**
If a different `uid` has been requested, then course permissions are generated for the user with that `uid`. Otherwise, course permissions are generated for the original authenticated user. This means that, in development mode (i.e., in docker on a local machine), switching the `role` or the `mode` …
> Fix authorization of effective user

- ChangeLog.md
- pages/instructorIssues/instructorIssues.js
- tests/index.js
- tests/testIssues.js
- tests/testIssues.sql
This PR allows course owners and editors to open and close issues, and nobody else (except administrators).
Formerly, access was being granted only to instructors - this broke the ability to open and close issues through the `pl/course` route, where we don't check whether or not users are instructors.
This PR also adds a test that you can report an issue and close it either at the course level or the course instance level.
Fixes #1995
> Fix permissions on issues page

- ChangeLog.md
- lib/editors.js
When a user adds or copies a course instance in the browser, a `userRole` will be created (if one does not exist already) that makes the user an `Instructor` for the new course instance. Without this change, the user would have been able to create new course instances but would not have had access to these new instances.
Fixes #2000
> Fix in-browser add and copy of course instance

- ChangeLog.md
- elements/pl-drawing/pl-drawing.py
As pointed out by Vadim on Slack changing the `angle-tol` parameter previously did not change anything, this fix makes the grader use that parameter when checking tolerances.
> Fix angle checks for vectors in `pl-drawing` element

- ChangeLog.md
- elements/pl-drawing/pl-drawing.py
Turns out unique matches were being stored, but not actually being checked in grading.  This should fix that issue, before students were able to get scores >100% just by placing multiple objects in the same position.
> Fix grading of duplicate elements in `pl-drawing`

- ChangeLog.md
- doc/courseInstance.md
- doc/faq.md
- pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- pages/instructorGradebook/instructorGradebook.ejs
Add explanation of `None` role in documentation and instructor gradebook view. Close #964
Modeled after footer in assessment statistics:
> Add explanation of `None` role in documentation and instructor gradebook view

- ChangeLog.md
- elements/pl-string-input/pl-string-input.css
- elements/pl-string-input/pl-string-input.mustache
Fixes #2055 
Switches the `<samp>` tag to an inline `<code>` and adds some custom styling.
Tagging @zillesc to make sure it is working for his use case.
> Fix `pl-string-input` not rendering verbatim answer/input

- elements/pl-symbolic-input/pl-symbolic-input.py
The original syntax achieved the same thing, but only by accident. (Maybe this is too minor to consider, unless it could lead to confusion for someone later.)
> Fixing asymptomatic syntax mistake

- elements/pl-drawing/mechanicsObjects.js
Fixes #2147 
Before:
>![image](https://user-images.githubusercontent.com/1790491/76172335-97d17f80-6162-11ea-84cf-d2a9c36e0827.png)
>
>MathJax stores a cache of pre-rendered SVG glyphs which are normally linked to when rendering static math on the page, but in the drawing element these references are replaced with their actual value so that they show up correctly in the canvas context.
>
>Some of these references have a transformation applied to them which isn't getting carried over.
Fix:
Glyph transformations are now correctly copied over during rendering.
> Fix latex glyphs being rendered over each other

- sprocs/check_course_instance_access_rule.sql
- tests/testSproc-check_course_instance_access.js
- tests/testSproc-check_course_instance_access.sql
Updates the logic for course instances protected with `"institution": "LTI"` to force unauthorized unless the LTI course instance matches. Prior to this we weren't restricting access when comparing a NULL value, so users not associated with an LTI course instance could still access the course when protected with `"institution": "LTI"`.
> Fix course instance access LTI check

- pages/news_item/news_item.ejs
- pages/news_item/news_item.sql
- pages/news_items/news_items.ejs
- pages/news_items/news_items.sql
- sprocs/users_is_course_staff.sql
added a badge to news items that marks a news item to be for a "student"
> Show "student" badge on student news

- .travis.yml
We are now using the git log as our ChangeLog and we haven't been enforcing ChangeLog entries for PRs, so we might as well remove this. In fact we should maybe just turn off Travis, but it doesn't hurt to leave it running for now.
It would be good to explore solutions for auto-generating a ChangeLog file from commits.
> Remove ChangeLog check on TravisCI

- lib/config.js
- pages/instructorLoadFromDisk/instructorLoadFromDisk.js
I temporarily confused myself by trying to run without `config.courseDirs` set in local dev. This PR sets the default value `config.courseDirs = ['exampleCourse']` to avoid this.
> Add default course dirs

- cron/calculateAssessmentQuestionStats.js
- cron/calculateAssessmentQuestionStats.sql
- cron/index.js
- database/tables/assessment_instances.pg
- database/tables/instance_questions.pg
- doc/dev-guide.md
- lib/config.js
- migrations/164_instance_questions__modified_at__add.sql
- pages/instructorAssessmentInstances/instructorAssessmentInstances.sql
- sprocs/assessment_instances_close.sql
- sprocs/assessment_instances_grade.sql
- sprocs/assessment_instances_regrade.sql
- sprocs/assessment_instances_update.sql
- sprocs/assessment_instances_update_points.sql
- sprocs/assessment_instances_update_score_perc.sql
- sprocs/instance_questions_update_in_grading.sql
- sprocs/instance_questions_update_score.sql
- sprocs/submissions_insert.sql
The nightly cron job to update question statistics used to iterate over assessments inside the SQL. However, this now takes more than 10 minutes so we timeout the query. This PR changes it to iterate over assessments in JS, so each individual SQL query should be below 10 minutes.
Fixes #1635
Fixes #1323
> Fix nightly calculation of question statistics

- elements/pl-file-editor/pl-file-editor.js
The markdown preview accidentally broke normal editors by assuming the 'preview' element exists.
> Fix editor breaking on no preview

- doc/elements.md
- elements/pl-variable-output/pl-variable-output.mustache
- elements/pl-variable-output/pl-variable-output.py
- exampleCourse/questions/elementVariableOutput/question.html
- question-servers/freeformPythonLib/prairielearn.py
Adds a tab to the `pl-variable-output` element that shows pre-formatted _R_ code in scalar/vector/matrix form. Close #1460
Note: `byrow = TRUE` is required because _R_ stores data in column-format whereas _NumPy_ stores it in row-format.
> Add display of R vector/matrix object in pl-variable-output

- doc/contributing.md
Remove outdated line from `contributing.md`:
> Travis CI has been configured to fail if you issue a PR without updating the ChangeLog.
> Remove outdated "required by CI" line

- ChangeLog.md
- pages/studentAssessmentInstanceHomework/studentAssessmentInstanceHomework.ejs
Fix #1989 by removing the intro blurb on homeworks. And since the alert now contains nothing but `assessment_text_templated`, move the `if` logic to wrap the whole alert.
`if assessment_text_templated`:
`else`:
> Remove homework intro text (#1989)

- .eslintignore
- sync/fromDisk/assessmentSets.js
- sync/fromDisk/assessments.js
- sync/fromDisk/courseInfo.js
- sync/fromDisk/courseInstances.js
- sync/fromDisk/courseStaff.js
- sync/fromDisk/questions.js
- sync/fromDisk/tags.js
- sync/fromDisk/topics.js
- sync/performance.js
- sync/syncFromDisk.js
This PR removes `/sync/` from our `.eslintignore` file so that syncing code can be properly linted. This actually caught a bug - see [#fdd03fe](https://github.com/PrairieLearn/PrairieLearn/commit/fdd03feca978bd6320f0f48483298931f91d650a)!
> Lint the syncing code

- elements/pl-string-input/pl-string-input.py
Fixes #2165
Strips trailing and leading whitespace from the correct answer if enabled, removes any spaces from the correct answer if enabled.
> Allow spaces in correct answer in pl-string-input 

- ChangeLog.md
- Dockerfile
- doc/installing.md
- docker/config.json
Fixes #813:
* Creates nine mount points: `/course`, `/course2`, `course3`, ... `course9`
* Updates `installing.md` doc for multiple `-v` flags
Checked docker build:
```
$ docker build -t prairielearn .
$ docker run -it --rm -p 3000:3000 prairielearn /bin/bash
course course2 course3 course4 course5 course6 course7 course8 course9
```
Checked multiple course loading:
```
$ docker run -it --rm -p 3000:3000 -v /path/to/course:/course -v /path/to/course2:/course2 prairielearn
```
> Add extra /course* mount points (#813)

- public/stylesheets/local.css
Before:
After:
Note: in the pl-code element, the code is not written in the \<pre> tag but in \<span> tags, and when I tested the code would still wrap in Safari but would not in chrome. Should I add the span class to the css?
Resolves #1661
> added css overflow-wrap: normal for pre tag Issue #1661

- doc/elements.md
- exampleCourse/questions/elementElementCodeDocumentation/question.html
- exampleCourse/questions/elementElementCodeDocumentation/server.py
Fixes #2210
The correct answer for the _symbolic input_ field was using a floating point variable `x` instead of symbolic `x`, which breaks the sympy parser because it doesn't like floats.
> Fix errors in element documentation question

- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs
Fix #2207. Spaced according to personal preference. Can alter if requested.
(Also the default bullet padding seems a bit much here, but I didn't change it for now).
`if allow_real_time_grading:`
`else:`
> Fix exam overview "Grade" button spacing

- pages/studentAssessmentExam/studentAssessmentExam.ejs
We no longer generate questions at the start of the exam (we use "lazy" generation when we first access each question). This PR changes the message to reflect this.
> Change "Generating questions" message to "Generating assessment"

- database/tables/assessment_access_rules.pg
- doc/accessControl.md
- doc/assessment.md
- exampleCourse/courseInstances/Sp15/assessments/exam02-realTimeGradingDisabled/infoAssessment.json
- middlewares/studentAssessmentAccess.ejs
- middlewares/studentAssessmentAccess.js
- migrations/166_assessment_access_rules__show_closed_assessment__add.sql
- schemas/schemas/infoAssessment.json
- sprocs/authz_assessment.sql
- sprocs/authz_assessment_instance.sql
- sprocs/check_assessment_access.sql
- sprocs/sync_assessments.sql
- sync/fromDisk/assessments.js
- testCourse/courseInstances/Sp15/assessments/exam8-disableRealTimeGrading/infoAssessment.json
- tests/helperClient.js
- tests/testRealTimeGradingDisabled.js
- tests/testShowClosedAssessment.js
- tests/testShowClosedAssessment.sql
This PR adds a new `showClosedAssessment` flag to assessment access rules that controls whether closed assessments can be opened if their access rules would otherwise permit them to be opened.
Resolves #560
I unfortunately have a day job to go do this week, so I'm passing this off to @mwest1066 to see through.
**TODO**
- Consider `accessWhenClosed` instead of `showClosedAssessment`, and `displayWhenClosed` for `completelyHideAllTraceOfClosedAssessment`
> Add showClosedAssessment access rule restriction

- doc/elements.md
- elements/pl-integer-input/pl-integer-input.mustache
- elements/pl-integer-input/pl-integer-input.py
- elements/pl-matrix-input/pl-matrix-input.mustache
- elements/pl-matrix-input/pl-matrix-input.py
- elements/pl-number-input/pl-number-input.mustache
- elements/pl-string-input/pl-string-input.mustache
- elements/pl-string-input/pl-string-input.py
- elements/pl-symbolic-input/pl-symbolic-input.mustache
- elements/pl-symbolic-input/pl-symbolic-input.py
- exampleCourse/questions/elementIntegerInput/question.html
- exampleCourse/questions/elementIntegerInput/server.py
- exampleCourse/questions/elementStringInput/question.html
- exampleCourse/questions/elementStringInput/server.py
- exampleCourse/questions/elementSymbolicInput/question.html
- exampleCourse/questions/elementSymbolicInput/server.py
Adds `size` and `show-help-text` for:
- `pl-string-input`
- `pl-integer-input`
- `pl-symbolic-input`
Add `show-help-text` for:
- `pl-matrix-input` (this is a block element)
Fixes #2218
> Add `size` and `show-help-text` attributes to elements

- pages/partials/countdown.ejs
Fixes #2246. Noticed the cause when I was digging around `countdown.ejs` for 2215.
(yellow does work, no screenshot)
> Fix countdown timer bar colors

- doc/installingLocal.md
- docker/init.sh
- package.json
There were already fragments of `nodemon` lying around, but this PR makes it actually usable:
```
$ docker run -it --rm -p 3000:3000 -e NODEMON=true -v /path/to/PrairieLearn:/PrairieLearn prairielearn/prairielearn
```
```
waiting for server to start.... done
server started
> PrairieLearn@3.2.0 start-nodemon /PrairieLearn
> node_modules/nodemon/bin/nodemon.js -L server.js
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
info: PrairieLearn server start
info: Running migration 167_assessments__require_honor_code__add.sql
info: Not using Redis for message passing
info: External grader running locally
info: PrairieLearn server ready, press Control-C to quit
info: Go to …
```
> Add support for server-side live-reloading

- doc/dev-guide.md
- lib/editors.js
- middlewares/authnToken.js
- pages/instructorAssessmentSettings/instructorAssessmentSettings.js
- pages/instructorAssessments/instructorAssessments.js
- pages/instructorCourseAdminInstances/instructorCourseAdminInstances.js
- pages/instructorCourseAdminSettings/instructorCourseAdminSettings.js
- pages/instructorFileBrowser/instructorFileBrowser.js
- pages/instructorFileEditor/instructorFileEditor.js
- pages/instructorFileTransfer/instructorFileTransfer.js
- pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.js
- pages/instructorQuestionSettings/instructorQuestionSettings.js
- pages/instructorQuestions/instructorQuestions.js
- pages/shared/syncHelpers.js
- question-servers/freeform.js
- tools/external-grading-load-test/main.js
- webhooks/grading/grading.js
Calls to `logger.error()` must have a string as the first argument to log correctly. This PR fixes all the calls that were missing this.
> Fix logger.error() calls without a string argument

- doc/remoteExams.md
At the moment all the notes come before the actual `allowAccess`
configuration, so it's not even obvious that there is any configuration
information present. This PR reverses the order.
> Fix the remote exam docs to show the config earlier

- lib/config.js
- lib/question.js
- server.js
When we render the new question panels for externally graded results, we
have been triggered by the grading results queue and so we are not
inside a request. This means we don't have `res.locals`, but rendering
assumes we have it, so we construct a fake `locals` object that has all
the same info. We had missed `locals.devMode`, which was subtly changing
the caching behavior in dev. To fix this, and hopefully ensure we keep
the real locals and fake locals the same in the future, this PR adds a
helper function to create the base locals object, and makes both normal
requests and the fake locals creator use the helper.
> Fix locals for externally-graded question panels

- public/stylesheets/local.css
Fixes #2090. I just copied the values that Bootstrap uses to set horizontal padding in card headers so that the sides of tables are aligned. 
| Before | After |
| ---- | ---- |
| ![pl-tables-before](https://user-images.githubusercontent.com/32315760/77986600-260dd100-72dd-11ea-8eb0-20eaa2f0a831.png) | ![pl-tables-after](https://user-images.githubusercontent.com/32315760/77986609-2b6b1b80-72dd-11ea-9bec-777a601cc4a0.png) |
> Add padding to table rows to match bootstrap card headers

- exampleCourse/courseInstances/Sp15/assessments/exam02-realTimeGradingDisabled/infoAssessment.json
I will properly convert exam02 later when I have time (#2286), but it's probably best to remove `"requireHonorCode": false` first.
> Remove disabling of the honor code from exam02

- elements/pl-matrix-component-input/pl-matrix-component-input.py
- public/stylesheets/local.css
Closes #2352.
Before:
After:
Recent changes to table padding are shifting entries in the matrix input, so created a `.table-no-row-padding` class and applied it to the component input to turn off the padding.
> Fix unaligned matrix input

- lib/externalGraderLocal.js
Tried this patch based on suggestions in Slack, but looks like I'm not getting the custom error message. Not sure if it's the wrong location or just implemented incorrectly.
```
$ docker run -it --rm -p 3000:3000 -v C:\Users\Tim\PL\pl_ag_jobs:/jobs -e HOST_JOBS_DIR=C:\Users\Tim\PL\pl_ag_jobs -v /var/run/docker.sock:/var/run/docker.sock -v C:\Users\Tim\PL\PrairieLearn:/PrairieLearn prairielearn/prairielearn
...
info: docker pull output:  {"status":"Pulling from prairielearn/grader-python","id":"latest"}
info: docker pull output:  {"status":"Digest: sha256:cd80c016363207c7c956effbe35080ae0779e0fc13e961fd4b35fce8545f5c8f"}
info: docker pull output:  {"status":"Status: Image is up to date for prairielearn/grader-python:latest"}
error: Error processing external grading job 1
error: …
```
> Improve Docker ag error message

- pages/partials/questionFooter.ejs
When I spam save/grade enough times on an autograded question, the console eventually spits out a const redeclaration error. I could only reproduce on autograded questions, so not sure if it's due to websockets or just coincidence. I was hoping this would also deal with #2234 but no dice (another fix incoming for that). Still, this issue should be addressed as well.
```
SyntaxError: redeclaration of const form [preview:1:1]
<anonymous> (index):1
jQuery 7
fetchResults (index):1106
onack (index):312
onpacket (index):236
exports index.js:21
emit index.js:133
ondecoded (index):332
exports index.js:21
emit index.js:134
add index.js:246
ondata (index):322
exports index.js:21
emit index.js:133
onPacket socket.js:451
setTransport socket.js:268
emit index.js:133
onPacket transport.js:145
onData …
```
> Fix const redeclaration race condition in beforeunload script

- docs/clientServerFiles.md
- docs/oldQuestion.md
Fixes #2264 -- moves "Accessing files from code via RequireJS" and "Deprecated access modes" to `oldQuestion.md`
> Change RequireJS doc location

- api/v1/endpoints/courseInstanceAssessmentInstances/index.js
- api/v1/endpoints/courseInstanceAssessments/index.js
- api/v1/endpoints/courseInstanceGradebook/index.js
- api/v1/endpoints/courseInstanceSubmissions/index.js
Here's that PR for changing the setting of course_instance_id to come from res.locals.course_instance.id rather than req.params.course_instance_id in the code that implements the API.  I changed index.js in the all the directories under endpoints:
courseInstanceAssessmentInstances
courseInstanceAssessments
courseInstanceGradebook
courseInstanceSubmissions
> Get course_instance_id from res.locals instead of req.params

- docs/contributing.md
Fixed a little typo in the git clone command on the Contributing page.
Not sure how this wasn't noticed earlier!  Guess others know their git stuff well enough to not have to refer to the docs :smile: .
> Fixed typo in git clone command

- lib/named-locks.js
It looks like b190cdc207e248cb6229d32fde5836d3374cac66 broke `tryLock()` by changing the `_getLock()` helper function so that it would return an error when it couldn't get the lock, rather than returning a `null` lock: 
This change did not affect `waitLock()`, because it was checking for a `null` lock and returning an error anyway, so after the change it would still return an error.
However, `tryLock()` was returning the `null` lock rather than raising an error, and the callers of `tryLock()` (especially `cron`, which is what I noticed) were relying on this behavior to tell whether the lock could not be acquired.
This PR restores the earlier behavior of returning `null` when the lock could not be acquired, and only returning actual errors as errors.
> Fix namedLocks.tryLock() to return null if lock was not acquired

- docs/accessControl.md
In `accessControl.md`:
> It is common to pair `showClosedAssessment` with disabled real-time grading
> It is common to pair **`"showClosedAssessment": false`** with disabled real-time grading
> Change ambiguous `showClosedAssessment` in docs to specify `false`

- server.js
As a workaround for #2396, this PR makes the server exit with an error code on idle client errors, so that the process supervisor can restart the server.
> Change to exit on idle-client-error from DB

- lib/named-locks.js
It turns out that #2395 did not completely fix the tryLock() handling. If we fail to acquire the lock, we need to both return null _and_ end the transaction. The change in #2395 fixed the "return null" part, but it turns out that b190cdc207e248cb6229d32fde5836d3374cac66 had also eliminated the code that ended the transaction if the lock was null. This PR adds this back.
I also added more comments to explain how the locking logic works.
> Fix tryLock() to end the transaction if the lock was not acquired

- docs/installingLocal.md
Seems like the numbered bullets don't increment as desired when there's text in between. Not sure if there's a way to fix the numbering, but I just changed to dots for now.
https://prairielearn.readthedocs.io/en/latest/installingLocal/#connecting-to-an-existing-docker-container
> Fix bullets in docs/installingLocal.md

- database/tables/questions.pg
- docs/devElements.md
- docs/question.md
- exampleCourse/questions/demoCustomStylingScripts/clientFilesQuestion/script.js
- exampleCourse/questions/demoCustomStylingScripts/clientFilesQuestion/style.css
- exampleCourse/questions/demoCustomStylingScripts/info.json
- exampleCourse/questions/demoCustomStylingScripts/question.html
- migrations/170_questions__client_dependencies__add.sql
- question-servers/freeform.js
- schemas/schemas/infoQuestion.json
- sprocs/sync_questions.sql
- sync/fromDisk/questions.js
Resolves #2271 
Questions can now load dependencies from the following:
Property | Description
--- | ---
`coreStyles` |  The styles required by this question, relative to `[PrairieLearn directory]/public/stylesheets`.
`coreScripts` | The scripts required by this question, relative to `[PrairieLearn directory]/public/javascripts`.
`nodeModulesStyles` | The styles required by this question, relative to `[PrairieLearn directory]/node_modules`.
`nodeModulesScripts` | The scripts required by this question, relative to `[PrairieLearn directory]/node_modules`.
`clientFilesQuestionStyles` | The scripts required by this question relative to the question's `clientFilesQuestion` directory.
`clientFilesQuestionScripts` | The scripts required by this question relative to the question's …
> Allow loading of dependencies per-question

- elements/pl-matrix-component-input/pl-matrix-component-input.py
Looks like #2387 broke invalid submissions rendering by accident, this should fix it.  The code before was assuming that there was a submitted answer to check in invalid submissions (and not even setting the shape during invalid submissions, woops).
> Fix invalid submissions for pl-matrix-component input

- docs/dev-guide.md
- docs/devElements.md
- docs/newQuestion.md
- docs/question-flow.gv
- sprocs/grading_jobs_insert_external_manual.sql
- sprocs/grading_jobs_insert_internal.sql
- sprocs/select_assessment_questions.sql
This started out to fix a couple of typos/misspellings I had noticed in dev-guide.md, but then I did a more complete check of the spelling in that file and found some more, and as a double-check on those misspellings I found what looked like misspellings in a number of other files (almost all in comments or strings).  Hopefully I didn't change anything that shouldn't have been changed.
> Fixed some typos/misspellings in dev-guide.md and a few other files

- elements/pl-file-upload/pl-file-upload.py
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.ejs
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql
Fixes #2409
As well as stripping `_files` from `submitted_answers` for the CSV download, this PR also deletes the temporary answer name that `pl-file-upload` uses to store the files before it moves them into `_files`.
> Change manual grading CSV to not include uploaded files

- sprocs/instance_questions_points_homework.sql
Fixes #2424
We were incorrectly referncing the return value as the current value for `highest_submission_score`, so it was always `NULL` and we always set the new `highest_submission_score` to the latest score. This only affected Homeworks, not Exams.
> Fix highest-score statistic in Homework instance questions CSV.

- package.json
PR adds `ejs` monitoring (default = `js`, `mjs`, `json`).
> Add *.ejs to NodeMon

- docs/courseInstance.md
- pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- pages/instructorGradebook/instructorGradebook.ejs
Assistant is misspelled as "assisstant" in some places in the interface and docs.
> Fix "teaching assisstant" typos

- elements/pl-external-grader-results/pl-external-grader-results.py
Resolves #2469
Rendering would break because `results` is `null` in submissions that have timed out instead of a valid dictionary, we now check for this before grabbing the `gradable` attribute.
> Fix external grader timeout rendering bug

- package-lock.json
- package.json
jQuery 3.5.0 breaks bootstrap collapse fields, downgrade to fix.
Have tested and can confirm this resolves #2483
> Downgrade jQuery to 3.4.1

- pages/partials/mathjax.ejs
MathJax 3.0.5 breaks on SVG output when representing double/triple/quad primes with `''`, `'''`, and `''''`.  Here is a fix by one of the MathJax developers to get around this.
> Fix MathJax rendering bug

- elements/pl-matrix-input/pl-matrix-input.mustache
Clarifies that 1D arrays can be created in the `pl-matrix-input` element, but they are row vectors by default.
> Add help text for 1D arrays in matrix input element

- lib/cache.js
- question-servers/freeform.js
This PR uses the cache for the data generated by file() requests, mirroring the existing usage for HTML question panel rendering. To test it, run with `NODE_ENV=production` and set `"questionRenderCacheType": "memory"` in `config.json`.
> Add caching for file() requests

- pages/partials/navbar.ejs
- pages/partials/navbarInstructor.ejs
- public/stylesheets/local.css
[Updated 5/12] Fixes #2350 by replacing the circle separators in the instructor navbar with slashes `/` to more clearly communicate their purpose.
|Comparison|
|---|
|Before|
|![image](https://user-images.githubusercontent.com/32315760/81769571-934b7f00-94a3-11ea-9538-1c9c9b31a66a.png)|
|After| 
|![image](https://user-images.githubusercontent.com/32315760/81769543-7e6eeb80-94a3-11ea-92c1-bd24b86dca39.png)|
Some other minor cosmetic changes: 
- If an item in the navbar is active and has a dropdown arrow attached, the dropdown arrow will no longer show itself as active: 
(Hard to see, but the arrow isn't white anymore)
- Items in the navbar are now aligned at their baselines, including the "PrairieLearn" brand text.
> Fixing unclear navbar symbol, text baseline alignment, broken active elements

- cron/externalGraderLoad.js
- cron/sendExternalGraderDeadLetters.js
- cron/serverLoad.js
- cron/serverUsage.js
- docker/init.sh
- docker/start_postgres.sh
- lib/aws.js
- lib/config.js
- lib/externalGraderResults.js
- lib/externalGraderSqs.js
- pages/instructorGradingJob/instructorGradingJob.js
- schemas/schemas/serverConfig.json
Adds the ability to specify AWS endpoints to use PrairieLearn under different frameworks, like https://github.com/localstack/localstack
Adds `config.runningInEc2` to mimic PrairieGrader for some load reporting toggling (that localstack doesn't support).
> Config toggles for localstack usage

- elements/pl-checkbox/pl-checkbox.css
- elements/pl-checkbox/pl-checkbox.mustache
- elements/pl-checkbox/pl-checkbox.py
- elements/pl-multiple-choice/info.json
- elements/pl-multiple-choice/pl-multiple-choice.css
- elements/pl-multiple-choice/pl-multiple-choice.mustache
- elements/pl-multiple-choice/pl-multiple-choice.py
Fixes #1215 by sticking labels in a vertically aligned flexbox div/span
Also cleans up some of the code in the checkbox and multiple choice elements by moving markup out of the python files into their respective mustache templates
Before:
After:
Small tweak, but labels are now horizontally aligned such that their left border will line up.
Checkbox/mc items now have more padding between them:
> Vertically align inputs in checkbox and multiple choice elements 

- docs/faq.md
Docker Toolbox requires some shenanigans to connect to a local instance of PrairieLearn, this documents how to get the VM IP and then connect to it.
> Add FAQ entry for running with Docker Toolbox

- docs/python-grader/index.md
- exampleCourse/questions/demoAutograderNumpy/question.html
- exampleCourse/questions/demoAutograderPandas/question.html
- exampleCourse/questions/demoAutograderPlots/question.html
- exampleCourse/questions/demoAutograderRandom/question.html
- exampleCourse/questions/demoAutograderSquare/question.html
- exampleCourse/questions/demoCodeEditorAutograded/question.html
- exampleCourse/questions/demoCodeUploadAutograded/question.html
- graders/python/Dockerfile
- graders/python/python_autograder/pl_unit_test.py
- mkdocs.yml
Fixes #2577 
Student submissions are no longer displayed as a test case, but instead use the `pl-file-preview` element.  This has the benefit that submissions are now displayed if a student clicks "save" instead of "save and grade".
> Switch Python autograder to use file preview element

- elements/pl-external-grader-results/pl-external-grader-results.py
Fixes #2517
Point values are rounded to two decimal digits the same way the score is rounded
New:
Previous (stolen from issue page):
> Fix bad rounding of external grading points in tests

- graders/python/python_autograder/pl_unit_test.py
Resolves #2580
Plot grading was using the old `set_percent()` instead of `set_score()`
> Fix python autograder failing when grading plot labels

- api/v1/endpoints/queries.sql
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql
Resolves #2565 
The `submissions_for_manual_grading.csv` file is now structured like:
> Add "partial_scores" column to manual grading submissions CSV

- elements/pl-checkbox/pl-checkbox.css
- elements/pl-multiple-choice/pl-multiple-choice.css
Fixes #2582 
Strangely enough, this bug only occurs on macOS.
Before:
After:
> Fix label keys for pl-checkbox and pl-multiple-choice

- docs/installing.md
From pl-dev:
> **davemussulman** We should be explicit about not supporting Docker Toolbox on our docs.
> Add doc note that Docker Toolbox is not supported

- graders/python/python_autograder/pl_execute.py
- graders/python/python_autograder/pl_main.py
Previously, the autograder would use only absolute paths for everything.  This gives problems when the test cases/setup code/user code want to access files in the same directory like images, for example. 
This PR updates the grader to CD into the base directory with all files before executing user code, test code, and setup code.
> Python autograder: change working directory before executing test code

- package.json
Since files in /public contain frontend JS, it shouldn't require a server restart if we edit one of these files.
> Ignore /public directory in Nodemon

- lib/config.js
Deactivates a warning in favor of emphasizing a single-course setup is being used.
Closes #2525
> Change warning -> info in config for docker startup (Close #2525)

- graders/python/Dockerfile
- graders/python/python_autograder/run.sh
~-p creates intermediate subdirectories if they are missing and also suppresses errors if existing. This may or may not help with the Windows deployment issue~
> Adding check for /grade to avoid problems

- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql
Resolves #2613 
Student file submissions were trying to be named with the their UIN in the filename, but there was a bug in the query.  I took the UIN out of the filename because it looked cluttered IMO, but I can add this if wanted.
> Fix file downloads for assessments

- database/tables/questions.pg
- migrations/178_questions__workspace_graded_files__add.sql
Looks like we also need a `questions.workspace_graded_image` column based on #2504's proposed json:
```json
{
"workspace": {
"image": "some-docker-image-name",
"gradedFiles": [
"animal.h",
"animal.cpp"
]
}
}
```
> Add `questions.workspace_graded_image` column

- pages/partials/mathjax.ejs
Previously we were loading the MathJax script asynchronously (this is what was shown on the docs), but this leads to weird race conditions, especially with the `pl-drawing` element.  Now we will load the script synchronously, but the startup is still async.
> Load MathJax script synchronously

- docs/dev-guide.md
Check with mkdocs `site/` preview. Fixed to actually show diff syntax now, but had to remove numbering/indentation.
> Fix markdown syntax of "JSON syncing" docs

- docs/python-grader/index.md
- graders/python/python_autograder/pl_execute.py
- graders/python/python_autograder/pl_unit_test.py
- graders/python/python_autograder/run.sh
Resolves #2667 
`data` can be accessed from the test cases using `self.data`.
Also, the `data.json` file is deleted before user code is run so that students do not have access.
> Allow use of the `data` parameter in python autograder test cases

- environments/centos7-plbase/python-requirements.txt
Adds to the base image `mkdocs-material`, which includes Material for MkDocs theme, [MkDocs][2],
[Markdown][3], [Pygments][4] and [PyMdown Extensions][5]. 
**Note:** `mkdocs` was missing from the image before.
[2]: https://www.mkdocs.org
[3]: https://python-markdown.github.io/
[4]: https://pygments.org/
[5]: https://facelessuser.github.io/pymdown-extensions/
> Add mkdocs-material to python requirements for new doc system

- question-servers/freeform.js
(Ported over from #2152 )
Stages `generate`, `prepare`, `parse`, `grade`, and `test` now have access to `data['options']['question_path']` and `data['options']['client_files_question_path']`
> Populate data['options'] for other Freeform stages

- question-servers/freeform.js
fixes #2693 by checking if `fileData` is undefined/null before converting it to base64
> Fix server crash on undefined file data

- docs/mathjax-config.js
- mkdocs.yml
Adds a small MathJax config script and loads MathJax proper from cdn.jsdelivr.net
> Add MathJax support to docs

- database/tables/questions.pg
- docs/workspace/index.md
- exampleCourse/questions/demo/workspace/info.json
- migrations/181_questions__workspace_args__add.sql
- schemas/schemas/infoQuestion.json
- sprocs/sync_questions.sql
- sync/fromDisk/questions.js
- tests/sync/questionsSync.js
- tests/sync/questionsSync.sql
- tests/sync/util.js
The motivation is to allow users to pass Docker arguments (e.g., `"args": "--auth none --foo bar"`).
> Add `questions.workspace_args` column

- server.js
At the moment we can't upload files in questions when they are viewed in the context of a course. It works fine when viewing in a course instance. This is a problem for users who have course-level Editor access but not access to any course instance.
> Fix file upload when editing a course question

- docs/elements.md
- elements/pl-python-variable/pl-python-variable.css
- elements/pl-python-variable/pl-python-variable.py
- exampleCourse/questions/element/pythonVariable/question.html
- exampleCourse/questions/element/pythonVariable/server.py
New options for the `pl-python-variable` element to let you hide header labels of various kinds on a Pandas DataFrame. Includes example and doc edits.
It seemed like there should also be an option to hide the overflow horizontal scrollbar if the dataframe is very small, just for aesthetics, but decided to leave that out. People can do that with a CSS hack in their question HTML if they want it.
> New options on pl-python-variable to hide DataFrame labels

- docker/coveralls.sh
Based on the dev meeting convo -- prevent coveralls from blocking CI.
Travis does have an [**allow_failures**](https://docs.travis-ci.com/user/customizing-the-build#jobs-that-are-allowed-to-fail) option, but I couldn't tell exactly how to use it in our config.
> Change coveralls script to not block CI

- .github/workflows/main.yml
#2710 changed `coveralls.sh`, but it seems that was only used by the old travis CI config. This PR changes the current CI workflow to `continue-on-error` for the coveralls step.
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
Side note: should we delete the deprecated travis config/scripts?
> Change coveralls CI step to continue on error

- question-servers/freeform.js
Resolves #2696 
Adds `serverFilesCourse` to the Python path for course elements.  This is already in the path for server code, and I don't really see any downside to letting course elements and questions potentially share code.
> Add serverFilesCourse to course elements path

- pages/instructorAssessments/instructorAssessments.ejs
Fixes #2616 
The URL prefix for the instructor assessments page was changed a while back (probably when the web editor was merged) and the csv links weren't updated.
> Fix CSV download links on instructor assessments page

- pages/administratorOverview/administratorOverview.ejs
- pages/administratorOverview/courseUpdateInstitutionColumn.ejs
- pages/administratorOverview/courseUpdateInstitutionColumnForm.ejs
- sprocs/courses_update_column.sql
Resolves #2697 
Adds an edit button to the institution column in the courses table on the admin overview page.  Institutions are shown in a dropdown field.
> Add edit button for course institutions

- lib/question.js
Resolves #2692 
Checks if courseInstance exists before grabbing id, otherwise passes along null to `ensureVariantWithClient()`.
Turns out this was a simple fix since the `variants_insert` sproc (what ultimately ends up getting called) is okay with a null courseInstance.
> Fix server crash when testing without courseInstance

- docs/elements.md
- elements/pl-checkbox/pl-checkbox.mustache
- elements/pl-checkbox/pl-checkbox.py
- elements/pl-multiple-choice/pl-multiple-choice.mustache
- elements/pl-multiple-choice/pl-multiple-choice.py
- exampleCourse/questions/element/checkbox/question.html
- exampleCourse/questions/element/multipleChoice/question.html
Adds a `hide-letter-keys` boolean for pl-multiple-choice and pl-checkbox tags. Useful when the answer options are letters themselves.
cc @glherman @echuber2
> Add option to hide letter keys in pl-multiple-choice and pl-checkbox

- pages/authLogin/authLogin.js
- pages/partials/navbar.ejs
Fixes regression in the navbar logic to not display anything about mode outside of a course instance context.
> Fix navbar display of mode in course context

- docs/elements.md
- elements/pl-file-editor/pl-file-editor.js
- elements/pl-file-editor/pl-file-editor.mustache
- elements/pl-file-editor/pl-file-editor.py
I'm making a question with multiple embedded file editors that are halfway down the page. The 2nd editor was stealing focus and dragging the page scroll way down. I think it's very disorienting to the student. Also, if there are multiple editors in one question, it's confusing to focus the last one.
The culprit was:
```
// this.editor.focus();
```
I left the line commented out with an explanatory comment to discourage someone from adding it back again. Things seem to work fine without the focus grab.
> Add option to not focus the file editor

- middlewares/authzCourse.js
- middlewares/authzCourse.sql
- middlewares/authzCourseInstance.js
- middlewares/authzCourseInstance.sql
- pages/instructorQuestionSettings/copyForm.ejs
- pages/instructorQuestionSettings/instructorQuestionSettings.ejs
- pages/partials/navbarInstructor.ejs
- sprocs/courses_user_can_view.sql
- sprocs/index.js
Resolves #2685 
Turns out this was as simple as updating the interface, the server code already was allowing users to copy questions as long as they has edit permission in the destination.
I was able to test this locally by adding course permissions to the dev user, then dropping dev user from the admin table.
> Allow course "viewers" to copy questions

- lib/cache.js
At the moment, on cache error we log the error (which contains the
value) as well as the value itself. When the cache fails, this fills up
the logs with the large values (often full HTML pages).
> Change the cache error logging to exclude the large value.

- exampleCourse/courseInstances/Sp15/assessments/hw03-elementExamples/infoAssessment.json
Looks like we forgot to move this when we moved the prairie draw question from exampleCourse to testCourse
> Remove prairieDrawFigure from example assessment

- workspace_host/interface.js
When we get Jupyter Lab at / it returns a 404 (because it's actually mounted at `workspaces/:workspace_id/container`).  We should just consider 404 to be a successful container start, since there is a server listening.
> Fix workspace host container checking for Jupyter Lab

- workspace_host/interface.js
- workspace_host/interface.sql
`settings.workspace_graded_files` can now be accessed in the `settings` object passed through the callbacks.
> Add workspace graded files to container settings query

- workspaces/xtermjs/src/index.html
- workspaces/xtermjs/src/server.js
Adds:
- The host now only forks one pseudoterminal and each connection shares the same terminal.
- `LC_CTYPE` is set by default so `tmux` will work out of the box
- Copy + paste works correctly
- The terminal process will automatically restart when the running process dies
> Add xtermjs workspace enhancements

- pages/partials/question.ejs
Resolves #956
Previously console log data was only shown for administrators, this should be visible to instructors as well.
> Fix issue output not displayed for instructors

- question-servers/freeformPythonLib/prairielearn.py
Fixes #2848 by removing `pretty_print` formatting from `inner_html()`, as debugged by @nicknytko and @mwest1066 earlier. I'm not seeing any side effects in `exampleCourse` questions.
> Fix extraneous line breaks added to element html

- graders/python/python_autograder/pl_execute.py
- graders/python/python_autograder/pl_unit_test.py
it's really as simple as just adding `encoding='utf-8'` everywhere
> Add unicode support to Python autograder

- lib/aws.js
- lib/workspace.js
- workspace_host/interface.js
Left these as logger.infos. Can change more if needed.
lib/aws.js
```
logger.info('Loading AWS credentials for external grading and workspace S3 resources');
```
lib/workspace.js
```
logger.info('Loading configuration from "aws-config.json"');
logger.info('Using local S3RVER configuration');
```
interface.js
```
logger.info(`Workspace S3 bucket: ${config.workspaceS3Bucket}`);
logger.info(`Listening on port ${workspace_server_settings.port}`);
logger.info('Successfully initialized workspace host');
logger.info(`Pulling docker image: ${workspace_image}`);
logger.info('Not pulling docker image');
logger.info(`Creating docker container for image=${settings.workspace_image}`);
logger.info(`Sending files for grading as ${zipPath}`);
```
> Change workspace logger.info() to debug()

- lib/workspace.js
- workspace_host/interface.js
We should not store config variables in global variables (like `zipPrefix`), because these global variables are initialized when the code is loaded from disk, which is _before_ we've had a chance to load user-provided config files. This means that the global variable (`zipPrefix` in this case) will always have the default value of the config variable, even if it was later overridden.
> Fix workspace config variable caching for zip directory

- docs/accessControl.md
Updated documentation for access control to refer to the course instance timezone instead of the default.
> Documentation: dates based on instance timezone

- ChangeLog.md
- sync/fromDisk/courseInstances.js
If an institution is not specified by a course instance access rule, it should be set to `null` and not to `"UIUC"`.
This gets us the behavior that we want - when no institution is specified, we default to checking that the user's institution is the same as the course's institution to grant access.
> Fix default institution

- ChangeLog.md
- middlewares/selectAndAuthzAssessmentInstance.sql
- middlewares/selectAndAuthzInstanceQuestion.sql
The last input argument of the function `authz_assessment_instance` is the boolean `group_work`, which is meant to indicate whether or not the corresponding assessment is for group work. This argument was hard-coded as `TRUE` in the two places where `authz_assessment_instance` was being called, when it should have been `a.group_work`.
This mistake does not seem to have any negative consequences right now, but that is just a lucky chance.
> Fix group work flag bug

- sprocs/sync_assessments.sql
- tests/sync/assessmentsSync.js
We forgot some `WHERE deleted_at IS NULL` checks, so we were picking up deleted rows and updating more than assessments row in this UPDATE: https://github.com/PrairieLearn/PrairieLearn/blob/eac3eb5ba50654be86e274119be499b7c3d01948/sprocs/sync_assessments.sql#L134
This would then fail with `query returned more than one row` because it was RETURNING into a scalar value here: https://github.com/PrairieLearn/PrairieLearn/blob/eac3eb5ba50654be86e274119be499b7c3d01948/sprocs/sync_assessments.sql#L164
The actual fix is just the one for this query (plus a test case that used to fail and now doesn't). I also added `WHERE deleted_at IS NULL` to a few other places where it seemed necessary (anywhere we are looking up an assessment by its `tid`), but I didn't write tests beforehand to see whether …
> Fix assessment syncing with deleted assessments having the same TID

- sprocs/sync_questions.sql
- tests/sync/questionsSync.js
This is the same category of bug as in #2912, except for questions rather than assessments. In this case the impact was much lower (invisible to end users), but still worth fixing.
> Fix question syncing with deleted questions

- sprocs/sync_course_instances.sql
- tests/sync/courseInstancesSync.js
This is more of the same bug class as #2917 and #2912 (not checking for `WHERE deleted_at IS NULL` during sync).
In this case two of the bugs were serious (would sync data to the deleted course instance rather than to the new non-deleted one) and one of the bugs was harmless for end users.
> Fix course instance syncing with deleted course instances

- ChangeLog.md
- pages/studentAssessmentExam/studentAssessmentExam.sql
- pages/studentAssessmentHomework/studentAssessmentHomework.sql
The block `find_single_assessment_instance` appears in both of these SQL files:
* `pages/studentAssessmentHomework/studentAssessmentHomework.sql`
* `pages/studentAssessmentExam/studentAssessmentExam.sql`
As its name indicates, this block returns an assessment instance, if one exists. Both blocks used comma-joins like this:
```
SELECT
ai.*
FROM
assessment_instances AS ai,
(SELECT *
FROM group_users AS gi
JOIN groups AS gr ON gi.group_id = gr.id
WHERE $user_id = gi.user_id AND gr.deleted_at IS NULL) AS gid
WHERE
ai.assessment_id = $assessment_id
AND ai.number = 1
AND ((ai.group_id = gid.group_id) OR (ai.user_id = $user_id));
```
Unfortunately, these comma-joins cause the block to return nothing (always) if the assessment instance is not associated with group work. So, …
> Fix group users comma joins

- pages/instructorAssessmentGroups/instructorAssessmentGroups.sql
Thanks @mfsilva22 for pointing out the bug. It was a SQL mistake that did not check course_instance_id.
> Fix Group Work - displaying not assigned students from other courses' instances

- lib/editorUtil.sql
Another case of missing `WHERE deleted_at IS NULL` (see #2912, #2917, #2918). I didn't write any tests for this because that's going to take me too long to figure out how to test the file editor and a fix is urgently needed in production.
> Fix the file editor when there are soft-deleted rows

- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql
- sprocs/groups_uid_list.sql
- sprocs/index.js
The use of `group_info()` was preventing the query planner from selecting an appropriate plan, leading to it using seq scans and the queries timing out. This PR removes the use of `group_info()` and codes the group JOINs inline. It's actually not too bad, so I'm tentatively in favor of removing `group_info()` everywhere.
Fixes #2930
> Fix downloads page by removing group_info() sproc

- cron/stopStaleWorkspaces.js
- cron/stopStaleWorkspaces.sql
- lib/config.js
Also separate out launched-timeout and heartbeat-timeout so we can add better messages to the workspaces in these cases.
> Add overall timeout on workspace launching

- workspace_host/interface.js
Adds some more debug information when a container launch times out, could be helpful for debugging on prod:
Incidentally, I'm not sure what the garbage characters are on the left hand side.  Maybe a dockerode issue?
> Display workspace logs on container launch timeout

- workspace_host/interface.js
This removes the every-five-second log of `_autoUpdateJobManager(): Pushing changed files to S3: {}` that is spamming everyone's local prairielearn terminal, even if they aren't using workspaces. I think we don't need this, because the timer canaries should pick up any failure of the cron job.
> Remove frequent debugging output for workspace sync

- pages/instructorGradebook/instructorGradebook.sql
Fixes #2927. The problem was that we were unconditionally JOINing over
group_users, even for groups that were not part of the current course
instance.
> Fix extra columns in the gradebook

- lib/workspace.js
PR #2937 fixed the use of `initial.zip`, but this had the unfortunate
side-effect of breaking reboots. The problem is that we were _always_
setting `useInitialZip: true` when starting a stopped or uninitialized
workspace. In fact we only want to use the initial zip when the
workspace is uninitialized. When it's stopped, we just want to start it
again without overwriting the home directory.
> Fix workspace reboot

- workspaces/jupyterlab/Dockerfile
Workaround for some permission errors in the jupyterlab workspace.
From @mwest1066 in slack: https://github.com/jupyter/notebook/issues/5058
```
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
result = await result
File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 742, in run
yielded = self.gen.throw(*exc_info)  # type: ignore
File "/opt/conda/lib/python3.8/site-packages/notebook/services/sessions/handlers.py", line 69, in post
model = yield maybe_future(
File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
value = future.result()
File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 742, in run
yielded = self.gen.throw(*exc_info)  # type: ignore
File …
```
> Add jupyter environment variables to workspace image

- sprocs/workspace_hosts_find_terminable.sql
Change `HAVING` to `WHERE`, this used to be a `GROUP BY` query but this was never switched over.
> Fix workspace_hosts_find_terminable sproc

- exampleCourse/questions/demo/workspace/jupyterlab/workspace/Workbook.ipynb
> Fix unescaped backslash in JupyterLab demo notebook

- pages/studentAssessmentInstanceHomework/studentAssessmentInstanceHomework.ejs
Truncates the "total points" section on the student homework instance page to 2 decimal points at most, so that ugly cases like this don't occur:
[This already happens in the student exam instance page](https://github.com/PrairieLearn/PrairieLearn/blob/truncateScore/pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs#L83), it just wasn't added for homework.
> Format total points in student Homework instance

- sprocs/workspace_hosts_find_terminable.sql
> Rename workspace host sproc variable (terminated->terminating)

- pages/partials/zoneInfoBadge.ejs
- pages/studentAssessmentInstanceExam/studentAssessmentInstanceExam.ejs
- pages/studentAssessmentInstanceHomework/studentAssessmentInstanceHomework.ejs
At some point, the text inside of these badges got misaligned. Now they display properly and the code is simplified by moving them into a partial.
> Fix layout of zone info badges and move into partial

- cron/workspaceHostTransitions.js
- sprocs/workspace_hosts_find_terminable.sql
This fixes a bug introduced by PR #3068, which changed "terminated" to
"terminating" in the sproc but did not update the corresponding JS file.
In addition this PR renames this variable to "terminable" to better
match the meaning and usage in the JS caller.
> Fix "terminable" host naming

- graders/python/requirements.txt
https://hub.docker.com/repository/registry-1.docker.io/prairielearn/grader-python/builds/524a6055-164c-476d-a992-18dcf137cbf9
Recent `prairielearn/grader-python` builds are failing because `ipython==7.18.1` is too new for the version of Python that is installed in the grader container.
> Downgrade Ipython for Python grader

- graders/python/python_autograder/pl_execute.py
- graders/python/python_autograder/pl_helpers.py
- graders/python/python_autograder/pl_result.py
- graders/python/python_autograder/pl_unit_test.py
Resolves #3015 
When students submit a notebook that contains a syntax error or some other error, the grader will now only show their code instead of the entire contents of the notebook.  This was leading to issues where grading results were over 1mb, because the whole notebook and any executed cells were being printed.
Before:
After:
> Fix displaying of notebooks on error in Python grader

- sprocs/assessment_instances_insert.sql
`date_limit` was being inserted before it was actually calculated, so it was always null, which meant `assessment_instance_remaining_ms` was also null.
> Fix broken assessment timer

- server.js
It turns out that the `res` object here doesn't support the `status()`
method for some reason (perhaps it's not actually an ExpressJS `res`
object?). In any case, we'll revert to the basic type of error reporting
that used to work.
Fixes #3104
> Fix proxy error reporting to client

- sync/course-db.js
We had a left-over `console.log()`.
> Remove debugging code during sync

- lib/config.js
- workspace_host/interface.js
Resolves #3027:
Only update the percent message if these two conditions are met:
> Change workspace progress indicator to be rate limited

- sprocs/workspaces_state_update.sql
- workspace_host/interface.js
- workspace_host/interface.sql
> Change workspace "launched_at" to denote start rather than end of launch

- middlewares/selectAndAuthzAssessmentInstance.sql
- pages/instructorAssessmentInstance/instructorAssessmentInstance.ejs
- pages/instructorAssessmentInstance/instructorAssessmentInstance.js
- pages/instructorAssessmentInstance/instructorAssessmentInstance.sql
- sprocs/group_info.sql
Fixes #2990
Some students created a group, started an instance, and left the group. These "empty groups" are displayed on the Instructor Group page but not the Instructor Student page (instructorAssessmentInstances.ejs)
> [Group Work] display empty groups on instances and instance detail page

- pages/instructorAssessmentGroups/instructorAssessmentGroups.ejs
- pages/instructorAssessmentGroups/instructorAssessmentGroups.js
Fix [Issue#2924](https://github.com/PrairieLearn/PrairieLearn/issues/2924) "When I check Join Groups, Create Groups, and Leave Groups, the checkboxes don't stay checked when re-opening config. Student Permissions at the top indicates that those settings have been applied, but it would be nice to have the checkboxes reflect the current status of the permissions when opening" @glherman
> [Group Work] Group Config - Student Permission Checkboxes

- workspace_host/interface.js
> Change workspace init to keep hosts healthy on container errors

- docs/workspaces/index.md
Previous comment syntax couldn't be directly copy pasted. Borrowed syntax from external grading docs.
> Fix workspace run command to be copy-pastable

- graders/python/python_autograder/code_feedback.py
This would previously give a cryptic error message because of the missing `*args` and `**kwargs`
> Fix 'not allowed' function in python grader

- lib/chunks.sql
The chunks JSON uses camelCase while we were using snake_case in the SQL.  This was leading to us (I think) grabbing all chunk metadata (even those corresponding to invalid or deleted entities?) and error-ing when we tried to download chunks.  This at least fixes MATH 241 and 221 for me on live prod prairielearn.org.
Resolves #3185
> Fix incorrect chunking metadata code

- docs/accessControl.md
- sprocs/check_assessment_access.sql
- testCourse/courseInstances/Sp15/assessments/exam1-automaticTestSuite/infoAssessment.json
- tests/testAccess.js
> Disable timeLimitMin for CBTF assessments

- public/localscripts/questionPageScripts.js
With Jonatan's question:
* On submission, the question form gets serialized with `__variant_id` and `__csrf_token` query params
* On reload, those params are gone (thus the confirmation dialog)
---
> Fix unload confirmation by filtering question form serialization

- admin_queries/workspace_hosts_all_unhealthy.json
- admin_queries/workspace_hosts_all_unhealthy.sql
We only had the 'confirm' parameter so that the query wouldn't run
immediately on entry. Now that we have the 'unhealthy_reason' parameter,
we don't need 'confirm' anymore.
> Remove confirmation from unhealthy hosts admin query

- elements/pl-symbolic-input/pl-symbolic-input.mustache
When showing the "Why?" popover with a format error, it seems that some users are confusing the generic format info with the specific error information at the top. This PR adds a header to try and make this clearer.
> Add header to pl-symbolic-input format info

- sprocs/chunks_insert.sql
Tested and seems to work on `TEST 101` on staging.prairielearn.org:
```
staging=> select c.*, q.uuid, q.qid from chunks as c left join questions as q on q.id = c.question_id where c.course_id=4 and c.type='question';
id  |                 uuid                 |   type   | course_id | course_instance_id | assessment_id | question_id |                 uuid                 |         qid
------+--------------------------------------+----------+-----------+--------------------+---------------+-------------+--------------------------------------+----------------------
241 | 36ab7b98-e395-409a-9353-89d0e59f82b5 | question |         4 |                    |               |        3901 |                                      | New_1
126 | 76b2520a-9b89-442b-920b-558010cb03c3 | question |         4 …
```
> Update chunks to allow duplicate entity UUIDs

- sprocs/workspaces_state_update.sql
Fixes #3211 (`launched_at` was mistakenly removed when merging #3135 with master)
> Fix missing launched_at in workspace_state_update sproc

- server.js
@tdy made the excellent observation that #3210 broke dev mode because the Dev user wasn't being set to admin.  This should fix that.
The issue was that the the dev user gets inserted as an administrator if `config.devMode` is set, but that was set when the server was started *after* the dev user got inserted into the db.
> Fix dev user not being set to admin

- pages/studentAssessmentHomework/studentAssessmentHomework.js
- tests/testGroupStudent.js
Tracked down by @andrewstec:
#3023 renamed `joincode` to `joinCode` on the EJS side but not JS.
> Fix join code naming bug

- docs/accessControl.md
I think we could stand to have a separate section about the distinction between Instructor, TA, and Student roles, since it's implied prerequisite knowledge in several of the pages and doesn't seem to primarily belong under any of them, although it is currently spelled out in a table on the page about course instance configuration.
> Link to the user role explanations where it makes sense

- sprocs/workspaces_state_update.sql
Fixes #3227 
After #3189 lowered `config.cronIntervalWorkspaceTimeoutSec` to 60, heartbeats and timeouts were both firing at 60 sec intervals, so workspaces were being stopped before heartbeats could register.
> Fix workspace heartbeat/timeout race condition

- middlewares/selectAndAuthzInstanceQuestion.sql
- pages/instructorAssessmentInstance/instructorAssessmentInstance.sql
fix #3077 
@mwest1066 Please check whether my understanding is correct:
1. When using LEFT JOIN, the order matters. We should LEFT JOIN group and confirm its deleted_at first, then group_users. This order is critical if I am putting the check on the same line with LEFT JOIN
```
LEFT JOIN groups AS gr ON (gr.id = ai.group_id AND gr.deleted_at IS NULL)
LEFT JOIN group_users AS gu ON (gu.group_id = gr.id)
```
2. The order will not matter when I put the deleted_at check in the WHERE clause
```
LEFT JOIN groups AS gr ON (gr.id = ai.group_id)
LEFT JOIN group_users AS gu ON (gu.group_id = gr.id)
WHERE gr.deleted_at IS NULL
```
> [Group Work] Enforce g.deleted_at

- elements/pl-file-editor/pl-file-editor.py
Multiple pl-file-editor elements with the same file name are typically an oversight of the question creator, and can generate unpredictable behaviour. This PR makes it so PL refuses to build the question, showing the problem right away instead of only after data loss.
> Error message if question has more than one pl-file-editor with same file name

- sprocs/sync_assessments.sql
This arose from #3250, but this only fixes the symptom of all courses being affected, and doesn't address the underlying bug.
> Fix sync_assessments assertion

- elements/pl-file-preview/pl-file-preview.mustache
- elements/pl-file-preview/pl-file-preview.py
One of the issues in #3159.
The button is currently created with base64 blob in the link itself, which works fine for small enough files, but may cause the page to take longer to load if the file is too big. Alternative would be to create a new URL entrypoint for downloading, but that would probably take more work.
> Added download button to pl-file-preview.

- pages/partials/question.ejs
This PR adds stack trace visibility at the course level with `authz_data.has_course_permission_view` (#2835 fixed visibility at the instance level). Tested locally with non-admin course viewer.
Fixes #3247
Fixes #956
> Fix question backtrace visibility at course level

- exampleCourse/questions/demo/workspace/vscode/info.json
- exampleCourse/questions/demo/workspace/vscode/question.html
Includes a note to course staff about 3.5.0 being bugged, just in case any new courses are basing off this vscode demo.
> Pin demo/workspace/vscode to code-server:3.4.1

- docs/externalGrading.md
- elements/pl-external-grader-results/pl-external-grader-results.mustache
Currently all images received from external autograders have the label "Figure". This change allows the specification of a label for each image. The previous functionality is kept if there is no label.
> Added labels to images created by external graders.

- elements/pl-checkbox/pl-checkbox.py
- elements/pl-multiple-choice/pl-multiple-choice.py
- question-servers/freeformPythonLib/prairielearn.py
This should fix issue #3133 
Loops past `z` to `aa`, works for arbitrary number of options, e.g `.... -> zzzy -> zzzz -> aaaaa -> aaaab -> ....`
> Implemented correct mcq past z

- sync/course-db.js
- tests/sync/assessmentsSync.js
Closes #2211 
* Add unit tests and edit titles of tests for allowRealTimeGrading:false used with arrays
* Update error messages when a points array with multiple elements is used in this case
> Fix allowRealTimeGrading:false bug to allow 1-element points arrays

- lib/editors.js
The current code assumes that all DB ojects have "long names" (titles).
This assumption is no longer valid with the new robust sync code, which
will sync objects even if their titles are NULL.
Fixes #3320
> Fix editor crash when existing objects don't have long names

- cron/externalGraderLoad.js
- sprocs/grader_loads_current.sql
The external grader fleet autoscaling code using multiple metrics to
estimate the desired number of graders. Most of these take a `max()`
over recent historical data and so are not subject to "flapping" (rapid
upscaling followed by immediate downscaling). However, we also use the
instantaneous number of ungraded jobs to compute the desired number of
graders, which can rapidly fluctuate. To avoid the flapping that this
can cause, this PR unconditionally latches the desired number of graders
to a `max()` over the recent past. This will avoid flapping due to
upscaling-then-downscaling. We can still have downscaling-then-upscaling
flapping, but we want that because it's caused by the need to respond to
actual load increases.
> Fix flapping during external grader autoscaling

- docs/c-grader/index.md
- graders/c/cgrader/cgrader.py
From experience students tend to ignore compilation warnings if the compilation test passes. This PR highlights the warnings in the main tests message, so students can address them as a possible reason for their tests to be failing.
> C Grader: compilation warnings message on main results page.

- elements/pl-file-editor/pl-file-editor.js
Addresses #3164. Two downsides to this solution are
- It doesn't solve #3164 in 100% of cases, though the holdouts don't seem likely to be naturally occurring - e.g. `$3 *4 5* 6$` (with exactly that weird spacing) would still break the Latex rendering
- It does change how markdown is rendered even for folks not using Latex, e.g. 'foo_bar_baz' will now be rendered unchanged instead of italicizing the 'bar' (but how often does someone _actually_ want to italicize/bold in the middle of a word?)
If anyone objects to the second issue, I could create a new option for options.preview so the new rendering mode would be entirely opt-in.
> pl-file-editor markdown rendering: treat mid-word * and _ as literal, not bold/italics

- lib/markdown.js
This was changed in https://github.com/syntax-tree/mdast-util-to-hast/pull/39
Currently emits a harmless warning, but the option has been renamed and the old name is deprecated.
> Update deprecated mdast option

- pages/courseSyncs/courseSyncs.ejs
The Show button on the Sync page, which shows questions linked to a docker image, was reloading the page on click. This fixes that issue.
> Fixes "Show" button on Sync page refreshing the page

- elements/pl-drawing/pl-drawing.mustache
- pages/partials/mathjax.ejs
This is a hack to default to the CommonHTML MathJax renderer (which works on lo-dpi displays with Chrome/Windows) and only use the SVG MathJax renderer for elements that need it (at the moment only `pl-drawing`). Elements can choose to use SVG by adding the class `pl-requires-svg-mathjax` to their output HTML.
Fixes #3086
> Fix thin lines in math on Chrome/Windows

- pages/partials/instructorInfoPanel.ejs
In Edge Chromium, in the instructor's panel, the link to show/hide the answer wasn't working. It seems Edge (or some script I can't find) replaces the href attribute from `#instructorTrue_answer` to the full URL followed by this tag (which would be innocuous if this were an actual link). This doesn't seem to be a problem in Chrome or Firefox, or even when running on localhost. This PR changes the link to a button, using `data-target` instead of `href`, which according to Bootstrap documentation (https://getbootstrap.com/docs/4.0/components/collapse/) should have equivalent functionality.
> Changes to Show/Hide answer button in instructor panel

- docs/question.md
As noted in https://github.com/PrairieLearn/PrairieLearn/issues/3191 it would be ideal to get a real option for this rather than a workaround...
> Add doc note about preventing 100 credit from locking question

- docs/python-grader/index.md
- exampleCourse/courseInstances/Sp15/assessments/hw06-demoPythonAutograder/infoAssessment.json
- exampleCourse/questions/demo/autograder/python/leadingTrailing/info.json
- exampleCourse/questions/demo/autograder/python/leadingTrailing/question.html
- exampleCourse/questions/demo/autograder/python/leadingTrailing/server.py
- exampleCourse/questions/demo/autograder/python/leadingTrailing/tests/ans.py
- exampleCourse/questions/demo/autograder/python/leadingTrailing/tests/initial_code.py
- exampleCourse/questions/demo/autograder/python/leadingTrailing/tests/leading_code.py
- exampleCourse/questions/demo/autograder/python/leadingTrailing/tests/test.py
- exampleCourse/questions/demo/autograder/python/leadingTrailing/tests/trailing_code.py
- graders/python/python_autograder/pl_execute.py
- graders/python/python_autograder/run.sh
Adds support for `tests/trailing_code.py` for python autograder and a small blurb to the documentation.
Adds example question `demo/autograder/python/leadingTrailing`:
Closes #3613
> Add support for leading and trailing code in Python autograder

- elements/pl-file-upload/pl-file-upload.js
The existing file upload element didn't allow download.  (Download buttons appeared only in the corresponding pl_file_preview element, which requires the user to first save or save & grade.  This is non-intuitive.) 
I basically copied the code from: https://github.com/PrairieLearn/PrairieLearn/pull/3217/files
Currently the download button is too close to the 'Show Preview' button.  I don't know the preferred way to add some space between them. 
(Also, I apologize for not making this branch in my own repo... I didn't see the contributing guidelines until the patch was complete.)
> Added download button to file upload element

- question-servers/freeform.js
Fixes #3651
`params` is listed as changeable in the docs &mdash; this updates the code to reflect that.  Have tested this out locally and I don't see anything breaking because of it.
> Allow params to be changed in grade()

- public/localscripts/histmini.js
- public/localscripts/histogram.js
- public/localscripts/parallel_histograms.js
- public/localscripts/scatter.js
- public/localscripts/stacked_histogram.js
PR #3649 changed the d3 import from a local copy to an npm-installed version, which had the side-effect of upgrading it from v3 to v6. It turns out that v3 -> v4 had many breaking changes in the d3 API, which we had been shielded from until now. This PR fixes the local PL client-side plotting scripts to work with d3 v4+. The key changes are:
* Change `scale.{linear,ordinal}` -> `scale{Linear,Ordinal}`. See https://stackoverflow.com/a/47068531
* Change `svg.axis` -> `axis{Bottom,Left}`. See https://stackoverflow.com/a/40465701
* Change `rangeRoundBands` -> `rangeRound.padding`. See https://stackoverflow.com/a/40229243
* Change `scale.category10` -> `scaleOrdinal(d3.schemeCategory10)`. See https://stackoverflow.com/a/38391511
* Change `rangeBand` -> `bandwidth`. See …
> Update plots for d3 from v3 to v4+ (currently v6.3.1)

- pages/error/error.js
Reducing log level from `info` will avoid spamming syslog with user errors. System errors (status >= 500) will still go to syslog.
> Change user error log level to verbose

- cron/workspaceHostTransitions.sql
We had inconsistent use of `AS wh` and using the `wh.` prefix. This broke the `set_host_unhealthy` and `set_terminated_hosts_if_not_launching` queries. I tidied up the other queries as well.
I haven't tested this.
> Fix workspace host cleanup queries

- docker-compose.yml
- docs/docker.md
- docs/externalGrading.md
In order to make it easier to pop up a local build of PraireLearn, I've created a docker compose file that emulates the ["running locally with docker"](https://prairielearn.readthedocs.io/en/latest/externalGrading/#running-locally-on-docker) command from the ReadTheDocs.
I've had some issues trying to get alternative start commands to run on windows due to the split terminal--I don't know if this works on other OSes.
There's more comments on `docker-compose` in the comments of #3174.
> Add a Docker Compose File

- docs/elements.md
Fix non-active URLs due to reference links MIA at end of element docs.
> Fix pl-order-block example links

- elements/pl-matrix-component-input/pl-matrix-component-input.py
The `pl-matrix-component-input` element allows a matrix of ints to be set as the correct answer, even if it is not a numpy array. However, if this is done, and there is a parse error in the submission (e.g., one of the elements is left blank), this will cause a set of issues to be raised, due to a render error in this element that assumes that correct answer is a numpy array. This PR fixes that issue by ensuring the array is converted to a numpy array if necessary.
> Fix error in pl-matrix-component-input for non-numpy answer

- exampleCourse/questions/demo/autograder/python/orderBlocksAddNumpy/info.json
- exampleCourse/questions/demo/autograder/python/orderBlocksRandomParams/info.json
Just a minor issue that some pl-order-blocks questions doesn't have the "element" prefix.
> Renamed pl-order-blocks questions for consistency

- lib/python-caller-trampoline.py
While working on https://github.com/PrairieLearn/PrairieLearn/pull/1626, I noticed that Python processes took on the order of hundreds of milliseconds to exit and return control to the parent. When a Python process implicitly exits (or exits with `sys.exit()`), it doesn't actually exit immediately - it allows things to gracefully shut down and clean themselves up. While this is generally a good thing, in this case, we just want to get out of the process as fast as possible so we can re-use the worker. Switching to `os._exit()` allows us to do this.
For the metric of "delta between start of question generation to the instant that all the python callers used for that question are available again", this change reduces that metric from ~`1200ms` to ~`120ms`. This should allow us to …
> Use os._exit() to exit Python worker process

- lib/cache.js
The LTI authentication code stores used nonces in the cache to detect whether a nonce has been re-used (not allowed). However, the cache code that sets values with a maxAge parameter was incorrect. It used the underlying redis syntax with a `PX` argument, whereas the `redis-lru.set()` function does not need (or support) this argument:
https://github.com/facundoolano/redis-lru/blob/40fcf9f7d4690ad126528547fafecd671fbfda26/index.js#L112
Note that the underlying code _does_ use `PX` because it's talking directly to redis:
https://github.com/facundoolano/redis-lru/blob/40fcf9f7d4690ad126528547fafecd671fbfda26/index.js#L119
> Fix LTI nonce re-use detection

- .dockerignore
- Makefile
- docker/init.sh
- docker/lint_js.sh
- docker/lint_python.sh
- docker/start_s3rver.sh
- docker/start_workspace.sh
- docker/typecheck.sh
- docs/dev-guide.md
- docs/installingNative.md
- package.json
Given some changes in behaviour in NPM 7, this PR replaces all `npm run` scripts with `make` targets.
> Replace npm scripts with make targets

- question-servers/freeform.js
- sync/syncFromDisk.js
We currently call `reloadElementsForCourse()` towards the end of `syncDiskToSqlWithLock()`, but this is unnecessary because we always call `loadElementsForCourseAsync()` before running any course code and:
1. In production we always check the `commit_hash` for the course and reload elements if it has changed.
2. In dev mode (where there might not be a commit) we call `flushElementCache()` from `syncDiskToSqlWithLock()` which ensures we will always reload all elements.
3. During tests we might have `commit_hash = null` but we now check for this explicitly and always reload elements in this case.
All of the above also applies to course element extensions.
> Remove unnecessary reloadElementsForCourse()

- workspaces/jupyterlab/Dockerfile
- workspaces/jupyterlab/install.sh
Adds a small `install.sh` script like the other images, and installs `pygraphviz` in the default jupyter workspace image.
> Add pygraphviz to Jupyter workspace

- server.js
Depending on the phase of rendering (before submission, after submission) the instructor question preview URLs sometimes have a trailing slash and sometimes do not. This matters when legacy question types (v2) set relative URLs like `.../text/xxx.png` because we will have either:
* NO trailing slash: `.../:question_id/preview` -> `.../:question_id/text/xxx.png`
* WITH trailing slash: `.../:question_id/preview/` -> `.../:question_id/preview/text/xxx.png`
To handle both cases this PR explicitly adds routes for the second case.
> Fix legacy question data routes for instructor views

- database/tables/group_configs.pg
- database/tables/group_users.pg
- database/tables/groups.pg
- database/tables/users.pg
- migrations/229_group_config_unique_index.sql
The previous version of `migrations/229_group_config_unique_index.sql` simply changed the `unique_group_config_per_assessment` index to be unique. But this is not possible because we had previously been setting `deleted_at` on group configs and creating new ones for the same assessment, so we had multiple group configs with the same `assessment_id`.
This PR hard-deletes any soft-deleted group configs so that there is only one group config per assessment, allowing the creation of the new unique index. To speed up the deletion this PR changes the ON DELETE behavior of groups to SET NULL for `group_config_id` changes.
The previous version of the migration also resulted in two redundant indexes, which this PR fixes.
> Fix migrations/229_group_config_unique_index.sql

- lib/chunks.js
The `ensureSymlink()` function silently does nothing if the destination already exists, even if it isn't the correct symlink (see jprichardson/node-fs-extra#786, jprichardson/node-fs-extra#869, jprichardson/node-fs-extra#826). This means that with the new symlink chunk code (see #3354) we will never update a question chunk, even when there is a new version of the question available. To work around this we create the link with a temporary name and move it to the correct link name.
> Fix chunk symlinks to ensure overwriting old links

- elements/pl-external-grader-results/pl-external-grader-results.py
The palette shown already specifies all 16 colors explicitly, so there's no need to duplicate to get the second 8 (the "bright" set). Coincidentally, the library automatically generates a "bright" variant of the first eight colors for the second eight, if they aren't already specified.
By the way, the built-in "xterm" palette is very similar to the one defined here.
> Remove superfluous "* 2" on color palette

- api/v1/endpoints/courseInstanceAssessmentInstances/index.js
- pages/instructorAssessmentInstance/instructorAssessmentInstance.ejs
- pages/instructorAssessmentInstance/instructorAssessmentInstance.js
- sprocs/assessment_instances_select_log.sql
Until #3035 or equivalent is merged we are storing files as JSONB in the DB. This produces problems when viewing the assessment instance log because the files are too big. Recent math exams have been having students upload large PDFs which break the rendering of the assessment instance page because of this problem.
To fix the problem, this PR strips the files from the submitted answer JSON when getting the log. This is the same technique used when downloading submissions: https://github.com/PrairieLearn/PrairieLearn/blob/a4380b697baa6db8a288d35995424c833f363567/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql#L111 This PR only conditionally strips the files. It strips them for the HTML page and the corresponding CSV download, but it keeps them for the API access to …
> Remove uploaded files from instructor assessment instance log

- docs/dev-guide.md
- docs/faq.md
- docs/installingLocal.md
- docs/installingNative.md
Some documentation fixes that I'd like to suggest.
*  Replace reference to `pages/instructorQuestion` with `pages/instructorQuestionPreview` here: https://prairielearn.readthedocs.io/en/latest/dev-guide/, as `pages/instructorQuestionPreview` superseded the former page here: https://github.com/PrairieLearn/PrairieLearn/commit/0019d997bf0d7e42588faa94130da23e4d84f888#diff-9672e40fe7e2b2b203956bdc79c5e450eb09be38c268458f5e17902fe8b0e581
* Add source directory options for PowerShell and WSL to accompany WIN CMD and macOS/Linux: https://prairielearn.readthedocs.io/en/latest/installingLocal/
* Suggest `--rm` when installing node packages inside a container as there's no need for the container to persist: https://prairielearn.readthedocs.io/en/latest/installingLocal/
* Change path to Python's …
> Documentation fix

- sprocs/instance_questions_update_score.sql
Field should not be updated, since the field is expected to represent the creation user.
> Remove update of auth_user_id when adding manual grade

- .github/workflows/main.yml
- tools/build-image-if-needed.sh
- tools/build-plbase-if-needed.sh
We were previously only building the `plbase` image in CI. This PR also builds all images in `graders/` and `workspaces/`. The `graders/python` image currently fails to build because of version conflicts between numpy and tensorflow, which we didn't catch earlier because we weren't building that image in CI.
> Add builds for all images in CI

- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js
- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql
Some instance downloads (e.g., final submissions, best submissions) don't return all submissions in case of group work. This seems to be related to the use of `unique_group` in the downloads file, since the code aims to only return one element per group, but that one element could not match the final or best submission.
```
(row_number() OVER (PARTITION BY v.id ORDER BY s.date DESC, s.id DESC)) = 1 AS final_submission_per_variant,
(row_number() OVER (PARTITION BY v.id ORDER BY s.score DESC NULLS LAST, s.date DESC, s.id DESC)) = 1 AS best_submission_per_variant,
(row_number() OVER (PARTITION BY g.id, v.id, s.id)) = 1 AS unique_group,
...
WHERE
($include_all
OR ($include_final AND final_submission_per_variant)
OR ($include_best AND best_submission_per_variant))
AND (($group_work AND …
```
> Fix handling of group users in instance downloads

- database/tables/course_instances.pg
- docs/courseInstance.md
- migrations/231_course_instances__hide_in_enroll_page__add.sql
- pages/enroll/enroll.sql
- schemas/schemas/infoCourseInstance.json
- sprocs/sync_course_instances.sql
- sync/course-db.js
- sync/fromDisk/courseInstances.js
Some instructors may wish to hide their course from the list of available course instances in the Enroll page. This may be done to provide a small level of control over which students get access to the course, or to avoid confusion in case of course instances that are not expected to be visible to students in general. For these instances, this new setting will hide the course instance from the list of instances in the Enroll page, even if the instance is available for enrollment.
> Add option to hide course instance from enrollment page

- elements/pl-order-blocks/pl-order-blocks.py
The order of blocks in `pl-order-blocks` was not maintained once there is a submission. This was particularly relevant in case of `source-blocks-order="ordered"`, since the blocks would no longer be ordered once a submission was sent.
> Preserve order of blocks after submission (bugfix)

- .github/workflows/cla.yml
This will prompt contributors to sign our CLA when they make a contribution for the first time.
> Add cla-assistant GitHub Action

- package-lock.json
- package.json
CI tests are giving an error: `Cannot read property 'split' of undefined`. This error is resolved if `yargs` is downgraded back to 16.2.0 (had been upgraded to 17.0.1 in #4174).
> Downgrade yargs to 16.2.0 to fix CI testing problems

- docs/elements.md
- docs/pl-drawing/index.md
- docs/question.md
- elements/pl-symbolic-input/pl-symbolic-input.py
I had a look at all of the example problems and all of them use `data["correct_answers"]` rather than `data["correct_answer"]`. In some cases in the docs, `correct_answer` is used and generates an error (specifically in the symbolic_input question.
It would be nice if someone could confirm this is the case before updating the documentation.
> Replace `correct_answer` with `correct_answers`

- elements/pl-threejs/pl-threejs.py
Not much to say: wrong attribute name being used in prepare, was causing even the example course sample of pl-threejs to fail.
> Fix attribute name answer-name for pl-threejs

- elements/pl-symbolic-input/pl-symbolic-input.py
#4217 added `atan` as a valid function in `pl-symbolic-input`, but `atan` was being used in tests as an example of an invalid function. This PR fixes that by replacing the invalid function with something that is unlikely to be valid any time in the future.
> Bugfix: change invalid function test to no longer use atan

- LICENSE
We messed up and filled in our own values into fields that were intentionally supposed to be placeholders in the license :sweat_smile: this fixes that
> Restore AGPLv3

- docs/question.md
At the bottom of the [Question configuration](https://prairielearn.readthedocs.io/en/latest/question/) documentation page, there is a broken link to the [External grading](https://prairielearn.readthedocs.io/en/latest/externalGrading/) page. This PR fixes the issue.
> Fix broken link to external grader page

- prairielib/lib/util.js
- prairielib/lib/util.test.js
The `sanitizeObject` function in prairielib uses `typeof value === 'object'` as a way to check if `value` is an object, but this expression is also true for `null`. This has implications in grader hosts, whenever autograders include, in the results, a key that points to `null`. Instead of treating the object as null, this would trigger a parsing error on the results object. This PR fixes it by handling null values explicitly.
> Change sanitize function to properly handle null values

- graders/python/requirements.txt
* Upgrade tensorflow from 2.4.1 to 2.5.0 to resolve "version not found" for 2.4.x
* Downgrade numpy from 1.20.1 to 1.19.4 because tensorflow doesn't yet support numpy version 1.20.x
* Downgrade pygraphviz from 1.7 to 1.6 because 1.7 doesn't build. The build failure is because it can't find `cgraph.h` which is in `/usr/include/graphviz/cgraph.h` (from the system package `graphviz-devel`). I don't know whose fault this is, but see https://github.com/pygraphviz/pygraphviz/issues/155
I'm not sure why the original numpy 1.20.0 upgrade PR (#3748) succeeded.
> Fix grader-python build with compatible package versions

- graders/python/requirements.txt
TensorFlow has been causing significant issues because it does not track latest versions of NumPy very quickly, so this PR removes it from the default python grading image. We will encourage anyone who needs TF (or similar libraries such as PyTorch) to make their own copy of the `grader-python` image where they can add TF and select appropriate versions of NumPy and other libraries.
> Remove TensorFlow from grader-python

- package-lock.json
- package.json
This was previously installed implicitly by `winston`.
> Install logform package explicitly

- server.js
Now that sprocs are in a per-run schema (see #4412), it makes no sense to create them as part of DB initialization.
> Move exit point for migrate-and-exit argument

- database/tables/submissions.pg
- migrations/234_submissions__regradable__add.sql
Adding a column with a `NOT NULL` constraint requires rewriting the entire table and blocks writes while it's happening. This is too expensive for a large table like `submissions`. While it's nice to have `NOT NULL` on this column, it shouldn't actually be required.
Weirdly, everything I [can](https://brandur.org/postgres-default) [find](https://www.depesz.com/2018/04/04/waiting-for-postgresql-11-fast-alter-table-add-column-with-a-non-null-default/) about PG 11 seems to suggest that `ADD COLUMN ... NOT NULL DEFAULT FALSE` should be just as fast as `ADD COLUMN ... DEFAULT FALSE` (without the NOT NULL). But in my experiments the latter version is super fast (maybe 1 second for 45-million rows) while the former version is super slow (at least 10 minutes, at which point it was auto-killed).
> Remove NOT NULL constraint on submissions.regradable

- schemas/schemas/infoQuestion.json
- sync/course-db.js
- sync/fromDisk/questions.js
After implementing an array with enumerated string types (ie. gradingMethod: ["External", "Manual"]) in a Question info.json configuration file, I found a bug during the JSON schema validation import. This PR fixes the bug with one possible approach.
The current implementation on PrairieLearn/master is that a gradingMethod can support one enumerated string type. (ie. One of "Manual", "Internal", or "External"). The implementation on the `manual-grading-col-split` branch intended to change `gradingMethod` from an enumerated string type to a UNION enumerated string type OR array of enumerated strings type. 
Note that we cannot do union types in strict mode of our schema validation. Therefore, implementing the string and array union possibility on the `gradingMethod` property is not possible …
> Manual grading col split schema fix

- .github/workflows/main.yml
- Dockerfile
- Makefile
- docker/init.sh
- docker/lint_grader_host.sh
- docker/lint_prairielib.sh
- docker/start_support.sh
- docker/test_grader_host.sh
- docker/test_js.sh
- docker/test_prairielib.sh
- docker/test_python.sh
- docs/dev-guide.md
- docs/installingLocal.md
- docs/installingNative.md
- grader_host/Makefile
- grader_host/package.json
- package.json
- prairielib/Makefile
- prairielib/package.json
npm v7 has a horrible misfeature:
> When npm is run as root, scripts are always run with the effective uid and gid of the working directory owner.
(see https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major)
This causes lots of problems when mounting a local copy of the PrairieLearn source into the container at `/PrairieLearn` because the working directory will be owned by a different user to the files inside the container (e.g., `/root/.gitconfig`), causing hard-to-debug errors due to permissions being wrong. For example, #4586 is caused by this.
@jonatanschroeder fixed most of this by switching from `npm` scripts to `make` in #3818, but we missed a few cases. This PR eradicates all remaining references to `npm` scripts and `npx`.
Fixes #4586
> Remove all use of npm scripts and npx

- tests/helperDb.js
We were correctly initializing sprocs in the test suite using the new random-schema-based method (see #4412), but we were only initializing them for the first run of the tests, when we do a full database creation. On repeated runs of the tests we use a copy of the existing template DB and in this case we were not initializing the sprocs. This PR adds the new sproc initialization method to the repeated-test-case setup. Fixes #4585
> Fix sprocs init for repeated test runs

- .gitignore
- package-lock.json
- package.json
- tests/testCourseEditor.js
- tests/testFileEditor.js
This fixes the tests in the case where a previous test run died and left behind the directories `tests/testFileEditor/courseLive` and `tests/testFileEditor/courseOrigin`. If these directories are left behind then the next test fails with:
```
Error: Command failed: git clone /PrairieLearn/tests/testFileEditor/courseOrigin /PrairieLearn/tests/testFileEditor/courseLive
fatal: destination path '/PrairieLearn/tests/testFileEditor/courseLive' already exists and is not an empty directory.
```
We now unconditionally remove these at the start of the relevant tests.
This PR also uninstalls the [`rimraf`](https://www.npmjs.com/package/rimraf) package and replaces it with `fs-extra.remove()`.
> Fix tests by removing courseLive/Origin after failures

- sprocs/grading_jobs_insert_external_manual.sql
Grading_method_internal substituted with grading_method_manual, as it is defined and relevant to this particular guard that raises an error. 
This has been fixed already in the `manual-grading-anti-ta-overlap-spin-lock-views` branch, where we split the external and manual sprocs into two separate sprocs, to make the integration between mine and Maja's work. This fix is just to bring this branch up to working condition so it can be merged.
> Bug fix: grading_method_internal undefined

- docs/accessControl.md
Changed:
> The `showClosedAssessment` access rule restriction is only useful in conjunction with [disabling real-time grading](assessment.md#disabling-real-time-grading) and setting `"showClosedAssessment": false`.
To:
> The `showClosedAssessmentScore` access rule restriction is only useful in conjunction with [disabling real-time grading](assessment.md#disabling-real-time-grading) and setting `"showClosedAssessment": false`.
> Correcting typo (also changes meaning of sentence)

- pages/administratorQuery/administratorQuery.js
According to https://highlightjs.org/, the call to `hljs.highlight()` with the language as first argument has been deprecated. This replaces the call with an equivalent call suitable for the new version.
> Replace deprecated version of highlight.js library call

- pages/instructorRequestCourse/instructorRequestCourse.sql
We auto-approve course creation for users who are Owners or Editors: https://github.com/PrairieLearn/PrairieLearn/blob/a8d7eabbd268ae76ebe7bc736394ce2ce1654a4e/sprocs/course_requests_insert.sql#L18
But when we get the existing course settings for the user we only look for Owners: https://github.com/PrairieLearn/PrairieLearn/blob/a8d7eabbd268ae76ebe7bc736394ce2ce1654a4e/pages/instructorRequestCourse/instructorRequestCourse.sql#L42
This means that a course Editor who requests a new course will be auto-approved, but we'll error out before actually creating the course.
Fixes #4630
> Fix auto course creation for editors who aren't owners

- docs/devElements.md
- docs/elementExtensions.md
- docs/question.md
- elements/pl-drawing/info.json
- elements/pl-file-upload/info.json
- elements/pl-matrix-component-input/info.json
- package-lock.json
- package.json
- schemas/schemas/infoElementCore.json
- schemas/schemas/infoElementCourse.json
- schemas/schemas/infoElementExtension.json
- schemas/schemas/infoQuestion.json
Replaced references to:
* `underscore.js` and `lodash.min.js` -> `node_modules/lodash/lodash.min.sh` (resolves #4654 );
* `sha1.js` -> not in use in modern elements/codes/questions;
* `dropzone.js` -> `node_modules/dropzone/dist/dropzone.js`;
Old copies of core scripts are kept for backwards compatibility. References to `PrairieUtil.js` (mainly code to create a copy to clipboard button) are kept, as well as any code for deprecated elements and v2 questions.
Since `sylvester.js` doesn't have an easy browser-friendly NPM package (the existing packages are mostly for node), it's kept as is for now as well.
Still missing: documentation to encourage new development using node modules instead of core scripts were appropriate.
> Replace references to core scripts with node modules

- pages/instructorQuestions/instructorQuestions.ejs
- pages/instructorQuestions/instructorQuestions.js
#3020 changed where authorized course_instances were found, but questions page was not updated to account for this new location. This PR restore access to the assessments columns in the questions page.
Also fixes #4682.
> Restore access to assessments column in questions page

- pages/home/home.ejs
I updated this message for two reasons:
1. Instructors may be confused to see this list empty if they have accessed it before #3020.
2. In `devMode` this message asks to Load from disk, even if this was done already and all courses are in the instructor side (most common case for devMode).
Also remove the suggestion to use the enroll button if it's not shown.
> Update message for home page if no student courses found

- sprocs/sync_assessments.sql
- sprocs/sync_course_instances.sql
Fixes #4687 
As reported by Geoff Herman, the access rule sync process is ignoring the first access rule of every assessment. This rule used to be (in his case) the rule assigned to TAs. The current sync process updates the rules based on their number, so the first rule being updated will be the one that used to be the TA role. Since the role wasn't updated anymore, and TA roles are ignored, this caused this role to now be ignored. This PR restores the update of the role, but setting it to Student always.
This is necessary until #4659 is merged, so if #4659 becomes ready really fast (which I don't think will happen), this is a workaround.
@mwest1066 this is probably one to be merged ASAP.
> Fix access rules role sync

- pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- pages/instructorGradebook/instructorGradebook.ejs
- pages/instructorQuestions/instructorQuestions.ejs
Firefox has a bug whereas if a background is set to a `td` where the table has `border-collapse`, the border disappears. The workaround is to use `background-clip: padding-box`, which ensures the background doesn't apply to the border itself. Should not make a difference for other browsers, since this setting should only make a difference from the default if the border uses opaque/transparent elements.
See https://bugzilla.mozilla.org/show_bug.cgi?id=688556, https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip
> Add workaround for Firefox not showing borders in sticky columns

- pages/partials/questionScorePanel.ejs
Fixes #4694.
This page still has a problem that affects a very narrow set of circumstances: the check that this is controlling is to ensure that, if an instructor opens a student's instance question, they don't report an error as that student by mistake. Similar controls are in place to avoid attaching files or submitting answers:
https://github.com/PrairieLearn/PrairieLearn/blob/8558e7e799739caaef86670209f5eebe1c1d5a6b/pages/partials/attachFilePanel.ejs#L46
https://github.com/PrairieLearn/PrairieLearn/blob/8558e7e799739caaef86670209f5eebe1c1d5a6b/pages/partials/questionFooter.ejs#L5
https://github.com/PrairieLearn/PrairieLearn/blob/8558e7e799739caaef86670209f5eebe1c1d5a6b/pages/partials/questionFooter.ejs#L75
This works fine for the most common cases, but if an instructor opens the …
> Fix grading results refresh when external grader completes

- pages/instructorAssessmentInstances/instructorAssessmentInstancesClientJS.ejs
The page was crashing when an assessment instance wasn't properly assigned to a group (e.g., a group was deleted or an instance was created before the assessment was setup as groupwork).
> Fix formatting of group members for empty/deleted groups in students tab

- pages/instructorCourseAdminInstances/instructorCourseAdminInstances.js
- pages/instructorCourseAdminInstances/instructorCourseAdminInstances.sql
- sprocs/course_instances_with_staff_access.sql
Since #3020 was deployed we've been seeing much higher DB CPU loads. The main culprit is `sprocs/users_is_instructor_in_course_instance`, which we are currently calling about 20,000 times per second at the moment (averaged over the day, much more during peak load). I think the vast majority of these calls are coming from here: https://github.com/PrairieLearn/PrairieLearn/blob/1dfd2d9be1f713d96f75d625dbc2f449e4844c69/sprocs/course_instances_with_staff_access.sql#L68
The current flow is:
* On every authz in `middlewares/middlewares/authzCourseOrInstance.sql` we call `sprocs/course_instances_with_staff_access` to get the list of course instances to put in the navbar dropdown menu that allows rapid switching between course instances.
* In addition to finding the list of accessible course …
> Remove unused enrollment counts in authorization

- lib/config.js
- middlewares/authzWorkspace.js
- middlewares/authzWorkspaceCookieCheck.js
- middlewares/authzWorkspaceCookieSet.js
- server.js
This PR adds a cookie-based authz cache for workspaces. After successful authz for a workspace, we give the client a cookie that lets it bypass authz for this specific workspace for the next 60 seconds.
An alternative would be to cache authz server-side, by keying a redis entry off of the `pl_authn` cookie and the `workspace_id`. I don't have a strong opinion about whether its better to do this with a cookie or a server-side cache, but I went with the cookie because it's simple and doesn't add any load to our cache.
> Add authz cache for workspace proxy

- database/enums/enum_exam_type.pg
- database/tables/exams.pg
- migrations/238_enum_exam_type__create.sql
- migrations/239_exams__exam_type__add.sql
- sprocs/ip_to_mode.sql
This keeps the "force mode=Exam with a checked-in reservation" for online exams, but reverts back to the pre-pandemic behavior for in-person exams. That is, in-person exams will now require an IP match for mode=Exam
> Fix mode=Exam for in-person exams to require IP match

- pages/instructorCourseAdminStaff/instructorCourseAdminStaff.ejs
We allow instructors to add arbitrary UIDs as course staff and we don't check whether they are valid users. This is helpful, because it allows instructors to add course staff without waiting for them to have logged in first. However, it can be confusing if a UID is spelled incorrectly or is missing the `@domain`. In this case the instructor will look at the Staff page and see the UID they entered, without realizing that it's incorrect.
At the moment the blank "Name" field is a sign that the UID is unrecognized. However, this signal is not clear enough for instructors (we just had a case of this).
This PR tries to signal more clearly to an instructor that a UID they entered is unrecognized.
> Add a warning for unknown course staff on the Staff page

- docs/faq.md
As previously suggested by @mwest1066 , this FAQ item explains a workaround for hiding the correct answer in general.
The text was suggested by @jonatanschroeder and @firasm
> FAQ item about hiding the correct answer generally

- docs/elements.md
- elements/pl-figure/pl-figure.mustache
- elements/pl-figure/pl-figure.py
- exampleCourse/questions/element/figure/question.html
Added an alt text field for the pl-figure element for accessiblity reasons. Updated the element *.py files and documentations.
Couldn't use alt or alt-text as a variable name in Python because alt is a reserved word, so apologies on the inconsistent naming of the variables.
Chose "PrairieLearn Figure" as the default text but would happily change if there is a better choice here. Could also go with an empty string.
> Add alt-text attribute for <pl-figure>

- docs/faq.md
The "Read the Docs" setup doesn't seem to handle Markdown properly when backtick-fenced code blocks are nested in lists.
A workaround that seems to work is to use 8 spaces to indent the code block, no backticks, and a blank line before and after each code block. Unfortunately this doesn't let you specify a syntax for the block. (Or does it? Please let me know.)
There may be other places in the docs where this fix is still needed. Note that on GitHub, the problem isn't evident. You have to view it in "Read the Docs" mode.
Tested locally with:
```bash
cd PrairieLearn/docs
make preview
```
Thanks @mwest1066 and @jonatanschroeder for the preview tips.
> fix formatting for nested code fences (8 spaces, no backticks)

- docs/dev-guide.md
Currently 404s without the `../`
> Fix test suite link in developer guide docs

- elements/pl-matching/pl-matching.py
I had problems with this for a student that opened a question that had been released by mistake before it was properly set, but this can also be a problem if a question is changed after a submission had been made (bad practice, but should have a cleaner solution). Current version creates issues every time the question is opened. This should remove that problem
> Error handling in pl-matching if params is not set

- elements/pl-file-upload/pl-file-upload.js
Fixes #4828. I'm assuming empty files are to be considered invalid/ungradable in the context of uploading data (similar to an empty answer for typical submission elements), so this is replacing the incorrect behaviour with a warning and ignoring blank files on upload.
> pl-file-upload: warning if uploaded file is empty

- images/plbase/plbase-install.sh
Otherwise, you could have cases where the plbase image succeeds to
build, but doesn't function properly, as in this build where python
packages weren't installed properly:
https://github.com/PrairieLearn/PrairieLearn/runs/4101152775?check_suite_focus=true
> If plbase-install.sh fails, the plbase build should also fail

- lib/assets.js
The `courseHash` and `urlPrefix` args were switched in `assets.courseElementExtensionAssetPath`, which was causing the question `demo/drawing/extensions ` to break.  This flips them to match `assets.courseElementAssetPath`.
> Fix course element extensions caching

- elements/pl-drawing/mechanicsObjects.js
fabric.js's line class doesn't like when both the `left`, `top` and the endpoints of the line are specified.  This was giving weird behavior where we would get things like this being displayed:
This PR should fix that
> Fix misplaced help line in pl-drawing

- prairielib/lib/sql-db.js
This was introduced by me in #4989 - I didn't properly translate the old code into async/await. This meant that we were leaking DB clients if transactions ever errored.
> fix: Ensure DB client is released if transaction errors

- pages/instructorQuestionManualGrading/instructorQuestionManualGrading.js
Previously, the manual grading page was using `grading_jobs_insert_internal` which was a total hack, because that's supposed to be for autograded questions. This caused a couple of issues including: 
- questions could only be graded once from the manual grading page, it wouldn't save properly if you tried to go back and change the grade
- inconsistent behavior based on 'credit' depending on which page you manually enter the grade on (still not totally clear what we should do here)
This solution isn't probably the end of this, we need to think more deeply about how scores from manual grading should be handled.
However, it will get use something that 'mostly works' for now, which is better than what we currently have.
> Use instance_questions_update_score to save scores in manual grading

- .github/workflows/images.yml
As far as we can tell, the arm64 variant of the `prairielearn/prairielearn` image has been building successfully on master for some time now. This should allow us to build it normally with the amd64 image, instead of separately at the end of the workflow with `continue-on-error: true` set to ignore errors.
There's no great way to test this from a branch - I'll monitor the master build once this lands, and if it turns out that this broke something, I'll revert it again.
Closes https://github.com/PrairieLearn/PrairieLearn/issues/4671.
> fix: Build arm64 version of PrairieLearn image

- .yarnrc
This is a followup to https://github.com/PrairieLearn/PrairieLearn/pull/5105 that tries to fix the new build failures on master by increasing the Yarn timeout. If this doesn't work, we may have to switch to Yarn 2.
> chore: Increase Yarn network timeout

- .dockerignore
- .yarnrc
`.dockerignore` strikes again... In #5106 I didn't explicitly exclude `.yarnrc`, so it didn't end up in the container and Yarn thus didn't use the modified timeout.
To avoid the overhead of another cycle, I also bumped the timeout up to 300s (5 minutes) since I saw that value recommended in a few other GitHub threads.
> fix: Exclude .yarnrc from .dockerignore; bump Yarn timeout

- .dockerignore
- .github/workflows/images.yml
- .yarnrc
This PR reverts the changes from #5105, #5106, #5107 - I couldn't get the build passing, so I want to put master back in a good state until we can get to the bottom of why they're failing.
> fix: Revert arm64 build changes

- pages/partials/instructorGradingPanel.ejs
Without a back button on this page, you have to go through 4+ clicks just to switch which student you are grading: 
Assessments -> Assessment Name -> Manual Grading -> Question Name
This is a bit much, I think we should have the back button here. 
Currently looks like this: 
Which is a good start, but I'm happy for input on the UI, I'm not totally stuck on it or anything.
> Add back button to question manual grading page

- lib/chunks.js
As described in #3939, we were previously caching chunk promises indefinitely. This is a memory leak (although we haven't yet had it impact anything in production) and also means we were caching _rejected_ promises. So, if a chunk failed to load, it would fail to load forever since we had cached the failure.
This PR ensures that a chunk loading promise is removed from our cache once it settles.
Closes #3939.
> fix: Don't cache rejected chunk promises

- images/plbase/plbase-install.sh
We shouldn't log that we're installing R packages if we aren't actually installing them!
> chore: Skip R logs if R packages won't be installed

- pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
- pages/instructorGradebook/instructorGradebook.ejs
Fixes #5108 . It turns out, most search tables were not affected as the "formatting" that was the issue was correlated with buttons and badges. As such, all columns with buttons and badges now have the appropriate flag. This is why the questions page is not affected, as the columns that would have been affected don't allow for free-input search.
> Set search-formatter = false where needed

- .github/workflows/main.yml
- graders/c/Dockerfile
- graders/c/cgrader/cgrader.py
- graders/c/requirements.txt
- tools/build-image-if-needed.sh
This PR "fixes" two issues: 
* build of prairielearn/grader-c in arm64 (including cython and python3.8-dev in dependencies);
* crashing if XML file generated by Check contains characters that are not valid UTF-8.
It also adds arm64 building to CI to allow building errors to be caught on pull rather than on merge.
> C grader: fix arm build and invalid UTF characters

- .git-blame-ignore-revs
This PR adds a `.git-blame-ignore-revs` file, which can be used to configure Git to exclude certain commits when doing a `git blame`. Notably, this excludes 2f3b359987bebf00d45a8c32d58e3b302d117c4a, where I bulk-reformated all JS files with Prettier.
Note that GitHub does not yet understand this file; see https://github.community/t/support-ignore-revs-file-in-githubs-blame-view/3256 for the feature request.
> chore: Add .git-blame-ignore-revs file

- elements/pl-order-blocks/dag_checker.py
- elements/pl-order-blocks/pl-order-blocks.py
- question-servers/freeformPythonLib/prairielearn.py
This resolves an issue with a server that's running an older version of Python. Once the servers are all up to date with Python, we'll revert this to get type checking back.
> Remove all type annotations

- lib/chunks.sql
Fixes #5293 - see that ticket for more details.
> fix: Exclude deleted questions when fetching question templates

- elements/pl-order-blocks/dag_checker.py
- elements/pl-order-blocks/pl-order-blocks.py
Rename some variables in the grading code for internal consistency as well as better consistency with the naming in the upcoming paper about the grading algorithm.
> pl-order-blocks: Rename variables in dag_checker for consistency

- elements/pl-order-blocks/pl-order-blocks.py
Fix #5300 
The new code to convert the ranking to the DAG grading wrongly assumed that the answer blocks would be in some correct order in the HTML.
NOTE that users should still write their problems with the answer in the correct order in the HTML, because the order given in the HTML is the order that will be shown to students as the 'correct' solution. This is a documented known problem that I just haven't gotten around to fixing yet (see e.g. #4650).
> pl-order-blocks: fix incorrect internal conversion from ranking to dag grading

- .github/workflows/cla.yml
By default, the [`cla-assistant`](https://github.com/contributor-assistant/github-action) GitHub Action will lock PRs after they're merged. This is not ideal for the reasons outlined in the comment in this PR. We're willing to accept the risk of someone deleting/editing their comment in the future.
> chore: Disable cla-assistant PR locking

- elements/pl-checkbox/pl-checkbox.mustache
- elements/pl-multiple-choice/pl-multiple-choice.mustache
Recent changes in `pl-multiple-choice` and `pl-checkbox` included the use of `d-inline-flex` to allow for a cleaner visualization of the feedback element. This change, though, causes issues if the answer code contains HTML itself (e.g., `<b>` tags), as reported recently on Slack. This PR adds a span around the answer code to ensure that the answer HTML is not a direct child of the inline-flex parent, and thus the full answer is counted as a single child.
> fix: Embed multiple-choice HTML in span to account for inline-flex

- tests/helperDb.js
- tests/helperServer.js
This refactoring lays the groundwork for additional refactoring to allow us to use Mocha's `--parallel` flag to speed up test runs.
> chore: Refactor DB test helpers to use async/await

- docs/whatToTellStudents.md
There is a typo in the example piazza note under "What to tell students":
```...your point total with never go down!``` -> ```...your point total will never go down!```
> Typo in example note of "What To Tell Students"

- elements/pl-order-blocks/pl-order-blocks.py
co-authored with @CoffeePoweredComputers
> pl-order-blocks: Allow indentation under the DAG grading mode

- elements/pl-order-blocks/pl-order-blocks.py
Fix #5368
I should probably have test cases with every possible combination of configuration options
> pl-order-blocks: Allow partial credit when using ranking grading

- graders/java/JUnitAutograder.java
As reported by @NormanCHutchinson, the Java autograder was repeating tests any time more than one JUnit test class was found in the junit folder. So if there were classes A, B and C, the execution of A would run the tests of A, the execution of B would run the tests of A and B, and the execution of C would run the tests of A, B and C. Caused by the reuse of a request builder in the JUnit launcher API.
> fix: Java autograder repeat test if multiple test classes

- elements/pl-checkbox/pl-checkbox.py
- elements/pl-multiple-choice/pl-multiple-choice.py
Closes #5399 
Fixes empty feedback div in multiple choice and checkbox questions by utilizing that `None` and empty strings both evaluate to `False` in python to set `display_feedback` boolean. Non-empty feedback strings will evaluate to `True`.
> Remove empty feedback on MC and Checkbox elements

- sprocs/instance_questions_calculate_stats.sql
As reported on Slack, the stats were giving weird results if the first submission was non-gradable (score set to null). In that case the first submission has a grade of null, but max and average did not count that submission. For consistency this PR updates it so only gradable submissions are included in stats.
> fix: Only consider gradable submissions in question stats

- lib/question.js
In an effort to gain more information about the intermittent "stuck in transaction" problem that affects chunk servers, this PR adds logs that will dump out some information if transactions don't complete within 60 seconds. Hopefully this will allow us to identify a common cause during failures (a specific question, or course, a particularly large submission, etc.).
> chore: Add logs to help diagnose freezing chunk servers

- admin_queries/generate_assessment_instances.sql
An admin query that adds an assessment instance to every student was still filtering by role "Student". The enrollment role has been deprecated since #3020 so the filter should have been removed.
> fix: Remove outdated column role from admin query

- sprocs/question_order.sql
Fixes an ambiguous variable reference introduced by #4497. Without this fix, everything works fine locally and in staging, but the `question_order()` function takes about 60 seconds to run in production.
> Fix slow load of student assessment page

- lib/question.sql
(as discovered and fixed by @nwalters512) Fixes an incorrect JOIN introduced by #4497. The JOIN assumes that submissions have an associated instance question, which is only true for student questions. For instructor questions this JOIN means that external grading questions fail to re-render the submission panel after grading is complete.
> Fix instructor grading panel refresh

- lib/config.js
- server.js
This is for canary servers, which will have news items that the older stable servers do not. We do not want the canary servers to add their unreleased news items to the DB.
> Add config option to control news item initialization

- database/tables/assessment_questions.pg
- migrations/246_assessment_questions__effective_advance_score_perc__default.sql
This is a cleaner fix for #5425 that simply adds a default value for `assessment_questions.effective_advance_score_perc`. As of PG v11 adding a default value does not cause any DB writes until rows are rewritten, so it's effectively free.
> Fix forced-question-order for unsynced courses

- docs/java-grader/index.md
Adding documentation based on discussion with another instructor that was relying on Java `assert` statements, which are disabled by default by `javac`.
> docs: Add note about Java built-in assert statements

- lib/code-caller.js
- lib/question.js
- prairielib/lib/sql-db.js
When we generate/save/grade questions, we do so with a transaction held open to avoid duplicate work + data. However, on chunk servers, we actually run additional database queries while the transaction is held open, but we try to run the queries with a new client. During periods of high load (or if we just happen to get 10+ requests in the same small window of time), this means that we'd end up with 10 transactions held open. The only way to get out of the transaction is through a query that requires a new DB client, but all the DB clients were in use via the transactions. This is a classic deadlock scenario that ended up with entire servers being unable to respond to requests.
This PR fixes that by using [`AsyncLocalStorage`](https://nodejs.org/api/async_context.html#class-asynclocalstora …
> fix: Avoid acquiring additional database clients inside transactions

- migrations/247_assessment_questions__effective_advance_score_perc__update.sql
#5426 was not enough to fix the problem, because the `effective_advance_score_perc` was already created before we applied the new default. This means that existing rows with NULL values were not updated with the default. It would have been ok if we'd set the default when creating the column, but that's not retroactively possible. This PR fixes this by updating the existing rows to be the default. This will bring the DB up to the state it would have been in if we'd had a default value for the column originally.
> Fix forced-question-order for unsynced courses, v2

- admin_queries/db_running_queries.sql
This could help a little bit with investigations of stuck queries by allowing us to identify which host is making the query.
> feat: Add client column to db_running_queries query

- pages/instructorGradingJob/instructorGradingJob.ejs
- pages/instructorGradingJob/instructorGradingJob.js
Files like archive.tar.gz and job.tar.gz should not be accessible to course content previewers.
> Proper archive files access control

- lib/server-jobs.js
If the `errorAbandonedJobs` cronjob happens to run while a job is in progress, it will fail to invoke `callback()`, which in turn won't ever release the lock. Since locks are implemented via DB clients, it'll hold the client until our idle-in-transaction timeout is hit 10 minutes later and kill the server.
This PR ensures that we always call `callback()`.
> fix: Invoke callback even if server job is running

- Makefile
- docker/init.sh
For folks like me who frequently run natively (not in Docker), running `make start-workspace-host` would unexpectedly put the command in the background and render it unable to be stopped by Ctrl-C. This PR fixes that by removing the `&` from the `start-workspace-host` target and instead using `-j 2` to run both the PL server *and* the workspace host with the same invocation of Make.
> fix: Change how workspace process is run in background

- lib/chunks.sql
- lib/workspace.js
@echuber2 pointed out this typo in my comment after I merged #4791. Just for fun, I searched the codebase for `instn` and lo and behold, I'd made the same typo before 🙃
> fix: Correct typo in lib/workspace.js comment

- lib/aws.js
This fixes the error `TypeError: Cannot read property 'uploadDirectoryToS3Async' of undefined` when importing `lib/aws.js` from typescript.
> fix: Typescript-compatible exports in aws.js

- lib/redis.js
- prairielib/lib/sql-db.js
- prairielib/lib/sql-db.test.js
This PR fixes two issues with using PrairieLearn code in PrairieTest:
- Usage of `this` to refer to the context that `module.exports` functions are executed in (same issue as #5515).
- Exports from `sql-db.js` were being executed with the wrong `this` context when imported as `import * as db from '...'` in a file that was then processed by Babel.
> fix: Ensure compatibility with Babel+TypeScript in PrairieTest

- prairielib/lib/sql-db.js
@mwest1066 discovered this issue while looking at server logs for the `autoFinishExams` cronjob. This was just obviously broken code.
> fix: Improve error handling during transaction rollback

- database/tables/group_logs.pg
- migrations/248_group_logs__indexes_add.sql
- sprocs/assessment_instances_select_log.sql
- tools/pg_describe
This PR introduces two performance optimizations to the `assessment_instances_select_log` sproc:
- Restructures how we fetch from `page_view_logs`. Previously, we had a nested `SELECT 1 ...` query that would check for group `join` events in order to determine which users we had to show logs for. However, an `EXPLAIN ANALYZE ...` revealed that this resulted in a sequential scan of `group_logs` *per page view log*, which was very slow. Now, we first do a single filter of `group_logs` based on the `assessment_instance` ID to find all the user IDs we should fetch `page_view_logs` for, and then we filter `page_view_logs` on `assessment_instance_id` and `authn_user_id`. We can then reuse the results of that when we check for assessment/variant view logs.
- Adds indexes to the `group_logs` table …
> feat: Improve performance of assessment_instances_select_log

- lib/assessment.js
Fixes #5526.
As discussed in #5526, I think we should make `gradeAssessmentInstance()` return without error if the instance is closed and `requireOpen == true`. That could wait for a later PR, however.
> fix: Add missing argument when grading all assessment instances

- admin_queries/course_instance_active_enrollments.json
- admin_queries/course_instance_active_enrollments.sql
This PR adds some more useful statistics to the `course_instance_active_enrollments` admin query. These should help to identify the term in which course instances were active.
I've tested this on the UIUC Staging server.
> feat: More stats for active course instance admin query

- pages/administratorQuery/administratorQuery.ejs
- pages/administratorQuery/administratorQuery.js
- pages/administratorQuery/administratorQuery.sql
This PR adds a new "Recent query runs" panel to admin query pages. This makes it easier to access the results of recent runs without having to dive into the database to get a query run ID.
> feat: Display recent admin query runs

- sprocs/variants_insert.sql
This bug was introduced in #5489, which manifested as the following error in production:
```
function variants_select(json, bigint, bigint) does not exist
```
Interestingly, this means we are indeed hitting race conditions in prod!
> fix: Correctly get ID of existing variant in variants_insert

- CONTRIBUTING.md
- docs/requestCourse.md
- docs/workshop/index.md
Per @trombonekenny, this is the preferred link for joining the PrairieLearn Slack org. Closes #4486.
> docs: Update Slack invite link

- graders/java/JUnitAutograder.java
Some students have been creating background threads for some tasks, but don't close them properly when needed. This causes the autograder to hang after completing the JUnit tests. This PR forces the system to exit after results are saved, which also closes any pending threads.
> Java autograder: force exit after saving results to close background threads

- docs/getStarted.md
- docs/workshop/index.md
- docs/workshop/lesson1.md
- docs/workshop/lesson2.md
- docs/workshop/lesson3.md
- docs/workshop/lesson4.md
- mkdocs.yml
This PR fixes the workshop documentation, removing outdated content:
- fixes links to PL and request course information
- remove mention to CBTF
- remove outdated reference to spreadsheet for the HW
> docs: update request course and workshop 

- docs/workshop/index.md
I just realized the markdown rendering looked different on my computer yesterday, compared to how it appears now live:
Should instead appear as:
This PR adds one indentation, which seems to solve the issue.
> docs: Fix itemized list

- public/stylesheets/local.css
Fix #5535. The issue was that labels were white on a white background. This PR just changes them to be black.
> fix: Show plot labels in stats pages

- pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql
Fixes #5511
Fixes #4848 
Files associated to all submissions or to instance questions were being duplicated based on a join of group_users that wasn't even used.
> fix: Duplicate submission rows for group assessments

- graders/java/autograder.sh
For cases like compilation errors of Java tests (typically caused by changes in method signature) and application crashing, the error messages were sometimes vague, leading to many questions by students about what they mean. This PR adds some additional comments of common cases for these problems.
> Java grader: better error messages for ungradable cases

- images/plbase/plbase-install.sh
R packages take up a lot of time and space, so I'll often set `SKIP_R_PACKAGES=yes` when I'm trying to work quickly in a non-production environment, e.g. build a new EC2 AMI to test. However, even with that flag set, we would still install `r-essentials` and `rpy2`. This PR changes that such that `SKIP_R_PACKAGES=yes` won't install *anything* R-related.
> fix: Don't install anything R-related if SKIP_R_PACKAGES is set

- docs/dev-guide.md
- middlewares/authn.js
- middlewares/authzWorkspaceCookieSet.js
- pages/authCallbackAzure/authCallbackAzure.js
- pages/authCallbackLti/authCallbackLti.js
- pages/authCallbackOAuth2/authCallbackOAuth2.js
- pages/authCallbackShib/authCallbackShib.js
- pages/authPassword/authPassword.js
This change ensures that our authentication cookie won't be accessible to client-side JavaScript, which is a security best practice (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies).
> fix: Improve security of cookies

- pages/partials/attachFilePanel.ejs
- pages/studentAssessmentInstanceFile/studentAssessmentInstanceFile.js
- pages/studentAssessmentInstanceFile/studentAssessmentInstanceFile.sql
This PR improves downloads of assessment attachments:
- Removes the possibility of assessment attachments being used as an XSS vector
- Improves authorization for access to files
Shoutout to @dwang for identifying these issues!
> fix: Improve assessment attachment downloads

- .changeset/fresh-months-tap.md
- packages/html/src/index.test.ts
- packages/html/src/index.ts
Because `typeof null === 'object'`, we would previously throw an error when trying to render `null` values: https://github.com/PrairieLearn/PrairieLearn/blob/69b1ad97bd8f2bb88fb205b487ea23929bcfdfe5/packages/html/src/index.ts#L12
This PR also prints a more informative error message when an object can't be rendered.
@nwalters512 can you remind me how to release a new version of this library after this PR is merged?
> fix: Don't error on 'null' in HTML templates

- .prettierignore
See https://github.com/changesets/changesets/issues/616. This fixes the CI issue on #5614.
> fix: Don't run Prettier on Changesets changelogs

- elements/pl-xss-safe/pl-xss-safe.mustache
- elements/pl-xss-safe/pl-xss-safe.py
Instead of templating the student-provided content to a variable in the `pl-xss-safe` element, it is passed as a data attribute (`data-code`). This removes an XSS vector where a closing `</script>` tag gets interpreted, so the content is never sanitized.
For consistency, the language is also passed as a data attribute (`data-language`).
@jonatanschroeder
> fix: Use data attributes in pl-xss-safe

- package.json
I noticed that every time I saved a file in the Web interface `nodemon` would restart the server. This seems to be related to the fact that saving a file in the file editing interfaces causes a JSON file to be added to `s3rver/file-store`, which triggers `nodemon` to restart the server. This change causes this directory to be ignored by `nodemon`.
> chore: Add s3rver file store to ignore list for nodemon

- docs/requirements.txt
- docs/workspaces/index.md
- mkdocs.yml
Readthedocs markdown needs 4 space indent for nested lists.
> docs: Fix indentation in `workspaceOptions` list

- .changeset/stale-actors-repeat.md
- packages/opentelemetry/src/index.ts
Fixes the issue [reported on Slack](https://prairielearn.slack.com/archives/C0XBTPZMZ/p1649879271667649
) where the following is logged three times at startup:
```
no function to unwrap.
Error
at ExpressInstrumentation.unwrap [as _unwrap] (/PrairieLearn/node_modules/shimmer/index.js:84:13)
at InstrumentationNodeModuleDefinition.unpatch (/PrairieLearn/node_modules/@opentelemetry/instrumentation-express/build/src/instrumentation.js:72:22)
at ExpressInstrumentation.disable (/PrairieLearn/node_modules/@opentelemetry/instrumentation/build/src/platform/node/instrumentation.js:123:24)
at /PrairieLearn/packages/opentelemetry/dist/index.js:108:43
at Array.forEach (<anonymous>)
at Object.init (/PrairieLearn/packages/opentelemetry/dist/index.js:108:26)
at async.series.msg …
```
> fix: Don't disable instrumentation if OpenTelemetry isn't enabled

- tests/helperDb.js
- tests/sync/assessmentSetsSync.test.js
- tests/sync/assessmentsSync.test.js
- tests/sync/courseInstancesSync.test.js
- tests/sync/initialSync.test.js
- tests/sync/questionsSync.test.js
- tests/sync/tagsTopicsSync.test.js
This builds on and depends on the work in #5352. I'm just submitting as a separate PR for easier review.
This uses `TRUNCATE` to reset the database state instead of recreating the entire DB from scratch for each test. This is much faster: when running tests serially (this is close to what happens on CI since the GitHub runners only have two cores), this change cuts the time to run the sync tests from 24 seconds to just 12!
> chore: Use TRUNCATE to reset database state in sync tests

- workspaces/desktop/Dockerfile
- workspaces/desktop/pre-install.sh
Was previously broken because we were always downloading x64 vscode.  Now we download the correct version based on the platform.
> Fix desktop workspace build on arm64

- .changeset/pink-cameras-wink.md
- packages/opentelemetry/src/index.ts
- server.js
Before this change, a process receiving `SIGTERM` wouldn't actually terminate. Now, it does!
Instead of having `@prairielearn/opentelemetry` handle `SIGTERM`, I opted to just expose a `shutdown()` function that a consumer could call. This makes it possible to coordinate with other handlers that need to do something before the process exits.
I tested this locally by setting `"openTelemetryEnabled": true` in my `config.json`, starting PL, finding its PID with `ps aux | grep "node server.js"`, and then running `kill -TERM $PID`
> feat(opentelemetry): Don't handle SIGTERM by default

- .changeset/eight-carrots-hug.md
- packages/html/src/index.test.ts
- packages/html/src/index.ts
Now, we'll get compile-time warnings for trying to interpolate objects in an `html` tagged template literal. This matches the runtime behavior, which is to throw an error.
Closes https://github.com/PrairieLearnInc/PrairieTest/issues/464.
> feat(html): Add type constraints for interpolated values

- grader_host/index.js
This is a bandaid for #5669 that should hopefully allow us to get things operational for students and instructors again while we work on identifying the root cause and a better fix.
Originally, I did this with `_.once`, but ultimately realized that it was more robust to just refactor this to use promises. Promises have nice semantics where they can only transition from pending to fulfilled exactly once, so that prevents any of these kind of errors from occurring.
> fix: Ensure createImage callback only executes once

- elements/pl-string-input/pl-string-input.py
The `remove-leading-training` option removes all whitespace from the beginning and end of a string, but `remove-spaces` only removed the space character. Other whitespace (tabs, for example) were not removed.
This PR updates `remove-spaces` to remove other whitespace as well.
> Ensure remove-spaces on pl-string-input removes all whitespace

- graders/python/requirements.txt
This reverts the change from #5650. `networkx==2.8` requires `scipy>=1.8`, but we currently have an older version installed (`1.7.1`). Rather than bumping `scipy` right now, we're going to wait til after finals are over. I opened #5685 to track that.
Fixes #5679.
> Temporarily downgrade networkx

- pages/instructorInstanceAdminLti/instructorInstanceAdminLti.ejs
Fixes #5672 
In the rare case that you initiate LTI linking from an LTI consumer on a new course instance with no assessments, visiting the LTI admin page crashes the template with a specific combination of variables being defined while `assessments` is null. This fix prevents iterating over the null array.
I haven't tested this yet due to the complexity of mocking the LTI consumer situation.
> fix edge case in EJS for LTI admin page

- tests/helperQuestion.js
I've noticed tests, specifically "Auto-test questions in exampleCourse", failing intermittently in CI, e.g. on https://github.com/PrairieLearn/PrairieLearn/pull/5673 (failing run: https://github.com/PrairieLearn/PrairieLearn/runs/6234885939). We don't currently have enough logs for the failure case to tell went wrong. This PR adds those. This is consistent with the [logs in the `waitForJobSequence` function](https://github.com/PrairieLearn/PrairieLearn/blob/529f6dffb1b5b79d1d0ebf777a99741eab8f6aa7/tests/helperQuestion.js#L39).
> Add logs to help debug failing question tests in CI

- docs/pl-drawing/index.md
- elements/pl-drawing/defaults.py
- elements/pl-drawing/elements.py
This PR adds an opacity attribute to: rectangle, triangle, polygon, circle, line, arc, and point elements.
The `opacity` attribute partially addresses #5280 . It allows us to use `pl-drawing` and `pl-overlay` in combination, to ask questions where students "annotate" an image or graph by placing semi-transparent drawing elements on it.
> Add opacity attribute to some drawing elements

- grader_host/config/base.yaml
- grader_host/index.js
- workspace_host/interface.js
The main server process already has `config.postgresqlPoolSize` and `config.postgresqlIdleTimeoutMillis`. This PR adds them for workspace hosts and grader hosts. No defaults are changed by this PR so there will be no change in behavior unless the new config options are set.
> Add config vars for PG pool size and timeout

- lib/question.js
- tests/gradingMethods.test.js
The current grading methods tests was not properly submitting an answer to test if the submission process worked. As a result, the testing was done based on outdated variable values from internal grading instead of from manual grading itself. This PR fixes the test to actually submit a value.
A result of this distinction is that it detected a case where questions with manual grading were allowing a grade action which had been disabled in the UI. This PR also fixes the error that the test originally failed to identify.
> fix: Grading methods test not submitting manual answer

- .github/workflows/main.yml
This PR changes the triggers for our CI workflow so that we only run one CI job per commit on a pull request. Previously, we ran two, which more quickly exhausted our maximum parallel jobs and made folks wait longer to get a green result to merge.
Per suggestion from @SethPoulsen, I'm lifting this change out of #1626 so it can be reviewed and merged independently.
> Only run CI once for PRs

- Makefile
I believe this is needed to use the copy of `turbo` that's installed by `yarn`. Without this I get a "command not found" for `turbo` because I don't have it globally installed.
> fix: Use Yarn to execute Node tools

- docs/elements.md
In the docs, Elements for writing questions > Conditional elements > pl-question-panel element > Details had a heading level inconsistent with the rest.
> Fix incorrect heading level in docs

- docker/init.sh
When a local docker process runs, it uses `make -j` to start the workspace host and PrairieLearn server in parallel. This is typically fine, since in most cases stdin isn't used by either the server or the workspace host, however when nodemon is used (`-e NODEMON=true`), nodemon relies on standard input to allow user-led restart of the server (by typing `rs`). This PR ensures that nodemon receives access to standard input so that this restarting is possible, by ensuring it is the first job listed in make (https://www.gnu.org/software/make/manual/html_node/Parallel-Input.html).
> Direct standard input to nodemon for local Docker runs

- lib/ltiOutcomes.js
- lib/ltiOutcomes.sql
[As reported on Slack](https://prairielearn.slack.com/archives/C266KEH9A/p1655148217555639), it's possible that an LTI assessment might be missing a callback URL to report the score, resulting in an error like the following:
```
options.uri is a required argument
```
This PR updates our LTI code to gracefully handle that case.
> fix: Gracefully handle missing LTI callback URL

- docs/elements.md
Actually my understanding of panels is so incredibly low * that someone
should double-check whether this is the correct fix.
* bad attitude due to 1.5 hours of `*-panel` debugging.  If I actually learn enough to understand I will try to improve these docs but prognosis is dim
> docs: Fix typo in pl-question-panel description

- Makefile
- package.json
- yarn.lock
`depcheck` doesn't appear to understand our Yarn workspaces setup, and it definitely doesn't work with the way that we currently use dependencies on the client. It also brings along a lot of unnecessary dependencies with it. I'm opting to remove it; if someone really wants to run it, they can just run `npx depcheck`.
> Remove depcheck

- pages/partials/question.ejs
CS 411 reported a strange issue with question display where the rendered submission didn't match the score: https://prairielearn.slack.com/archives/C266KEH9A/p1656516492465929.
It turns out #5793 inadvertently broke the display of older submissions - the rendered submission HTMLs weren't paired with the correct submission metadata (score, time, etc.).
> Fix display of old submissions

- tools/verify-changelog.sh
This is no longer needed as we're no longer updating the changelog.
> Remove verify-changelog.sh script

- images/plbase/plbase-install.sh
Doing this independently of #5993 so that we can build and publish a new base image. It looks as though the `pltest` image used in CI is built from the *latest* version of `prairielearn/plbase` from Dockerhub, not the version of `plbase` that we actually build during CI. That's a problem we should solve, but not one I can right now.
> Add gcc g++ compiler to plbase image

- images/plbase/plbase-install.sh
- package.json
- tools/build-image-if-needed.sh
NodeJS v16 is now ["Active"](https://nodejs.org/en/about/releases/) so we should upgrade to it.
> Upgrade to NodeJS v16 (from v14)

- question-servers/freeform.js
This manifested during testing with the following error:
```
Cannot destructure property 'data' of '(intermediate value)' as it is undefined.
```
> Fix getCachedDataOrCompute function

- .github/workflows/cla.yml
This pulls in the latest changes, including those from https://github.com/contributor-assistant/github-action/pull/104 that should improve the experience for folks signing the CLA for the first time!
> Install latest version of cla-assistant/github-action

- question-servers/freeform.js
Followup to #6015 that instruments `generate` and `prepare`; I missed them in the first PR!
> Add even more instrumentation to freeform operations

- graders/c/Dockerfile
Updated the DockerFile for cgrader to include /grade/serverFilesCourse in PYTHONPATH.  This will allow any python files copied from serverFilesCourse to be importable in the testing script.
This was discussed in [How to append to environment variable in external graders? #6048](https://github.com/PrairieLearn/PrairieLearn/discussions/6048)
> Added /grade/serverFilesCourse to PYTHONPATH in cgrader

- lib/question.js
- pages/partials/question.ejs
As discussed with @ffund, the manual grading page should always show the correct answer.
> Show correct answer in manual grading page regardless of status

- question-servers/freeform.js
Fixes #6116 
This was a subtle typo in the recent async refactoring in `freeform.js`: `data.feedback` should be `resultData.feedback`.
> Fix disappearing feedback in gradeAsync

- database/tables/migrations.pg
- prairielib/lib/migrations.sql
- tests/database.test.js
To my credit, the code was so robust that I didn't notice this problem during my initial testing since the timestamp would always be synced on the second boot 😂
> Fix database migration application

- middlewares/selectAndAuthzAssessment.sql
- pages/instructorAssessmentSettings/instructorAssessmentSettings.ejs
PR #4360 introduced modules and does an unconditional JOIN on `assessment_modules` in `selectAndAuthzAssessment.sql`. However, modules are optional and so any assessment without one will return no rows from this query, thus failing authorization.
I will check other authz paths as well before merging this.
> Fix assessment authorization with modules

- pages/instructorAssessments/instructorAssessments.sql
- pages/studentAssessments/studentAssessments.sql
This should fix the issue that @mfsilva22 reported where assessments weren't being grouped correctly on the assessment pages.
I believe this works because the order of rows in the partition need to match that of the result set so that we put the "new section" marker in the correct place.
As for why this issue showed up in production and not locally: this is because ordering was dependent on IDs, which are not consistent between environments.
> Fix grouping of assessments by module

- prairielib/lib/sql-db.js
This is necessary for some migration we're doing to ES Modules in PrairieTest. This is necessary because [`cjs-module-lexer`](https://github.com/nodejs/node/tree/main/deps/cjs-module-lexer) only supports `module.exports` if the properties are identifiers or string literals.
> Use exports instead of module.exports for sql-db functions

- ee/auth/saml/index.js
- ee/auth/saml/router.js
Without this, an error during SAML authentication would crash the server, which is obviously no good!
> Fix error handling during SAML authentication

- lib/config.js
- pages/authLogin/authLogin.ejs
This will be useful as we transition from Apache Shibboleth to using PrairieLearn's built-in support for SAML authentication that was introduced in #6112.
> Add config option to hide the Shibboleth login button

- pages/instructorAssessmentManualGrading/assessment/assessment.sql
Fixes #6152 
This reduces the query execution time in #6152 from 2 minutes to 80 milliseconds.
The key change here was to move from the EXISTS sub-query over variants+submissions to JOINing over variants+submissions and then using DISTINCT to select one row per instance question.
I also moved the "only select instance questions with submissions" part of the query into its own separate CTE at the top. I don't think this was necessary but it made it easier to explore what was going on.
I don't understand why the query planner has trouble with the EXISTS sub-query, but I do personally find the new query to be "safer" in the sense that it's just a big sequence of JOINs that I know the query planner can handle without trouble.
```sql
selected_instance_questions AS (
SELECT
iq.*
FROM …
```
> Speed up instructor manual grading query

- .changeset/slimy-moles-study.md
- packages/html-ejs/src/index.ts
- prairielib/lib/sql-loader.js
This will help ease the transition to ESM, as we can just pass `import.meta.url` directly to these functions.
> Allow file URLs to be used in renderEjs and loadSqlEquiv

- graders/r/Dockerfile
- graders/r/README.md
This also switches the CRAN package injection from using the c2d4u repo with its ~5k packages to the newer r2u with full coverage, which reduces on RUN step as we no longer need any 'additional' CRAN packages installed from source.
Otherwise standard updated which @barbehenna tested locally based on a build we did in the predecessor repo.  The PR is otherwise very narrow and touches nothing outside the r-autograder directory.
> Update R autograder to Ubuntu 22.04, R 4.2.1 and current packages

- lib/question.js
The switch from using callbacks to an `async` function means we can now properly catch and handle errors if something fails (for instance, we saw a case in the wild where the encoded JSON exceeded the maximum size of a string in Node).
Relatedly, we will now only generate the base-64 encoded JSON when we're rendering a legacy (v2, not Freeform) question, as Freeform questions don't make use of that value at all.
> Handle errors when encoding question data into JSON

- cron/workspaceHostTransitions.sql
If a workspace host unexpectedly dies or is terminated, we need to mark any workspaces that were allocated to run on it as stopped.
> Mark workspaces as stopped when their host terminates

- tests/sync/questionsSync.test.js
- yarn.lock
I ran `yarn-deduplicate`, which pulled in a new version of `@types/chai`. That resulted in two new type errors, courtesy of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59859. This PR fixes those.
> Fix chai.assert typechecking

- grader_host/index.js
- workspace_host/interface.js
Followup to https://github.com/PrairieLearn/PrairieLearn/pull/6182 that enables Sentry for grader and workspace host.
This doesn't yet capture *every* type of error; just global ones and a few specific local errors that I picked basically at random.
> Enable Sentry for graders and workspaces

- lib/assessment.js
Resolves #6255. The format of the message is somewhat analogous to what would be printed if results.json did not exist or could not be parsed as JSON.
> fix: Proper error message if external grader has invalid score

- package.json
- tools/pg-describe.js
- tools/pg-diff.js
- yarn.lock
This should unblock #6289; see https://github.com/yargs/yargs/issues/2175 for the root cause of the blockage (the Jest types are now pulling in `@types/yargs`).
> Install @types/yargs

- lib/config.js
- pages/home/home.ejs
- pages/partials/title.ejs
We were notified by ZJUI that we need to make specific changes to our site to comply with local regulations:
- We need to change the `<title>` on all pages to a specific value.
- We need to add the website registration number and a link to the [Ministry of Industry and Information Technology](https://en.wikipedia.org/wiki/Ministry_of_Industry_and_Information_Technology) domain registration website.
Adding these config values will allow us to comply with regulations without hardcoding anything specific into PrairieLearn's source code.
> Add config options for compliance with Chinese regulations

- packages/bind-mount/README.md
You guys sick of me making one line documentation PRs yet?
> docs: fix typo in bind-mount README

- server.js
Throwing an error in the `router` function of `http-proxy-middleware` currently produces an unhandled exception. Until https://github.com/chimurai/http-proxy-middleware/pull/823 is merged, we need special handling to avoid blowing through our Sentry error budget.
> Don't send "Workspace is not running" errors to Sentry

- graders/r/Dockerfile
This minimal PR adds `pandoc` ~and `pandoc-citeproc`~ to the R autograder container.
> Add pandoc to graders/r/Dockerfile

- images/executor/Dockerfile
This shaves several hundred MB off the size of the executor image.
https://github.com/wagoodman/dive looks to be a great tool for identifying where the biggest parts of a Docker image come from.
> Clean yum cache in executor image

- images/plbase/plbase-install.sh
This shaves another ~80MB off our Docker images.
https://docs.conda.io/projects/conda/en/latest/commands/clean.html
> Clean Conda caches after installation

- lib/chunks.js
- lib/chunks.sql
- tests/chunks.test.js
- tests/chunks.test.sql
Fixes the following Sentry error: https://sentry.io/organizations/prairielearn-inc/issues/3580869456/?project=6704263
Closes #6308.
When we're fetching chunks, we use the presence of an `id` field on the results of [`select_metadata_for_chunks`](https://github.com/PrairieLearn/PrairieLearn/blob/8e752630568f07b018096aaa7f93d92f0dd1335c/lib/chunks.sql#L18) to indicate whether or not a given chunk exists. If it does not, we remove that chunk from disk. However, this was failing for `clientFilesAssessment` chunks, as the resulting row from the database did not include the course instance name or the assessment name. This ultimately causes the following `path.join` call to fail since `chunkMetadata.courseInstanceName` and `chunkMetadata.assessmentName` are both `null`: …
> Fix deletion of non-existent chunks

- pages/studentInstanceQuestionExam/studentInstanceQuestionExam.js
This will keep this event out of Sentry, and it also more accurately reflects what the error actually is.
> Use 403 status code when exam time limit has expired
