PrairieLearn/PrairieLearn

server.js

We observed some crashes during boot during a recent deployment that were causes because we started processing external grading results before actually starting the websocket server. This PR fixes that, and reorders a few other startup processes as well.

Ensure socket.io has started before processing external grading results

---

server.js

This was causing startup failures during a deploy this morning:
```
Error: duplicate jobType: python_worker_idle
```

Initialize estimators earlier during boot

---

docs/course.md
news_items/038_organize_by_module/index.html

The link in the news item has the wrong fragment (`#` part).

Fix doc link in news item

---

docker-compose.yml
lib/workspace.js
package.json
workspace_host/interface.js
yarn.lock

This PR makes a few improvements to workspace host error handling based on the errors we've seen in Sentry:
- Instead of writing the graded files archive to disk, we now directly pipe it to the response. This incidentally fixes an error where we were a) not awaiting the `fsPromises.unlink` return value and b) sometimes passing `undefined` to `fsPromises.unlink`
- The return value of `_getWorkspaceSettingsAsync` was previously unawaited; now it is.
- We weren't using the `new` keyword with `Stream.Transform`.
I also wired up Sentry request tracking for workspace host commands.

Improve workspace host error handling

---

server.js

This should fix some issues we've been seeing in production with Shibboleth requests.

Use regex to route Shibboleth requests

---

pages/enroll/enroll.ejs
pages/enroll/enroll.sql

Resolves #6349. If a student is enrolled in a course, the `hideInEnrollPage` flag is ignored to allow a student to remove a course.
Also allows courses to be listed in the enrollment page (partially handles the comment in https://github.com/PrairieLearn/PrairieLearn/issues/3149#issuecomment-1252837329).

Show enrolled hidden courses and instructor access in enroll page

---

Makefile

The legacy mode (`-L` flag) of `nodemon` is causing 100% CPU usage. Given it was (presumably) originally used to address cases of mounted drives inside containers, and those problems don't seem to be an issue anymore (tested on Windows at least), I propose removing the flag, which fixes the CPU usage issue.

Remove legacy mode for nodemon invocation

---

elements/pl-dropdown/pl-dropdown.mustache
exampleCourse/questions/element/dropdown/question.html

Fixes #5898. Dropdown was using div instead of span for an object intended to be inline. Also removed the dropdown id for parts that didn't use them.

fix: pl-dropdown proper use of inline tags

---

grader_host/index.js
grader_host/lib/jobLogger.js

This PR fixes a few unhandled errors that were reported by Sentry:
- We weren't handling errors thrown from `container.kill()`; now we handle and log them.
- We weren't handling `'error'` events emitted from the S3 logger; I added error handling based on the `s3-streamlogger` docs: https://github.com/Coggle/s3-streamlogger#handling-logging-errors. I also increased the buffer size so that we'd be less likely to run into `SlowDown: Please reduce your request rate.` errors.

Fix unhandled errors in grader host

---

pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs
pages/instructorAssessmentInstances/instructorAssessmentInstancesClientJS.ejs

Resolves #6341. Sorts closed assessments first (somewhat equivalent to expired/negative time limit), then assessments with a time limit, then assessments with no time limit (equivalent to infinite time limit).

Improve time limit sorting behaviour in assessment instances list

---

pages/instructorFileBrowser/instructorFileBrowser.js

This makes a few improvements to syntax highlighting in the instructor file browser:
- When checking if a file is binary and determining its MIME type, use methods that read a limited number of bytes directly from disk. This limits the memory consumption and IO usage for especially large files.
- Treat any text file larger than 1MB as a binary file to avoid reading it into memory or trying to highlight it.
- Instead of using `highlightAuto` to guess the language, we now first guess based on file extension. If that guess fails, we'll use `highlightAuto` to try to guess based on just the first 2000 bytes of the file. This improves the speed of guessing and ensures we don't run out of memory if we try to highlight a particularly large file.

Improve syntax highlighting for instructor file browser

---

lib/chunks.js

Closes #6361.
AFAICT this occurred because there were existing chunks in the DB for course instances that no longer existed. Those course instances would have appeared in `existingCourseChunks`, but not in `courseData`, hence the error that we've seen.

Fix chunk generation when deleted course instances exist

---

lib/assessment.js
lib/question.js
pages/error/error.js
sprocs/assessment_instances_ensure_open.sql
sprocs/variants_ensure_open.sql

This should clean up reports of 500 errors from Sentry and our load balancer logs, which should improve the signal-to-noise ratio there.
I don't *love* inspecting the text of error messages here, but it's the simplest option considering that the sprocs that are raising these exceptions are themselves called from inside *other* sprocs.

Use appropriate HTTP status codes for SQL exceptions

---

.gitignore
grader_host/README.md
grader_host/lib/config.js
lib/aws.js

This is a small bit of low-impact cleanup.
If someone wants to use AWS credentials when running locally, they should use the standard `AWS_*` environment variables (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html, e.g. `AWS_PROFILE`). This is the standard way that AWS clients work; there's no need for our own idiosyncratic layer on top of that.
If we find ourselves needed to do more than configure credentials, we should add support for e.g. and `aws.config` property in our standard `config.json` file.

Remove aws-config.json support

---

lib/editors.js
pages/instructorFileBrowser/instructorFileBrowser.js
tests/courseEditor.test.js
tests/courseEditor.test.sql

This PR fixes the issues that @ffund reported on Slack this morning: https://prairielearn.slack.com/archives/C266KEH9A/p1663865172180029
For posterity, Fraida renamed an assessment from something like `foo/bar/infoAssessment.json` to `bar/baz/infoAssessment.json`. This left behind a `foo` directory that didn't contain any `infoAssessment.json` file in itself or its descendants, so that was flagged as a sync error.
After this PR, we'll now run `git clean -dfx` a second time after committing the edits to disk. This will ensure that no empty directories remain when we read in the course state from disk.

Run git clean before syncing from disk after performing an edit

---

images/executor/Dockerfile
images/plbase/plbase-install.sh
images/plbase/python-requirements.txt

A few minor optimizations to the creation of our Docker image:
- We now run `nvm cache clear` to remove cached Node downloads
- `psutil` is now listed in `python-requirements.txt` (this should be slightly faster, and will allow Dependabot to update it)
- `procps-ng` is installed in `plbase` instead of in the `executor` image (this should be faster, as we don't have to download the RPM repository metadata again)

Improve creation of Docker images

---

README.md
docs/index.md

This PR brings the README and documentation page in sync with each other. It removes outdated references to Coveralls, Docker builds, Travis, our license, and our changelog.

Update README and documentation index page

---

grader_host/index.js

This fixes a bug I inadvertently introduced in #6339.

Fix external grader usage of async.waterfall

---

server.js

Followup to #6335. I don't think we caught this at the time, but we were actually waiting until *after* we had started the server before we would init the freeform code (basically, constructing the element cache). We need that in place before we can serve requests.
This shouldn't have mattered in practice, as we'd need to pass a couple of health check intervals before we actually received traffic. However, this is still more correct.

Initialize freeform code before taking requests

---

lib/config.js
server.js

Fixes the following issue reported in Slack: https://prairielearn.slack.com/archives/C266KEH9A/p1664576961459249. tl;dr: users running locally were no longer admins, which naturally causes a lot of problems.
I inadvertently broke this this morning with #6383 when I shifted the call to `insertDevUser` _after_ the call to `startServer()`. I didn't realize that `config.devMode` was set in `startServer()`, so `config.devMode` was false when we checked whether or not to insert the dev user.
The fact that `config.devMode` isn't available during parts of server initialization strikes me as the kind of idiosyncrasy that'll cause future problems, so I opted to fix this by computing `config.devMode` when config is actually initialized.
This no longer uses `app.get('env')`, but the behavior should …

Fix creation of dev mode user

---

python/zygote.py

Shortly after deploying new code, we sometimes see issues like the following occurring:
These originate from matplotlib's `FontManager` class:
https://github.com/matplotlib/matplotlib/blob/0517187b9c91061d2ec87e70442615cf4f47b6f3/lib/matplotlib/font_manager.py#L1098
This PR silences that warning by disabling the `Logger` instead that `FontManager` uses.
However, the fact that `FontManager` can take >5s to finish loading its cache is itself concerning. To attempt to alleviate that, we now import `matplotlib.font_manager` during zygote startup to hopefully ensure that it's available by the time someone tries to use it in their code.
Note that [EBS lazy initialization](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-initialize.html) is probably partly responsible for the slow loading …

Silence matplotlib logging during startup

---

pages/error/error.js
server.js

Followup to #6360. Our error handler runs after the Sentry error handler, which means `err.status` wasn't set in time for Sentry to read it.

Set error status code before Sentry error middleware

---

tests/groupStudent.test.js

Remove console.log() call from group tests

---

database/tables/jobs.pg
lib/server-jobs.sql
migrations/20221011010233_jobs__status__add_index.sql

This PR makes two improvements to the performance of `errorAbandonedJobs`, which runs once every 10 minutes:
- Add an index of `jobs.status`. This avoid a table scan to find the jobs in the 'Running' state when executing `select_running_jobs`.
- Select only the columns we need, not all of them (this will likely have a very negligible impact on performance).

Improve performance of errorAbandonedJobs

---

lib/config.js
server.js

This should resolve the occasional 502s we see in the load balancer logs.
See the following for more details:
- https://www.tessian.com/blog/how-to-fix-http-502-errors/
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout
Closes https://github.com/PrairieLearnInc/sysconf/issues/398

Configure HTTP keep-alive timeout

---

middlewares/logResponse.js

Express can mutate `Request#path` as it's passed around between middleware, so we were seeing inaccurate paths in our response logs. This PR changes the logging middleware to capture the path at the start of the request.

Use correct path in response logs

---

pages/instructorIssues/instructorIssues.sql
sprocs/issues_select_with_filter.sql

This PR applies the course ID filter earlier inside the `issues_select_with_filter` sproc. This should avoid doing a full table scan on `issues` every time the issues page is rendered.
Originally described in https://github.com/PrairieLearnInc/sysconf/issues/397.

Avoid table scans when querying for course issues

---

database/tables/issues.pg
migrations/20221011211919_issues__question_id__add_index.sql

The existing `issues_question_id_open_idx` index was actually a duplicate of the `issues_course_id_open_idx` index. This PR drops that existing index and replaces it with the one we actually want.
This should eliminate the table scan from the following query:
https://github.com/PrairieLearn/PrairieLearn/blob/d5c54956a74ae90a5182ca23fb6eaba094c60f90/middlewares/selectAndAuthzInstructorQuestion.sql#L6

Fix issues_question_id_open_idx index

---

pages/studentAssessments/studentAssessments.sql

As it turns out, `NULLS FIRST` was indeed necessary, contrary to what both @mwest1066 and I thought (https://github.com/PrairieLearn/PrairieLearn/pull/6143#discussion_r949764816). I left comments so that we don't make this mistake again in the future.
Closes #6158.

Fix ordering of multiple-instance assessments in student view

---

pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ejs

When renaming the column in assessment question from `manual_points` to `max_manual_points` in #5909 , one file was inadvertently skipped.

fix: Incorrect column name in manual grading page

---

images/plbase/plbase-install.sh

Before this change, Conda would take ages (and sometimes get OOM-killed) when trying to "solve" the environment. I don't know why this fixes things, but coupled with a larger instance type, we can now build AMIs again!
Inspired by a recommended way of installing documented at https://docs.anaconda.com/anaconda/user-guide/tasks/using-r-language/.

Attempt to fix R installation

---

migrations/20221018160700_instance_questions__status__update.sql
sprocs/instance_questions_points_homework.sql

The instance question status indicates how the grading of the instance question is applied. In particular, I believe the intention is:
* unanswered: no submission;
* saved: submission saved, but not graded;
* invalid: submission saved, but parsing failed;
* grading: submission saved and grading requested but still waiting for completion (external grading);
* correct/incorrect: submission saved and graded, and more submissions allowed;
* complete: submission saved and graded, and no more submissions allowed (exams).
These are not properly handled right now. A homework question has the status "saved" until it is correct (i.e., "incorrect" is not used). Exams handle this properly.
Also, the "grading" status is never used (from what I could tell), the status in place while grading is actually …

Update status from saved to incorrect in homeworks upon grading

---

.changeset/cold-tips-peel.md
packages/opentelemetry/package.json
packages/opentelemetry/src/index.ts
yarn.lock

Jaeger is a self-contained OpenTelemetry collector and UI that can be run really simply with a single Docker command:
```sh
docker run --rm --name jaeger \
-e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
-p 5775:5775/udp \
-p 6831:6831/udp \
-p 6832:6832/udp \
-p 5778:5778 \
-p 16686:16686 \
-p 14268:14268 \
-p 14250:14250 \
-p 9411:9411 \
jaegertracing/all-in-one:1.21
```
This makes it easy to locally investigate response traces with a nice UI without having to e.g. sign up for Honeycomb or another service that can collect traces.

Add support for Jaeger OpenTelemetry exporter

---

sprocs/assessment_instances_select_log.sql

Based on discussion on Slack. Given the raw submitted answer for questions with files will contain the base64 content of the file for a key like `_file_upload_XXX` or `_file_editor_XXX`, keys that start with a `_` are removed for cases where files should not be included.

Add raw submitted answer to assessment instance log

---

lib/code-caller/code-caller-container.js

This fixes an issue where error information from previous calls would incorrectly be shown if a code caller timed out. Now, the error output is reset on each new call.
This code is not yet running in production, so there was no risk of information leakage across courses.
Closes https://github.com/PrairieLearnInc/sysconf/issues/446.

Reset outputBoth in CodeCallerContainer

---

pages/shared/syncHelpers.js

Without this, servers crash when they fail to sync images. Best reviewed with whitespace changes ignored..
Yet another reason to move towards `async`/`await`!

Fix error handling in ecrUpdate sync helper

---

sprocs/sync_assessments.sql
sprocs/sync_course_instances.sql
sprocs/sync_questions.sql
tests/sync/assessmentsSync.test.js
tests/sync/courseInstancesSync.test.js
tests/sync/questionsSync.test.js
tests/sync/util.js

Fixes https://github.com/PrairieLearn/PrairieLearn/issues/6539. See inline comments for details on the fix itself! Since we use essentially the same syncing algorithm for questions, assessments, and course instances, I had to make the fix in all three places.

Fix sync error in the face of renames and duplicate UUIDs

---

workspace_host/s3-log-forwarder.js

The missing `.` meant that our timestamps were invalid after the first upload.

Fix workspace log persistence

---

executor.js
lib/code-caller/README.md
lib/code-caller/code-caller-container.js
lib/code-caller/code-caller-native.js
lib/code-caller/code-caller-shared.js
lib/code-caller/index.js
python/zygote.py

We've observed intermittent timeouts under periods of high load. When a timeout occurs, we kill the child process and start a new one. However, because we preload a number of large Python libraries, starting a new worker can take a long time. Previously, our calling code wasn't aware of this. We believe this was capable of causing cascading failures where we'd send a call to a worker while it was still booting up, and that call would time out, leading to another restart, and so on.
This PR allows the host process to "ping" the child when it's booting up for the first time to ensure that it's ready to accept calls. This ping is modeled as a normal call; this means that when a worker is able to respond to a ping, it'll be able to respond to question/element calls too.
I originally started …

Wait for code callers to boot up before sending calls to them

---

lib/file-store.js
pages/partials/attachFilePanel.ejs
pages/shared/studentInstanceQuestion.js

This PR solves the following Sentry error: https://sentry.io/organizations/prairielearn-inc/issues/3581270096/?project=6704263
The specific error is `Cannot read properties of undefined (reading 'originalname')`, coming from here:
https://github.com/PrairieLearn/PrairieLearn/blob/f2ee0e4280da6a83e36f271df6db5342c3154408/pages/shared/studentInstanceQuestion.js#L35
For good measure, I'm validating both on the client (don't allow submission if a file hasn't been selected) and on the server (respond with a 400 if no file was attached).

Block file attachment submission if no file selected

---

sync/syncFromDisk.js

Fixes #6546. Note that if writing to the database itself fails, we won't print warnings and errors because an error will have been thrown. I think this is acceptable, as syncing is designed to be extremely resilient and shouldn't ever actually fail. If it does (like in #6540), we have a bigger problem.
Here's how the syncing output looks now:

Print sync warnings/errors after writing to database

---

lib/markdown.js
lib/question.js
package.json
tests/markdown.test.js
yarn.lock

Fixes #6600. Remark (via remark-raw) is better suited to handle badly formatted html.

Replace showdown with remark in manual feedback rendering

---

workspace_host/interface.js

#6381 changed the interface to initialize a socket server, but a reference to this interface was not updated in the workspace host call. This caused the workspace host not to be initialized properly, as a callback function that was expected to run was indeed not running anymore.

fix: Initialization of socket server in workspace host

---

lib/code-caller/code-caller-container.js

Closes #6614. This makes the `CodeCallerContainer` state machine match that of `CodeCallerNative`, where we transition to `WAITING` as soon as we have a child, before we've actually health-checked it.

Fix CodeCallerContainer state machine during child creation

---

grader_host/index.js

Closes #6605.
This explains why I'm unable to reproduce the error in #6605, and why the issue was fixed for the author when they reduced the amount of output: the data is now small enough to fix in the SQS results message, so we now never try to read this file in PL. When the results file was originally larger, it *didn't* fit in the SQS results, so we had to read it from S3. We don't use this code locally, which explains why it can't be reproduced locally either. This *also* explains why this particular error went away
The `'binary'` has been present for as long as the external grader host code has existed. I don't know why I used that in the first place, but I can't see any reason why we should use it - everything should be UTF8.

Don't treat external grader results JSON as binary-encoded

---

lib/socket-server.js
server.js

Closes #6619. There should never be a need for us to "gracefully" shut down the HTTP or socket.io servers. If they still have connections when we start terminating, something else has gone wrong and we can allow those connections to die unceremoniously.

Fix termination sequence

---

.prettierignore

Now that https://github.com/changesets/changesets/issues/616 has been resolved by https://github.com/changesets/changesets/pull/905, we no longer need to ignore changelogs during Prettier formatting.

Don't ignore package changelogs from Prettier

---

elements/pl-order-blocks/pl-order-blocks.py

We've had a few people confused why problems aren't being graded properly, when they shouldn't be using duplicate tags.
Throw an error so the question won't even render.
This could potentially break some questions in the wild. Though arguably they are already broken if they are using duplicate tags. Making them break loudly might be better than having them be broken silently, which is what currently happens.

pl-order-blocks: raise exception if question has non-unique tags

---

pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js
pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql

Resolves #6623. Adds columns for assigned grader and last grader to the CSV downloads for instance questions and submissions (all/best/last).
#6623 refers to a column for when the assessment was last graded. This column already exists as "Grading date" in the submissions files.

Add manual grader columns for assessment downloads

---

pages/instructorAssessmentSettings/instructorAssessmentSettings.js
pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.js

Fixes #6628. Because we set [`trust proxy`](https://expressjs.com/en/guide/behind-proxies.html) to 1 when running behind a load balancer, it will respect the value of `X-Forwarded-Proto` and use it for `req.protocol`.

Use correct protocol for student links

---

lib/node-metrics.js

This PR wraps the collection and reporting of Node metrics in a `try`/`catch` block to ensure that the process doesn't die if metrics collection fails.
It's recommended to review this PR with whitespace changes hidden.

Fix crash when getting Node metrics fails

---

lib/config.js
lib/lifecycle-hooks.js
server.js

This PR removes the code that polls for the ASG instance lifecycle state. Automated termination should now be handled with the webhook that was added in https://github.com/PrairieLearn/PrairieLearn/pull/6608.

Remove ASG lifecycle state polling

---

lib/lifecycle-hooks.js

This PR avoids errors if we try to start up or shut down outside the context of an ASG lifecycle change. See inline comments for more details.
Closes https://github.com/PrairieLearnInc/sysconf/issues/547.

Only complete ASG lifecycle actions if instance is in wait state

---

elements/pl-matching/pl-matching.py

This was reported on Slack: https://prairielearn.slack.com/archives/C266KEH9A/p1670371314582939. The element appears to already support `weight`, and the attribute is even documented; it just wasn't listed here when this element was implemented in #3670.

Allow weight attribute for pl-matching element

---

docs/running-in-production/setup.md

While we hope to be able to officially support zero-downtime deploys in the future, they currently require specialized tooling and the occasional manual intervention. In the meantime, we'll documented what *is* supported for folks running self-hosted installations.

Document recommended way of upgrading to new versions

---

pages/authCallbackShib/authCallbackShib.js

#810 introduced support for URLs like https://pl-dev.engr.illinois.edu/pl/shibcallback/redirect/pl/course_instance/4/instructor/assessment/10/. #1057 improved this by storing the desired URL in a cookie and redirecting to it once auth is complete, so the `.../redirect/...` is no longer necessary.

Remove legacy login redirects

---

schemas/schemas/serverConfig.json

We've assigned a meaning to `redisUrl: null`:
https://github.com/PrairieLearn/PrairieLearn/blob/310ff716139f576b20280456a64b3b5fb34f5a93/lib/redis.js#L16
This PR ensures that the JSON schema for our config allows Redis to be disabled.

Allow redisUrl to be null

---

pages/workspaceLogs/workspaceLogs.js

If a workspace is created from a question preview without a course instance in the URL (e.g. `pl/course/1/question/87/preview`), the workspace won't have an associated course instance.

Fix workspace logs when course instance not present

---

docs/devElements.md

Docs were referring to old location of the library in the code.

docs: Fix reference to python libraries

---

lib/config.js
pages/home/home.ejs
pages/partials/advertisement.ejs
pages/partials/navbar.ejs
pages/studentAssessments/studentAssessments.ejs
pages/studentGradebook/studentGradebook.ejs

This PR adds the ability to configure a site-wide announcement that will appear at the top of every page. This is primarily meant to be used to announce maintenance windows, including the upcoming downtime in January 2023.
This also removes the old "advertisement" code in favor of this new configurable announcement.

Add configurable site-wide announcement

---

lib/config.js

The code uses the variable name `config.announcementHtml` but in `config.js` we initialize a default value for `config.announcementText` (note `...Text` vs `...Html`). This PR fixes the `config.js` name to be `...Html`.

Fix default name of config.announcementHtml

---

package.json
packages/compiled-assets/package.json
packages/html-ejs/package.json
packages/html/package.json
packages/opentelemetry/package.json
packages/sentry/package.json
yarn.lock

This PR fixes the following warnings that would appear when running `yarn` in a project:
```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @prairielearn/compiled-assets@workspace:packages/compiled-assets doesn't provide @types/node (p790b8), requested by ts-node
➤ YN0002: │ @prairielearn/html-ejs@workspace:packages/html-ejs doesn't provide @types/node (p82ca1), requested by ts-node
➤ YN0002: │ @prairielearn/html@workspace:packages/html doesn't provide @types/node (p312bc), requested by ts-node
➤ YN0002: │ @prairielearn/opentelemetry@workspace:packages/opentelemetry doesn't provide @types/node (pe8f1a), requested by ts-node
➤ YN0002: │ @prairielearn/sentry@workspace:packages/sentry doesn't provide @types/node (pd6f60), requested by ts-node
➤ YN0000: │ Some peer dependencies are incorrectly met; …
```

Add missing peer dependencies

---

.github/dependabot.yml

When merging a PR forces all Dependabot PRs to be rebased, the subsequent GitHub Actions run queue prevents new jobs from running for hours. This PR disables the automatic rebasing behavior to avoid this.
I've taken to manually applying and grouping JS dependency updates into a single PR (see e.g. https://github.com/PrairieLearn/PrairieLearn/pull/6893), so having automatic rebasing is less important. Fingers crossed that GitHub will implement grouped dependency updates soon: https://github.com/dependabot/dependabot-core/issues/1190.

Disable Dependabot rebasing

---

images/plbase/plbase-install.sh

The `prairielearn/plbase` image wasn't correctly rebuilt after #6793 was merged. This PR makes a small change to the plbase files to force it to rebuild.

Make change to plbase files to force it to rebuild

---

package.json
yarn.lock

`eslint-plugin-import` depends on `array.prototype.flatmap`, but that dependency isn't declared in its `package.json`. We can move back to the latest version once this is resolved. See https://github.com/import-js/eslint-plugin-import/issues/2663.
Normally this would have been caught by CI, but I accidentally pushed https://github.com/PrairieLearn/PrairieLearn/commit/7a81139913d54a83c6cd5c7ff458df12a952a060 straight to master 😭

Temporarily downgrade eslint-plugin-import

---

lib/chalk.js
package.json
sync/course-db.js
yarn.lock

Note that we can't yet use chalk 5+, as we can't yet use EMS-only packages.

Install latest compatible version of chalk

---

lib/databaseDescribe.js
lib/databaseDiff.js
tools/pg-describe.js

For unknown reasons, these issues appear to have not been caught by Mocha, and in fact made Mocha skip much of our test suite and exit 0. They also weren't caught by TypeScript somehow?

Fix test suite failures caused by chalk

---

ee/cron/chunksHostAutoScaling.js

Metrics have the dimension `Server Group`, not `ServerGroup`. For consistency, I also updated the dimension for the of the metrics that chunk autoscaling emits. This will require us to update CloudWatch dashboards once this is deployed.

Fix chunk autoscaling metric queries

---

.github/workflows/main.yml
.github/workflows/release.yml
.yarnrc.yml
Dockerfile

This PR makes a few changes to how we use Yarn:
- Enables the global cache. This makes our host-based deploys faster, as we can reuse cached downloads between different revisions.
- Enables the `preferAggregateCacheInfo` option. This makes Yarn print a single-line message for missing cache entries (e.g. `29 packages were already cached, 1517 had to be fetched`) instead of one line per package.
- Replaces the now-deprecated `--frozen-lockfile` option with `--immutable`.

Improve Yarn config

---

database/tables/assessment_instances.pg
database/tables/assessment_score_logs.pg
database/tables/instance_questions.pg
migrations/20230119091410_points_in_grading__drop.sql

Resolves #5911. These columns are not used anywhere in the code, and #5909 removed all remaining instances of these columns being updated (they were not used before that point even).

Drop columns for points and score in grading

---

pyproject.toml

Running `make format` locally produced some false positive errors:
```
error: cannot format workspaces/xtermjs/src/node_modules/node-pty/deps/winpty/misc/DumpLines.py: Cannot parse: 5:10:     print i, "X" * 78
Python 2 support was removed in version 22.0.
error: cannot format workspaces/xtermjs/src/node_modules/node-pty/deps/winpty/ship/common_ship.py: Cannot parse: 23:22:                 print "+ rm -r " + path
Python 2 support was removed in version 22.0.
error: cannot format workspaces/xtermjs/src/node_modules/node-pty/deps/winpty/ship/ship.py: Cannot parse: 48:6: print "Determining Cygwin/MSYS2 DLL versions..."
Python 2 support was removed in version 22.0.
Oh no! 💥 💔 💥
118 files left unchanged, 3 files failed to reformat.
```
These don't show up in CI because we don't install the deps …

Exclude all node_modules directories from Black formatting

---

middlewares/logPageView.js
middlewares/logPageView.sql
package.json
pages/administratorOverview/administratorOverview.ejs
pages/administratorOverview/administratorOverview.sql
question-servers/freeform.js
yarn.lock

These stats are better tracked by Honeycomb and CloudWatch.
I've left the `panel_render_cache_hit_count` and `panel_render_count` columns in the DB so that we can safely deploy this. Once we've done that, I'll remove them: #6958

Don't track render cache stats in the database

---

docs/elements.md
elements/pl-big-o-input/pl-big-o-input.mustache
elements/pl-big-o-input/pl-big-o-input.py
elements/pl-symbolic-input/pl-symbolic-input.mustache
elements/pl-symbolic-input/pl-symbolic-input.py
exampleCourse/courseInstances/SectionA/assessments/gallery/elements/infoAssessment.json
exampleCourse/questions/element/bigOInput/question.html
exampleCourse/questions/element/symbolicInput/question.html

See title, in relation to https://github.com/PrairieLearn/PrairieLearn/issues/6968. Also cleans up mustache templates and adds a variable to reduce duplication of string literal name of the mustache template.

feat: Customizable placeholder text for pl-symbolic-input and pl-big-o-input elements

---

.gitattributes

This is to ensure files in `.yarn` are not included in results of `git grep` or `git diff`.

Add binary attribute to .yarn files

---

lib/code-caller/code-caller-native.js

This reduces a Python call from ~3s to about 200ms 🎉 
This was especially bad because Node feeds us data in chunks of 8kB. For elements that output megabytes of data, we'd do the `indexOf` operation 100s or 1000s of times. Each check only took a few milliseconds, but that was really expensive across so many operations. If I recall from undergrad correctly, that would make this $O(n^2)$ on the length of the data 😭

Optimize Python calls with large amounts of data

---

.github/workflows/main.yml

This PR caches the Yarn dependencies that are installed on the GitHub Actions host and used to build and publish the executor image. Note that this doesn't have any impact on the dependencies installed in the `prairielearn/prairielearn` Docker image itself.

Cache Yarn dependencies in CI

---

.github/workflows/images.yml

We've heard from folks that doing local course dev against `prairielearn/prairielearn:latest` can result in using features that aren't available in the deployed version yet. This change will make it possible to reference the SHA in a deploy announcement and pull the image that corresponds with that exact version.

Tag prairielearn/prairielearn Docker image with commit SHA

---

pages/authCallbackOAuth2/authCallbackOAuth2.js

This PR picks off some information from a Google OAuth error and sends it to Sentry so that we can investigate `invalid_grant` errors that we're occasionally seeing.

Capture detailed information after failed OAuth authentication

---

pages/instructorAssessments/instructorAssessments.ejs
pages/instructorAssessments/instructorAssessments.js

This PR removes the download of all files ever submitted for a course instance. The query puts an incredible amount of stress on our database and will almost always exceed the 60 second timeout at the load balancer, meaning the data can't be accessed anyways. If course staff really wants all this data, they can fetch each individual submission from the API. In the vast majority of cases, they should be able to use the assessment-specific download links.

Remove download of all course instance files

---

elements/pl-symbolic-input/pl-symbolic-input.py

For some unequal expressions, the sympy `equals` function will return `None`, which raises an assertion failure in the grader code (which expected `equals` to return to return a boolean). Unfortunately, tooling didn't catch this because Sympy doesn't have type annotations.

`pl-symbolic-input` return type fix

---

schemas/schemas/infoQuestion.json

@jonatanschroeder reported seeing the following error when running tests:
```
strict mode: missing type "object" for keyword "properties" at "#/properties/workspaceOptions/additionalProperties" (strictTypes)
```
This PR should fix that.

Fix strict mode warning on question JSON schema

---

docs/installing.md

As discussed on Slack, includes the tags for `us-prod-live` and `ca-live` for the latest deployed version in Docker Hub. `us-canary-live` is not added to avoid confusion.

docs: Add deployed tags for local execution

---

lib/code-caller/index.js

This is a huge kludge to work around the issue described here: https://github.com/getsentry/sentry-javascript/issues/7031. Tl;dr: we need to ensure that code callers are created outside the ["domain"](https://nodejs.org/api/domain.html) of a request. Otherwise, that domain will indefinitely hold on to the Express `res` object, which in turn means that any large values in `res.locals` will be kept alive (prevented from being garbage-collected) for the lifespan of the worker.
I tested this in isolation on my reproduction repo: https://github.com/nwalters512/sentry-domain-memory-leak/pull/1. After refreshing 6 times, memory usage falls back to normal levels, so I believe this fix should work. However, it's difficult to test in PrairieLearn itself, as it's difficult to reproduce the failure …

Attempt to fix code caller memory leak

---

jobs/workspaces/workspace-2-2/current/fibonacci.py
lib/workspace.js
pages/workspace/workspace.ejs

Fixes #7023. The key change here is that we separate joining the socket room from actually starting the workspace. That allows us to rejoin the room when a client reconnects *without* also restarting the workspace.

Improve workspace reconnection handling

---

.eslintrc.js
package.json
tests/chunks.test.js
yarn.lock

@trombonekenny pointed out on Slack that we had a skipped chunks test. This PR unskips it and adds a few new ESLing rules so that this doesn't happen again.

Disallow skipped or exclusive Mocha tests

---

lib/question.js
lib/question.sql
pages/partials/submission.ejs

#6375 changed v3/Freeform questions to lazily render all old submissions when their panels are expanded. However, we were still actually loading all the data for *every* submission to a variant, which could be quite a lot. We believe this is partially responsible for some memory issues we've been seeing in production recently.
This PR changes that to only load the detailed information (the JSONB columns) for the submissions that will actually be rendered. This does mean that we'll need 2 database round-trips instead of just one, but the cost of that should be low.

Load only rendered submissions from database

---

.github/workflows/main.yml
docker/start_postgres.sh

This made the Node tests run ~40s faster in CI. While this is not as much as a speedup as we'd hoped, it's still something! Bigger gains are likely to come from changes to tests themselves.

Use tmpfs filesystem for Postgres data in CI

---

lib/question.js
lib/question.sql

This PR makes two improvements to the issues queries used in `lib/question.js`:
- When only a count is needed, only load the count instead of all the data.
- If the `course_data` will not be displayed, don't load it.
These should both reduce load on the database and decrease memory consumption.

Improve issue queries

---

lib/code-caller/index.js

Fixes the issue reported by @jonatanschroeder on Slack where tests would hang after completing.

Unref code caller timeout to allow tests to exit

---

lib/externalGraderCommon.js

Empty files will have a blank contents attribute, which is treated as falsy. This should be allowed.

Fix handling of empty files in external grader

---

.github/workflows/cla.yml
.github/workflows/main.yml

Per https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue, we need this to trigger workflow runs.

Configure GitHub Actions workflows for the merge queue

---

lib/code-caller/code-caller-container.js
lib/code-caller/code-caller-native.js

After spending some time with the Node inspector, I think this may have been contributing to our memory issues. We'd be holding this object in memory until `this.lastCallData` gets reassigned in the next `call()` call. If we get unlucky and have a lot of failed calls in a row *and* have a low request rate (read: we're not cycling through the Python code callers very quickly), we might have a lot of these objects hanging around in memory. By dropping the reference to it, we allow it to be garbage collected ASAP.

Allow lastCallData to be quickly garbage collected

---

lib/issues.js
lib/question.js
lib/question.sql

Applies the same changes from #7112 and #7113 to the `system_data` of issues. This should further improve memory usage and performance in the average case when errors are encountered (that is, the user is a student).

Truncate and conditionally load issue system data

---

pages/authLoginOAuth2/authLoginOAuth2.js

Addresses part of https://github.com/PrairieLearn/PrairieTest-feedback/issues/20. The issue is that, when using Google Auth, often the user is already logged in to a single Google account (e.g., their Gmail), but they may need to login with an institution-specific account. Causing the account page to always be shown when logging in ensures the user is aware of which account is being used, even in the specific cases where the Gmail account (or whatever they're already logged in with) is the expected one.
Unfortunately I don't have the means to test this.

Force Google auth to prompt user for account

---

pages/authLogout/authLogout.js

After this change, http://localhost:3000/pl/logout?redirect=https://google.com will redirect to google.com after clearing the cookies.

Support redirect after logout

---

question-servers/freeform.js
tests/courseElementExtension.test.js

Another fix I'm lifting out of #7128. I don't think this would have actually manifested as an error in practice, but it'll pose a problem with the experimental renderer.

Fix bug when loading missing element extensions

---

lib/config.js
package.json
pages/authCallbackOAuth2/authCallbackOAuth2.js
pages/authLoginOAuth2/authLoginOAuth2.js
yarn.lock

`googleapis` is a massive package, weighing in at ~120MB and taking ~250ms to load on my machine. `google-auth-library` is comparably much smaller: it's only 680kB and takes ~20ms to load on my machine.
This change should decrease the size of our Docker image, decrease application boot time, and make our production AMI builds complete more quickly.

Use google-auth-library instead of googleapis

---

graders/java/autograder.sh

Previous fix actually made the autograder stop working altogether.

Java grader: fix handling of disabled Java management

---

graders/java/Dockerfile
graders/java/autograder.sh

Continuation of #7154. This will cause any attempt to use classes in `java.lang.management` and related classes to fail with:
```
java.lang.UnsatisfiedLinkError: no management in system library path: /usr/lib/jvm/java-18-openjdk-amd64/lib
```

Java grader: fully disable Java management module

---

elements/pl-drawing/pl-drawing.mustache
elements/pl-drawing/pl-drawing.py

While comparing the rendered HTML from #7128, I observed that it was behaving differently for questions using `<pl-drawing>`. While this ultimately ended up being a bug in the new rendering code, I think it's still worth changing this code to use double-quoted attributes and explicitly escape any quote characters in the JSON.

Fix pl-drawing HTML attribute escaping

---

Makefile

Tiny change to add `make ci` to the makefile to mimic what the CI tests do on GitHub (without the docker checks). Locally I kept forgetting to run a typecheck or lint, thinking that test did all of them. This takes it down to one command.

feat: make ci  shortcut

---

lib/externalGrader.js

Currently if there is an unknown error in the external grader (e.g., a disk full error), the external grader provides an error message to the student, but still keeps the submission as gradable. For questions with limited attempts (either exam questions, or homework questions with limited tries per attempt), this causes the student to lose an attempt at the question through no fault of their own. This PR changes that behaviour to tag the question as not gradable, which is the same behaviour used for other errors like formatting errors, blank answers or compilation errors in the external grader.

Cause external grader errors to tag submission as not gradable

---

sprocs/authz_course_instance.sql

Sentry alerted us to this very rare race condition: there's the possibility that another writer inserted an enrollment between the read a few lines up and this write.

Fix race condition in authz_course_instance sproc

---

elements/pl-file-upload/pl-file-upload.js

A fix done in #6995 allowed the preview to open automatically upon submitting a new file. The corresponding button, however, was not properly updated to show "Hide preview" as needed.

fix: pl-file-upload button text on new submission

---

elements/pl-external-grader-results/pl-external-grader-results.css

When external grader results include long messages or outputs, the output boxes can cause the scrolling of results to become overwhelming. This is particularly a problem when the message provides the expected value, and the output provides the obtained value, and the student may have issues trying to compare the results.
The change here causes these boxes to use at most 40% of the screen height, introducing scrollbars if necessary. This makes the boxes easier to navigate overall.
An existing CSS rule for an `.output` class was removed as well, since there is no element with such a class in the mustache template.

Limit height of output/message in external grader results

---

lib/config.js
package.json
server.js
yarn.lock

The Sentry CPU profiling added in #7145 ended up not being particularly helpful for us; its focus on individual requests made it difficult to see the big picture. Our hope is that Pyroscope will serve us better in helping us to understand production performance.

Add Pyroscope CPU/memory profiling

---

.dockerignore
.prettierignore

This has no effect on Github CI but can give warnings when running the linter locally. Also adds it to .dockerignore for consistency.

Add built assets to .prettierignore

---

pages/administratorCourses/administratorCourses.ejs

This was removed accidentally in #2378; it got lost in the shuffle as we were moving things between pages.

Add missing institution link

---

workspace_host/interface.js
workspace_host/lib/docker.js

This PR improves the performance of workspace logs parsing by avoiding the allocation of a new `Buffer` on each iteration of the loop. For an artificial log with 100000 "chunks", this improved performance from ~14 seconds to ~100ms.
This also changes the log handling to read at most 50k lines of logs, which should also help ensure that we don't process/transmit/store ridiculous amounts of information.

Improve performance of workspace logs parsing

---

pages/partials/instructorInfoPanel.ejs

The extra whitespace around the QID text can result in Firefox incorrectly selecting the QID on double-click, as reported by @daviddalpiaz. This is apparently a Firefox bug, as @nwalters512 found (https://bugzilla.mozilla.org/show_bug.cgi?id=1043118) but this PR should work around it.

Remove whitespace around instructor QID link

---

Makefile
grader_host/tests/receiveFromQueue.test.js
package.json
packages/prettier-plugin-sql/package.json
prairielib/lib/config.test.js
prairielib/lib/migrations.test.js
prairielib/lib/util.test.js
yarn.lock

This removes a lot of deps from our dependency tree, which should speed up installs and reduce Docker image size.

Replace remaining usages of Jest with Mocha

---

lib/assessment.js

This was introduced in #7194. The `LEFT JOIN`s on `users` in this query make it pretty clear that that we might not have a user. ~I don't know exactly why.~ The auto-close event doesn't have an associated user.

Make auth_user_uid nullable for assessment logs

---

pages/workspaceLogs/workspaceLogs.js
pages/workspaceLogs/workspaceLogs.sql

Before this change, trying to get logs from a stopped workspace would cause an error:

Only fetch workspace logs from host if running

---

pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs

(And apparently some whitespace cleanup too)

fix: instructor assessment instances page modal typo

---

tools/start_workspace_tmux.sh

I've made several additions to the optional tmux entrypoint script in `tools/`. Now it can optionally invoke yarn upon load and re-chown generated files in a dev mount (e.g. `node_modules`...) back to the local user's uid:gid. Also, kill lingering workspaces upon exit.

enhancements for tmux script in light of yarn, local mounting

---

elements/pl-drawing/mechanicsObjects.js

This seems to have been an issue that may have been introduced indirectly by #6974 (works in 1e4140495, does not work in 0e9b51088). In essence this approach is likely better anyway.
At the moment the element is referenced, it is not yet part of the document's DOM, so it would not be found. Looks for the specific object ID inside the SVG reference instead of in the whole document.
Before the change:
After the change:

fix: pl-drawing MathJax reference to objects not yet in DOM

---

graders/c/cgrader/cgrader.py

In #5910, the check-based functionality of the C grader implemented a copy of the XML log to the `/grade/results` directory so it could be investigated if needed. The problem is that this directory may not exist at that point.

C Grader: create results directory if it does not exist

---

python/prairielearn.py

Fixes the pint cache issue, discussed on slack. Summary: If multiple `zygote.py` processes are running on the same server, then this creates a race condition with `pint` cache creation, where a process might try and read a cache file that's still being created. To solve this, we use a separate cache directory for each process, that way, the cache file creation won't interfere with other processes.

Fix pint cache issue

---

lib/code-caller/code-caller-container.js

I made two bad assumptions when writing this code:
1. Unmounting will only ever fail if the directory wasn't already mounted.
2. If an error occurred while unmounting, we could safely proceed with the subsequent mount.
In practice, we seem to have a really weird failure case where transient issues outside our control result in a bind mount being unable to be removed (e.g. `EBUSY` errors). If we try to re-mount on top of an existing mount, weird things that I don't fully understand happen, and the kernel locks up for a while.
It's vastly preferable for us to fail to grade/render a question (this can be retried by the student) than it is to get stuck in a state where the kernel is unhappy, so I'm changing this code so that we'll only try to remove a bind mount if we know we created one …

Allow unmounting errors to propagate up

---

sprocs/variants_insert.sql

I've seen a low volume of errors like `no such variant_id for this question: ######` in prod for a while, but wasn't able to identify why until I was looking at traces for an unrelated error today. The root of this problem is that `real_question_id` was `NULL` when we called `variants_select()`. By reordering the statements, we ensure a non-null `real_question_id`.
Interestingly, this tells us that the race condition _is_ in fact happening in prod!

Fix error when selecting newly-created variant

---

lib/code-caller/code-caller-container.js
lib/code-caller/code-caller-native.js
package.json
yarn.lock

When I implemented similar changes in #6994, I neglected to make them for the container code caller. I also realized that we're doing a lot of unnecessary string allocation here, so I changed things to collect an array of data chunks and only join them all together at the end.

Improve performance of code caller output handling

---

pages/userSettings/userSettings.ejs

Closes #7189 
Part of the effort to resolve the Mathjax rendering complexities and support, issues, and PRs
Also adds some logged-in user data (like institution and authentication source) readonly to the user settings page. We don't show that information anywhere and it could be helpful for LTI development

feat: user settings page: add user info, mathjax reset button

---

grader_host/index.js
lib/externalGraderLocal.js

Because no one likes horizontal scrolling.
Before:

style: line wrap grader timeout message

---

docs/installing.md
docs/installingLocal.md
docs/installingNative.md
mkdocs.yml

I didn't change the file names so as not to break existing links.
Closes #5030.

Tweak documentation page titles about local installation

---

exampleCourse/questions/demo/annotated/LectureVelocity/1-Introduction/question.html
exampleCourse/questions/demo/annotated/LectureVelocity/2-Derivative/question.html
exampleCourse/questions/demo/annotated/LectureVelocity/4-KnowledgeTest/question.html
exampleCourse/questions/demo/annotated/MarkovChainGroupActivity/MarkovChains-Gambler/question.html
exampleCourse/questions/demo/annotated/MarkovChainGroupActivity/MarkovChains-Intro/question.html
exampleCourse/questions/demo/annotated/MarkovChainGroupActivity/MarkovChains-PageRank/question.html
exampleCourse/questions/demo/annotated/engBeamStress/question.html
exampleCourse/questions/demo/annotated/engBinary/question.html
exampleCourse/questions/demo/annotated/engCircuit/question.html
exampleCourse/questions/demo/annotated/engMarkovBrewing/question.html
exampleCourse/questions/demo/annotated/engVectorDrawing/question.html
exampleCourse/questions/demo/annotated/graphAdjacencyMatrix/question.html
exampleCourse/questions/demo/annotated/mathFunctionDerivative/question.html
exampleCourse/questions/demo/annotated/mathMatrixMult/question.html
exampleCourse/questions/demo/annotated/mathMatrixMultT/question.html
exampleCourse/questions/demo/annotated/mathNumberInput/question.html
exampleCourse/questions/demo/annotated/mathNumbersConcept-all/question.html
exampleCourse/questions/demo/annotated/mathOuterProduct/question.html

While reviewing another PR, I noticed that the documentation note in `exampleCourse/questions/demo/annotated/mathNumberInput/question.html` wasn't actually a comment. I changed that and took the opportunity to find/replace to remove an unnecessary `<p>` tag.

Reformat exampleCourse documentation comments

---

packages/tsconfig/tsconfig.json

Locally, this cut the time for a `yarn turbo build --force` in half from ~8 seconds to ~4 seconds. This should help a lot on CI where we have fewer CPUs to parallelize things.

Disable lib checking in tsconfig.json

---

pages/partials/logout.ejs
pages/partials/navbar.ejs

This small change removes the conditional on showing the logout link in the navbar so that it is never disabled.
I ran into a case in development where my auth cookie was no longer valid and I noticed the error page didn't give me the logout link to easily remove the cookie. When I traced through the partials, I found I had a case for the only conditional in that partial (maybe there were originally more?), so I simplified it just to always show the link in `navbar.ejs`

fix: navbar always show logout option

---

.changeset/flat-ways-roll.md
.changeset/heavy-balloons-appear.md
.changeset/poor-drinks-change.md
graders/python/python_autograder/pl_result.py
packages/named-locks/src/index.ts
packages/opentelemetry/README.md
packages/opentelemetry/src/index.ts
packages/opentelemetry/src/metrics.ts
packages/postgres/src/default-pool.test.ts
packages/postgres/src/default-pool.ts
packages/postgres/src/pool.ts
server.js

This should allow us to better understand how our queries are performing under load. Specifically, this will give us insight into how queries are queueing.
Here's what these look line on Honeycomb. Once I finally limited my local connection pool to 2 clients, you can see that we start measuring waiting clients!

Capture Postgres pool metrics

---

.github/workflows/release.yml

A recent merge to master failed because `yarn.lock` wasn't in sync after running `changeset version` (https://github.com/changesets/action/issues/170). We now run `yarn` after `changeset version` to make any necessary changes to `yarn.lock` automatically.

Update yarn.lock after changeset versioning

---

docs/c-grader/index.md
graders/c/cgrader/cgrader.py

Extend the work in #7342 by allowing question code to determine additional rejected symbols.
Given the commit in #7342 also did not cause the image push CI to run, this PR is also intended to update the image on Docker Hub.

C Grader: add option to reject symbols in student code

---

graders/c/cgrader/check.h

This ensures ASAN calls in check.h are only used if ASAN is actually enabled. As discussed in Slack.

C Grader: fix handling of questions using Check without ASAN

---

lib/assessment.sql
lib/workspace.sql
sprocs/assessment_groups_add_member.sql
sprocs/assessment_groups_delete_group.sql
sprocs/assessment_groups_delete_member.sql
sprocs/assessment_instances_lock.sql
sprocs/courses_update_column.sql
sprocs/grading_jobs_lock.sql
sprocs/group_users_insert.sql
sprocs/instance_questions_lock.sql
sprocs/submissions_lock.sql
sprocs/variants_lock.sql

This should help reduce lock contention by allowing `page_view_logs` to insert records even when locks are held on referenced tables.
Though this is probably only necessary for `assessment`/`assessment_instance`/`variant` tables, I opted to make the change for all tables. This should be safe, as we're neither deleting a row or changing its primary key after acquiring a lock on it.
Closes https://github.com/PrairieLearnInc/sysconf/issues/870.

Use FOR NO KEY UPDATE instead of FOR UPDATE

---

packages/postgres/src/index.ts
packages/postgres/src/pool.test.ts
packages/postgres/src/test-utils.ts
tests/helperDb.js
tests/mocha-hooks.mjs
tests/sync/questionsSync.test.js

This allows us to reuse our utilities for spinning up and tearing down test databases across packages, including in `@prairielearn/postgres` itself.
Once sproc handling is moved into a shared package, I plan to introduce a package like `@prairielearn/server-test-utils` that encapsulates migrations and sproc creation as well; we can then reuse that across PrairieLearn and PrairieTest (and any other servers we end up with in the future).

Move database testing utilities into @prairielearn/postgres

---

graders/c/cgrader/cgrader.py

The current version of the C grader assumes `gcc` will create a file with extension `.i`, but that is only used for C code. If the code is C++ the extension will be `.ii`, and if the code is Objective-C the extension will be `.mi`. The fix checks the first suitable extension that exists, and fails gracefully if none of them exist.

C Grader: proper handling of preprocessor file for C++/Objective-C

---

pages/instructorAssessmentInstances/instructorAssessmentInstances.ejs

Fixes #7378. The sorting functionality was originally set when roles included a distinction between TA and instructor. The relevant function was removed in #3020, but the column still had a reference to the function. This change uses default sorting for the role.

fix: Sort assessment instances by role

---

pages/studentAssessments/studentAssessments.sql

@nwalters512 discovered that the `studentAssessments` page query had recently switched to a seq scan over `assessment_instances` for a small number of course instances. The specific problem was in the CTE: https://github.com/PrairieLearn/PrairieLearn/blob/a2fde2c64ad291eba85b692d8eaceed3c0feaf6a/pages/studentAssessments/studentAssessments.sql#L80 and even more specifically in the join condition: https://github.com/PrairieLearn/PrairieLearn/blob/a2fde2c64ad291eba85b692d8eaceed3c0feaf6a/pages/studentAssessments/studentAssessments.sql#L125-L128
To help postgres use indexes for both `assessment_instances.user_id` and `assessment_instances.group_id`, this PR uses two joins on `assessment_instances`, one for `user_id` and one for `group_id`. In testing this allowed postgres to use index scans …

Fix bad studentAssessments query plan

---

pages/instructorQuestions/instructorQuestions.ejs
pages/partials/issueBadge.ejs

Fixes #7375. The badge shows the number of open issues, but was linking to a list of all issues (including closed).

Change issue badge link to show open issues only

---

database/tables/institutions.pg
migrations/20230331212027_institutions__display_timezone__add.sql
pages/instructorEffectiveUser/instructorEffectiveUser.js

#7340 didn't account for the fact that the effective user page is also mounted to `/pl/course/...`, where we won't have access to a course instance from which we can fetch a timezone.

Define fallback timezones for effective user page

---

database/tables/job_sequences.pg
migrations/20230331223233_job_sequences__course_request_id__add_index.sql
pages/administratorCourseRequests/administratorCourseRequests.sql
pages/administratorCourses/administratorCourses.sql

This PR speeds up the CTE queries for course request jobs by ~43x and reduces memory usage from 639MB to just 1MB. By using `course_requests` as the left table (instead of `job_sequences`), we avoid a very expensive `HashAggregate` on all 392,000 `job_sequences` rows.
Before:
```
HashAggregate  (cost=25859.30..25864.85 rows=444 width=48) (actual time=4335.904..4401.829 rows=408 loops=1)
Group Key: cr.id
Batches: 77  Memory Usage: 639037kB  Disk Usage: 4592kB
->  Nested Loop Left Join  (cost=20.29..22026.90 rows=383240 width=64) (actual time=0.195..504.843 rows=392340 loops=1)
->  Hash Left Join  (cost=19.99..12176.41 rows=383240 width=48) (actual time=0.187..246.744 rows=392340 loops=1)
Hash Cond: (js.course_request_id = cr.id)
->  Seq Scan on job_sequences js  (cost=0.00..11150.40 …
```

Improve query plan for course request jobs

---

elements/pl-code/info.json
elements/pl-code/pl-code.js

We're long since used Pygments to highlight code; this script is unnecessary.

Remove references to highlight.js from pl-code

---

lib/cache.js

I broke this accidentally in #7428. TypeScript lied to me, so I didn't notice; see https://github.com/isaacs/node-lru-cache/issues/289.

Fix require of lru-cache

---

lib/cache.js
package.json
yarn.lock

Followup to #7480; the named export is more elegant than tacking a `.default` on the end. The change from https://github.com/isaacs/node-lru-cache/commit/798fef3902e4a1a9d7ba106b285394bd93476022 allows us to do this!

Use LRUCache named export from lru-cache

---

.changeset/friendly-colts-glow.md
packages/html/src/index.test.ts
packages/html/src/index.ts

I'm making use of `BigInt` values over in #7292; this will allow me to easily interpolate them into HTML templates.

Allow interpolating BigInt values in @prairielearn/html

---

package.json

The `yarn version` command run during our "Release" workflow recently started failing:
```
➤ YN0000: │ @@ -2884,9 +2884,9 @@
➤ YN0000: │    version: 0.0.0-use.local
➤ YN0000: │    resolution: "@prairielearn/migrations@workspace:packages/migrations"
➤ YN0000: │    dependencies:
➤ YN0000: │      "@prairielearn/error": ^1.0.0
➤ YN0028: │ -    "@prairielearn/named-locks": ^1.0.0
➤ YN0028: │ +    "@prairielearn/named-locks": ^1.2.0
➤ YN0000: │      "@prairielearn/postgres": ^1.2.0
➤ YN0000: │      "@prairielearn/tsconfig": "*"
➤ YN0000: │      "@types/fs-extra": ^11.0.1
➤ YN0000: │      "@types/mocha": ^10.0.1
➤ YN0000: │ @@ -2898,9 +2898,9 @@
➤ YN0000: │      typescript: ^4.9.5
➤ YN0000: │    languageName: unknown
➤ YN0000: │    linkType: soft
➤ YN0000: │  
➤ YN0028: │ …
```

Force Yarn to mutate lockfile in version script

---

database/tables/assessment_instances.pg
database/tables/last_accesses.pg
database/tables/variants.pg
lib/databaseDescribe.js
lib/databaseDescribe.sql

I discovered in #7292 that our tooling didn't support `CHECK` constraints in the descriptions it generates. This PR adds support for that. It turns out there were already some existing constraints that weren't captured yet!

Add support for CHECK constraints to database description tooling

---

package.json
yarn.lock

`s3-streamlogger` recently updated to use `@aws-sdk/client-s3` under the hood. This caused problems during a recent production deployment, as it was not able to discover which region it was operating in. This wasn't an issue with the old `aws-sdk`-based implementation, because we specifically initialized with the region we discovered in the EC2 IMDS:
https://github.com/PrairieLearn/PrairieLearn/blob/cbbfceb5552765ec1c7eafbbb6f5c9575603e03c/grader_host/lib/config.js#L69
However, the v3 SDK doesn't pull from that same place (and in fact there's seemingly no way to configure a global region), so it was failing to find the region.
I'm downgrading instead of fixing because I ultimately want to replace this with a different implementation that's more similar to what we do with workspace logs.

Downgrade s3-streamlogger

---

lib/editors.js
lib/github.js
pages/instructorFileEditor/instructorFileEditor.js
pages/shared/syncHelpers.js

This fixes a syncing issue that came up recently. If a sync failed before chunks could be generated, we'd be left with new course code on disk and the latest commit hash in the DB. However, on the next sync, we'd use that new commit hash when deciding what chunks to regenerate, which means we'd "lose" any changes that had been made in the last sync. This same kind of issue could occur if a server died in the middle of performing a sync.
By only updating the commit hash in the database _after_ chunks have been generated, we ensure that a future successful sync will include the previous changes.
This change has a potential side effect: the fact that we now don't update the hash means that the question render cache may serve state entries until a successful sync occurs. I think this is fine; …

Only update course commit hash after successful sync

---

package.json
yarn.lock

bootstrap-table 1.21.4 changed the way filters are applied in custom search functions, which broke some filter functionality in our pages. This downgrades it to the previous version until we have time to review these changes.

Downgrade bootstrap-table to 1.21.2

---

.changeset/serious-bugs-push.md
packages/html/src/index.test.ts
packages/html/src/index.ts

Previously we silently discarded booleans in `html` template strings. This allowed the use of the pattern:
```
html`${bool_value && 'some string'}`
```
which would template in `some string` if `bool_value` was true and nothing otherwise. However, it also meant that it was easy to accidentally fail to render a boolean value when we actually wanted to do it. This PR fixes this, but it does mean that we'll need to replace the pattern above with:
```
html`${bool_value ? 'some string' : ''}`
```
I personally prefer the explicit nature of this anyway.

Render booleans in html template strings

---

sync/course-db.js
sync/infofile.js
tests/chunks.test.js
tests/sync/courseDb.test.js

This is part of a broader effort to enable TypeScript strict null checks. Having these properties be potentially undefined complicates a lot of code + error handling. It's easier to just always have the array be defined but treat an empty array as the "no warnings"/"no errors" case.

Make warnings and errors non-optional on infofiles

---

.changeset/early-colts-count.md
package.json
tools/fix-workspace-versions-before-publish.mjs
tsconfig.json

Changesets unfortunately doesn't support publishing with Yarn, which means that `workspace:` version ranges aren't replaced prior to publishing:
* https://github.com/changesets/changesets/issues/432
* https://github.com/changesets/action/issues/246
This meant that packages were published to npm with literal `workspace:^` versions, which obviously broke when we tried to install them in another project.
This PR introduces a small script that will rewrite the versions for us.

Fix workspace versions before publish

---

docs/c-grader/index.md
graders/c/cgrader/cgrader.py

While this was already possible with the separation of compiler and linker, the idea here is to simplify the use of this option.

C Grader: Add option to invoke objcopy for student code

---

lib/chunks.sql

For a query that tries to delete 1000 question chunks, this PR reduces the execution time from ~18 seconds to 10 milliseconds.
Postgres was choking on the `chunks.type = cm.type` condition of the `chunks_to_delete` CTE. The execution order it took was to do that join first, and only *then* filter out rows where the type/IDs were mismatched. This resulted in essentially a cross product between the deleted questions and *all* questions, which was millions of rows. By using separate CTEs, we allow Postgres to work much more efficiently.
The only reason we were attempting to delete this many chunks on a regular basis is that we weren't *actually* deleting chunks for deleted questions/assessments/etc, meaning the number of questions we tried to delete each sync just increased over time. This …

Optimize chunk deletion query

---

pages/instructorQuestionPreview/instructorQuestionPreview.js
pages/shared/studentInstanceQuestion.js

This ensures that these errors aren't reported to Sentry.

Use 400 HTTP status for missing issue description

---

database/enums/enum_log_level.pg
migrations/20230421225700_enum_log_level__drop.sql

This type has long been unused. I lifted this out of #7333 since it wasn't really related to the changes there.

Drop unused enum_log_level type

---

lib/workspace.js
lib/workspace.sql

No code is reading this column anymore, so we can avoid writing to it.

Don't update workspaces.homedir_location column

---

pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ejs
sync/fromDisk/courseInfo.js
sync/fromDisk/courseInfo.sql

This is a remnant from an implementation of external grading that never shipped. We'll remove the column entirely in the future once we've been able to deploy this PR.

Stop reading and writing pl_courses.grading_queue

---

sprocs/instance_questions_update_score.sql

Fixes #7556. In essence it ensures that, if there is more than one variant, then a variant with submission is chosen.

Fix: manual feedback of questions with variants without submission

---

lib/editors.js
pages/shared/syncHelpers.js

If the course object passed to `getOrUpdateCourseCommitHash` already has a `hash` property, it would be returned immediately. However, we don't want that behavior in these two cases: we always want to force a new hash to be computed and persisted to the database.

Use correct function to update course commit hash

---

packages/migrations/package.json
packages/postgres-tools/package.json
packages/postgres/package.json
packages/workspace-utils/package.json
yarn.lock

This requires slightly less fiddling with exactly which extensions we want to copy - it'll just copy everything that isn't already being transformed by TypeScript.
I'm once again wishing `tsc --copy-files` was a thing! Alas, https://github.com/microsoft/TypeScript/issues/30835.

Use typescript-cp instead of copyfiles

---

.changeset/clever-insects-bow.md
packages/postgres/package.json
yarn.lock

I forgot to remove these in #7543. They were left over from a previous iteration when I put these commands inside the `@prairielearn/postgres` package instead of the separate `@prairielearn/postgres-tools` package where they ended up.

Remove unused commands and dependencies from postgres package

---

lib/assets.js
tests/assets.test.js

Once we move the PrairieLearn code to `apps/prairielearn`, we won't be able to _necessarily_ rely on serving `node_modules` assets from exactly one of `node_modules` and `apps/prairielearn/node_modules` - Yarn could in theory place dependencies in either directory (though it will generally host them to the root `node_modules` directory).
This PR uses `require.resolve` to locate the correct version to serve. This is conceptually similar to what we used to do before #6330, except it's robust to the issue that caused us to change this in the first place.
Note that I'll be updating `app.use('/cacheable_node_modules/:cachebuster', ...)` in `server.js` in the PR that actually moves PrairieLearn. We'll need to serve from both `node_modules` directories to handle all cases.

Don't rely on fixed node_modules path for assets

---

packages/postgres-tools/package.json
yarn.lock

I discovered this while working on the move to `apps/prairielearn` in another branch.

Add missing yargs types to postgres-tools package

---

lib/assets.js
lib/code-caller/code-caller-native.js
lib/config.js
lib/editors.js
lib/file-paths.js
lib/paths.js
pages/administratorQueries/administratorQueries.js
pages/administratorQuery/administratorQuery.js
pages/elementFiles/elementFiles.js
question-servers/freeform.js
server.js
tests/assets.test.js
tests/chunks.test.js
tests/courseElementExtension.test.js
tests/exampleCourseQuestions.test.js
tests/fileEditor.test.js
tests/gradingMethods.test.js
tests/groupGenerateAndDelete.test.js
tests/groupScoreAndSync.test.js
tests/groupStudent.test.js
tests/helperDb.js
tests/helperServer.js
tests/manualGrading.test.js

This PR introduces a number of constants from which we can construct paths instead of sprinkling `path.resolve(__dirname, ...)` all over the project. This will minimize the number of changes we have to make when we move the PrairieLearn code to the `apps/prairielearn` directory.

Use path constants to construct paths

---

packages/postgres/src/pool.test.ts
packages/postgres/src/pool.ts

This PR fixes a pub where a Postgres cursor+client would remain indefinitely it a client did not fully consume all of the cursor's rows. This lead to queries that remained active for multiple days until they were manually killed.
Closes https://github.com/PrairieLearnInc/sysconf/issues/983.

Fix query cursor stream closing

---

middlewares/staticNodeModules.js
server.js

Lifting this out of #7640. See the JSDoc comment on the middleware for more details. This abstraction exists so we don't have to repeat each `express.static` middleware twice for each `node_modules` directory.

Add middleware for serving static files from node_modules

---

lib/config.js
server.js

Lifting this out of #7640. This is primarily for backwards compatibility so that we don't break people's dev workflows.

Load config files from both app and repository roots

---

.eslintrc.js

We don't have any files in `apps/prairielearn/assets/scripts` on master, so this wasn't caught until Jonatan pulled the recent changes into his manual grading rubrics branch.

Update path to assets scripts in .eslintrc.js

---

apps/prairielearn/src/lib/server-jobs.js
apps/prairielearn/src/lib/server-jobs.sql

We long since stopped doing anything with these columns; we use the unified `output` column instead. This PR removes all remaining code that writes to these columns; we can then remove the columns themselves once this has been deployed.
I'm doing this ahead of #6475 to reduce the number of things I have to account for in that PR.

Don't store server job stdout/stderr separately

---

.changeset/rude-books-suffer.md
packages/postgres-tools/src/diff.ts

Before:
After:
The key change is that this shows context instead of just added/removed lines. I could have used the patch format directly, but this is a bit more concise and skips over info that (IMO) is unnecessary, like file names (which may not even be defined for a diff) and line numbers.

Improve formatting of postgres-tools diff

---

apps/prairielearn/src/server.js

This is unused in production. @trombonekenny points out that this could be useful in the future if we want to serve files that aren't part of PrairieLearn itself, but we really want to avoid that in general.

Remove localRootFilesDir handling from server.js

---

apps/prairielearn/src/tests/mocha-hooks.mjs
apps/prairielearn/src/tests/sprocs/users_select_or_insert.test.js
apps/prairielearn/src/tests/sync/assessmentsSync.test.js
apps/prairielearn/src/tests/sync/courseInstancesSync.test.js
apps/prairielearn/src/tests/sync/questionsSync.test.js
apps/prairielearn/src/tests/sync/tagsTopicsSync.test.js

This removes the `chai-as-promised` boilerplate from all tests in favor of declaring it once in a Mocha root hook.

Make chai-as-promised available in all tests

---

graders/java/JUnitAutograder.java

Resolves #7718. In essence, if an exception happens in a test factory (including value sources and other methods that generate dynamic tests), the question is tagged as ungradable. Instructors should be able to identify the proper error in the grading job log.
For a technical explanation: the `executionFinished` listener method is called when any test or test container finishes executing. Typically for non-test (i.e., containers) the result would not affect the tests themselves and would not cause any changes in the autograder results, but in this case the container itself fails to generate dynamic tests. Since presumably the test containers are based on instructor code, not student code, the details of the error are shown only in the grading log, so that the instructor can check it while …

Java grader: better handling of exceptions in test factories

---

.github/workflows/main.yml
Makefile
docker/typecheck_tools.sh
package.json
tsconfig.json
yarn.lock

The top-level `tsconfig.json` file referenced paths that no longer exist. This PR removes them. It also re-adds CI type checking for the `tools/` directory, which was inadvertently lost during the recent repo reorganization.
Closes #7720.

Simplify top-level tsconfig.json

---

apps/prairielearn/src/pages/workspace/workspace.html.js

Thanks @jonatanschroeder for pointing this out. This package is imported into `workspaceClient.ts`, so it doesn't need to be loaded independently.

Remove unneeded socket.io-client script tag

---

apps/prairielearn/.mocharc.js
apps/prairielearn/src/tests/mocha-env.mjs
apps/prairielearn/src/tsconfig.json
apps/prairielearn/tsconfig.json

This keeps `ts-node` happy when running things like `yarn mocha src/tests/assets.test.js`.

Improve ts-node config for Mocha

---

apps/grader-host/package.json
apps/prairielearn/package.json
apps/workspace-host/package.json
packages/migrations/package.json
packages/postgres-tools/package.json
packages/workspace-utils/package.json
yarn.lock

This should get rid of some Yarn warnings printed during package installation:
```
>>> ➤ YN0060: │ @prairielearn/grader-host@workspace:apps/grader-host provides typescript (p3eebb) with version 5.0.4, which doesn't satisfy what typescript-cp requests
>>> ➤ YN0060: │ @prairielearn/migrations@workspace:packages/migrations provides typescript (pe0664) with version 5.0.4, which doesn't satisfy what typescript-cp requests
>>> ➤ YN0060: │ @prairielearn/postgres-tools@workspace:packages/postgres-tools provides typescript (p295c6) with version 5.0.4, which doesn't satisfy what typescript-cp requests
>>> ➤ YN0060: │ @prairielearn/prairielearn@workspace:apps/prairielearn provides typescript (p2eb12) with version 5.0.4, which doesn't satisfy what typescript-cp requests
>>> ➤ YN0060: │ …
```

Install latest version of typescript-cp

---

Makefile

This is necessary for deployments on machines with limited memory.

Add build-sequential target to Makefile

---

apps/prairielearn/package.json
apps/prairielearn/src/tests/mocha-env.mjs
apps/prairielearn/src/tsconfig.json

I accidentally broke `make dev`/`yarn dev` in #7723. This should get everything back into a good working state. I tested the following commands and they all work!
- `make dev` from repo root
- `yarn dev` from app root
- `yarn test` from app root
- `yarn mocha src/tests/assets.test.js` from app root

Fix ts-node config for dev mode

---

apps/grader-host/src/index.js
apps/grader-host/src/lib/pullImages.js
apps/prairielearn/src/lib/code-caller/code-caller-container.js
apps/prairielearn/src/pages/shared/syncHelpers.js
apps/workspace-host/src/interface.js
packages/docker-utils/src/index.ts

This removes an unused parameter from the `setupDockerAuth` function.
I also changed a few usages of `setupDockerAuth` to `setupDockerAuthAsync`.

Clean up setupDockerAuth function

---

apps/prairielearn/assets/scripts/instructorFileEditorClient.js
apps/prairielearn/src/lib/assets.ts
apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.ejs
apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.js
apps/prairielearn/src/server.js

When testing this after deploying to our staging environment, I discovered that our new compilation process (reasonably) doesn't play well with the pattern used here: serving a client-side script located in the `pages` directory. Now that we have support for client-side code bundles, I can use that instead.
I deliberately did not do any work to convert this to TypeScript or actually include ace or `crypto-js` in the bundle; I'm doing the least amount of work possible now to unblock a production deployment.

Fix instructor file editor client code

---

apps/prairielearn/src/cron/index.js

This will give us additional visibility into when cron jobs aren't behaving as expected.

Report cron errors to Sentry

---

apps/workspace-host/package.json
yarn.lock

The remaining usage of `aws-sdk` is via `winston-aws-cloudwatch`, which I intend to replace with logging to CloudWatch via the CloudWatch agent on our hosts.

Remove aws-sdk dependency from workspace-host

---

apps/prairielearn/src/pages/instructorGradingJob/instructorGradingJob.js

TypeScript treats the last (callback) argument to non-promise `pipeline` as optional, but the observable runtime behavior is that it is actually required! That's why this didn't get caught until I deployed to staging.

Fix instructor grading job pipelining

---

packages/migrations/src/batched-migrations/batched-migrations-runner.ts

If we can't acquire a lock, we consider that to be a case where there's nothing to do; this function is already designed to return `null` if there isn't work to be done.

Use tryWithLock when starting batched migrations

---

apps/prairielearn/src/tests/helperServer.js
apps/prairielearn/src/tests/newsItems.test.js

I'm hoping that this will reduce the recent flakiness we've seen in some tests that looks like the following:
```
@prairielearn/prairielearn:test:        "after all" hook: shut down testing server in "News items":
@prairielearn/prairielearn:test:      Uncaught Error: endJob(): no such estimator: request
@prairielearn/prairielearn:test:       at Object.endJob (src/lib/load.js:151:44)
@prairielearn/prairielearn:test:       at /PrairieLearn/apps/prairielearn/src/server.js:432:12
@prairielearn/prairielearn:test:       at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
@prairielearn/prairielearn:test:       at listener (/PrairieLearn/node_modules/on-finished/index.js:170:15)
@prairielearn/prairielearn:test:       at onFinish (/PrairieLearn/node_modules/on-finished/index.js:101:5) …
```

Shut down load estimators after server during tests

---

apps/prairielearn/src/migrations/20230526124740_courses__manual_grading_visible__drop.sql
database/tables/pl_courses.pg

Resolves #7714. Given #6271 is deployed and #7507 removes the need for column-based feature flags, the column is no longer needed.

Drop legacy manual grading feature flag column

---

apps/prairielearn/package.json
apps/prairielearn/src/lib/code-caller/index.js
yarn.lock

This PR makes two key changes to shave ~3 seconds off application booting in development:
- Uses `swc` to transpile TypeScript instead of `tsc`. See https://typestrong.org/ts-node/docs/swc/. I can't wait for https://tc39.es/proposal-type-annotations/ to become accepted and for Node to implement it so we don't have to pay any tax at all for using TypeScript!
- Don't wait for the code callers to boot up in dev mode, where we don't particularly care if the code callers are ready by the time the application starts accepting requests.
After these changes, on my machine, it takes ~3.4 seconds to completely boot up the server in watch mode, down from ~6.2.

Speed up watch restarts

---

apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/gradingPanel.ejs
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/gradingPointsSection.ejs
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/rubricInputSection.ejs
apps/prairielearn/src/pages/partials/submissionStatus.ejs
apps/prairielearn/src/tests/manualGrading.test.js

Based on issue mentioned on Slack. Resolves two issues:
* Recent rubrics update broke the way manual input of points (particularly percentage) is handled, since the function relies on `this`, for which the function is no longer bound to. For safety and clarity this was replaced with an explicit argument.
* Resolves #7791, i.e., properly handles manual grading cases when the question is worth zero in total (i.e., no manual or auto points).

Fix use of percentage-based input in manual grading

---

docs/elements.md

fix: Added missing link for `pl-template` example in docs

---

apps/prairielearn/src/lib/code-caller/code-caller-container.js
apps/workspace-host/src/interface.js

Fixes an issue [reported on Slack](https://prairielearn.slack.com/archives/C266KEH9A/p1685241582002019) where workspace images couldn't be pulled in local development. This was a regression introduced by https://github.com/PrairieLearn/PrairieLearn/pull/7731.

Only perform ECR auth if cache registry is configured

---

docs/python-grader/index.md

This was just straight up incorrect. Thankfully, all our other examples use the correct class name.

Fix Python grader docs

---

.changeset/fluffy-bottles-drive.md
apps/prairielearn/src/migrations/20221122001508_time_series__date__add_index.sql
apps/prairielearn/src/migrations/20230309222017_workspace_logs__workspace_id__create_index.sql
apps/prairielearn/src/migrations/20230331223233_job_sequences__course_request_id__add_index.sql
packages/migrations/README.md
packages/migrations/src/load-migrations.test.ts
packages/migrations/src/load-migrations.ts
packages/migrations/src/migrations/migrations.ts

Now that we're running on Postgres 14, we're revisiting https://github.com/PrairieLearn/PrairieLearn/issues/5530. Virtually all of our migrations can now run successfully inside a transaction, with the exception of `CREATE INDEX CONCURRENTLY`. To handle that case, a special annotation comment (`-- prairielearn:migrations NO TRANSACTION`) can be added to migration files to run the migration outside of a transaction.

Run SQL migrations inside transactions

---

apps/prairielearn/src/middlewares/logResponse.js

If an HTTP client (browser, test, API, etc.) reads from a URL but closes the stream before it's completely sent, the log response is not being triggered. This is because the `finish` event only triggers when the stream is completely sent. This often happens for responses that cause a redirection (e.g., most POST responses), since in that case the client only needs the header to identify the next location. This PR changes the logging to happen on the `close` event, which is triggered even when the stream is closed.
I have no means to test how this affects production environment and sentry logs.

Trigger response log on stream close

---

apps/prairielearn/package.json
apps/prairielearn/src/lib/cache.ts
yarn.lock

This is a deliberately low-effort conversion; I'm doing a refactor of this file soon in another PR. I just want to get the `.js` -> `.ts` change done such that Git will track the file contents between them.

Convert lib/cache to TypeScript

---

apps/prairielearn/src/server.js

Mirroring the corresponding change to PrairieTest. In practice, `--migrate-and-exit` is used instead.

Remove unused --exit flag

---

apps/prairielearn/src/pages/courseSyncs/courseSyncs.js

I'm guessing that this was a change caused by the upgrade to v3 of the AWS SDK in #7735 but I couldn't find anything in [the docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ecr/classes/ecr.html#describeimages.describeimages-2) about the format of `err`.
This fixes the problem reported by Abdu where visiting the course "Sync" page gave an error like:
```
The repository with name '<IMAGE_NAME>' does not exist in the registry with id '<REGISTRY_ID>'
```
I logged the error that `describedImages()` returns and it looks like:
```
{"name":"RepositoryNotFoundException","$fault":"client","$metadata":{"httpStatusCode":400,"requestId":"<REQUEST_UUID>","attempts":1,"totalRetryDelay":0},"__type":"RepositoryNotFoundException"}
```
I reproduced the error in staging and …

Fix detection of missing docker images on courseSyncs page

---

images/plbase/Dockerfile

Changing `.github/workflows/images.yml` in #7931 didn't actually trigger a rebuild of `prairielearn/plbase`. This PR makes a few trivial changes to force the image to rebuild.

Force rebuild of plbase image

---

apps/prairielearn/src/lib/features/index.ts
apps/prairielearn/src/lib/features/manager.ts
apps/prairielearn/src/lib/features/middleware.ts
apps/prairielearn/src/server.js

I'm doing this so that I can easily test #7128 in production. Specifically, I want to be able to quickly flip this feature on and off in arbitrary courses so that I can compare performance and results.
I borrowed this idea from https://github.com/jnunemaker/flipper/issues/283#issuecomment-327898906. However, I didn't implement all the pattern-matching stuff that that example used. It's just simple on/off for specific flags.

Allow admins to override feature flags on a per-request basis

---

exampleCourse/questions/template/numberInput/question.html
exampleCourse/questions/template/numberInput/server.py

While working on `pl-number-input` and using the template question `template/numberInput` for testing, I found a small bug where the correct answer wasn't showing up or used for grading for the question. This is caused by a minor typo in the question code, and this PR fixes the typo in the question code.

Fix correct answer not showing up in the question template/numberInput

---

apps/prairielearn/src/pages/instructorAssessmentGroups/instructorAssessmentGroups.ejs
apps/prairielearn/src/pages/instructorAssessmentGroups/instructorAssessmentGroups.js
apps/prairielearn/src/pages/instructorAssessmentGroups/instructorAssessmentGroups.sql

This was a regression introduced in #7907. Our query ended up with `uid_list = '{NULL}'` for empty groups, which we didn't handle correctly.

Fix handling of empty groups

---

apps/prairielearn/src/lib/question.sql

This was introduced by #7272. As far as I can tell, the broken version resulting in joining to every row of `pl_courses`, which is obviously wrong.

Fix select_submission_info query

---

apps/prairielearn/src/lib/db-types.ts

I considered marking the columns themselves as `NOT NULL`, but in this case I think it's actually reasonable for them to be nullable - that just indicates a lack of warnings!

Mark sync_warnings as nullable

---

apps/prairielearn/src/migrations/20230609223157_group_users__remove_invalid_rows.sql

Resolves #7924.
I used the following query to estimate the impact of this migration against our US production data:
```sql
SELECT
*
FROM
group_users AS gu
JOIN groups AS g ON (gu.group_id = g.id)
WHERE
g.deleted_at IS NOT NULL;
```
This revealed ~19000 rows!

Add migration to remove invalid group_users

---

apps/prairielearn/src/migrations/20230612162858_feature_grants__unique_nulls_not_distinct.sql
database/tables/feature_grants.pg

This ensures that we don't end up with duplicate rows for the same institution/course/instance/user combination where one or more of those entities is null.

Use NULLS NOT DISTINCT for feature_grants unique index

---

docs/python-grader/sphinx-docs.md
graders/python/python_autograder/code_feedback.py

This broke when we updated Pandas to v2 in #7813; this change was missed when reviewing the changelog.
Related: https://github.com/pandas-dev/pandas/pull/30745

Use supported Pandas testing utilities

---

.changeset/plenty-dodos-return.md
packages/browser-utils/package.json

This change is necessary because `tsc` does not view `index.d.ts` as "adjacent" to `index.mjs` and thus can't automatically resolve the types.
Once PL is also using ESM, we can stop dual-publishing to CJS and ESM, which will simplify things a bit.

Expose types from browser-utils package

---

apps/prairielearn/src/lib/chunks.ts

See inline comment for a description of this change.
To test this change, I added the following lines to `apps/prairielearn/src/tests/chunks.test.ts`:
```ts
describe.only('example course syncing', () => {
it('works', async () => {
const courseData = await courseDB.loadFullCourse(EXAMPLE_COURSE_PATH);
const changedFiles = await chunksLib.identifyChangedFiles(
EXAMPLE_COURSE_PATH,
'92e03fb6f',
'65aae01ac'
);
console.log('changedFiles', changedFiles);
const changedChunks = chunksLib.identifyChunksFromChangedFiles(changedFiles, courseData);
console.log('changedChunks', changedChunks);
});
});
```
Before this PR, no changes were reported:
```ts
changedFiles [
'.changeset/proud-moose-glow.md',
'.github/workflows/images.yml',
'.gitignore',
'apps/prairielearn/assets/scripts/mathjax.js', …
```

Fix syncing of course that is not at course repo root

---

apps/prairielearn/src/pages/courseSyncs/courseSyncs.ejs
apps/prairielearn/src/pages/courseSyncs/courseSyncs.js

If someone accidentally used an invalid image name in one of their questions, the sync page would fail to load because ECR would error out (see #7980). This PR fixes that by handling the error appropriately and displaying an "Invalid image name" badge:
I also tweaked the table itself:
- The empty state now does not display the table headers.
- If a cache image registry is not configured, there is no message displayed communicating that (it's never clear to the end user what a "local image repository" is).
Closes #7980.

Improve course image syncing

---

apps/prairielearn/python/zygote.py

The following error was reported on Slack:
I don't know why exactly this error occured, or why it didn't occur consistently. However, it's reproducible on multiple environments. See inline comment for more details. This is similar to an issue we've faced before with matplotlib. The new fix should be generic enough to handle both that and the fontconfig warning.

Fix graphviz fontconfig warnings

---

docker/start_postgres.sh

the postgres tools expect PG not PG_ in the names

Fix spelling of PGHOST environment variable

---

images/plbase/plbase-install.sh

As discussed on Slack. The `texlive-type1cm` is required for matplotlib to work. It likely used to be a dependency of a package previously used in Amazon Linux 2, but the switch to Amazon Linux 2023 in #7363 caused this package to no longer be installed by default. This caused dynamic images created using matplotlib to fail in some cases, e.g., in the example course question `gallery/includeFigure/complex`.

Add missing Latex package required by matplotlib

---

workspaces/xtermjs/src/index.html

The element with id `terminal` was recently changed from a `div` to a `main` for accessibility reasons, but the CSS wasn't updated to account for that change. This PR changes the CSS selector to just be `#terminal`, which should be resilient to future changes.

Fix xterm workspace CSS

---

apps/prairielearn/elements/pl-order-blocks/dag_checker.py
apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.py
apps/prairielearn/python/prairielearn.py
pyproject.toml

originally disabled in #5292
In addition to type checking and function annotations, a few of the option attributes were converted to Enums for better type safety.

pl-order-blocks: restore typechecking

---

apps/prairielearn/src/sync/fromDisk/topics.js

Closes #7952. In the long-term, we should consider the inlined TODO and require that all topics (even explicit ones) are not the empty string, or don't `.trim()` to the empty string. However, that would be backwards-incompatible with several courses, so I'm avoiding that disruption for now.

Allow empty implicit question topics

---

docs/installingNative.md

Someday, we can consider updating `make python-deps` to be smart enough to do this automatically. For now, we'll at least have this permanently documented somewhere where I'll remember to check for it in the future.

Document how to install pygraphviz on macOS

---

.github/dependabot.yml

Grouped updated for Dependabot are now in public beta (https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-1623832701) 🎉 
I'm turning it on for `@aws-sdk/*` and `@opentelemetry/*` packages, which generally need to all be upgraded at the same time.

Enable grouped dependabot upgrades

---

apps/prairielearn/elements/pl-threejs/pl-threejs.py

This bug was introduced in #5893. `data["answers-names"]` is not defined during the `render()` phase.

Move pl-threejs answers-names check to prepare phase

---

images/plbase/python-requirements.txt

Bucknell University's ECE Department wishes to include schemdraw v0.17 to PrairieLearn. Thank you!

Add schemdraw Python library

---

apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.py
docs/elements.md
exampleCourse/questions/element/multipleChoice/question.html

See title, resolves #1228 and #6350 for the multiple choice element. Uses code from https://github.com/PrairieLearn/PrairieLearn/pull/6119 (with attribution) for the allow blank logic.
Screenshots of allow blank behavior:
Blank submission:
Submission panel:

feat: pl-multiple-choice duplicate checking and allow blank.

---

workspaces/desktop/server/package.json
workspaces/desktop/server/yarn.lock

We use the `http-proxy` package, not `node-http-proxy`. Confusingly, the repo for the former is https://github.com/http-party/node-http-proxy, which is probably how `node-http-proxy` got installed in the first place.

Remove unused package from desktop workspace image

---

apps/prairielearn/src/server.js

Closes #832. This will help us tie requests to logs, Sentry events, etc.

Set X-Response-ID header for all requests

---

apps/prairielearn/package.json
apps/prairielearn/src/lib/config.js
apps/prairielearn/src/server.js
yarn.lock

https://github.com/grafana/pyroscope-nodejs/issues/28 means we haven't been able to use this in production. It's a shame, as we'd love to be using continuous profiling!

Remove pyroscope

---

apps/prairielearn/src/lib/chunks.ts

Ass discussed in office hours today. If a large number of files changed, syncing would fail with the following error:
```
RangeError: stdout maxBuffer length exceeded
at new NodeError (node:internal/errors:387:5)
at Socket.onChildStdout (node:child_process:470:14)
at Socket.emit (node:events: 513:28) at Socket.emit (node: domain: 489:12)
at addChunk (node: internal/streams/readable: 315:12)
at readableAddChunk (node: internal/streams/readable:285:11)
at Socket. Readable.push (node: internal/streams/readable:228:10) at Pipe.onStreamRead (node: internal/stream_base_commons: 190:23) at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
```
See https://us.prairielearn.com/pl/course/2691/jobSequence/443882 for one such failing job.

Fix chunk generation for large diffs

---

apps/prairielearn/python/python_helper_sympy.py
apps/prairielearn/python/python_helper_sympy_test.py
docs/elements.md

See title. Minor style changes to symbolic input backend code and docs typo fixes.
EDIT: After playing with this more, figured out a way to simplify the symbolic input parser use fewer dangerous function calls.

refactor: Simplify symbolic input parsing

---

yarn.lock

Pulls in the changes from https://github.com/elastic/require-in-the-middle/pull/76, which should slightly improve application startup times.

Upgrade to latest require-in-the-middle

---

apps/prairielearn/src/pages/shared/syncHelpers.js
apps/prairielearn/src/sync/syncFromDisk.js

#8111 accidentally broke syncing: our named locks are not reentrant, so the inner call to `syncDiskToSqlAsync` would fail because this would try to acquire a lock that had already been acquired.

Fix course sync locks

---

docs/extra.css
docs/requirements.txt
mkdocs.yml

Mkdocs does not allow indented code blocks by default in markdown (unlike GitHub markdown, which does allow this). See below for an example of bad rendering in our current docs due to this. This PR adds the [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) extension to fix this, as recommended [here](https://github.com/squidfunk/mkdocs-material/issues/2639). I checked the rendering locally and it looks fine (see below), although it does add an extra box around each code block. An alternative approach would be to dedent all the code blocks, as we do on other pages such as https://github.com/PrairieLearn/PrairieLearn/blob/b22e2039732aa67f02dc5d4cc258e2551a2e7c5d/docs/installingLocal.md?plain=1#L7-L11
What does everyone think about dedenting versus …

docs: Allow indented code blocks

---

apps/prairielearn/src/lib/authn.js
apps/prairielearn/src/lib/cookie.ts
apps/prairielearn/src/middlewares/authzWorkspaceCookieSet.js
apps/prairielearn/src/pages/authCallbackLti/authCallbackLti.js
apps/prairielearn/src/pages/authPassword/authPassword.js

Unlike other browsers, Safari does not persist `Secure` cookies on localhost. This means that changes like #8198 (and in fact any feature that uses cookies) won't work on Safari when developing locally.
This fix maintains the property that cookies will *always* be marked as secure in production, but makes an exception for development environments where HTTP is used. If HTTPS is used in development, the cookie will still be marked `Secure`.

Fix localhost cookies for Safari

---

apps/prairielearn/src/lib/authn.js
apps/prairielearn/src/lib/config.js
apps/prairielearn/src/middlewares/authn.js
apps/prairielearn/src/middlewares/authzCourseOrInstance.js
apps/prairielearn/src/middlewares/clearCookies.js
apps/prairielearn/src/middlewares/date.js
apps/prairielearn/src/pages/authLogout/authLogout.js
docs/running-in-production/authentication.md

As discussed on #8198.
This PR aims to maintain existing devMode behavior as much as possible. If someone opens PrairieLearn for the first time in their browser, we'll automatically authenticate them as `config.authUid` and friends. The only change is when the user clicks "Log out". In this case, we clear the `pl_authn` cookie and set a special `pl_disable_auto_authn` cookie. This prevents the automatic authentication behavior and allows the user to experience the site as a logged-out user. If they visit the login page, they can use the "bypass" auth option to set the cookie to what's configured in `config.authUid` (see `pages/authLoginDev`).
This will all become much more useful in #8198, where the login page will allow authenticating as arbitrary users in dev mode.
This is core auth …

Remove authType config

---

apps/prairielearn/src/middlewares/authn.js
apps/prairielearn/src/pages/authLogin/authLogin.html.ts
apps/prairielearn/src/pages/authLogin/authLogin.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.js

This supports a workflow where devs can authenticate as multiple users in multiple browsers in development mode. For instance, one could be a global admin in one browser, an instructor in another, and a student in an incognito window. This should make it easier to test complex interactions/states.
I believe this can close #2428.

Allow authenticating as arbitrary users in dev mode

---

apps/prairielearn/elements/pl-variable-output/pl-variable-output.mustache

By only rendering the tab contents for tabs that will actually be shown, we can save CPU cycles - around 100ms in my testing of a question that only showed Python and Sympy!

Optimize rendering of pl-variable-output element

---

apps/prairielearn/python/check_data.py
apps/prairielearn/src/tests/exampleCourseQuestions.test.js

https://github.com/PrairieLearn/PrairieLearn/pull/5893 broke the changes introduced in https://github.com/PrairieLearn/PrairieLearn/pull/7128. Technically, the former landed first, so I guess it's my fault for not testing thoroughly before merging!
This PR fixes things up and adds some tests to ensure this doesn't break again.

Fix in-worker question processing and add tests

---

.gitignore
workspaces/xtermjs/src/package.json
workspaces/xtermjs/src/yarn.lock

Some dependencies were causing errors on rebuild (see https://github.com/PrairieLearn/PrairieLearn/actions/runs/5801988527/job/15727442552). Tested locally and still works as expected.

Update dependencies in xtermjs workspace

---

apps/prairielearn/src/sprocs/sync_assessment_modules.sql
apps/prairielearn/src/sprocs/sync_assessments.sql
apps/prairielearn/src/tests/sync/assessmentModulesSync.test.js

The syncing code previously assumed that a course would always have an `assessment_modules` row with `number = 0`. However, if an instructor explicitly added an assessment module named "Default", that row would have a non-zero `number`.
This PR changes the assessment syncing code to instead look for some row with `name = 'Default'`, which is guaranteed to have been created by the assessment module syncing code.
Fixes #8344.

Sync explicitly-created default assessment module

---

apps/prairielearn/assets/scripts/lib/confirmOnUnload.ts

It seems that new versions of Chrome/Edge don't support returning an empty string from a `beforeunload` handler. On top of that, there are two parallel changes being made to Chrome:
- `beforeunload` will support `event.preventDefault()` like all other browsers: https://bugs.chromium.org/p/chromium/issues/detail?id=866818.
- Note that this landed and was then reverted, but it looks like they'll be turning it back on in Chrome 117.
- `beforeunload` will soon *explicitly* no longer support returning an empty string: https://bugs.chromium.org/p/chromium/issues/detail?id=1434509&q=beforeunload&can=2&sort=-modified
- The bug is still listed as open, but I'm wondering if they actually shipped this and hence we're seeing the behavior that we're seeing.
This PR aims to cover all our bases: it uses …

Fix beforeunload handler for Chrome and Edge

---

apps/prairielearn/src/ee/lib/billing/stripe.ts
apps/prairielearn/src/ee/pages/studentCourseInstanceUpgrade/studentCourseInstanceUpgrade.html.ts
apps/prairielearn/src/ee/webhooks/stripe/index.ts
apps/prairielearn/src/lib/cache.ts

This PR improves our Stripe webhook handling by flushing the product cache when a product or one of its prices changes.

Refine Stripe webhooks

---

apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts
apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.sql
apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.ts

Makes a few changes to the feature grant editor:
- `<select>` options are now sorted alphabetically.
- `<select>` options include both short/long names.
- The Zod schema now correctly handles empty strings.

Improve feature grant editor

---

apps/prairielearn/src/pages/partials/navbar.ejs

If something errors before the `flash` middleware runs, `res.locals.flash` will be undefined and we'll error when rendering the error page (ironic!). This fixes that.

Fix flash messages on error page

---

apps/prairielearn/elements/pl-dataframe/pl-dataframe.py

The example question `element/dataframe` was giving a deprecation warning:
```
/PrairieLearn/apps/prairielearn/elements/pl-dataframe/pl-dataframe.py:60: FutureWarning: Index.is_integer is deprecated. Use pandas.api.types.is_integer_dtype instead.
```
Since the warning was given in the output, it caused an issue to be raised. This code gets rid of the warning.

Replace deprecated pandas function in pl-dataframe

---

apps/prairielearn/src/question-servers/calculation-inprocess.js
apps/prairielearn/src/question-servers/calculation-worker.js

We were previously getting false positives with the `parallel-run` execution mode for v2 questions: the in-process variant would have `feedback: undefined`, but the subprocess one would be missing the `feedback` property entirely since `undefined` can't survive the round trip through JSON serialization.
We now normalize `feedback` to `null` so that it matches in all cases.

Normalize v2 question feedback to null

---

apps/prairielearn/src/lib/editors.js

This was a regression introduced by #7943. Type checking didn't catch the fact that we were trying to iterate over a non-awaited Promise because the types for `async.each` apparently aren't strict enough.

Fix file editors that create new items

---

packages/bind-mount/addon.cc

This first argument has to correspond to the length of the second argument 🤦

Fix bind mount native addon

---

apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts
apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.sql

This PR includes a few more improvements to the admin feature management pages:
- Deleted courses and course instances aren't shown as options in the `<select>` tags
- Feature grants are sorted more naturally (by human-readable name instead of ID)
- Feature grants display courses in our more standard `CS 101: Long Name Nere` instead of `Long Name Here (CS 101)`

Improve administrator feature management

---

apps/prairielearn/src/lib/cache.ts
apps/prairielearn/src/lib/config.js
apps/prairielearn/src/question-servers/freeform.js

This will ensure that Redis can make intelligent choices about when to evict values.

Make cache TTL mandatory

---

apps/prairielearn/src/server.js

This was not yet a meaningful vulnerability since the only thing we currently use sessions for is storing flash messages, and flash messages themselves aren't sensitive. Correctly stripping this cookie will be important once we start using the session for more interesting things.

Remove session ID from workspace proxied requests

---

apps/prairielearn/package.json
apps/workspace-host/package.json
yarn.lock

The `redis-adapter` package lists `socket.io-adapter` as a peer dependency. Up to this point PL had `socket.io-adapter` indirectly as a dependency of `socket.io`, but this is not properly interpreted by yarn, causing a warning every time a yarn command is issued (e.g., via `make deps`). While the warning can be safely ignored, in multiple occasions (see https://github.com/PrairieLearn/PrairieLearn/discussions/8142#discussioncomment-6642690 for an example, plus questions on Slack) new devs have been confused by this message.
This PR adds `socket.io-adapter` as an explicit dependency to avoid this particular warning. This is not expected to change the behaviour of any part of PL, other than to remove that warning when running yarn.

Add socket.io-adapter dependency explicitly

---

apps/prairielearn/src/server.js

As far as I can tell, `studentAssessmentAccess` only does anything useful in the context of an assessment (or assessment instance).
@trombonekenny I know you haven't touched SEB code in a long time, but it looks like this was added to these routes as part of that work. It'd be helpful if you could confirm that this middleware is in fact unnecessary for these routes.

Remove useless studentAssessmentAccess middleware

---

apps/prairielearn/src/migrations/20230830221243_course_instance_access_rules__institution__drop_default.sql
database/tables/course_instance_access_rules.pg

This default hasn't mattered for a long time. We always explicitly default the institution to `null` when syncing access rules:
https://github.com/PrairieLearn/PrairieLearn/blob/9c35a890518d54b7958f7ea4e04a3781e43c92a4/apps/prairielearn/src/sync/fromDisk/courseInstances.js#L25

Drop default for course_instance_access_rules.institution

---

apps/prairielearn/src/question-servers/calculation-inprocess.js
apps/prairielearn/src/question-servers/calculation-worker.js
apps/prairielearn/src/question-servers/calculation.js

We were seeing errors like the following in production when running with `"legacyQuestionExecutionMode": "parallel-run"` (formatted for legibility):
```json
{
"candidateResult": [
[],
{
"options": {},
"true_answer": {
"answers": {}
}
}
],
"controlResult": [
[],
{
"options": {},
"params": null,
"true_answer": {
"answers": {}
}
}
],
"name": "calculation-question-generate"
}
```
The value for `params` didn't match because the `subprocess` branch would omit `undefined` properties entirely, whereas the `inprocess` variant would always convert those to `null`:
https://github.com/PrairieLearn/PrairieLearn/blob/9c35a890518d54b7958f7ea4e04a3781e43c92a4/apps/prairielearn/src/question-servers/calculation-inprocess.js#L10-L15
By always defaulting to `null`, we ensure that we don't have false positive …

Use null as default value for v2 outputs

---

apps/prairielearn/src/lib/score-upload.js

I found out about this via Sentry in production.

Add missing await in score upload handling

---

apps/prairielearn/assets/scripts/mathjax.js
docs/faq.md

The broken docs were reported on Slack recently. This fix has two parts:
- Support the `tex2jax_ignore` class that we previously documented
- Update the documentation to use the `mathjax_ignore` class because that makes a lot more sense than `tex2jax`.

Fix the docs for making Mathjax ignore specific HTML

---

apps/prairielearn/src/pages/userSettings/userSettings.html.ts

We explicitly set `access_tokens.token` to `NULL` after the first page load.

Fix validation for access tokens on user settings page

---

apps/grader-host/src/index.js
apps/grader-host/src/lib/pullImages.js
apps/prairielearn/src/lib/code-caller/code-caller-container.js
apps/prairielearn/src/pages/shared/syncHelpers.js
apps/workspace-host/src/interface.js
packages/docker-utils/package.json
packages/docker-utils/src/index.ts

I'm making this change in advance of some changes to the way we construct our AWS clients that will allow us to avoid exceeding IMDS rate limits.

Require ECR client to be passed to setupDockerAuth

---

apps/prairielearn/src/tests/sprocs/users_select_or_insert.test.js
apps/prairielearn/src/tests/sprocs/users_select_or_insert.test.sql

Updates the `users_select_or_insert` sproc tests to fail in the bug fixed in #8379. In general, it makes sure the tests also run with a passed in institution_id, which is realistic for SAML auth but might not have been captured by the test cases.
Adds a function to display the audit_logs, which was helpful when debugging.
Some comments in-line for tests that failed with the 'institution_id' '1' added. Maybe we need to break out different tests when an institution_id is passed in and when it isn't?

fix: users_select_or_insert sproc tests with passed-in institution

---

apps/prairielearn/src/pages/partials/question.ejs

This handles the case where someone tries to copy a question to the default (first) option in the course `<select>` in the question copy modal. If the selected option didn't change, our little script would never have set the appropriate action or CSRF token. Now, they default to the values corresponding to the first course in the options.

Fix copying a question using the default course

---

apps/prairielearn/src/migrations/20230815184404_authn_providers_sequence__setval.sql

The `authn_providers` table has a `nextval('authn_providers_id_seq'::regclass)` setting, but at least on the containers it was being set to 1 each time. This migration sets the sequence number to the appropriate next number.
Before:
```
postgres=# insert into authn_providers (name) values ('dave');
ERROR:  duplicate key value violates unique constraint "authn_providers_pkey"
DETAIL:  Key (id)=(1) already exists.
postgres=# 
```
After:
```
postgres=# insert into authn_providers (name) values ('Dave');
INSERT 0 1
postgres=# select * from authn_providers;
id |    name    
----+------------
1 | Shibboleth
2 | Google
3 | Azure
4 | LTI
5 | SAML
6 | Dave
(6 rows)
```

fix: authn_providers sequence number set to match table

---

apps/grader-host/src/index.js
apps/prairielearn/src/lib/externalGraderLocal.js
apps/workspace-host/src/interface.js

We noticed recently that some courses were producing extremely large core dumps (>1GB) in workspaces. We're opting to disable core dump generation for now to prevent these files from bloating our storage.
Closes https://github.com/PrairieLearnInc/sysconf/issues/1246.

Disable core dumps in all Docker containers

---

images/plbase/plbase-install.sh

Explicitly installing `npm@latest` now fails becuase the latest version of npm requires a version of Node newer than the one we're using, which causes our `plbase` image to fail to build:
```
#8 74.80 npm ERR! notsup Not compatible with your version of node/npm: npm@10.0.0
#8 74.80 npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
#8 74.80 npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.2"}
```
We'll instead rely on nvm automatically installing npm when it installs Node.

Rely on implicit installation of npm

---

apps/prairielearn/src/sprocs/instance_questions_ensure_open.sql
apps/prairielearn/src/sprocs/variants_select.sql
apps/prairielearn/src/sprocs/variants_select_submission_for_grading.sql

This ensures that Sentry and our load balancer won't unnecessarily treat these as 500s.
This error code is processed here:
https://github.com/PrairieLearn/PrairieLearn/blob/ebc9ec4faf2c2e114e4c3223d26048c190f6ea32/apps/prairielearn/src/server.js#L1858

Add explicit error codes for more SQL exceptions

---

apps/prairielearn/elements/pl-integer-input/pl-integer-input.py
exampleCourse/questions/element/integerInput/question.html
exampleCourse/questions/element/integerInput/server.py

This error can happen in a scenario like:
* in server.py, correct answer is set to: `data["correct_answers"]["input"] = 0o11` (i.e., 9).
* the integer input has the base 8.
Expected behaviour: the correct answer to be accepted is "`11`". Currently this doesn't work, with an exception being thrown because "9" is not a valid correct answer in base 8. This would work if the correct answer had been set to a string, e.g., `'11'`.

Fix check of string correct answer in integer input

---

apps/prairielearn/src/migrations/20230913180450_pl_courses__created_at__add.sql
database/tables/pl_courses.pg

I'll open another PR to backfill this data. Right now, I'm thinking of filling it in based on several sources, with each one serving as a fallback if previous ones aren't available:
- The date of the earliest server job for the course (this should typically be a sync done right around when the course was first created)
- The date of the first commit in the course's repository

Add created_at column to pl_courses table

---

apps/prairielearn/elements/pl-external-grader-results/pl-external-grader-results.py

This regression was introduced by #7977. As far as I can tell, it was unintentional.
As reported on Slack, this manifested as strange output from the Python autograder:

Fix handling of ANSI escape codes in external grader results

---

apps/prairielearn/src/pages/workspaceLogs/workspaceLogs.js
apps/workspace-host/src/interface.js

This PR makes two improvements to the instructor experience when when a workspace fails to start:
- We now allow logs to be fetched directly from the workspace host when the workspace is in the `launching` state. This makes it possible to view logs before the container health-checks, which can be useful if a container crashes or takes a really long time to start up.
- If a workspace fails to health check, we now immediately invoke `dockerAttemptKillAndRemove()`. This will in turn immediately flush the workspace's logs to S3 instead of having to wait for our background maintenance processes to kill the container.

Improve workspace logs when workspace fails to start

---

apps/grader-host/src/lib/jobLogger.js

Follow-up to #8454. Our new lint rule didn't catch this for obvious reasons.
Long-term, I'm inclined to say we should only push logs at the very end of the grading process, similarly to what we do for workspaces. That would remove the need for this little third-party package.

Use shared AWS credential provider for grader job logger

---

apps/prairielearn/python/zygote.py
apps/prairielearn/python/zygote_utils.py
apps/prairielearn/python/zygote_utils_test.py

See title, partial resolution to #8462. Forces numbers that would be oversized ints to be parsed as floats using a custom deserialization function. Still needs more unit / functional tests, but code should be mostly complete.

fix: Add custom int parse function

---

apps/prairielearn/src/batched-migrations/20230913181816_pl_courses_created_at.sql
apps/prairielearn/src/batched-migrations/20230913181816_pl_courses_created_at.ts
apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/migrations/20230913181816_pl_courses__created_at__backfill.ts
packages/migrations/src/batched-migrations/batched-migration.ts

This PR adds a batched migration to backfill the `pl_courses.created_at` column introduced in #8477. It computes the date of the earliest commit to the repository and the date of the earliest server job, then takes the earliest of those two.

Backfill created_at column for all courses

---

apps/prairielearn/src/batched-migrations/20230913181816_pl_courses_created_at.ts

Sometimes IDs are skipped in practice. This PR updated the course creation date backfill migration to account for that.

Account for missing courses when backfilling creation date

---

apps/prairielearn/src/lib/externalGraderLocal.js

This is a change to the config file that should have been changed at the same time as this: https://github.com/PrairieLearn/PrairieLearn/pull/8487 but was missed

PrairieLearn External grader local config memory size change

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/migrations/20230922173830_pl_courses__created_at__backfill__finalize.ts
apps/prairielearn/src/migrations/20230922173839_pl_courses__created_at__set_not_null.sql
database/tables/pl_courses.pg

The batched migration has finished successfully in all our environments; we can safely finalize it and make the column `NOT NULL` in the schema.

Make pl_courses.create_at NOT NULL

---

docs/sync.md
mkdocs.yml

This PR makes a number of improvements to the syncing docs:
- Documents the fact that in-browser editing can be used
- Documents a preferred GitHub workflow
- Discusses the tradeoffs and benefits of different methods of editing course content
- Removes redundant information about permissions, which can be found on the "Course configuration" page instead.

Improve syncing docs

---

.changeset/green-bugs-tell.md
apps/prairielearn/src/lib/session-store.ts
packages/opentelemetry/src/index.ts

These metrics will allow us to validate that upcoming changes to the session store significantly reduce the write load on the database.

Export OpenTelemetry metrics for the session store

---

apps/prairielearn/src/batched-migrations/20230913181816_pl_courses_created_at.ts

The change in the schema in #8509 meant that anyone that runs the `created_at` backfill migration after merging with #8509 would see a schema error. This change causes the migration to allow the `created_at` column to be null at the point of migration.

Change migration to allow null created_at

---

apps/prairielearn/src/lib/externalGraderResults.js

`grader-host` will inline results if they are less than 256kB (an SQS limit), but if they're larger, it writes them to S3 and expects PL to read them back for processing. This explains why jobs generally work: most results are smaller than 256kB.
In the case of Norm from UBC who reported this issue, I looked at the size of his `results.json` files and they precisely straddle the line of 256kB. That, combined with the fact that his tests are non-deterministic, explains why the same student code would sometimes get a zero.

Await Promise to fix external grading results

---

apps/prairielearn/src/lib/assessment.js
apps/prairielearn/src/lib/externalGraderCommon.js
apps/prairielearn/src/lib/externalGraderCommon.test.ts

As discussed on #8521. If there was a serious error during external grading, we now mark the entire submission as ungradable. This avoids penalizing students for issues outside their control.

Mark failed external grader jobs as ungradable

---

apps/prairielearn/src/api/v1/endpoints/queries.sql

As requested by Seth. Data added to the submissions endpoint (individual and list). Three new values added:
* rubric_grading_computed_points (total computed from the rubric)
* rubric_grading_adjust_points (manual adjustment)
* rubric_grading_items (array of items with "text" and "points").

Add rubric grading information to API

---

apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts
apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.ts

The admin page for features currently only lists features granted through the database, but features can also be enabled/disabled through the config file. This change indicates that if a feature is set in the config file in that page, overriding any grants provided through that UI.
There are other means to enable features, like overrides, but those (as far as I can tell) are transient and do not affect the general state of the feature availability.

Admin: list feature enable in config file as a grant

---

apps/prairielearn/assets/scripts/lib/questionsTable.js
apps/prairielearn/src/models/questions.ts

Two similar issues related to the assessments column:
* Only assessments in course instances that the instructor has access to are listed. The ID comparison here was using `includes`, which expects equality, but the course instance ID was an int, while the course instance of the assessment was a string;
* Each column only lists the assessments associated to a particular course instance ID. Again, the types don't match.

fix: Questions table retrieval of assessments for a course instance

---

apps/prairielearn/assets/scripts/lib/questionsTable.js
apps/prairielearn/src/components/QuestionsTable.html.ts
apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/models/questions.sql
apps/prairielearn/src/models/questions.ts
apps/prairielearn/src/pages/instructorQuestions/instructorQuestions.html.ts

Currently there is no way to view which questions are in a given sharing set. 
This fixes that by enabling filtering by sharing set on the instructor questions page.

Enable filtering by sharing set on questions page

---

apps/prairielearn/package.json
apps/prairielearn/src/lib/socket-server.js
yarn.lock

This PR replaces #8628 by building on plain `master` rather than the forked copy of `socket.io-redis-adapter`.
We are switching to `ioredis` because `node-redis` does not reestablish subscriptions on reconnects. This is crucial for use with `socket.io/redis-adapter` because the adapter doesn't have any logic to do this itself. With `node-redis`, if we lose the Redis connection then `node-redis` will correctly reestablish it, but we won't be subscribed to notifications for the pub/sub channels and so the sub part of pub/sub will never receive any more events. In contrast, `ioredis` explicitly supports [resubscribing on reconnect](https://github.com/redis/ioredis#auto-reconnect):
> When reconnected, the client will auto subscribe to channels that the previous connection subscribed to.
I …

Switch from `node-redis` to `ioredis` for `socket-server`

---

apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ejs
apps/prairielearn/src/pages/partials/attachFilePanel.ejs

Resolves #7577 . This can be useful in cases where:
* students want to leave a note to instructors that cannot be saved in existing elements;
* students may include an explanation on how they reached the value;
* students with no attempts left can explain their rationale for manual review.

Add personal notes to manual grading page

---

apps/prairielearn/elements/pl-number-input/pl-number-input.py

Resolves issue brought up on Slack. The `show-correct-answers` option is not considered when showing feedback on the submission panel. See: https://us.prairielearn.com/pl/course_instance/4970/instructor/question/8211637/preview/?variant_id=81286593

Honor show-correct-answers option in number input feedback

---

exampleCourse/questions/element/graph/question.html

#8631 is actually caused by outdated chunks. This PR makes a small change to force chunk regeneration the next time the example course is synced.
Closes #8631.

Remove extraneous spaces from element/graph question

---

apps/prairielearn/src/ee/pages/studentCourseInstanceUpgrade/studentCourseInstanceUpgrade.ts

This will ensure that the metadata is propagated to the payment, which is what we ultimately interact with in Stripe's dashboard.

Add metadata to Stripe PaymentIntent when creating Checkout Session

---

apps/prairielearn/package.json
apps/prairielearn/src/lib/json-load.js
apps/prairielearn/src/question-servers/freeform.js
apps/prairielearn/src/tests/jsonLoad.test.js
yarn.lock

This came out of #8596, where I was looking into why `sinon` was installed. These functions/tests were unused, which allows us to remove the only usage of `sinon` from the `prairielearn` app.

Remove unused json-load functions

---

apps/prairielearn/src/lib/authn.js
apps/prairielearn/src/middlewares/authn.js
apps/prairielearn/src/pages/authCallbackLti/authCallbackLti.js

This lays the groundwork for deprecating the `pl_authn` cookie in favor of storing all relevant information in the session. With this PR, we'll start writing the `user_id` and `authn_provider_name` into the session. We also start using those values instead of the cookie whenever possible.
Once this has been deployed for a while, we should be able to stop reading the `pl_authn` cookie entirely.

Dual-write authentication data to both cookie and session

---

apps/workspace-host/src/interface.js
apps/workspace-host/src/interface.sql

Closes #8648. See inline description for more details.
Note that in some sense, this is just a bandaid, and results in what is still a subpar UX: the browser will receive launching updates from both launch attempts, which might result in the image pull percentage oscillating rapidly between two values from two different hosts or other weirdness. There are various ways we could fix this. One idea when updating the workspace state message, always do the same `launch_uuid` check to determine if we're still the "current" launch attempt.
I opted not to implement that or anything else in this PR; this will be valuable on its own as it will avoid the "Error proxying workspace request" message that can only be recovered from with another request.
Note: I was unable to test how this behaves during …

Fix workspace launch race condition

---

apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js
apps/prairielearn/src/lib/manualGrading.js
apps/prairielearn/src/lib/manualGrading.sql
apps/prairielearn/src/migrations/20231013150413__rubric_items__always_show_to_students.sql
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.js
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/rubricSettingsModal.ejs
apps/prairielearn/src/pages/partials/submission.ejs
apps/prairielearn/src/tests/manualGrading.test.ts
database/tables/rubric_items.pg

Resolves #6777. Allows each rubric item to be set to either always visible to students (the default, current functionality), or only visible when checked. This allows instructors to only show specific items (e.g., penalties) to those students that have received them.

Manual grading rubrics: allow instructor to hide items not applied from students

---

apps/prairielearn/src/lib/manualGrading.js
apps/prairielearn/src/lib/score-upload.js
apps/prairielearn/src/tests/exam.test.js

Resolves #4064. In particular, rows without a value in any of the score columns (score_perc, points, manual_score_perc, manual_points, auto_score_perc, auto_points, feedback, feedback_json, partial_scores) are skipped in the update. This means:
* these entries don't cause a manual grading log to be created for the assessment instance;
* the corresponding rows are not listed in the grading job log;
* a count of skipped rows is shown at the bottom of the log.
I chose not to give an error if the columns don't exist for simplicity, as in this case the warning will show that no rows were updated anyway.
Additional changes added:
* the corresponding lib was changed to remove references to `module.exports` and use `export function` instead. This should simplify a future renaming to TS, as …

Score upload: skip rows without score values to update

---

apps/prairielearn/elements/pl-units-input/pl-units-input.py

See title. Fixes the double escape bug and simplifies template reading for the units input element.

fix: Units input element escape bugfix and template simplification

---

docs/installingNative.md

This PR makes two additions that I noticed we needed while getting Myles set up for native dev yesterday:
- Document that Redis is required
- Document that one should have installed the XCode command line tools on macOS (necessary for pygraphviz to compile)
I also removed the "not recommended or supported" warning. While I'm not ready to make this the default way of installing PL, the DX is so much better that I also don't want to dissuade people from using a native installation.

Improve native installation docs

---

apps/prairielearn/src/lib/workspace.js

The existing type confused me for a while when I was investigating #8637. It took actually reading the code to determine that this function will in fact never return `null`.

Fix return type of workspace initialize function

---

graders/python/requirements.txt

Faker can be used to create randomized inputs for tests. It's already in use in plbase to randomize questions.

Add faker to Python autograder

---

graders/python/requirements.txt
workspaces/jupyterlab-python/requirements.txt

See title, adds unidecode to the Python autograder. Useful in some situations, especially if externally grading student input rather than student code.

feat: Add unidecode to the Python grader image

---

.changeset/curvy-waves-end.md
packages/session/README.md
packages/session/src/cookie.ts
packages/session/src/index.test.ts
packages/session/src/index.ts

This is a prerequisite for #8403. We need to start explicitly specifying a domain for all our cookies. However, if we just blindly added a `domain` property to our existing cookies, we'd actually be left in a situation where we have two identically-named cookies. So, we actually have to migrate to a brand-new cookie. This change will let us do so transparently to users.
The intended usage of this code: we'll simultaneously deploy config for this change with `name: ['_prairielearn_session', ['prairielearn_session']` (or some other suitable new name) and config to set the cookie domain. That way, we'll guarantee that `_prairielearn_session`, if it's present, has an explicit domain specified. Then, after this has been in production for a while (a week? maybe even shorter), we can drop the …

Add cookie rotation to @prairielearn/session

---

graders/python/requirements.txt
workspaces/jupyterlab-python/requirements.txt

As discussed with @eliotwrobson. He says that all courses are now using inline copies of this library, and a manual review of course repositories shows that to be true. Even then, only CS 347 actually appears to be using this library in external grading.
This should be extra safe to remove from `workspaces/jupyterlab-python`, as that image has only been around for a week or so and hasn't seen any adoption yet.

Remove automata-lib from Python grader and Jupyter images

---

.github/dependabot.yml

The new jupyterlab image was not added to dependabot configuration.

Add new jupyterlab image to dependabot configuration

---

apps/prairielearn/elements/pl-symbolic-input/pl-symbolic-input.py

See title. Dict key is not used in mustache template (can double check with grep).

style: Removed unused dict attrib

---

.github/dependabot.yml

`@sentry/*` packages should generally be bumped together.

Add Sentry group for Dependabot

---

apps/prairielearn/elements/pl-drawing/mechanicsObjects.js

Fixes a bug reported on Slack. When browser font size is increased, Latex labels in a `<pl-drawing>` element would be cut off. This is easily reproducible with the `demo/drawing/collarRod` question in the example course:
After this change, labels now render correctly, even at increased font sizes:
I made an explicit choice to favor rendering fidelity here. That is, an alternative option would have been to allow the font size to increase the size of the label (as was the case before). However, this means that drawings could display unpredictably in a way that the instructor didn't anticipate. So, the label is drawn with a non-scaling size. This matches the behavior of `<pl-text>` in non-Latex mode.
From an accessibility standpoint, I think this is fine. Users can't increase the text size …

Improve rendering of pl-drawing Latex text

---

.changeset/thin-birds-smell.md
apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessment/assessment.html.ts
packages/html/src/index.ts

Resolves #8742. Follow up to https://github.com/PrairieLearn/PrairieLearn/pull/8685#discussion_r1376853780. I made the separator optional and default to a blank string, though this may not be necessary as the `html` function already handles the case of arrays, but I added it to make it closer to the functionality of join.

Add function to join HTML safe values

---

apps/prairielearn/assets/scripts/navbarClient.ts
apps/prairielearn/src/pages/partials/head.ejs
apps/prairielearn/src/pages/partials/navbar.ejs
apps/prairielearn/src/pages/partials/navbarUserDropdownOverrideItem.ejs

Followup to #8704. Makes several improvements discussed there:
- The inline script for override items was replaced with an event handler in the new `navbarClient` code.
- The manual handling of `Enter` to submit a new UID was replaced with a standard `<form>` + `<button type="submit">`.
- The deprecated `keypress` event was replaced with `input`.
I also made some styling changes to make left margins more consistent. There's no need for such margins in this part of the dropdown because we won't ever show checkboxes there. I also changed the placeholder text from `netid@illinois.edu` to `student@example.com` in the interest of removing Illinois-specific details.
Before:
After:

Improve navbar overrides

---

apps/prairielearn/src/lib/config.js
apps/prairielearn/src/server.js

Builds on the changes from #8703. We'll need this to be configurable so we can configure the move of our session cookie to an explicit domain.

Add configuration for session cookie names

---

apps/prairielearn/elements/pl-drawing/pl-drawing.js

`Object.keys()` coerces object keys to strings. This means that `id + 1` would end up concatenating `1` to the end of each ID, meaning that our numbers would actually grow very very rapidly as more submissions were made an objects were added. Eventually, `id` would exceed $2^{53} - 1$ and the zygote would refuse to serialize it to JSON. Now, we explicitly parse the ID to an integer to ensure that we're doing math and not string concatenation.

Fix pl-drawing ID generation

---

apps/prairielearn/src/lib/question.sql

Resolves #8783. The original query had a control to ensure that the instructor preview page was only able to retrieve submissions from variants that were not associated to an assessment, but the preview page itself does not have that control (see #5418). After this change, the submission loading URL supports retrieving any variant/submission, as long as the user has access to the URL (which requires staff permission in the course). This matches the permissions needed in instructor preview itself.
The check remains in place for the other URL entrypoints for this code that have a validated instance question ID, e.g., student instance questions (can only open variants associated to the instance question) and manual grading.

Fix dynamic submission loading in instructor view for issues

---

apps/prairielearn/elements/pl-drawing/pl-drawing.mustache

To reproduce the underlying bug here, make 4 submissions to an `pl-drawing` question, then try to view the first submission; it would be an empty canvas.
We do moderately-hacky things when dynamically rendering submissions to ensure that any embedded scripts execute. In this case, it meant that the `<script>` tag was actually at a different point in the document and thus `document.currentScript.previousElementSibling` returned a completely unrelated element. I'm not 100% sure why it was done this way originally, but looking up the element by the ID (which was already set) should be much more robust.

Fix rendering of pl-drawing in dynamically-loaded submission

---

.readthedocs.yml

This is now required: https://blog.readthedocs.com/migrate-configuration-v2/
I tested a build of this branch and it's working as expected: https://prairielearn.readthedocs.io/en/readthedocs-config/
Closes #8794.

Migrate to v2 of Read the Docs config file

---

apps/prairielearn/src/lib/manualGrading.js
apps/prairielearn/src/lib/manualGrading.sql
apps/prairielearn/src/tests/manualGrading.test.ts

When rubric settings change, all existing gradings are reviewed for potential recomputation of grades. In essence, this recalculation happens when:
* If the starting points (i.e., positive vs negative) change, all existing gradings are recalculated
* If the minimum or maximum points change, all existing gradings are recalculated;
* If a rubric item is deleted, instance questions graded with that item are recalculated;
* If a rubric item has its points changed, instance questions graded with that item are recalculated.
This PR fixes two issues:
* If a question had been graded without applying any of the rubric items, changes in rubric items (points or deletion) still triggered an unnecessary recalculation;
* In the same scenario above, #8777's update would cause a schema problem.
~~There …

Fix rubric settings change when no items selected

---

apps/prairielearn/src/lib/manualGrading.ts

We `LEFT JOIN` on `submissions`, so we aren't guaranteed to have a submission ID:
https://github.com/PrairieLearn/PrairieLearn/blob/2cdc962b6f3e9401491512b40b090870d5d970b6/apps/prairielearn/src/lib/manualGrading.sql#L391
In fact, the code actually explicitly handles the case of no submission:
https://github.com/PrairieLearn/PrairieLearn/blob/2cdc962b6f3e9401491512b40b090870d5d970b6/apps/prairielearn/src/lib/manualGrading.ts#L571-L579

Fix manual grading submission query

---

apps/grader-host/package.json
apps/prairielearn/package.json
apps/workspace-host/package.json
yarn.lock

Dockerode v4 had an undocumented breaking change where `container.logs` now returns a string instead of a Buffer. This is breaking log collection on workspace hosts.

Downgrade dockerode

---

apps/prairielearn/src/lib/config.js
apps/prairielearn/src/lib/externalGraderLocal.js
apps/prairielearn/src/lib/externalGraderSqs.js
apps/prairielearn/src/sync/course-db.js
docs/externalGrading.md
exampleCourse/questions/demo/autograder/c/salesTax/info.json

Closes #8808. As noted in that issue, the limit of 10 minutes (600 seconds) has been selected to have minimal impact on current questions. While some courses do have higher limits set, we don't see any evidence that well-behaved submissions are coming anywhere close to exceeding those timeouts. 600 seconds allows virtually all questions/submissions to continue functioning as they have been.

Set maximum value for external grading timeouts

---

apps/prairielearn/src/pages/instructorGradingJob/instructorGradingJob.ejs

This PR fixes two bugs with the external grading results page:
- Sometimes, the spinner wouldn't be hidden once the output was loaded. AFAICT this is a race condition with Fontawesome, which actually replaces the `<i>` tag with an `<svg>` tag. Somehow, this results in jQuery not finding the node to remove it.
- The spinner was very wide and rotating, which made the page grow and shrink vertically as it rotated.
Both of these issues are visible in the following screen recording from prod:
https://github.com/PrairieLearn/PrairieLearn/assets/1476544/00016451-fa3a-49a1-96b8-6f5cc3d92541

Fix grading job output spinner

---

apps/prairielearn/assets/scripts/navbarClient.ts

Pages like the workspace page and the login page do not have a regular navbar. This causes the navbar script to trigger an error on start.

Fix navbar script in pages without the default navbar

---

graders/python/python_autograder/pl_main.py

In the Python grader, if there is a syntax error in the test code (tests/test.py), currently an error like the following would show in the grading job terminal:
```
info: container> [run] starting autograder
info: container> Traceback (most recent call last):
info: container>   File "/grade/run/pl_main.py", line 41, in <module>
info: container>     from filenames.test import Test as test_case
info: container>   File "/grade/run/filenames/test.py", line 4, in <module>
info: container>     from faker import Faker
info: container> ModuleNotFoundError: No module named 'faker'
info: container> During handling of the above exception, another exception occurred:
info: container> Traceback (most recent call last):
info: container>   File "/grade/run/pl_main.py", line 144, in <module>
info: …
```

Python grader: proper handling of syntax error in test code

---

apps/prairielearn/assets/scripts/workspaceClient.ts
apps/prairielearn/src/lib/workspace.js
apps/prairielearn/src/pages/workspace/workspace.html.js
apps/prairielearn/src/pages/workspace/workspace.js

Currently, workspace sockets aren't fully authenticated, meaning a user could in theory read the state (though not the contents) of another workspace. This PR implements token-based authentication to fix that.
Closes https://github.com/PrairieLearnInc/sysconf/issues/1468.

Lay groundwork for workspace socket authentication

---

apps/grader-host/.mocharc.js
apps/grader-host/package.json
apps/grader-host/src/index.js
apps/grader-host/src/lib/config.js
apps/grader-host/src/lib/receiveFromQueue.js
apps/grader-host/src/tests/receiveFromQueue.test.js

Previously, we would compute an expected visibility timeout immediately after receiving a message from SQS and update the visibility timeout to that. However, this causes problems if a grader host dies while processing a job, as we'll end up waiting quite a bit of time until it's retried.
Now, we use [the heartbeat approach from the SQS documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html#configuring-visibility-timeout):
> If you don't know how long it takes to process a message, create a heartbeat for your consumer process: Specify the initial visibility timeout (for example, 2 minutes) and then—as long as your consumer still works on the message—keep extending the visibility timeout by 2 minutes every minute.
This should …

Improve grader-host visibility timeout handling

---

images/plbase/plbase-install.sh

How do we feel about adding developer niceties into the containers? Can we spare 292k (1.0M installed) for tab completing make commands?
Or are we trying to keep things super slim and I should just run it locally?

add: bash-completion to docker shells

---

.gitattributes

This should make the language stats that GitHub generates a little more accurate.

Ignore vendored files from GitHub language stats

---

apps/prairielearn/package.json
apps/prairielearn/src/lib/question.js
yarn.lock

As discussed in our dev meeting. This is intended as a first step to simplify future changes to migrate these libs to new format. Typescript, async and changes in query functions are not done.
Lodash is still using the old notation, as it is used with chaining, and I wanted to avoid unnecessary changes in the functions themselves.
Best viewed with whitespace changes ignored.

Use ESM format for import/export in lib/question.js

---

apps/prairielearn/src/lib/question.sql

This column is no longer used; it appears to be left over from an ancient migration from MongoDB.

Don't query for unused submissions.sid column

---

.changeset/friendly-peas-sparkle.md
apps/prairielearn/src/lib/assessment.ts
packages/postgres/src/default-pool.ts

Follow-up to #8829. Also exports the `CursorIterator` type in the postgres package. `QueryParams` is also exported for completeness, though it is not used in this PR.
The `processGradingResult` receives a parameter currently set to `any`. This is because the current handling of parsing/evaluating the parameters causes issues with a more specific type. A future PR should include Zod parsing of the grading results, which should simplify this process and make it more robust.

Convert assessment lib to typescript

---

apps/prairielearn/src/lib/assessment.sql
apps/prairielearn/src/lib/assessment.ts

In #8829 the queries in assessment.js were updated to use Zod validation. One query was incorrectly marked as requiring a mandatory ID, even though the query allowed for a null ID. This wouldn't cause a problem before because the function being called would ignore null inputs, but the new validation caused an error. This error would typically not cause an issue on user interface, since this happened after the grading results were saved, but an exception would be thrown in the background.
To avoid confusion, in this fix the query is replaced with `queryOptionalRow`, which more clearly identifies this as a query that may not result a valid entry.

Fix update of LTI outcomes in external grader

---

apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.html.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ejs
apps/prairielearn/src/tests/questionSharing.test.ts

Tests were previously using `String.prototype.includes` to check for the presence of text on pages. However, this isn't ideal, as string may appear or disappear from pages for reasons unrelated to the thing being tested. This PR adds some `data-testid` attributes and uses Cheerio to run tests against those elements specifically.

Improve robustness of question sharing tests

---

apps/prairielearn/src/tests/courseEditor.test.js
apps/prairielearn/src/tests/fileEditor.test.js

This code was written while pairing with Nathan to fix some local errors. This pull request will set the default git branch to `master` while running tests in `fileEditor` and `courseEditor`. This corrects a use case of a user that has set up git to have a default branch other than 'master'. For example, my local setup had been using 'main' instead of 'master' as the default git branch. This PR ensures that git is using 'master' and that tests are able to run as expected.

Set default git branch while running tests

---

apps/prairielearn/src/tests/groupStudent.test.js

I thought the misplaced `callback()` invocations might have had something to do with the flaky group work test. Even after fixing them, I still occasionally see failures, but let's fix this up anyways.
I also rewrote tests that were unnecessarily using callbacks.

Fix callback invocation in group student tests

---

apps/prairielearn/.mocharc.js
apps/prairielearn/package.json
apps/prairielearn/src/pages/publicQuestionPreview/publicQuestionPreview.ts

Using `.ts` in the regexp works in dev, but won't work in prod when the file actually has a `.js` extension.
I added support for running our PL tests against the contents of `dist`, which is what will actually run in production. This is useful since it lets us validate that TypeScript/ESM transforms will produce code that works as expected. I'm not quite ready to make this the default thing we run in CI, but I think that will be a good thing to do in the near future, especially as work on TS/ESM picks up.

Fix public question preview page

---

apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.html.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ejs
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.js
apps/prairielearn/src/pages/publicQuestions/publicQuestions.html.ts

Previously there were a few inconsistencies in who could edit sharing permissions. 
Only a course owner could edit sharing sets and sharing names, but any course editor
could share a question. The permissions were also not made clear by the user interfaces.
This PR brings consistency by making it so only course owners can edit all sharing information,
and this is properly reflected by what UI elements are present to what users on pages.

Sharing info edit permissions consistency

---

packages/session/src/index.ts

This PR aims to fix a race condition in our session code where a session could be read before the updated session from the previous request was committed. It does so by replacing `res.redirect` with a function that commits the session before the redirect is actually executed. This is safe to do from the caller's point of view, as `res.redirect()` does not return anything.
When I added an artificial delay to session persistence, more of the session tests broke. Specifically, those that use `sendStatus()` didn't work. I briefly considered making the same change to that function, but `sendStatus()` is meant to return the `Response` object for chaining, and there's no way to do something asynchronous before returning from `sendStatus()`. Ultimately, I decided this is fine to avoid:
- We …

Commit session before redirecting

---

apps/prairielearn/src/lib/assessment.sql
apps/prairielearn/src/lib/assessment.ts
apps/prairielearn/src/lib/externalGrader.sql
apps/prairielearn/src/lib/externalGrader.ts
apps/prairielearn/src/lib/externalGraderResults.js

Based on results from #8870. Moves the function `processGradingResult` from assessment.ts to externalGrader.ts. This breaks several cycles of dependencies, since externalGrader.ts no longer depends on assessment.ts.
Conflicts with #8842. I will update that PR after this one is merged. In essence this PR does not change anything regarding the functionality of the function, it only moves its location.

Resolve circular dependencies in external grader library

---

apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.sql

If a course has no course instances, we used to still show the "Add..." button for student data access that rendered for a null course instance:
This is because `other_course_instances` looked like `[{ id: null, short_name: null }]`. Now we filter out rows where there wasn't even a course instance to join with. The staff page already correctly handled the case where the `other_course_instances` array was empty.

Handle case of no course instances on staff page

---

apps/prairielearn/src/lib/session-store.sql
apps/prairielearn/src/migrations/20231121232108_user_sessions__revoked_at__add.sql
database/tables/user_sessions.pg

As discussed on #8798, we want sessions to stay around forever so that we can associate them with client fingerprints. This PR switches our session store to "destroy" sessions by setting `revoked_at`.

Soft-delete user sessions

---

packages/browser-utils/package.json
packages/compiled-assets/package.json
yarn.lock

Now that `tsup` is using the latest version of `esbuild`, we can too.

Install latest esbuild

---

apps/prairielearn/src/pages/instructorGradingJob/instructorGradingJob.html.ts

This column will be `NULL` for grading jobs that aren't yet complete. We've seen this showing up in Sentry errors.

Handle ungraded grading jobs on instructor page

---

apps/prairielearn/src/pages/partials/navbarInstructor.ejs

`res.locals.assessments` won't be populated on assessment instance pages. More generally, it makes sense to only show the dropdown caret if there are actually assessments to choose between.

Disable assessment switcher on assessment instance

---

apps/prairielearn/src/server.js

This ensures that we don't log a page view if our access checks fail (for instance, if the assessment is closed or password-protected).

Only log assessment page views after access checks

---

.changeset/wise-ads-explain.md
packages/session/src/index.test.ts
packages/session/src/index.ts
packages/session/src/session.test.ts
packages/session/src/session.ts

This is a prerequisite for #8798. We want to be able to unconditionally look up a session by its `session_id` during a request and get a valid `id` back.

Immediately persist new sessions

---

apps/prairielearn/src/lib/score-upload.ts

As reported by @glherman . The score upload functionality fails with a Zod error when the specific question does not have a submission.

Fix score upload of questions without submissions

---

CONTRIBUTING.md

I'm not sure if the discussion is expected to be an official documentation of sorts, but until this is incorporated into the dev guide it's probably the best option.
Also added a note regarding using smaller PRs.

Add link to modernizing code discussion in CONTRIBUTING.md

---

apps/prairielearn/src/pages/instructorGradingJob/instructorGradingJob.html.ts
apps/prairielearn/src/pages/instructorGradingJob/instructorGradingJob.sql

This column was `NULL` when this page was served from the course route. I was originally going to mark it as `nullable()`, but it turns out it's completely unused!

Remove unused column from grading job page

---

apps/prairielearn/src/ee/auth/saml/index.ts

This allows institutions using passwordless auth to authenticate. I'll test this with UIUC's auth on staging first.

Allow any authentication context for SAML auth

---

package.json
tools/cjs-to-esm-candidates.mjs
yarn.lock

This PR contains a small CLI utility to help us prepare for the migration to ESM. It finds and prints all places where we load code via `const ... = require(...)` or `import ... = require(...)`. It uses a manually-curated list of packages that use `export = ...` to avoid printing anything for packages that we can't yet import with native ESM syntax.
This PR doesn't yet do anything to detect `module.exports`, though it'll be easy to expand it to handle that in the future.

Add script to find candidates for conversion to ESM imports

---

apps/prairielearn/src/lib/assessment.sql

Resolves #9062. Moves the `ORDER BY` clause from the CTE to the main query.

Fix order of assessment instance log

---

apps/prairielearn/python/prairielearn.py
apps/prairielearn/python/prairielearn_test.py

Lifted from #8903. Uses generator expressions to generate keys. Faster and more convenient in most situations. See original PR for usage.

refactor: Python key generator changes

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/schemas/schemas/infoQuestion.json
apps/prairielearn/src/sync/course-db.js
apps/prairielearn/src/tests/sync/util.js

This type was supported in the schema but not in the question modules.
The database enum was not modified, as changing the enum is not an easy migration, and there is no harm in keeping the enum values as they are in the DB.

Remove ShortAnswer question type

---

apps/prairielearn/src/tests/accessibility/index.test.js

I've noticed these tests timing out somewhat frequently in CI.

Increase timeout for accessibility tests

---

apps/prairielearn/src/tests/accessibility/index.test.js

As recommended by an `axe-core` contributor, we're able to speed up our accessibility tests by limiting the types of results it returns. This change gave us a roughly 2x speedup and allows us to get rid of our existing per-page performance hacks.

Improve performance of accessibility tests

---

apps/prairielearn/src/lib/grading.js
apps/prairielearn/src/lib/issues.ts
apps/prairielearn/src/lib/question-render.js
apps/prairielearn/src/lib/question-testing.js
apps/prairielearn/src/lib/question-variant.js
apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.js
apps/prairielearn/src/question-servers/calculation-subprocess.js
apps/prairielearn/src/question-servers/calculation-worker.js
apps/prairielearn/src/question-servers/freeform.js
apps/prairielearn/src/question-servers/index.ts
apps/prairielearn/src/tests/accessibility/index.test.js

Changes the question server functions to async functions. The implementation was already using async, only the calls were still through callbacks, so the server implementation itself was not affected.
Also rewrites some of the functions involved in question generation/grading/testing/rendering to async, where the change was relatively simple. Within this change, since all references to `writeCourseIssues` were converted to async, got rid of the callback version of this function.
~~Note: this PR includes/overrides the changes in #9083 and #9079, so it's up to you if you want to review those two first and have this one merged on top of them, or to skip those altogether and review only this one.~~
Diff best viewed with spaces ignored. ~~particularly if #9083 is not merged first~~

Converts question server functions to async

---

apps/prairielearn/src/lib/question-render.js

Fixes error introduced by #9085. A helper function was converted to async, but one of its calls was still promisifying the already promisified function.

Fix rendering of submission panel for external grading

---

apps/prairielearn/src/sync/fromDisk/assessments.js

Currently, if no questions set `canView` and `canSubmit` when roles are in play, all roles are set to not allow viewing and submitting. This PR changes that default to allowing all roles to view and submit unless explicitly set otherwise.

Set default role permissions to all permissions

---

apps/prairielearn/src/migrations/20231223101924_assessment_question_role_permissions__drop_index.sql
database/tables/assessment_question_role_permissions.pg

This index matches exactly the primary key, so it's redundant.

Remove redundant index for role permissions table

---

workspaces/xtermjs/Dockerfile

`buster` was released in 2019, and it's [past official end-of-life, in LTS mode](https://wiki.debian.org/DebianReleases). `bookworm` has been release this past June and is the latest stable version, with plans for long term support.
The previous version used a generic distro name without an explicit Node version (i.e., `node:buster` instead of `node:20-buster`). For bookworm this would be Node 21, which didn't work for `node-pty`. `20-bookworm` (using Node 20) worked as expected, and I believe setting a specific version of Node might not be a bad idea anyway.
The plan is to open this PR for review, but hold off on deploying it until late December (in between terms) to avoid potential issues in the middle of the term.

Update Debian version of xtermjs workspace

---

apps/prairielearn/src/lib/db-types.ts

To simplify future handling of code that replaces #8006 (and other related code), I'm creating these types separately, so that they can be ready whenever needed. The hope is to avoid duplicating effort in other PRs that may take time to be merged.

Add assessment and group tables to db-types

---

apps/prairielearn/src/ee/routers/lti13.ts

Avoiding a 500 status code makes sure that Sentry and other tools don't detect this as a server error.

Use 403 status code when LTI 1.3 is not enabled

---

.github/workflows/main.yml

As discussed on Slack. This is to ensure all tests run even if dedupe fails, which is pretty common to happen in dependabot PRs.

Move dedupe CI to the end of workflow

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.js

These arrays can contain `NULL` values; the Zod schema should reflect that.

Fix Zod schemas for instance_questions array columns

---

apps/prairielearn/src/sync/course-db.js

We need to read the old value to construct the error message before we update it, otherwise we always print the following, which doesn't make sense:
> External grading timeout value of 600 seconds exceeds the maximum value and has been limited to 600 seconds.

Fix warning about external grading timeout limits

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/lib/grading.ts
apps/prairielearn/src/lib/question-render.sql
apps/prairielearn/src/lib/question-testing.js
apps/prairielearn/src/sprocs/submissions_insert.sql
apps/prairielearn/src/sprocs/variants_select_submission_for_grading.sql

Part of #9205. Once we're no longer reading from or writing to this column in production, we can drop the column entirely.
AFAICT, we never actually do anything with the read value of this column, so I believe it's safe to stop writing to it before all servers would have necessarily stopped reading from it. Let me know if you think that's not the case.

Stop reads/writes for submissions.regradable

---

apps/prairielearn/src/lib/manualGrading.sql

Fixes #9231. This is a simple off-by-one error. The check uses `$number` to determine if there have been 10 entries with keyboard shortcuts, but `$number` is zero-based, so if `$number` is 10 this is the 11th rubric item.

Fix rubric keyboard binding for rubrics with more than 10 items

---

apps/prairielearn/src/lib/session-store.sql

While investigating another issue, I discovered that a lot of our `user_sessions` rows have a null `user_id` despite having a value in `data->>'user_id'`. The issue here should be obvious.
Once this is deployed, I'll introduce a batched migration to backfill all the empty `user_id` values.
We aren't currently relying exclusively on this value anywhere, so this wouldn't have had any observable impact to end users. However, it's important that we get this fixed in preparation for dropping the `pl_authn` cookie.

Fix handling of user_sessions.user_id during conflicts

---

apps/prairielearn/src/sprocs/group_info.sql

**WARNING: Currently untested!**
Fixes #9228
The problem was that the `group_info` query used a simple LEFT JOIN and so it returns `uid_list = [NULL]` when there aren't any group users. This PR changes to a two-stage query so that it will return `uid_list = []` in this case.
This function is only used in two files:
1. `instructorAssessmentInstances.sql`, which triggered the bug in #9228: https://github.com/PrairieLearn/PrairieLearn/blob/4158b0dc07463ad82c560b30529ec94ac705c607/apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.sql#L93
2. the API in two places: https://github.com/PrairieLearn/PrairieLearn/blob/4158b0dc07463ad82c560b30529ec94ac705c607/apps/prairielearn/src/api/v1/endpoints/queries.sql#L96 and …

Fix `group_info.sql` to not return NULL users

---

apps/prairielearn/src/pages/studentAssessments/studentAssessments.ejs

Closes #9214. The other approach is to hide the button entirely, but as discussed on that other issue, I think that's best only after we've implemented something like #2185.

Show disabled button for inactive multi-instance assessment

---

apps/prairielearn/src/pages/partials/navbarInstructor.ejs

I noticed while looking at a page's HTML that we had unbalanced double quotes here. Specifically, there was a double quote after `class="nav-link"`, but there shouldn't have been because the following two conditional that add `active` and `disabled` should have been included in the class list.

Fix HTML for instructor navbar

---

apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.js

In PR #9072, we added zod-validation to our queries and add schemas to validate the data. However, as pointed out #9246, there were columns from the `select_instance_questions` query that were not included int he `InstanceQuestionRowSchema`. Thus, there were bugs and features missing from the page. This PR intends to add those missing types to the Zod schema and restore features to the page. Closes #9246.

Add types to InstructorAssessmentInstance page

---

apps/prairielearn/src/lib/groups.sql
apps/prairielearn/src/lib/groups.ts

Fixes #9255 (as far as I can tell). That is, the student assessment overview page of an empty group now loads for me as an instructor. By separating the querying of group info and group membership, we can now load needed information even for an empty group.

Improve function to get group info

---

apps/prairielearn/src/middlewares/content-security-policy.ts
apps/prairielearn/src/server.js

This should not be merged until we've transitioned beta users of LTI 1.3 to opening PrairieLearn in a new tab instead of an iframe in Canvas.

Add a Content-Security-Policy header

---

apps/prairielearn/src/ee/lib/billing/plans.ts
apps/prairielearn/src/lib/features/manager.ts
apps/prairielearn/src/lib/server-jobs.ts
apps/prairielearn/src/lib/timezones.ts
apps/prairielearn/src/lib/workspaceHost.ts
apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.ts
apps/prairielearn/src/tests/chunks.test.js
apps/prairielearn/src/tests/instructorAssessmentGroups.test.ts
apps/prairielearn/src/tests/utils/auth.ts
apps/prairielearn/src/tests/workspaceHost.test.js
packages/migrations/src/batched-migrations/batched-migration-job.ts
packages/migrations/src/batched-migrations/batched-migration-runner.test.ts
packages/migrations/src/batched-migrations/batched-migration-runner.ts
packages/migrations/src/batched-migrations/batched-migration.ts
packages/migrations/src/batched-migrations/batched-migrations-runner.ts

This sets us up to remove `queryValidated*` and `callValidated*` in a future PR.

Remove usage of legacy queryValidated functions

---

apps/prairielearn/src/pages/authCallbackOAuth2/authCallbackOAuth2.js
apps/prairielearn/src/pages/authCallbackShib/authCallbackShib.js
apps/prairielearn/src/pages/authLoginOAuth2/authLoginOAuth2.js
apps/prairielearn/src/server.js

This keeps these errors out of Sentry and our load balancer error metrics.

Respond with 404 if Shibboleth/OAuth login disabled

---

.changeset/shiny-gifts-smell.md
apps/prairielearn/src/lib/sentry.ts
apps/prairielearn/src/pages/authCallbackOAuth2/authCallbackOAuth2.js
packages/sentry/src/index.ts

I noticed that `configureScope` was flagged as deprecated in my editor while reviewing the OAuth code.

Replace deprecated configureScope with getCurrentScope

---

apps/prairielearn/src/lib/course.ts

This allows us (or instructors) to get back to a known good state if we ever change the branch for their course. Previously, this would require manual intervention on disk by an admin.

Always check out configured branch when syncing course

---

apps/prairielearn/src/middlewares/content-security-policy.ts

This semicolon was added accidentally; it's unnecessary and in fact causes problems. CSP docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

Fix formatting of Content-Security-Policy header

---

apps/prairielearn/src/migrations/20240123213531_group_user_roles__cascade_deletes.sql
database/tables/group_roles.pg
database/tables/group_user_roles.pg
database/tables/groups.pg
database/tables/users.pg

Closes #9270.
I spot-checked all other group-related tables for missing `ON DELETE CASCADE` and didn't find any, so this should be all we need.

Cascade updates/deletes to group_user_roles table

---

apps/prairielearn/src/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js
apps/prairielearn/src/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql

Closes #9275. The list of roles assigned to each user is listed as an array in a new column in the "_groups.csv" downloaded file.

Include roles in groups download

---

apps/prairielearn/src/pages/instructorAssessmentQuestions/instructorAssessmentQuestions.ejs

As reported on Slack. This was causing issues on the assessment questions page for any assessment that had valid submissions and where stats had been calculated in some point (i.e., the histogram has values).

Fix variable name in assessment questions page

---

apps/prairielearn/src/middlewares/selectAndAuthzInstanceQuestion.js

This middleware is also used in the manual grading page, so this check should not be enforced for instructors.

Fix: allow instructors to open instance questions with invalid roles

---

apps/prairielearn/src/lib/groups.ts

After #9106, add group functionality was sent to a single lib function. This function didn't properly handle cases where the group maximum is undefined (unlimited). This case was causing a Zod error, as reported on Slack. This PR changes this, and ensures that group maximums are not applied if they don't exist.

Fix group adding functionality in assessments with no group maximum

---

apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/gradingPanel.html.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.html.ts

As discussed on Slack. The type of the graders object was incorrect, and it was using the wrong function. This meant the page didn't list the buttons to assign a question to a different grader.
Also, the buttons to assign to a different grader is also added to the conflict modal, allowing a conflict to be handled by a different staff member more easily.

Fix manual grading assign to other grader button

---

apps/prairielearn/src/server.js
apps/prairielearn/src/tests/helperServer.ts

This PR aims to fix flaky tests that we've observed since upgrading to Node 20.
As best as I can tell, our `helperServer.after` function would hang on actually closing the HTTP server. `HttpServer#close` waits for all connections to close before actually closing the server, but in our tests, there are a lot of scenarios where we `fetch()` something and never actually do anything with the response body. Non-deterministically, this results in the connection staying open, which in turn keeps the server from stopping immediately. It will eventually stop after `keepAliveTimeout` elapses (65 seconds), but this isn't fast enough to complete before Mocha decides that our shutdown step exceeded its timeout.
I honestly can't say why this only started happening after upgrading to Node 20. It's …

Fix flaky tests

---

.gitignore
.prettierignore
.vscode/settings.json

This PR adds an opinionated `.vscode/settings.json` file. Committing this to the repository is by no means optimal, as it makes doing local customization of this config more difficult. However, we feel the benefits of getting a functioning editor out-of-the-box outweigh the downsides. Hopefully the VSCode folks address https://github.com/microsoft/vscode/issues/40233 so we can get the best of both worlds.

Add .vscode/settings.json

---

.dockerignore

This file gets really big when PL runs for a long time during development (3.5GB for me). Trying to run `docker build ...` results in this file needlessly being included in the image. This PR ensures it isn't.

Add apps/prairielearn/server.log to .dockerignore

---

apps/prairielearn/src/lib/regrading.js
apps/prairielearn/src/lib/regrading.sql

This was incorrectly declared as `.optional()` instead of `.nullable()`, meaning we errored out if someone tried to regrade a group assessment instance (which doesn't have an associated user).

Fix Zod schema in assessment regrading

---

docs/python-grader/index.md

These headings were at the page title level instead of a section level, causing them not to be added to the TOC.

Fix heading levels in Python grader docs

---

apps/prairielearn/src/lib/features/index.ts

This feature flag is currently a no-op. I'm adding it independently so that we can get the appropriate feature grants in place before we make it actually do anything.

Add allow-rpy2 feature flag

---

apps/prairielearn/python/prairielearn.py

`to_json`, `from_json` do actually track sympy assumptions (since #7020); so, here's a PR to remove outdated comments saying they don't, which I found confusing.

remove outdated comments about sympy assumptions from {to,from}_json

---

docs/installingLocal.md

Two minor doc changes here, one of which confused me more than the other:
- A lot of people use M1/M2 macs, but the command listed here will give an error if you're on one (#8142). I added a pointer on what to do, but I guess it probably wouldn't hurt to just always include the `--platform` argument?
- My guess is a lot of people just copy-paste the docker line without paying too much attention and then get an error message about `/path/to/PrairieLearn` not existing. I suggest changing it to `.`, which is pretty likely to work where they're trying to run it from, and also makes it clear that a relative path is fine.

clarify docker instructions

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/lib/question-render.js
apps/prairielearn/src/lib/question-render.sql
apps/prairielearn/src/lib/question-testing.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ts
apps/prairielearn/src/pages/instructorQuestionPreview/instructorQuestionPreview.js
apps/prairielearn/src/pages/publicQuestionPreview/publicQuestionPreview.ts
apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js

Updates `getAndRenderVariant`:
* Makes it async;
* Converts all calls to it to await;
* Use modern query functions, with schemas.
While I used types in a few random spots, I didn't spend a lot of time working on those in the variables involved in res.locals. This can be done in the future.

Modernize variant rendering library function

---

apps/prairielearn/python/python_helper_sympy.py
apps/prairielearn/python/python_helper_sympy_test.py

This is the better solution to the student confusion that sparked #9322 (oh well):
In my case, I had a custom function `B(x)`. Two students who didn't really understand what was going on tried to write things like `1/B * x` in their answer, and were confused by the error message that `B` was an invalid variable name ("how am I supposed to write the answer???"). This makes it clearer.
(Not super happy with either the class name or the wording of the error message, very happy to hear better suggestions.)

symbolic: add a more specific error if someone tries to do `cos*x`

---

apps/prairielearn/src/news_items/006_manual_feedback/index.html
apps/prairielearn/src/news_items/041_element_question_writing/index.html
apps/prairielearn/src/news_items/043_units_element/index.html

Alt text added to screenshot images included with three news items to satisfy WCAG 2.1 level A 1.1.1 Non-text Content ("Image missing a text alternative").
Files formatted with prettier.

alt text to images in news items for accessibility, prettier'd this time

---

graders/python/requirements.txt
images/plbase/python-requirements.txt
workspaces/jupyterlab-python/requirements.txt

Pandas now prints a deprecation warning if `pyarrow` is not installed, as it will become a required dependency in Pandas 3.

Upgrade pandas, install pyarrow

---

apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ts

When rubric settings are set, if there are no rubric items, an error is supposed to show "No rubric items were provided". Due to a Zod issue, though, this error was not properly shown, rather a "System error" was returned with an issue being reported in Sentry. This PR fixes the Zod schema so that the error can be properly handled by the custom check instead of the Zod handler.

Fix handling of rubric settings with no items

---

graders/python/install.sh

The recent change to use AL2023 as the base image in #9373 meant that we were missing `su` and `uuidgen`. These are both provided by the `util-linux` package, which was installed as a dependency of one of other other installs in AL2, but not anymore in AL2023. This PR explicitly installs this package.
I've verified that we can successfully grade python questions with this change.

Explicitly install util-linux in graders/python

---

.github/workflows/main.yml
Dockerfile
images/executor/Dockerfile

My usage of `PRAIRIELEARN_IMAGE_TAG` before was just flat-out wrong, so we were always defaulting to `latest` in the Dockerfiles changed here. In practice, we never really noticed a difference, but the change here is still objectively the correct thing to do.

Use correct base images in CI

---

apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ts

As reported on Slack. In situations with 22 or more rubric items are selected, a Zod error was shown. This was caused the library used to parse the body (`qs`), which will use an object instead of an array when the index is any number over 20.
While it is possible to change `qs` to increase the array limit, any specified limit would be arbitrary. Instead, objects were embraced with a direct transformation into an array using `Object.values` (given the order of the array elements is not important).

Fix handling of rubric grading with more than 22 selected items

---

images/plbase/plbase-install.sh

See inline comment for the majority of the details.
For posterity: another approach we considered was setting `LD_LIBRARY_PATH` in the PrairieLearn `Dockerfile`:
```
ENV LD_LIBRARY_PATH="/usr/local/lib64:/usr/local/lib:/usr/lib64:/usr/lib:/lib64:/lib"
```
However, we felt this was much riskier than this more targeted approach. Famous last words, but this change should be very safe, as version `6.0.32` of the `libstdc++` supports all of the the same `GLIBCXX` symbols as `6.0.29`, in addition to the newer ones that `rpy2` relies on.
I'll test the built image before we merge this.

Fix rpy2 with libstdc++ symlink

---

apps/prairielearn/src/migrations/20240206175554_users__drop_scheduler_columns.sql

These columns were added to PrairieLearn tables by the legacy CBTF scheduler in some of our production environments. Let's get rid of them!

Drop legacy scheduler columns

---

docs/installing.md

This will be necessary until we can build a multi-platform image with ARM64 support.

Add note in docs about running on Apple Silicon Macs

---

apps/prairielearn/src/admin_queries/generate_assessment_instances.sql
apps/prairielearn/src/admin_queries/generate_assessment_instances_group.sql
apps/prairielearn/src/sprocs/assessment_instances_insert.sql
apps/prairielearn/src/sprocs/assessment_instances_regrade.sql

In some very narrow scenarios it is plausible for a student to create an assessment instance and not open it right away (e.g., in case of network interruption between the new instance POST operation and the GET that first opens the assessment instance). For Homeworks, this could cause a scenario that does not have instance questions or points.
This PR causes the update operation (which creates instance questions and updates points) to always be executed on assessment instance creation, regardless of assessment type. This will have the minor inconvenience that the update operation will run twice on start (once when it's created during POST, once in the redirected GET), but the second update will in essence be a no-op, and as a bonus the assessment instance data will be retained from the …

Update instance questions and points on assessment instance insert

---

apps/prairielearn/src/lib/question-render.js
apps/prairielearn/src/pages/partials/submissionInfoModal.ejs

Fixes #9403. The code assumed that the dates were strings, and explicitly parsed them, but recent updates caused Zod parsing to convert them to dates instead. ~~This is solved by parsing using `DateFromISOString`, which will properly parse if the value is string and use the Date object itself if it had already been parsed.~~ Given all cases where this function is called are already parsed with Zod, no additional parsing is needed.
This PR also fixes the handling of this box when there are timestamps still set at null. Before:
After:

Fix computation of grading phase durations in submission info box

---

apps/prairielearn/src/lib/workspaceHost.sql

For reasons that I cannot fathom, `workspace_logs.version` defaults to 1, so this silently took that default instead of failing 🙃

Add missing version to workspace logs

---

apps/prairielearn/src/sync/performance.ts

This PR only renames the file and adds enough typing to allow typechecks to pass. A follow-up PR will change the content. This is done to preserve rename history.

Convert sync performance util to TypeScript

---

apps/prairielearn/src/sync/performance.ts
apps/prairielearn/src/sync/syncFromDisk.ts

Follow-up to #9421. Adds better types, removes unnecessary JSDoc comments, removes deprecated (and unused) callback function.

Modernize performance sync library

---

docs/accessControl.md
docs/faq.md

We briefly considered changing the behavior to make workspaces inaccessible when `"active": false` is in effect, but we realized that some courses actually rely on the current behavior for review sessions. So, we're opting to explicitly document the current behavior for now.
In the future, we may consider adding something like `"workspacesAccessible": false` to `allowAccess` to allow instructors to explicitly control the behavior.

Document that workspaces aren't affected by active: false

---

graders/python/requirements.txt
images/plbase/python-requirements.txt

Now that we're using Amazon Linux 2023 everywhere, we can safely upgrade to this latest version everywhere.

Upgrade to pygraphviz 1.12

---

apps/prairielearn/elements/pl-matrix-input/pl-matrix-input.mustache

Before:
After:
An alternative would be to add horizontal scrolling, but IMO this works better, especially on smaller viewports.

Wrap pl-matrix-input answer/submission

---

apps/prairielearn/src/api/v1/endpoints/queries.sql

This change would expose the `modified_at` field of the `assessment_instances` table in the following endpoints:
- `/pl/api/v1/course_instances/:course_instance_id/assessments/:assessment_id/assessment_instances`
- `/pl/api/v1/course_instances/:course_instance_id/assessment_instances/:assessment_instance_id`
We have historically been fetching submissions multiple times a day using the assessment instance submissions API for our grade report system and we'd like to move to a more sustainable solution. 
This field should allow us to fetch only assessment instances that have been modified (i.e. changed scores) since the last time we fetched, and should significantly reduce the number of API calls needed to have up-to-date submission data.

Add modified_at to assessment instance API

---

apps/prairielearn/src/lib/workspace.ts
docs/workspaces/index.md

Currently workspace dynamic files without either a "contents" property or a "questionFile" cause the file to be an empty file. This, however, is subject to silent errors, as instructors may mistakenly miss the contents property (a recent case saw a typo in this property), which causes a silent issue.
This PR changes the process to create an issue in this context. The file is still created to ensure anyone that relies on this behaviour still has a working question.
This is a potentially breaking change, though affected cases are expected to be minimal (I don't expect many people to have empty files as dynamic files), and the "break", if it happens, causes at most new issues to be raised, with a simple fix of setting content to None/blank to avoid the issue.

Require workspace dynamic files to set contents explicitly

---

docs/installing.md

It seems like QEMU emulation isn't working will with the copy of Postgres that's embedded in our image, as Postgres fails to start with the following error:
```
pg_ctl: could not start server
```
Enabling Rosetta emulation has helped in several of these cases, so I figured I'd add it to our docs.

Document the need for Rosetta emulation on Apple Silicon

---

apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.sql

The Zod schema declares this is a `z.number().nullable()`, which will reject the string `bigint` that `count(...)` produces by default.

Fix manual grading instances.json

---

Makefile
pyproject.toml

This has two benefits:
- Discovering tests is now basically instantaneous. Before, it took quite a while, presumably because it was searching in every single directory.
- This appears to solve the module resolution issues we were facing with pytest 8 (https://github.com/PrairieLearn/PrairieLearn/pull/9508). I don't entirely understand why; maybe `testpaths` gets added to `PYTHON_PATH` somehow?

Define testpaths for pytest in pyproject.toml

---

packages/actions-report-image-sizes/src/index.ts

Fixes the issue described here: https://github.com/PrairieLearn/PrairieLearn/pull/9302#issuecomment-1977227141
See the inline comment for more details. It's unfortunate that Docker Hub responds with a 401 instead of a 404 in this case.

Handle missing images when reporting image sizes

---

apps/prairielearn/src/lib/db-types.ts

This is based on an observed error in our production environment: https://prairielearn-inc.sentry.io/issues/5023961427
Here's the relevant instance question and variant: https://us.prairielearn.com/pl/course_instance/147365/instance_question/361768852?variant_id=90904775
I haven't yet spent much time trying to understand exactly why this ended up with null entries, or if that's a valid state. It's possible that we actually _don't_ want to allow null items, in which case we should trace down where the null item came from and fix that.
From a quick look at the question, there was an error in v2 question grading code, and it's plausible that this could've resulted in a `null` value being introduced and passed around.

Allow null items in instance_question.variants_points_list

---

apps/prairielearn/src/lib/instructorFiles.js
apps/prairielearn/src/pages/instructorFileBrowser/instructorFileBrowser.js
apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.js

When `getPaths` threw an error, it would crash the entire server, as there was nothing to catch the error. This is because it was designed for callback usage, which expects functions to only pass errors to the callback instead of throwing them. At some point, we refactored `getPaths` to sometimes throw errors, which slipped through review.
Rather than changing the whole function back to just callbacks, I opted to introduce a wrapper that handles propagating errors back to callbacks. As we refactor the callsites of `getPathsCallback`, we can replace it with plain `getPaths`.

Fix getPaths for instructor file editor

---

apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts

We sometimes hit cases where an institution has multiple courses with the same `short_name` and `title`. This change will allow us to differentiate between them.
There are other bits of the UI where this change could be nice, e.g. the institution admin pages. I'm not going to touch those just yet.

Show course repository/path in feature editor

---

apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts
apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.sql

Followup to #9558. @mwest1066 pointed out on Slack that course ID is probably a better differentiator here, as it's guaranteed to be unique, doesn't require us to have remote repositories, and matches the fact that we anyways want to move course paths on disk to be based on the course ID.
While I was at it, I added ID display to institutions and course instances as well.

Show IDs in feature editor

---

exampleCourse/questions/demo/workspace/dynamicFiles/question.html
packages/workspace-utils/src/index.ts

This is necessary because of https://github.com/archiverjs/node-archiver/issues/743. For as long as `archiver` doesn't correctly support backslashes in file names, we'll have to disallow them.

Don't allow submitted workspace file paths to contain backslashes

---

apps/prairielearn/src/lib/config.ts
apps/prairielearn/src/lib/workspace.ts
apps/workspace-host/src/interface.js

The issue behind #9563 was made much worse by the fact that the error actually crashed the server because we weren't handling `error` events correctly. This PR improves that so if we get another similar error, it will at least fail somewhat gracefully and show _some_ kind of error to the user instead of just 502ing.

Improve error handling when getting workspace graded files

---

yarn.lock

Resolves https://github.com/PrairieLearn/PrairieLearn/security/dependabot/155.

Bump undici to 5.28.3

---

docs/accessControl.md

This is based on feedback that this documentation wasn't as clear as it could be. Specifically, there was confusion regarding whether or not this controlled visibility of the assessment on the assessments page. I hope these new docs are a little clearer.

Improve docs for the active property in access rules

---

apps/prairielearn/elements/pl-drawing/elements.py

These defaults have always been invalid, but they would have silently failed before #8174. But after that PR, which changed from `(for i = 0; i < thing.length, ...)` to `(for foo of thing)`, it fails loudly, because the defaults (which are objects) are not iterable.

Fix defaults for supporting-lines and grid-label

---

docker/start_s3rver.sh

Every time I get a new computer I spend way too long trying to figure out why tests that rely on S3 aren't working, and every time I remember it's because macOS listens on port 5000 by default when "AirPlay Receiver" is enabled (which it is, by default!). This change to the script will hopefully help the next person who runs into this.

Improve start-s3ver script

---

apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.html.ts

In the fingerprint popover, the link to `client.rdap.org` has a target of `blank` instead of `_blank`. This mean clicking two different links would open them both in the same tab.
Also took the opportunity to ensure the content was properly quoted/escaped.

Fix link for IP address in fingerprint popover

---

apps/prairielearn/src/pages/instructorAssessmentAccess/instructorAssessmentAccess.html.ts
apps/prairielearn/src/pages/instructorAssessmentAccess/instructorAssessmentAccess.sql
apps/prairielearn/src/schemas/schemas/infoAssessment.json
apps/prairielearn/src/sprocs/check_assessment_access_rule.sql
apps/prairielearn/src/sprocs/ip_to_mode.sql
apps/prairielearn/src/sync/fromDisk/assessments.js
apps/prairielearn/src/sync/fromDisk/assessments.sql
docs/accessControl.md
docs/remoteExams.md
docs/workshop/lesson2.md

I started cleaning up `ip_to_mode` for some unrelated changes; figured I'd do all the cleanup as long as I was at it.

Remove references to the legacy CBTF scheduler

---

apps/prairielearn/src/lib/question-submission.ts

This will keep such errors out of Sentry, where they aren't actionable.

Use 4XX status code when rejecting submissions to broken variants

---

packages/workspace-utils/src/index.ts

This PR works around https://github.com/nodejs/node/issues/52159, which we hit in production because VSCode workspaces create a Unix domain socket for IPC.

Fix readdir operation for workspace disk usage

---

apps/prairielearn/src/batched-migrations/20240320000007_workspaces__disk_usage_bytes__backfill.ts
apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/migrations/20240320000007_workspaces__disk_usage_bytes__backfill.ts
packages/workspace-utils/src/index.ts

Followup to #9576 to backfill `workspaces.disk_usage_bytes` for all existing rows.

Backfill workspace disk usage

---

apps/prairielearn/src/admin_queries/upcoming_exams.sql
apps/prairielearn/src/models/course-instances.sql
apps/prairielearn/src/pages/enroll/enroll.sql
apps/prairielearn/src/pages/home/home.sql
apps/prairielearn/src/pages/instructorAssessmentAccess/instructorAssessmentAccess.sql
apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.sql
apps/prairielearn/src/pages/instructorInstanceAdminAccess/instructorInstanceAdminAccess.sql
apps/prairielearn/src/pages/instructorQuestionStatistics/instructorQuestionStatistics.sql
apps/prairielearn/src/sprocs/check_assessment_access.sql
apps/prairielearn/src/sprocs/check_assessment_access_rule.sql
apps/prairielearn/src/sprocs/check_course_instance_access.sql
apps/prairielearn/src/sprocs/check_course_instance_access_rule.sql
apps/prairielearn/src/sprocs/sync_assessments.sql
apps/prairielearn/src/sprocs/sync_course_instances.sql

Contains the same changes as #4659, just without the migration that removes the columns. We can only safely apply that once nothing is reading from these columns.

Remove all references to access rule role columns

---

apps/prairielearn/src/pages/partials/question.ejs
apps/prairielearn/src/pages/publicQuestionPreview/publicQuestionPreview.ts

The public question preview page was showing the "Copy question" button for template courses, but the button wasn't actually doing anything because `question_copy_targets` wasn't defined. This PR makes the button work.

Allow copying template course questions from public sharing page

---

apps/prairielearn/src/api/v1/index.js
apps/prairielearn/src/server.js

Our API router terminates the error-handling process, so our usual Sentry error handle would never be used. This PR inserts the handler such that it'll also run for API errors.

Handle API errors with Sentry

---

apps/prairielearn/src/sprocs/workspace_loads_current.sql

Closes #9620. I did not implement rate limiting of new workspace host creation because I don't actually think that's necessary now that we don't have the load from dozens of hosts creating sprocs at the same time. @mwest1066 let me know if there are other factors that would still make such rate limiting desirable.

Improve workspace capacity calculation

---

apps/prairielearn/src/pages/administratorJobSequence/administratorJobSequence.html.ts
apps/prairielearn/src/pages/administratorQuery/administratorQuery.html.ts
apps/prairielearn/src/pages/authLogin/authLogin.html.ts
apps/prairielearn/src/pages/editError/editError.ejs
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/gradingPanel.html.ts
apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.ejs
apps/prairielearn/src/pages/instructorAssessments/instructorAssessments.ejs
apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.html.ts
apps/prairielearn/src/pages/instructorFileBrowser/instructorFileBrowser.ejs
apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.ejs
apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.ejs
apps/prairielearn/src/pages/instructorJobSequence/instructorJobSequence.ejs
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ejs
apps/prairielearn/src/pages/instructorQuestionStatistics/instructorQuestionStatistics.ejs
apps/prairielearn/src/pages/news_item/news_item.ejs
apps/prairielearn/src/pages/partials/assessmentSyncErrorsAndWarnings.ejs
apps/prairielearn/src/pages/partials/courseInstanceSyncErrorsAndWarnings.ejs
apps/prairielearn/src/pages/partials/courseSyncErrorsAndWarnings.ejs
apps/prairielearn/src/pages/partials/navbarInstructor.ejs
apps/prairielearn/src/pages/partials/navbarPublic.ejs
apps/prairielearn/src/pages/partials/questionSyncErrorsAndWarnings.ejs
apps/prairielearn/src/pages/studentAssessments/studentAssessments.ejs

Adding `role="button"` to links isn't advisable because it misrepresents the element to screen readers.

Fix misuses of role="button"

---

apps/prairielearn/src/lib/config.ts

Using `.refine()` didn't work because we parse an empty object to get default values:
https://github.com/PrairieLearn/PrairieLearn/blob/0208d4cc37d68deb8503eb54cfdf607b52c2ee2e/packages/config/src/index.ts#L96-L99
This means that we'd try to validate `null` before we got a chance to load any value from our config sources.

Fix validation of cookieDomain in config

---

docs/assessment.md

mkdocs seems to create the id in lowercase, so the link won't work as is.

Fix link to singleVariant option in assessment docs

---

apps/prairielearn/src/pages/instructorQuestionStatistics/instructorQuestionStatistics.js

This is the same change as #9704, just for the CSV download instead of the HTML table.

Add missing column to question stats CSV

---

apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/gradingPanel.html.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.sql
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ts

Closes #9678. Given many cases of manual grading involve resolving an issue raised by a student, this change allows the issue to be closed as the manual grading is submitted.
I chose to close the issue outside of the manual grading transaction, though I'm open to moving the logic to the manual grading process if that makes sense.

Add option to close related issues on manual grading

---

apps/prairielearn/src/ee/pages/institutionAdminCourse/institutionAdminCourse.html.ts
apps/prairielearn/src/ee/pages/institutionAdminCourseInstance/institutionAdminCourseInstance.html.ts
apps/prairielearn/src/ee/pages/institutionAdminCourses/institutionAdminCourses.html.ts
apps/prairielearn/src/ee/pages/institutionAdminLti13/institutionAdminLti13.ts
apps/prairielearn/src/pages/administratorCourses/administratorCourses.html.ts
apps/prairielearn/src/pages/administratorInstitutions/administratorInstitutions.html.ts
apps/prairielearn/src/pages/partials/navbarInstitution.ejs
apps/prairielearn/src/server.js
apps/prairielearn/src/tests/lti13.test.ts

This prepares us for the introduction of a separate hierarchy of institution pages for institution (not global) administrators. For now, we're going to retain these existing pages for global use, and then introduce new, simplified pages for institutional admins that reflect what should actually be visible/editable to them.

Move institution admin pages under administrator prefix

---

exampleCourse/questions/template/multiple-choice/numeric/server.py

If we were (un)lucky enough to select $a = 1.8$ and $b = 9$, we'd end up in a situation where the first two distractors were $7.2$. The easiest way to fix this was to adjust the range. I used the following code to verify that there weren't any more duplicate distractors:
```py
import numpy as np
for a in np.arange(2, 5.1, 0.1):
for b in np.arange(6, 12):
correct = round(a * b, 4)
distractor_1 = round((a - 1) * b, 4)
distractor_2 = round(b - a, 4)
distractor_3 = round((a + 1) * b, 4)
count_set = set()
count_set.add(correct)
count_set.add(distractor_1)
count_set.add(distractor_2)
count_set.add(distractor_3)
if len(count_set) != 4:
print("Duplicate found")
print(f"a: {a}, b: {b}")
print(f"correct: {correct}")
print(f"distractor_1: {distractor_1}")
print(f"distractor_2: {distractor_2}") …
```

Fix duplicate answers in template/multiple-choice question

---

graders/c/requirements.txt
images/plbase/python-requirements.txt

5.2.0 would produce a `SIGILL` when running under Rosetta x86 emulation.: https://bugs.launchpad.net/lxml/+bug/2059910. This is fixed in 5.2.1.

Upgrade lxml to 5.2.1

---

apps/prairielearn/src/lib/id.ts
apps/prairielearn/src/lib/paths.ts

Extracted from #8171. These conversions are needed there because of some dependencies that tsc complains about. These files have a very straightforward conversion.

Convert id and path libraries to Typescript

---

apps/prairielearn/python/question_phases.py
apps/prairielearn/python/zygote.py
exampleCourse/elements/course-element/course-element.py
exampleCourse/questions/demo/annotated/engMarkovBrewing/server.py
exampleCourse/questions/demo/computeRotationMatrix/server.py
exampleCourse/questions/demo/drawing/centroid/server.py
exampleCourse/questions/demo/drawing/collarRod/server.py
exampleCourse/questions/demo/drawing/frame-exploded/server.py
exampleCourse/questions/demo/drawing/gradeVector/server.py
exampleCourse/questions/demo/drawing/inclinedPlane-reaction/server.py
exampleCourse/questions/demo/drawing/inclinedPlane/server.py
exampleCourse/questions/demo/drawing/liftingMechanism/server.py
exampleCourse/questions/demo/drawing/pulley/server.py
exampleCourse/questions/demo/drawing/simpleTutorial/server.py
exampleCourse/questions/demo/drawing/vmDiagrams/server.py
exampleCourse/questions/demo/randomCheckbox/server.py
exampleCourse/questions/element/drawingGallery/server.py
exampleCourse/questions/element/dropdown/server.py
exampleCourse/questions/element/matrixComponentInput/server.py
exampleCourse/questions/element/matrixLatex/server.py
exampleCourse/questions/workshop/Lesson3_example3/server.py
exampleCourse/questions/workshop/Lesson5_example3/server.py
testCourse/elements/course-element/course-element.py
testCourse/questions/prairieDrawFigure/server.py

I'm doing this ahead of #9715. Skipping unnecessary JSON serialization will help with performance, even when using `orjson`.

Forbid returning different data object in zygote

---

apps/prairielearn/package.json
apps/prairielearn/src/ee/auth/saml/index.ts
apps/prairielearn/src/ee/pages/administratorInstitutionSaml/administratorInstitutionSaml.html.ts
apps/prairielearn/src/ee/pages/administratorInstitutionSaml/administratorInstitutionSaml.ts
yarn.lock

Every few months, I end up needing to decode/decrypt a SAML response, which sends me down a rabbit hole of trying to piece together a Node script to do that. I've done this enough that I felt it was worth my time to build this into PL. This automatically applies the correct private key, configured validation options, etc.

Add admin tool to decode SAML responses

---

apps/prairielearn/src/pages/error/error.js
apps/workspace-host/src/interface.js

With the race condition described in the inline comment, we'd end up hitting this bit of code:
https://github.com/PrairieLearn/PrairieLearn/blob/6e0957b5e380558b14bbace37b3efd55d09e5618/apps/prairielearn/src/server.js#L376
This would render a very ugly page to the user:
Originally discussed on Slack: https://prairielearn.slack.com/archives/C266KEH9A/p1713409158958589

Fix race condition in workspace launching

---

apps/prairielearn/src/pages/instructorAssessmentQuestions/instructorAssessmentQuestions.html.ts

As reported by @firasm on Slack. The EJS file was missing a variable.

Fix issue badge processing in assessment questions page

---

apps/prairielearn/package.json
yarn.lock

The bootstrap types package was at version 5, but PL is not currently using version 5 yet. This caused a mismatch in a recent development branch for me.

Downgrade bootstrap types version to match bootstrap itself

---

apps/prairielearn/src/ee/routers/lti13.ts
apps/prairielearn/src/lib/assets.ts
apps/prairielearn/src/lib/chunks.ts
apps/prairielearn/src/lib/file-paths.js
apps/prairielearn/src/middlewares/authn.js
apps/prairielearn/src/middlewares/authnToken.js
apps/prairielearn/src/middlewares/authzWorkspace.js
apps/prairielearn/src/middlewares/authzWorkspaceCookieCheck.js
apps/prairielearn/src/middlewares/authzWorkspaceCookieSet.js
apps/prairielearn/src/middlewares/csrfToken.js
apps/prairielearn/src/middlewares/selectAndAuthzAssessmentQuestion.js
apps/prairielearn/src/pages/authCallbackShib/authCallbackShib.js
apps/prairielearn/src/pages/authLoginOAuth2/authLoginOAuth2.js
apps/prairielearn/src/pages/authPassword/authPassword.js
apps/prairielearn/src/pages/clientFilesAssessment/clientFilesAssessment.js
apps/prairielearn/src/pages/clientFilesCourse/clientFilesCourse.js
apps/prairielearn/src/pages/clientFilesCourseInstance/clientFilesCourseInstance.js
apps/prairielearn/src/pages/clientFilesQuestion/clientFilesQuestion.js
apps/prairielearn/src/pages/editError/editError.js
apps/prairielearn/src/pages/elementExtensionFiles/elementExtensionFiles.js
apps/prairielearn/src/pages/elementFiles/elementFiles.js
apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.js
apps/prairielearn/src/pages/legacyQuestionFile/legacyQuestionFile.js
apps/prairielearn/src/pages/legacyQuestionText/legacyQuestionText.js
apps/prairielearn/src/pages/news_item/news_item.js
apps/prairielearn/src/pages/studentAssessmentInstanceFile/studentAssessmentInstanceFile.js
apps/prairielearn/src/pages/submissionFile/submissionFile.js
apps/prairielearn/src/question-servers/calculation-subprocess.js
apps/prairielearn/src/server.js

This brings us down to only 16 files using CJS!
```
Summary (16 files):
apps/prairielearn/src/executor.js: 3
apps/prairielearn/src/question-servers/calculation-worker.js: 3
apps/prairielearn/src/lib/require-frontend.js: 5
apps/prairielearn/src/pages/error/error.js: 5
apps/prairielearn/src/lib/ltiOutcomes.js: 7
apps/prairielearn/src/pages/authCallbackLti/authCallbackLti.js: 7
apps/prairielearn/src/pages/authCallbackOAuth2/authCallbackOAuth2.js: 7
apps/prairielearn/src/lib/code-caller/code-caller-native.js: 8
apps/prairielearn/src/lib/markdown.js: 9
apps/prairielearn/src/pages/studentSEBConfig/studentSEBConfig.js: 9
apps/prairielearn/src/pages/courseSyncs/courseSyncs.js: 10
apps/prairielearn/src/schemas/index.js: 14
apps/prairielearn/src/lib/code-caller/index.js: 15 …
```

Convert more files to ESM

---

apps/prairielearn/src/ee/pages/administratorInstitutionCourse/administratorInstitutionCourse.html.ts
apps/prairielearn/src/ee/pages/administratorInstitutionCourseInstance/administratorInstitutionCourseInstance.html.ts

I noticed that we were accidentally rendering `course.short_name` instead of `course_instance.short_name` in the admin pages. This PR fixes that.
I also opted to standardize on rendering course/instance names as `SHORT: LONG`:
This matches how we displayed things on the courses/instances admin pages.

Improve admin display of course and course instance names

---

apps/prairielearn/src/middlewares/date.js
apps/prairielearn/src/pages/studentAssessment/studentAssessment.js

This PR adds a few missing `// @ts-check` comments. I found these files with the following command:
```sh
grep -r -L "// @ts-check" apps/ | grep "\.js$" | grep -v "dist" | grep -v "prairielearn/public" | grep -v "prairielearn/v2-question-server" | grep -v "prairielearn/elements"
```

Improve TypeScript coverage

---

apps/prairielearn/src/tests/chunkAssessment.test.ts
apps/prairielearn/src/tests/groupGenerateAndDelete.test.ts
apps/prairielearn/src/tests/helperServer.sql
apps/prairielearn/src/tests/helperServer.ts
apps/prairielearn/src/tests/instructorQuestions.test.sql
apps/prairielearn/src/tests/serverJobs.test.ts

The callback versions were not in use anyway, so callback functions were removed and async functions were renamed. Also removed some other unused related code.

Remove unused callback functions in test helper code

---

apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.ts
apps/prairielearn/src/pages/publicQuestionPreview/publicQuestionPreview.ts
apps/prairielearn/src/pages/publicQuestions/publicQuestions.ts
apps/prairielearn/src/server.js

More native ESM prep; `export =` isn't supported there.

Replace export = with export default

---

apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts

The type had the same name as the one of the types in db-types, I renamed to avoid confusion.

Rename Sharing Set Info type to avoid type name duplication

---

apps/prairielearn/src/lib/externalGraderCommon.js
apps/prairielearn/src/lib/externalGraderLocal.js
apps/prairielearn/src/lib/externalGraderSqs.js

Also replaced calls to `fsExtra` functions to `fsPromises` where an appropriate alternative exists. `fsExtra.copy` was kept because [`fsPromises.cp` is still tagged as experimental](https://nodejs.org/api/fs.html#fscpsrc-dest-options-callback).
Review hiding whitespaces.

Convert external grader common library to async

---

apps/prairielearn/src/pages/partials/instructorInfoPanel.ejs

Don't show 'shared-as' if course sharing name hasn't been picked

---

docs/installing.md

The network tweak for Linux, and the fix for ARM Macs, were missing from the extended workspace invocations.

Update installing.md - clarify instructions for Linux and ARM Macs

---

apps/prairielearn/src/pages/instructorGradebook/instructorGradebook.js

It seems that the `course_id` parameter is needed for the `user_scores` query but not the `course_assessments` query.

Update instructorGradebook.js: omit unused course_id

---

.eslintrc.cjs
apps/prairielearn/src/lib/externalGraderCommon.js
apps/prairielearn/src/lib/workspace.ts

This should close #9842. `import * as fs from 'fs-extra` doesn't work as expected for this module, even though the types say they do. `import fs from 'fs-extra'` works correctly, and is in fact [one of the documented ways](https://github.com/jprichardson/node-fs-extra?tab=readme-ov-file#esm) to use this library with native ESM.

Fix fs-extra imports

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/pages/authCallbackLti/authCallbackLti.js

I broke this in #9384. There were multiple `results` variables shadowing each other, _and_ there wasn't type-checking in play, so this slipped through the cracks. This wasn't caught immediately and visibly in prod because `lti_outcomes` is one of our horrible old tables that lacks `NOT NULL` constraints, so we ended up with rows with null `user_id` columns, which broke things downstream.

Fix LTI 1.1 auth callback

---

apps/prairielearn/src/lib/question-render.js
apps/prairielearn/src/lib/question-render.sql

This fixes a regression from #6105.
To reproduce the error on master:
- Open an external grading question in student view (I used "External Grading: Alpine Linux smoke test" on HW9 in `testCourse`
- Submit an answer
- Observe that the page doesn't update in real time
- Observe the error in the logs
Repeat with this branch to see things working correctly.
Long-term, this will all by TypeScript, and we'll be able to have `tsc` tell us whenever we mess this up (because we mess this up pretty regularly!).

Fix real-time rendering of question score panel

---

apps/prairielearn/assets/scripts/question.ts
apps/prairielearn/src/lib/externalGradingSocket.js
apps/prairielearn/src/tests/gradingMethods.test.ts

Resolves #9852. Also adds some basic functionality in the question page, to make sure a console message is printed and the socket is closed if the panel rendering has any exception.

Add CI test for external grader socket results

---

apps/prairielearn/src/tests/accessibility/index.test.ts

I originally set out to reorder `disableInstrumentations()` until after all imports, which reflects what happens at runtime thanks to import hosting. However, I also tried just removing it, and everything still works as expected, so I opted to go that simpler route instead!

Remove disableInstrumentations call from accessibility tests

---

.eslintrc.cjs
.git-blame-ignore-revs
apps/prairielearn/src/server.js

This copies our `import/order` config from PrairieTest. This will be merged after #9857.

Add ESLint config to order imports

---

.changeset/nine-apes-taste.md
packages/opentelemetry/src/commonjs-preloads.ts

I neglected to do this during the ESM transition, which means that we currently have incomplete instrumentation for monkey-patched modules. This was failing to work because `require()` isn't defined in ESM modules. I made the error handling more precise to ensure that any similar errors will fail loudly in the future.

Fix OpenTelemetry CJS preloads

---

.codecov.yml

This should make Codecov less chatty and prevent it from adding failing status checks to PRs. I don't think we're ready to commit to a certain coverage percentage; we really just want to make it easy to see/track how many lines are covered.

Improve Codecov config

---

docs/sync.md

Fixed small typo in docs/sync.md. 
Before, it read: "If you wish, you can use continuous integration services to automatically test and validate changes yo your content.". 
Now, it reads: "If you wish, you can use continuous integration services to automatically test and validate changes to your content.

Fix small typo in docs/sync.md

---

apps/prairielearn/package.json
yarn.lock

Alternative to #9876. Avoids the dependencies for jsdom and canvas and all their subdependencies.

Use browser-specific version of fabric

---

packages/formatter/.mocharc.cjs
packages/formatter/package.json
packages/formatter/src/date.test.ts
packages/formatter/src/date.ts
packages/formatter/src/index.ts
packages/formatter/tsconfig.json
yarn.lock

This function has existed for some time in PrairieTest, but now we need it in PrairieLearn for #9103! Moving it to a package that can be used in both places ensure that we won't have duplicate implementations in the long run.
cc @mylesw27 since we talked about you doing this in an upcoming PR, let's land this one first so that other changes aren't blocked on your own larger PR!

Introduce formatter package with formatDate function

---

apps/prairielearn/src/pages/instructorCourseAdminSharing/instructorCourseAdminSharing.html.ts

Fixes error introduced in final commit of #9860, where the input box was accidentally moved outside of the form tag.
The error wasn't caught by tests because it doesn't affect calling the endpoint from code,
only submitting the form in the webpage itself.
@Michael-Holmes-SDE feel free to leave a review on this as well.

Fix broken form for choosing sharing name

---

apps/prairielearn/src/pages/error/error.js

Before this change, the error page would error out with the following in production:
```
ReferenceError: /Users/nathan/git/PrairieLearn/apps/prairielearn/src/pages/error/error.ejs:48
46|           <% } %>
47| 
>> 48|           <% if (errorStack) { %><p><strong>Stack trace:</strong></p><pre class="bg-dark text-white rounded p-2"><%= errorStack %></pre><% } %>
49| 
50|           <% if (error.data && error.data.sqlError) {%>
51|           <p><strong>SQL error:</strong></p><pre class="bg-dark text-white rounded p-2">error: <%= error.data.sqlError.message %>
errorStack is not defined
```

Fix error page in production

---

apps/prairielearn/src/lib/instructorFiles.js
apps/prairielearn/src/lib/uri-util.js
apps/prairielearn/src/pages/instructorFileDownload/instructorFileDownload.js
apps/prairielearn/src/tests/fileEditor.test.ts

Fixes #9906. Processing of file paths was decoding the URI components, but Express [already takes care of that](https://expressjs.com/en/api.html#req.params). This would cause issues in paths that included `%` symbols in its decoded form.
Also simplifies and adds types to `encodePath`, and removes the (now unnecessary) `decodePath` function.
Pending: add a CI test to ensure this is handled as expected.

Fix double decoding of instructor files

---

apps/prairielearn/src/lib/editors.ts
apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ts
apps/prairielearn/src/pages/instructorFileBrowser/instructorFileBrowser.js
apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.js

This is a prerequisite for #9894. See discussion here: https://github.com/PrairieLearn/PrairieLearn/pull/9894/files#r1613905518
In short, to avoid a TOCTOU bug, we need the `shouldEdit()` check to run with the course lock held, and for it to run after we've pulled in new changes from the remote. This PR achieves that by making the `Editor` class has a `shouldEdit()` function that it will call on itself when it wants to check if a write is safe.

Make shouldEdit() part of the Editor API

---

apps/prairielearn/elements/pl-rich-text-editor/info.json
apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js
apps/prairielearn/package.json
yarn.lock

As per https://quilljs.com/docs/upgrading-to-2-0, some adjustments were necessary:
* Update call to `convert`;
* Embed class has a different method of importing;
* `dist/quill.js` is now the minified version, so `dist/quill.min.js` no longer exists.
This update has been tested locally and works as expected. It may break any custom element that depends on the previous version of quill, though.

Upgrade quill to v2.0.2

---

docs/assessment.md

This makes the header capitalization in the docs consistent with the other headers in the same file.

Fix capitalization of section in assessment docs
