mkdocs.yml

Make it consistent with other entries in the table of contents.

Fix capitalization of sharing header in docs contents

---

apps/prairielearn/src/pages/partials/instructorInfoPanel.ejs

I noticed this was broken while testing another PR. When in the "no variant was created" mode, the `studentInstanceQuestion` page worked fine when viewed as a student, but failed when we tried to render the `instructorInfoPanel` in instructor mode.

Ensure "no variant" page renders for instructors

---

apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts
apps/prairielearn/src/lib/instructorFiles.js
docs/PrairieDraw.md
docs/assessment.md
docs/clientServerFiles.md
docs/codeExecution.md
docs/course.md
docs/elements.md
docs/questionSharing.md
docs/regrading.md

I was reading through some documentation and stumbled upon some minor typos. Two were found in the code but they're very small.

Fix typos in docs and code

---

apps/prairielearn/src/ee/auth/saml/index.ts
apps/prairielearn/src/pages/instructorCourseAdminInstances/instructorCourseAdminInstances.ts

When PrairieLearn cannot found course Path in /pl/course/:course_id(\d+)/course_admin/instances
PrairieLearn will crash.

Fix unawaited promise on course instances page

---

apps/prairielearn/src/ee/auth/saml/index.ts

Fix SAML still works when disabled SAML but well configuration. 
While SAML single sign-on providers are disable, even though the login entry is no longer displayed on the login page, it can still work on /pl/auth/institution/xxx/saml/login (However in the last judgment, user still unable to log in on users_select_or_insert.sql)
Code changed to add checking if saml is disable.

Fix SAML still try to work when disable SAML but well configuration

---

apps/prairielearn/src/ee/pages/administratorInstitutionGeneral/administratorInstitutionGeneral.ts

Updates the flash response on an institution save to imply it's updating not only enrollment limits.

fix: institution save flash response

---

images/plbase/plbase-install.sh

This ensures that images built in GitHub Actions will run on other machines. Specifically, this fixes an issue where `CREATE EXTENSION vector;` would fail with "Illegal instruction" on my Apple Silicon Mac.

Disable machine-specific optimizations for pgvector

---

docker/init.sh

Users that run PrairieLearn locally have commented on Slack about errors when running without workspaces enabled. This is caused by the fact that the workspace host assumes that Docker is available, but this is not the case in this context.
This PR checks if the Docker socket is available locally. If it's not, it runs only the main PrairieLearn code (not the workspace host), and prints a message on the terminal pointing instructors that wish to use external graders and workspaces to the appropriate link.
The text I propose is a suggestion, I'm open to changing it to make it clearer or (if expected) less intrusive.

User-friendly message on Docker if workspaces are unavailable

---

.github/workflows/main.yml
Dockerfile

This will allow us to debug package build failures like the one in https://github.com/PrairieLearn/PrairieLearn/actions/runs/9356677931/job/25754696479.

Use Yarn --inline-builds flag in image builds and CI

---

apps/prairielearn/src/pages/instructorFileBrowser/instructorFileRenameForm.ejs
apps/prairielearn/src/pages/partials/changeIdForm.ejs

The form used to change QID, AID, CIID uses the `pattern` attribute to validate IDs. However, this attribute requires a pattern that uses the `v` flag, see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern#overview (emphasis mine):
> The pattern's regular expression is compiled with the ['v' flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Character_class#v-mode_character_class). This makes the regular expression [unicode-aware](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode#unicode-aware_mode), and also changes how character classes are interpreted. This allows character class set intersection and subtraction operations, and in addition to ] and \, **the following characters …

Fix use of pattern in change id form

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/migrations/20240605165348_assessment_sets__not_null_constraints__add.sql
apps/prairielearn/src/tests/sprocs/check_assessment_access.test.sql
database/tables/assessment_sets.pg

I checked in our production databases and this table already satisfies these new constraints. Having this be safely reflected in our types will help out with refactoring some other pages.
I deliberately decided not to use the more complicated multi-step migration like the one in [`apps/prairielearn/src/migrations/20240111010531_groups__group_config_id__not_null.sql`](https://github.com/PrairieLearn/PrairieLearn/blob/bf96affaace6514e83c62cd828ad2083749fea06/apps/prairielearn/src/migrations/20240111010531_groups__group_config_id__not_null.sql). `assessment_sets` has less than 10k rows in all production environments so even if we hold a table lock, it'll be for a very short amount of time.

Add NOT NULL constraints to assessment_sets table

---

exampleCourse/questions/workshop/PeriodicTable1/question.html

The changes proposed are to eliminate the confusion that may arise when a student is faced with having to provide an answer for "atomic number" when in reality, the question expects the student to provide an answer about the "number of atoms".

Fix prompt in example chemistry question

---

apps/prairielearn/src/lib/db-types.ts

This was introduced in #9961 with an incorrect type.

Fix type for assessment_access_rules.mode

---

apps/prairielearn/src/lib/aws.js
apps/workspace-host/src/lib/aws.ts
docker/start_s3rver.sh
packages/aws/README.md

This should fix the CI failures like the one here: https://github.com/PrairieLearn/PrairieLearn/actions/runs/9485947777/job/26139121551?pr=10003
I'm not entirely sure what the actual root cause is, but here's what I observed:
- A lot of tests were failing with `ECONNREFUSED 127.0.0.1:5000`
- When running the original `node_modules/.bin/s3rver ...` command manually, it logs `S3rver listening on ::1:5000` (an IPv6 address)
- When I run `curl  http://localhost:5000`, I get a response from s3rver
- When I run `node -e "fetch('http://localhost:5000')"`, I get the same `ECONNREFUSED` we see in the test failures
- When I run `node -e ...` on my _local_ machine (macOS) outside the container, everything works as expected, even though s3rver is listening on an IPv6 address
- `node -e …

Force s3rver to listen on 127.0.0.1

---

packages/actions-report-image-sizes/package.json
packages/aws-imds/package.json
packages/aws/package.json
packages/cache/package.json
packages/config/package.json
packages/signed-token/package.json
yarn.lock

This will be required for compatibility with other package managers like `pnpm`.

Use workspace references for tsconfig package

---

apps/prairielearn/assets/scripts/instructorFileEditorClient.js
apps/prairielearn/elements/pl-file-editor/pl-file-editor.js
apps/prairielearn/elements/pl-file-editor/pl-file-editor.mustache

This was surfaced by a recent accessibility review. Now, to place the cursor into the editor, one must focus it and then press <kbd>Enter</kbd>. To be able to tab to other inputs, one can press <kbd>Esc</kbd> to exit the focus trap and one can then <kbd>Tab</kbd> and <kbd>Shift</kbd> + <kbd>Tab</kbd> as normal.
I also took the opportunity to improve the keyboard accessibility of other parts of the `<pl-file-editor>` element.

Enable keyboard accessibility for Ace editor

---

apps/prairielearn/src/middlewares/authzCourseOrInstance.js
apps/prairielearn/src/pages/error/error.html.ts
apps/prairielearn/src/pages/error/error.js

This fixed two regressions introduced by #9935:
- `error.info` was previously rendered with `<%- ->` in EJS; we need to maintain that property now that we're no longer using EJS.
- `error.info` was previously shown even in production environments, but that was inadvertently broken.
I also added an additional check to make sure that we only render the `info` property of `AugmentedError` instances.

Fix rendering of info HTML on error page

---

apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js

Resolves #10011. In essence ensures that if the content is blank, then a blank answer is sent to the input, so that the appropriate check can be done for missing answer. This was not the case if you type something then delete it.
This uses `quill.editor.isBlank()` as a means to identify if the answer is empty or not. This is an undocumented API, so the code is written to have a bit of control so that, if the function ceases to exist in the future, the code doesn't break.
The code will be considered blank in the same scenarios where Quill shows the placeholder, so things like adding a space or an empty list item will not be considered blank.

Fix check for blank answer in pl-rich-text-editor

---

apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js

Resolves #10013 (at least in part, until slab/quill#3952 is addressed). In essence, it overrides the case where a tab keypress inserts a tab character and causes it to focus on the next focusable element. It does not override other tab behaviours, like indenting lists, switching cells in a table, or indent inside a code block, so this would not work in those contexts, but it at least provides an option for a user to leave that context (if applicable) and exit the answer element.

Enable keyboard accessibility for pl-rich-text-editor

---

.github/workflows/main.yml
.github/workflows/release.yml

Applies the change from #10015 to the GitHub Actions workflows to avoid CI failures.

Preinstall node-gyp headers in GitHub Actions workflows

---

apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.sql

If your course is consuming shared questions which are not present in local dev, the qid is null, causing an error on the instructorQuestionSettings page: 
```
ZodError: [
{
"code": "invalid_type",
"expected": "string",
"received": "null",
"path": [
184
],
"message": "Expected string, received null"
}
]
at get error [as error] (file:///PrairieLearn/node_modules/zod/lib/index.mjs:587:31)
at ZodArray.parse (file:///PrairieLearn/node_modules/zod/lib/index.mjs:692:22)
at PostgresPool.queryRows (/PrairieLearn/packages/postgres/src/pool.ts:902:29)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at <anonymous> (/PrairieLearn/apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts:244:18)
```
This should only be a temporary fix, this …

fix: Filter null qids on instructor question settings page

---

packages/compiled-assets/src/index.test.ts
packages/compiled-assets/src/index.ts

If an error would be thrown in production because of a missing script/stylesheet, it will now be thrown in development/testing environments. This should make errors like #10036 much easier to catch before we hit production.

Make compiled-assets throw errors in dev mode for missing files

---

docs/installing.md
docs/installingLocal.md

It seems mkdocs is defaulting to bash for highlighting blocks:
This PR changes the language to "console" for text that is intended to demonstrate the output of commands. This disables any highlighting related to known keywords in the default language.

Docs: update highlight language in console output

---

apps/prairielearn/src/tests/groupExam.test.ts
apps/prairielearn/src/tests/groupExamRolePermissions.test.ts
testCourse/courseInstances/Sp15/assessments/exam16-groupWorkRoles/infoAssessment.json

There are currently two exams with number 15 in the test course. These were both created by long-standing PRs, so the number confusion was understandable. To avoid confusion this PR changes one to 16.

Deduplicate exam numbers in test course

---

apps/prairielearn/public/stylesheets/local.css
apps/prairielearn/src/pages/partials/navbar.ejs
apps/prairielearn/src/pages/partials/navbarStudent.ejs

These changes ensure that the navbar renders correctly with both Bootstrap 4 and Bootstrap 5 styles. Things should render basically the same with Bootstrap 4, with the exception that the dev mode "Load from disk" button is now a) smaller and b) located outside of an `<li>`, which is necessary for proper alignment in Bootstrap 5.

Make navbar compatible with Bootstrap 5

---

apps/prairielearn/src/pages/instructorAssessments/instructorAssessments.ejs

I noticed this while going through our UI with a fine-tooth comb while evaluating Bootstrap 5.
Before:
After:

Remove unnecessary margins from instructor assessments footer

---

exampleCourse/questions/element/dataframe/question.html

The documentation in the question mentions `show-dtype="none"`, but this should be `show-dtype="false"`. Also, the attribute was missing from the actual code in the example, although the default value is false anyway.

Update example element/dataframe/question.html - typo with show-dtype

---

apps/prairielearn/src/sprocs/ip_to_mode.sql
apps/prairielearn/src/tests/sprocs/ip_to_mode.test.sql
apps/prairielearn/src/tests/sprocs/ip_to_mode.test.ts

This fixes a bug with PrairieTest access control. When network filtering isn't active, we use simple heuristics to check if a reservation is considered "active". One of them is to check if it's been less than an hour since checkin. This is to ensure that the student is put into exam mode immediately after checking in, even before they've started their exam. However, for very short exams, it's possible that `access_start` and `access_end` will occur very quickly. In that case, we were still considering the reservation to be "active" even after `access_end`, thus keeping the user in Exam mode. There was no way for an instructor to recover and take the student out of Exam mode, as there's no way to check out a student once they've started their exam.
The fix is to only look at `checked_in` …

Correctly revert to Public mode after access end

---

apps/prairielearn/src/pages/courseSyncs/courseSyncs.ejs

This issue became apparent with Bootstrap 5's updated table border styles.

Fix colspan for course commit hash

---

.eslintrc.cjs
.git-blame-ignore-revs

Depends on #10076. Once that is merged, will add the commit hash to .git-blame-ignore-revs.

Add lint rule to block unnecessary backticks

---

apps/prairielearn/assets/scripts/instructorCourseAdminSettingsClient.ts
apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.html.ts

Uses the same functionality as the one in the course instance/assessment pages for student links.

Add copy button to repository field on course settings

---

.changeset/large-bees-lay.md
packages/opentelemetry/src/init.ts

Fixes #10241. @trombonekenny could you try this out and report if this fixes the issue you were seeing?

Only enable OTel AWS resource detector in production-like environments

---

apps/prairielearn/assets/scripts/instructorGradebookClient.ts

#10175 updated the gradebook page, but introduced a bug in search. In particular, the new page uses fields that use sub-properties ([supported by bootstrap-table](https://github.com/wenzhixin/bootstrap-table/blob/eab8d6f1bad7b2371c3560fd696592e7429a513f/src/utils/index.js#L490-L494)), but it seems search does not properly support this kind of field identification (to the best of my knowledge, this is because the check in search [uses `!== null`](https://github.com/wenzhixin/bootstrap-table/blob/eab8d6f1bad7b2371c3560fd696592e7429a513f/src/bootstrap-table.js#L1083), which does not account for undefined).
The solution here is to disable search on score columns.

Fix search in gradebook with missing assessments

---

apps/prairielearn/src/pages/partials/navbar.ejs

Changes in Bootstrap v5 result in the existing markup overflowing out of the dropdown container:
This updated markup improves things in a backwards-compatible way: rather than (mis-)using the `col*` classes to make space when an item is not checked, it now uses `visibility: hidden` to show/hide the checkbox as appropriate.

Improve markup/styling of user menu

---

apps/prairielearn/src/pages/partials/navbar.ejs

`left` is not a valid `justify-content` value and thus the `justify-content-left` doesn't even exist. This could be replaced with `justify-content-start` but that doesn't seem to be necessary.

Remove invalid justify-content-left class

---

apps/prairielearn/src/lib/json.test.ts
apps/prairielearn/src/lib/json.ts

This is a utility that will be useful in upcoming work to programmatically modify JSON. It tries to maintain the existing order of keys so that a `git diff` is as clean as possible. This may not matter much for the average user who isn't ever looking at Git history, but it'll be very valuable to me and other testers who are trying to validate that the editor is idempotent for unchanged data.
I'm opening a PR for this in isolation since this is trivially reviewable/testable on its own.

Introduce applyKeyOrder function

---

apps/prairielearn/assets/scripts/navbarClient.ts
apps/prairielearn/src/middlewares/authzCourseOrInstance.js
apps/prairielearn/src/pages/instructorEffectiveUser/instructorEffectiveUser.html.ts
apps/prairielearn/src/pages/instructorEffectiveUser/instructorEffectiveUser.ts
apps/prairielearn/src/tests/permissions/studentData.test.ts

This came out of discussion here: https://github.com/PrairieLearn/PrairieLearn/pull/9743#discussion_r1683578490
Users already have two good options for testing assessments that only have PrairieTest access rules:
- Use "Student view without access restrictions" (easy)
- Run a 1-person course session in PrairieTest (high fidelity with the PrairieTest experience)
With upcoming changes to make exam mode more secure, the mode override/emulation already wouldn't work without additional, complex configuration for users. So, we're opting to remove it entirely.

Remove user-facing mode overrides

---

apps/prairielearn/src/lib/config.ts
apps/workspace-host/src/lib/config.ts

This allows local debugging of workspaces to match the workflow in production. We already configure this bucket via `s3rver`: https://github.com/PrairieLearn/PrairieLearn/blob/57bffa851437c4b4b0f9a89ec59855c2e40bb227/docker/start_s3rver.sh#L27

Set default S3 bucket for workspace logs in dev mode

---

testCourse/courseInstances/Sp15/assessments/exam11-activeAccessRestriction/infoAssessment.json
testCourse/courseInstances/Sp15/assessments/hw8-activeAccessRestriction/infoAssessment.json

I noticed this while testing the assessment access rules editor. Though the trailing Z passes our validation, it doesn't make a lot of sense since these dates are always treated as relative to the course instance timezone.

Drop Z from end of testCourse access rule dates

---

.changeset/giant-shirts-complain.md
packages/sentry/src/index.ts

This fixes an issue that reared its head in production.

Avoid infinite recursion in Sentry event processor

---

apps/prairielearn/src/server.js

`setExpiration` expects either a `Date` or a milliseconds value.

Fix session extension

---

apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts

Fixes #4154. The original code assumed that the example course does not have the repository column set, which is no longer the case.

Fix GitHub link for example course questions

---

packages/compiled-assets/src/index.ts

This fixes a bug with the instructor assessments page. That page has a script that lazy-loads assessment stats; it uses `async.eachLimit` to do so in parallel:
https://github.com/PrairieLearn/PrairieLearn/blob/a7af6ed27d636da3611c5fcde03da4790eac5092/apps/prairielearn/assets/scripts/instructorAssessmentsClient.ts#L28
However, the `async` library requires that async functions actually _be_ async with the `async` keyboard. When `esbuild` targets `es6`, it transforms async functions into generator functions, so the `async` library doesn't know to await them. This means that only three assessments worth of stats will be loaded per page load, since the `async` library thinks the first three never finishes.
This change should be very safe, as async functions as ES2017 in general have been …

Configure esbuild to target ES2017

---

apps/prairielearn/assets/scripts/instructorFileEditorClient.ts

Resolves #10247. Replaces the check for hash with a check for actual content in client side comparison of file editor content, which identifies if Save button should be enabled. While a hash clash is unlikely to cause a problem in these cases, this has the advantage of removing the dependency on cryptojs in the client side code.

Use disk contents to check for changes in file editor

---

apps/prairielearn/src/pages/workspace/workspace.html.ts

As a precursor to other changes in the workspace page (e.g., #10295), this PR updates the page to use some more modern conventions:
* use of the modal component;
* separate popover content into separate function and escape it explicitly.

Modernize workspace page

---

packages/compiled-assets/src/index.ts

Configure esbuild to target ES2017 in dev mode

---

apps/prairielearn/src/ee/lib/contextEmbeddings.ts

Using an absolute path means we'd accumulate the same document multiple times during deploys, since each deploy has a unique path on disk. Using the relative path to the PL repo ensures uniqueness.

Use relative paths for question generation context embeddings

---

apps/prairielearn/assets/scripts/instructorAssessmentManualGradingAssessmentQuestionClient.ts

This button did not have an explicit type, which caused it to default to submit (since it's inside a form). This is not causing a problem currently, but seems to be a problem in Bootstrap 5, where clicking the button causes a submit event to be triggered.

Fix "Tag for grading" button type

---

apps/prairielearn/src/lib/github.js
apps/prairielearn/src/lib/github.test.ts
apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.html.ts
apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts

Resolves #10271. This should reduce the confusion that often comes up in questions about giving staff access to the course repository. This code uses the same pattern used in the "Show on GitHub" link in the question settings page.

Add link to GitHub access settings from course staff page

---

packages/session/src/index.test.ts

This PR aims to fix some flaky tests in the `@prairielearn/session` package. One test failure can be seen here: https://github.com/PrairieLearn/PrairieLearn/actions/runs/10169846939/job/28127680417
AFAICT, the test fails because the change isn't committed to the session store before we try to read it. We should be able to work around this by adding `await res.text()` in between making the request and reading from the session store, which will ensure that [all this garbage](https://github.com/PrairieLearn/PrairieLearn/blob/9683b6754ed6ce9cba52543b63450bed4f991807/packages/session/src/before-end.ts) works as expected.

Fix flaky session tests

---

apps/prairielearn/assets/scripts/lib/questionsTable.js

Fixes #10387. Issue was related to a change in the assessment badge. The filter assumed no spaces before/after the assessment label, which used to be the case but is no longer the case.

Fix filter by assessment in questions page

---

apps/prairielearn/assets/scripts/lib/mathjax.ts

Without this change, there's a period of time during the MathJax initialization process where `window.MathJax.typesetPromise` isn't defined. That means that code [like this](https://github.com/PrairieLearn/PrairieLearn/blob/d078da2229918014143a1eff31c64595792928d9/apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.mustache#L70) will produce errors during page initialization:
By using an accessor property descriptor, we git ourselves a way to hook into the assignment that MathJax does and add our `typesetPromise` function back to `window.MathJax`.

Ensure MathJax.typesetPromise is available during initialization

---

apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.mustache

Fixes #10396. The original code would cause problems for any option that included double quotes `"`, as it would close the `data-content` attribute.

Fix escaping of multiple choice options with dropdown display

---

apps/prairielearn/assets/scripts/instructorAssessmentQuestionsClient.ts
apps/prairielearn/assets/scripts/instructorAssessmentsClient.ts
apps/prairielearn/assets/scripts/lib/questionsTable.js
apps/prairielearn/public/stylesheets/local.css
apps/prairielearn/src/pages/instructorAssessmentQuestions/instructorAssessmentQuestions.html.ts
apps/prairielearn/src/pages/instructorAssessments/instructorAssessments.html.ts

`$(this).data('bs.popover').getTipElement()` is an undocumented, not-officially-supported API, and it won't work at all in Bootstrap 5. `data-custom-class`, on the other hand, is officially supported in both BS4 and BS5.
Fixes [an issue with the BS5 migration](https://github.com/PrairieLearn/PrairieLearn/pull/10095#issuecomment-2265321358) reported by @jonatanschroeder.

Use official Bootstrap API to set sync popover max width

---

apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts
apps/prairielearn/assets/scripts/instructorAssessmentManualGradingAssessmentQuestionClient.ts
apps/prairielearn/assets/scripts/instructorGradebookClient.ts
apps/prairielearn/assets/scripts/lib/questionsTable.js

`bootstrap-table` defaults to using `bootstrap-icons` when used with Bootstrap 5. However, we still want to use FontAwesome for the time being, so we need to set `iconsPrefix: 'fa'`. If we were able to pick up https://github.com/wenzhixin/bootstrap-table/pull/7190, we'd be able to just set that and have it automatically pick up the correct icons. However, we can't consume the latest version of `bootstrap-table` because of the breaking change introduced in https://github.com/wenzhixin/bootstrap-table/issues/6745, so we have to re-specify all the icons we use.
Part of #10095.

Add forwards compat for bootstrap-table icons in Bootstrap 5

---

apps/prairielearn/src/components/SubmissionPanel.html.ts

Before:
After:
This is consistent with all our other card headers.

Improve alignment in course staff feedback header

---

graders/c/cgrader/cgrader.py

Based on an issue raised on Slack. The `change_mode` method changes the mode (permissions)  of a file, and also ensures that the entire path is accessible to all users. This used to be done by setting the parent permissions recursively to 711, ensuring all users have the x (1) permission. The problem with this approach is that, if the parent directory had already been given other permissions (e.g., through a previous call to `change_mode`), this change would remove those permissions. The change here ensures that permissions are only added to the parents, never removed.

C Grader: fix mode change for parent directory

---

apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/gradingPanel.html.ts

I noticed this while going through things with a fine-toothed comb while testing the Bootstrap 5 migration.
Before:
After:

Improve spacing in manual grading sidebar

---

apps/prairielearn/assets/scripts/instructorAssessmentManualGradingAssessmentQuestionClient.ts

Opportunistic cleanup ahead of the Bootstrap 5 migration. With the new underlines in BS5, the badge looked weird when it was part of the link.

Convert manual grading issues badge to tooltip

---

apps/prairielearn/src/pages/studentAssessment/studentAssessment.html.ts

The end result is the same, but this is just objectively a better way to center something, and it's compatible with tweaked checkbox styles in Bootstrap 5.

Improve honor pledge markup

---

apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts
apps/prairielearn/assets/scripts/lib/questionsTable.js
apps/prairielearn/public/stylesheets/local.css
apps/prairielearn/src/pages/instructorAssessmentQuestions/instructorAssessmentQuestions.html.ts
apps/prairielearn/src/pages/instructorAssessments/instructorAssessments.html.ts

Takes the place of #10405 and builds on #10401 to use a single `popover-wide` class for all "wide" popovers that should be wider than Bootstrap's default.

Unify wide popovers

---

apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.html.ts

Remove extra space from course sync message

---

apps/prairielearn/src/components/AssessmentRegenerate.html.ts
apps/prairielearn/src/components/GroupWorkInfoContainer.html.ts
apps/prairielearn/src/ee/pages/administratorInstitutionSaml/administratorInstitutionSaml.html.ts
apps/prairielearn/src/pages/administratorInstitutions/administratorInstitutions.html.ts
apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.html.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.html.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/rubricSettingsModal.html.ts
apps/prairielearn/src/pages/instructorIssues/instructorIssues.html.ts
apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.html.ts
apps/prairielearn/src/pages/workspace/workspace.html.ts

Resolves #10414. Modals that have two or more buttons in the footer should always have the main "action" button on the bottom-right corner, with the cancel/close/dismiss button to the left of that action button.
Review ignoring whitespace.

Reorder buttons in modals for consistency

---

apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts
apps/prairielearn/src/ee/pages/instructorAiGenerateQuestion/instructorAiGenerateQuestion.ts
apps/prairielearn/src/pages/administratorSettings/administratorSettings.ts
apps/prairielearn/src/server.js

This PR fixes several issues with AI question generation:
- Sentry's usage of `import-in-the-middle` breaks the `openai` library (see https://github.com/openai/openai-node/issues/903 and https://github.com/getsentry/sentry-javascript/issues/12414). I applied the recommended fix from Sentry.
- Server jobs weren't actually being associated with the course (the code was incorrectly reading `course.course_id` instead of `course.id`).
- Server job redirection was using routes that only exist in dev mode. I've updated them to use the correct routes.

Fix AI question generation bugs

---

apps/prairielearn/src/lib/features/index.ts

This flag allows us to configure specific courses/institutions to render with Bootstrap 4 instead of Bootstrap 5.
I'm landing this in advance of https://github.com/PrairieLearn/PrairieLearn/pull/10095 so that I can disable this in advance of the Bootstrap 5 deploy.

Add Bootstrap 4 feature flag

---

apps/prairielearn/assets/scripts/application.ts
apps/prairielearn/assets/scripts/instructorAssessmentGroupsClient.ts
apps/prairielearn/assets/scripts/instructorAssessmentUploadsClient.ts
apps/prairielearn/assets/scripts/instructorFileBrowserClient.ts
apps/prairielearn/assets/scripts/studentAssessmentInstanceClient.ts
apps/prairielearn/assets/scripts/studentInstanceQuestionClient.ts
apps/prairielearn/src/pages/instructorAssessmentGroups/instructorAssessmentGroups.html.ts
apps/prairielearn/src/pages/instructorAssessmentUploads/instructorAssessmentUploads.html.ts
apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.html.ts

This is going away entirely in BS5, but for now, moving it to the application bundle means that we can get rid of a few page-specific bundles too.

Handle custom file inputs globally

---

apps/prairielearn/src/ee/auth/azure/callback.ts
apps/prairielearn/src/ee/auth/saml/router.ts

A very small percentage of logins fail due to missing user data from Passport. From what I can tell, these errors are transient and we have no control over them. This PR changes those errors to return a 200 status code so that we don't get non-actionable alerts over 500 errors.
Note that other errors, e.g. SAML signature validation failures, will still be raised as 500s for now.

Don't report missing user data after login as 500-level error

---

apps/prairielearn/src/components/InstructorInfoPanel.html.ts
apps/prairielearn/src/components/QuestionScore.html.ts

Closes #10428. Currently, submitting an empty input field when reporting an issue in a question produces an error screen. This PR seeks to prevent submitting an empty form field by adding a `required` attribute to this input.

Add input validation to issue reporting

---

apps/prairielearn/assets/scripts/behaviors/dropdown.ts
apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts
apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.html.ts

Doing this ahead of Bootstrap 5. This change ensures that the dropdown remains open when the popover is triggered, which ensures that Bootstrap can place the popover correctly relative to the triggering element.

Improve behavior of instance time limit adjust popover

---

.github/dependabot.yml

This PR makes a number of changes to our Dependabot config that should make its PRs more manageable and useful for us:
- We use the new `directories` key to a) ensure minimal PRs per ecosystem and b) reduce the duplication of config.
- Instead of using bespoke dependency groups, we now prefer to group all patch/minor updates together. The exception for this is `@opentelemetry/*` dependencies; see the inline note about this.

Refine Dependabot config

---

apps/prairielearn/elements/pl-multiple-choice/info.json
apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.css
apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.js
apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.mustache
apps/prairielearn/package.json
exampleCourse/questions/element/multipleChoice/question.html
yarn.lock

`bootstrap-select` doesn't fully support Bootstrap 5, which is a problem given we want to upgrade to Bootstrap 5 (#10095).
This PR switches us to use [`tom-select`](https://github.com/orchidjs/tom-select) instead, which better supports Bootstrap 5.

Switch from bootstrap-select to tom-select

---

apps/prairielearn/elements/pl-external-grader-results/pl-external-grader-results.mustache
apps/prairielearn/elements/pl-file-preview/pl-file-preview.css
apps/prairielearn/elements/pl-file-preview/pl-file-preview.js
apps/prairielearn/elements/pl-file-preview/pl-file-preview.mustache
apps/prairielearn/elements/pl-file-upload/pl-file-upload.css
apps/prairielearn/elements/pl-file-upload/pl-file-upload.js
apps/prairielearn/public/stylesheets/local.css
apps/prairielearn/src/components/CourseRequestsTable.html.ts
apps/prairielearn/src/components/QuestionContainer.html.ts
apps/prairielearn/src/components/SubmissionPanel.html.ts

This is being done ahead of Bootstrap 5. In v5, they changed how `data-toggle="collapse"` is handled. Now, they handle click events for that in the capturing phase instead of the bubbling phase (see https://github.com/twbs/bootstrap/issues/36063). This means that we no longer have the option of using `stopPropagation()` to ensure that clicks on nested buttons don't toggle the open/closed state. I opened https://github.com/twbs/bootstrap/pull/40574 to change Bootstrap to handle these events in the bubbling phase, but that's unlikely to be reviewed or released soon.
Now, collapse toggling is controlled only by an explicit button. The main user-facing change is that clicking on question submission/feedback panel headers will no longer toggle the open/closed state of the panel. IMO this is …

Improve collapse behavior

---

workspaces/jupyterlab-python/requirements.txt

The maintainer of `nltk` deleted this version for PyPi (https://github.com/nltk/nltk/issues/3301), which broke our builds. This PR downgrades it so the image will build again.

Downgrade nltk in workspace-jupyterlab-python

---

.github/dependabot.yml

This will keep Dependabot from trying to update things we don't want it to.

Add ignores to Dependabot config file

---

apps/prairielearn/elements/pl-checkbox/pl-checkbox.mustache
apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.mustache

Bootstrap 5 changed how radios/checkboxes are styled. It now uses floating, which isn't compatible with `display: flex`.
To fix this, I used Bootstrap 5's new "gap" utilities to add that spacing back. These classes don't exist in Bootstrap 4, so they won't have any effect there.

Add backwards-compatible fix for checkbox/radio spacing

---

apps/prairielearn/src/pages/instructorAssessments/instructorAssessments.html.ts
apps/prairielearn/src/pages/partials/navbar.ejs
apps/prairielearn/src/pages/studentAssessments/studentAssessments.html.ts

This PR makes two straightforward accessibility improvements:
- In the student/instructor assessment lists, the assessment badge (e.g. "HW1") no longer links to the assessment. This change was made for two reasons:
- It prevents confusion from having two differently-named links that both go to the same place
- The old link was an extraneous tab stop for someone tabbing through the page. Now, they can more quickly jump from assessment to assessment.
- The homepage link in the navbar now has an improved label ("Homepage") and the "Go home" text that appears on hover has sufficient contrast with the background.
- The assessment set/module header rows now use `scope="row"` to indicate the the heading applies to the row, not to the column as a whole.

Miscellaneous accessibility improvements

---

apps/prairielearn/public/stylesheets/local.css
apps/prairielearn/src/pages/administratorSettings/administratorSettings.html.ts

This PR aims to improve our button focus styles to meet certain accessibility requirements from the University of Illinois. They claim that the default Bootstrap focus indicators lack sufficient contrast with the background. The solution I went for here is to introduce another focus outline that matches the color of the text, which should hopefully offer sufficient contrast (given that the button text itself has sufficient contrast with button background colors).
These styles are applied only when the [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) pseudo-class applies, so they'll only be visible to folks who are navigating PrairieLearn via keyboard.

Improve button focus styles

---

apps/prairielearn/elements/pl-dropdown/pl-dropdown.mustache

This is a forwards-compatibility fix for Bootstrap 5. The updated `<select>` styles caused a problem when a `<pl-dropdown>` element was positioned towards the right of a `<pl-overlay>`:
Using `width: auto` ensures that the select uses its natural width so that the options are visible:

Fix width of pl-dropdown when used in pl-overlay

---

docs/externalGrading.md

Two small tweaks to the documentation on external grading as mentioned over on Slack. Starting with something simple to make sure I have the workflow correct.
I did not see a Compare and Review button as mentioned [here](https://prairielearn.readthedocs.io/en/latest/contributing/#contributing-to-prairielearn) so not sure if this is the correct order of operations or the instructions are out of date

Fix typo in external grading documentation

---

apps/prairielearn/package.json
apps/prairielearn/src/question-servers/freeform.js
tools/snapshot-question-html.mjs
yarn.lock

The new version of Cheerio causes problems with the legacy question renderer. This can be reproduced by disabling the new question renderer in the example course and then viewing the `demo/fixedCheckbox` question.
I'm temporarily downgrading until we can figure out why this occurs.

Downgrade cheerio to fix legacy question renderer

---

apps/prairielearn/src/middlewares/selectAndAuthzInstanceQuestion.sql
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.html.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.sql

Closes #10503. Three changes in this modal:
* Moves the headings to be closer to their corresponding grading panels in the DOM.
* Makes the grading jobs more responsive by moving to a top-down layout in narrow viewports.
* Replaces the sproc-based formatted dates with library calls.
I did not add semantic headings, but I'm happy to add them if you believe they are relevant here, just let me know which heading level to use so it properly matches the conventions used in #10483 and #10440.

Improve accessibility and responsiveness of grading conflict modal

---

apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts
apps/prairielearn/assets/scripts/instructorGradebookClient.ts
apps/prairielearn/src/components/EditQuestionPointsScore.html.ts
apps/prairielearn/src/components/PersonalNotesPanel.html.ts
apps/prairielearn/src/components/StudentAccessRulesPopover.html.ts
apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.html.ts
apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.html.ts
apps/prairielearn/src/pages/partials/issueBadge.ejs
apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.html.ts
apps/prairielearn/src/pages/studentAssessments/studentAssessments.html.ts

Closes #10486. This PR intends to add accessibility labels to buttons that may be missing them. This will improve readability for screen readers when focusing on a button. I have tested most pages with a screen reader and I think I caught most of the buttons that did not have labels. If you are able to find anymore, please let me know.

Add accessibility labels to buttons

---

.changeset/young-beans-wink.md
apps/prairielearn/assets/scripts/behaviors/popover.ts
packages/browser-utils/README.md
packages/browser-utils/src/focus.ts
packages/browser-utils/src/index.ts

Closes #10488.
I tested this on the assessment "Settings" tab with the "Change AID" button, though these changes should apply to all popovers. To test:
- Click to open a popover.
- Hit <kbd>Esc</kbd>; the popover should close.
- Open the popover again.
- Check that the focus moves to the first focusable child.
- Click inside the popover; the popover should not close.
- Click on the input inside the popover; the popover should not close.
- Click outside the popover; the popover should close.
- Hit <kbd>Tab</kbd> or <kbd>Shift+Tab</kbd> repeatedly; focus should not leave the popover.

Improve popover accessibility

---

apps/prairielearn/src/ee/auth/saml/router.ts

Without this, we get a fun error:
```
TypeError: Cannot read properties of undefined (reading '_options')
at generateServiceProviderMetadata (/Users/nathan/git/PrairieLearn/node_modules/@node-saml/passport-saml/src/multiSamlStrategy.ts:82:17)
at node:internal/util:430:7
at new Promise (<anonymous>)
at generateServiceProviderMetadata (node:internal/util:416:12)
at <anonymous> (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/ee/auth/saml/router.ts:139:83)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I tested this change locally and confirmed that it fixed the error.

Fix SAML metadata endpoint

---

apps/prairielearn/assets/stylesheets/questionsTable.css

Fixes #10516. Bootstrap 5 introduces CSS styles that override our own custom styling for sticky columns. This PR changes the selectors to be more specific than the ones listed by Bootstrap. It also uses BS variables where appropriate, falling back to fixed colors to allow BS4 to continue working as before. This was tested in both BS4 and BS5.

Fix sticky column styles in questions table for Bootstrap 5

---

apps/prairielearn/src/server.js

Certain environments run Sentry without also enabling OpenTelemetry. Before this change, Sentry wouldn't have the required OTel pieces in place for request isolation to work (see https://docs.sentry.io/platforms/javascript/guides/node/opentelemetry/custom-setup/). Now, if our own OTel setup isn't enabled via our config, we'll allow Sentry to set OpenTelemetry up for itself.

Fix Sentry memory leak when OTel is disabled

---

apps/prairielearn/assets/stylesheets/instructorGradebook.css
apps/prairielearn/assets/stylesheets/questionsTable.css
apps/prairielearn/public/stylesheets/local.css
apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.html.ts

Fixes #10525. This also centralizes the CSS styling of custom bootstrap-table handling sticky table and toolbar/pagination padding.

Fix sticky column issue in gradebook and students tab

---

apps/prairielearn/src/ee/pages/administratorInstitutionSaml/administratorInstitutionSaml.html.ts

This bit me during a recent setup process when I forgot to include the header/footer. Hopefully between a default that includes the header/footer and a documented requirement for them, I won't make that same mistake again.

Improve setup experience for SAML public certificates

---

apps/prairielearn/elements/pl-checkbox/pl-checkbox.mustache
apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.mustache

Fixes https://github.com/PrairieLearn/PrairieLearn/issues/10534.
Before:
After:

Prevent radio/checkbox inputs with long labels from shrinking

---

docs/saml.md

The fact that this was missing from the docs came up during a recent SAML setup process with an institution.

Document optional email attribute in SAML setup docs

---

apps/prairielearn/assets/scripts/behaviors/popover.ts

As reported by @eliotwrobson, if a popover with `data-trigger="focus"` contains a focusable child, focus would be immediately moved to that child, which would close the popover:
https://github.com/user-attachments/assets/bf2f9480-1f18-44a3-832f-049faafcdb74
Now, we detect when a popover is focus-triggered and skip the autofocus/focus-trap logic, which ensures that the popover stays open:
https://github.com/user-attachments/assets/93845bad-c3ed-491e-b1e5-cf44ba6d9ed4
To test this, you can add a focusable child to a popover's contents. I tested this with both Bootstrap 4 and 5, and it worked correctly in each.
I think we should abandon `data-trigger="focus"` in favor of the default `"click"` trigger. Now that we have <kbd>Esc</kbd> and close-on-click-outside implemented universally, that …

Don't immediately close focus-triggered popover with focusable child

---

docs/elements.md

Recent changes to pl-file-preview were not properly addressed in the documentation, which had conflicting information. Also adds a reference to workspaces, which may be a source for these files.

Update documentation for pl-file-preview

---

apps/prairielearn/src/sprocs/grading_jobs_update_after_grading.sql

This fixes an issue reported on Slack: https://prairielearn.slack.com/archives/C266KEH9A/p1724793294305189
For posterity, this can be reproduced with the following question:
```html
<pl-question-panel>
This is a test
</pl-question-panel>
<pl-answer-panel>
{{{params.answer-feedback}}}
</pl-answer-panel>
<pl-submission-panel>
{{{params.submission-feedback}}}
</pl-submission-panel>
```
```py
def grade(data):
data["params"]["submission-feedback"] = "HELLO"
data["params"]["answer-feedback"] = "TEST"
data["score"] = 1
```
The expected behavior is that after one submission, `HELLO` would be shown in the submission panel and `TEST` would be shown in the answer panel. However, this didn't occur; it was only shown after the _second_ submission.
I broke this (or rather, uncovered this bug) in #10495 …

Update submission params and true_answer after grading

---

apps/prairielearn/src/lib/code-caller/index.js

This reverts the changes from #7092. Sentry now uses `AsyncLocalStorage` to propagate context under the hood, so those hacks should be unnecessary.

Remove hacky code caller memory leak fix

---

docs/elements.md

Follow-up to #9900 
I forgot to update the documentation with the new case style. `exampleCourse/questions/element/excalidraw/question.html` already uses the correct style.
Thanks to @firasm for finding the bug!

fix stale documentation for pl-excalidraw

---

packages/compiled-assets/src/index.ts

When we initialize the middleware, we always ensure that `publicPath` ends with a slash, so adding another slash is redundant:
https://github.com/PrairieLearn/PrairieLearn/blob/9e9b7292f21485543466af4ccb3c4f41aecb168a/packages/compiled-assets/src/index.ts#L47-L49

Fix production assets path

---

apps/prairielearn/package.json
apps/prairielearn/src/question-servers/freeform.js
tools/snapshot-question-html.mjs
yarn.lock

Closes #10500. Adding `"xmlMode": false` was enough to fix the issues I described there. Based on the back-references on https://github.com/cheeriojs/cheerio/issues/4034, it seems like other people are encountering the same issue and fixing it the same way.
To test this, remove `"useNewQuestionRenderer": true` from a course's `infoCourse.json` file and render some questions. They should look more or less like they normally do (plus or minus any expected differences between the legacy and new renderer).

Upgrade to Cheerio 1.0.0

---

docs/c-grader/index.md
graders/c/Dockerfile

Add support for clang as a compiler in the cgrader. It can be invoked by adding `compiler="clang"` to the compilation functions. Addresses part of #10530.

C Grader: add clang

---

apps/prairielearn/elements/pl-file-preview/pl-file-preview.js
apps/prairielearn/elements/pl-file-preview/pl-file-preview.mustache
apps/prairielearn/elements/pl-file-upload/pl-file-upload.js
apps/prairielearn/src/pages/instructorFileBrowser/instructorFileBrowser.html.ts

As discussed on Slack. The use of `object type="application/pdf"` seems to cause Safari to crash. Using `iframe` produces a similar interface in Edge/Chrome/Firefox on Windows, and now works on Safari on Mac.

Fix PDF previewer in Safari

---

apps/prairielearn/assets/scripts/lib/qrCodeButton.ts

The QR code popover doesn't show when using Bootstrap 5. A console error indicates that `$().popover` isn't initialized when it is called to set up this popover. This PR ensures that the document has been initialized, which also means the JQuery API for Bootstrap 5 is initialized, before setting up the popover.

Fix display of QR code popover in Bootstrap 5

---

apps/prairielearn/src/pages/authLogin/authLogin.html.ts

In production where we have a lot of institutions, some of them would get cut off at the bottom of the list on narrow viewports:
This occurred because of the `height: 100%` we used on the `html` and `body` tags. Changing that to `min-height: 100vh` resolves this.
I also changed how the background was styled so that one wouldn't see a dark stripe at the bottom of the page if there weren't many institutions or login options.

Fix scrolling issue on login page

---

apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts

When the example question cannot be edited, it should say "View question configuration" to parallel "Edit question configuration." However it currently says "View course configuration" by mistake.

Typo in instructorQuestionSettings.html.ts: "course" -> "question"

---

apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.html.ts

There were two instances of missed EJS conversions in the `instructorCourseAdminStaff` page. This PR intends to convert those to TS.

Convert missed EJS to TS

---

apps/prairielearn/src/sprocs/format_interval.sql
apps/prairielearn/src/sprocs/format_interval_short.sql

We saw a case in practice where an instructor configured an assessment instance to close in the year 2214. That's a lot of milliseconds when computed as an interval relative to the present: 6.3 trillion milliseconds, give or take. This is quite a bit larger than the maximum of a 4-byte integer (2.1 billion).
With this change, we can now handle intervals of somewhere between 100 million and 200 million years.

Cast to BIGINT in interval formatting sprocs

---

workspaces/xtermjs/Dockerfile

The xtermjs workspace includes, in its entrypoint script, support for command line arguments, in particular the terminal command (shell). This can be useful if a different program is to be used instead of bash (e.g., python). However, the Dockerfile configuration does not currently allow run args to be passed to the entrypoint. This PR changes the entrypoint configuration so that, if the question sets the value of `args` (e.g., `"args": "-c /usr/bin/python"`), these arguments are sent to the workspace script.

Add support for arguments in xtermjs workspace

---

apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css

I'm not sure when this broke or whether it was a bootstrap 5 issue or a font awesome issue. I just noticed today, here's the fix.
before: 
after:

fix: centering of check and x-mark badges in pl-order-blocks

---

workspaces/desktop/server/package.json
workspaces/desktop/server/yarn.lock

`novnc` released a breaking change in a minor version, see https://github.com/novnc/noVNC/issues/1792. We can't consume any version newer than `1.4.0`.

Downgrade novnc in prairielearn/workspace-desktop

---

apps/prairielearn/elements/pl-file-upload/pl-file-upload.js

As reported on Slack. The preview feature of pl-file-upload fails on Chrome/Edge for PDF files that are larger than 1536KB (i.e., whose base64 representation is larger than 2MB), likely due to the length of the data URL. This PR fixes this by converting the base64 content to a blob URL. This was tested locally with a 46MB file (far larger than what the upload will require) and it works very well.
For completeness I also did the same change in image uploads, although I didn't have the same issue in those cases.

Fix preview for upload of PDF files over 2MB

---

apps/prairielearn/src/schemas/schemas/infoCourseInstance.json
apps/prairielearn/src/sync/course-db.ts
apps/prairielearn/src/tests/testFileEditor/courseTemplate/courseInstances/Fa18/infoCourseInstance.json
apps/prairielearn/src/tests/testLoadCourse/brokenCourse/courseInstances/Fa18/infoCourseInstance.json
docs/courseInstance.md
exampleCourse/courseInstances/SectionA/infoCourseInstance.json
testCourse/courseInstances/Sp15/infoCourseInstance.json

In the aftermath of some access confusion at Berkeley, we realized that we weren't rejecting extra properties if they were present in course instance JSON files. This made it too easy for an instructor to introduce config that didn't actually do anything.
The only complexity here is the fact that in our documentation, examples, and template course, we always included a `"shortName"` property that was never actually used. Rather than forcing every single course to delete it, we added it to the schema, marked it as deprecated, and added  a sync warning for any course instances that are accessible now or will be in the future.

Perform strict validation of course instance JSON

---

apps/prairielearn/src/components/Scorebar.html.ts

This is being done in response to feedback that our frequent use of red in the UI can be anxiety-inducing. While we believe many usages of red are justified (e.g., alerting a student to an incorrect answer or unanswered question), there's no need to highlight the incorrect/unanswered portion of the score in red.
Before:
After:
This change has a positive impact on accessibility as well: it's better for users with red/green colorblindness. Strictly speaking, the previous design was accessible since it didn't exclusively use color to communicate information. Even then, it can be convenient to visually scan a list for outliers instead of reading a bunch of percentages, which is now much easier withour red and green being adjacent to each other.

Remove red portion of scorebar

---

apps/prairielearn/src/ee/lib/ai-grading.ts

GPT4 has been tested to be better than GPT3.5 when dealing with longer contexts. Future developments of AI grading will involve providing graded examples to the LLM, and local tests have shown GPT4 with RAG to decrease the error from 15% to 7%. GPT4 also supports more stable parsing of json outputs than GPT3.5. Thus, we are bumping the GPT version used in AI grading to GPT4. 
My next PR will work on implementing RAG in the grade to achieve a better performance.

Use GPT4 with Structured Outputs for AI grading

---

apps/prairielearn/src/components/Scorebar.html.ts

This makes the scorebar more visible, especially at a 0% score or when the containing table row is hovered.

Add colored border to scorebar

---

apps/prairielearn/src/components/NavbarContext.html.ts
apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/pages/instructorCourseAdminModules/instructorCourseAdminModules.html.ts
apps/prairielearn/src/pages/instructorCourseAdminModules/instructorCourseAdminModules.sql
apps/prairielearn/src/pages/instructorCourseAdminModules/instructorCourseAdminModules.ts
apps/prairielearn/src/server.js

Closes #10658. While working on #10653, it was realized that we do not have a page that displays the modules for a course. This PR intends to add that page.
I have added columns from the `assessment_modules` table in the DB. If there is any other information that would add value here, please let me know.

Add course instructor page for modules

---

apps/prairielearn/src/components/SubmissionPanel.html.ts

This change ensures that these buttons have sufficient contrast with their background. Before, the contrast was 4.44, which was insufficient: https://webaim.org/resources/contrastchecker/?fcolor=6C757D&bcolor=F8F9FA
Before:
After:

Improve contrast of buttons in submission panel header

---

apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.html.ts
apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.ts
apps/prairielearn/src/tests/permissions/courseAdminAccess.test.ts

As discussed on Slack, allowing Owner to be added through the add user dialogue instead of requiring a second step to do this.
> IIRC at some point there was a second button for adding a single user which did allow one to set a user up as an Owner in one step. A while ago we collapsed the single + multiple user case into the form that's currently there. In light of that, I'm happy to remove this check and make "Owner" an option there. - Nathan
I left the if statement there in case changes are made in the future or if something breaks it will act as a fail safe. Please let me know if this is the right process for this change or if I need to make any changes.

Allow for Owner to be added at the Add User level

---

apps/prairielearn/elements/pl-big-o-input/pl-big-o-input.mustache
apps/prairielearn/elements/pl-checkbox/pl-checkbox.mustache
apps/prairielearn/elements/pl-drawing/pl-drawing.mustache
apps/prairielearn/elements/pl-dropdown/pl-dropdown.mustache
apps/prairielearn/elements/pl-integer-input/pl-integer-input.mustache
apps/prairielearn/elements/pl-matching/pl-matching.mustache
apps/prairielearn/elements/pl-matrix-component-input/pl-matrix-component-input.mustache
apps/prairielearn/elements/pl-matrix-input/pl-matrix-input.mustache
apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.mustache
apps/prairielearn/elements/pl-number-input/pl-number-input.mustache
apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.mustache
apps/prairielearn/elements/pl-string-input/pl-string-input.mustache
apps/prairielearn/elements/pl-symbolic-input/pl-symbolic-input.mustache
apps/prairielearn/elements/pl-units-input/pl-units-input.mustache
apps/prairielearn/src/components/QuestionContainer.html.ts
apps/prairielearn/src/components/QuestionNavigation.html.ts
apps/prairielearn/src/components/QuestionScore.html.ts
apps/prairielearn/src/components/StudentAccessRulesPopover.html.ts
apps/prairielearn/src/pages/courseSyncs/courseSyncs.html.ts
apps/prairielearn/src/pages/instructorAssessmentAccess/instructorAssessmentAccess.html.ts
apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.html.ts
apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.html.ts
apps/prairielearn/src/pages/instructorCourseAdminInstances/instructorCourseAdminInstances.html.ts
apps/prairielearn/src/pages/instructorInstanceAdminAccess/instructorInstanceAdminAccess.html.ts
apps/prairielearn/src/pages/instructorInstanceAdminLti/instructorInstanceAdminLti.html.ts
apps/prairielearn/src/pages/instructorIssues/instructorIssues.html.ts
apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.html.ts
apps/prairielearn/src/pages/workspace/workspace.html.ts

Focus-triggered popovers have been a frequent source of strange UX issues, accessibility problems, and browser-specific bugs. Using clicks (and/or <kbd>Enter</kbd> and <kbd>Space</kbd>) to open and dismiss popovers should provide for a more reliable and consistent experience across the board.
Closes #6272.
> [!IMPORTANT]
> Please pay close attention to and check for the following while reviewing:
> - Ensure that all `<button>` tags have `type="button"`
> - Ensure that all opening/closing tags match

Use click as trigger for all popovers

---

apps/prairielearn/src/lib/instructorFiles.ts
apps/prairielearn/src/tests/fileEditor.test.ts
docs/clientServerFiles.md
docs/courseInstance.md
docs/faq.md
docs/questionSharing.md

serverFilesCourseInstance and serverFilesAssessment are not accessible through any means. The only code reference for these directories is in the file editor code, where it is used in the button for "Add server file", even though there isn't a use for that file in these contexts. serverFilesQuestion is in a similar boat, though it is accessible by question code already as a regular directory (i.e., it's not a special directory).
This PR removes references to these directories in the file editor, corresponding tests, and docs.

Remove references to unsupported server file directories

---

apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.html.ts

These buttons were missing Bootstrap `btn` classes, which caused problems with the changes from #10672. This PR adds the new `btn-ghost` style from #10671.
Before:
After:

Fix popovers on assessment instance page

---

apps/prairielearn/src/components/QuestionScore.html.ts

Before this change, students were immediately presented with a wall of red upon starting an exam:
Now, they'll see yellow instead:
We're using yellow instead of a more neutral color because we _really_ want students to be aware of any questions they haven't answered.
Red is reserved for invalid or incorrect answers:

Use yellow color for unanswered status badge

---

docs/running-in-production/authentication.md

The existing information isn't very useful, Shibboleth is no longer officially supported in PrairieLearn, and we plan to eventually remove that code entirely.

Remove Shibboleth from authentication docs

---

docs/installingNative.md

We rely on Node 20 for things like [`import.meta.dirname`](https://nodejs.org/api/esm.html#importmetadirname).
If the `postgres` user didn't already exist, creating a database is necessary.

Specify Node version and database creation in native install docs

---

apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/gradingPanel.html.ts

I think this broke during the Bootstrap 5 upgrade. Before this PR, the checkboxes for every issue would have appeared stacked on top of each other, making them impossible to click:
Now, they're displayed correctly:

Fix checkboxes for closing issues while manual grading

---

apps/prairielearn/assets/scripts/lib/mathjax.ts
apps/prairielearn/elements/pl-file-editor/pl-file-editor.js
apps/prairielearn/elements/pl-file-preview/pl-file-preview.js

#10692 uncovered an issue with the MathJax typesetting process: `<pl-file-editor>` typesetting would in some cases race against the initial global typesetting that MathJax does once it has loaded. This race meant that typesetting was performed before the [`braket` extension](https://docs.mathjax.org/en/latest/input/tex/extensions/braket.html) that handles `\set{...}` had loaded.
The solution is to avoid running any "custom" typesetting until the page as a whole has been typeset. This is achieved by waiting for the Promise returned from `MathJax.startup.defaultPageReady()` to resolve. MathJax even mentions some of this in its documentation: https://docs.mathjax.org/en/latest/web/configuration.html#performing-actions-after-typesetting
While I was here, I updated elements to typeset only the …

Fix MathJax typesetting race

---

apps/prairielearn/src/ee/pages/administratorInstitutionCourse/administratorInstitutionCourse.html.ts
apps/prairielearn/src/ee/pages/administratorInstitutionCourseInstance/administratorInstitutionCourseInstance.html.ts
apps/prairielearn/src/ee/pages/administratorInstitutionCourseInstance/administratorInstitutionCourseInstance.ts

I noticed from the institutional admin view we didn't have an easy way to link into the courses or courses instances. This PR add links near the bottom of the page.

Add course and course instance links to institution admin course page

---

docs/running-in-production/docker-compose.md
docs/running-in-production/setup.md

The Docker Compose setup relies on the version of Postgres that's bundled in the Docker container, so the note about setting Postgres config options is irrelevant.

Tweak documentation for self-hosting

---

apps/prairielearn/src/cron/index.ts
apps/prairielearn/src/lib/code-caller/code-caller-container.js
apps/workspace-host/src/interface.js

This is a best practice to avoid clock skew, timezone changes, and other potential problems with `Date.now()`.

Always use performance.now() to measure elapsed time

---

apps/prairielearn/src/middlewares/logResponse.js

This will make it a little easier to identify slow requests from the raw logs.

Log request duration

---

apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.py

The experimental question processor behind the `process-questions-in-worker` feature flag has stricter checks for modifications to `data`. Specifically, it runs the checks during `render()` to make sure no one is mutating data. This broke with `pl-order-blocks`, which _did_ incorrectly mutate `data["submitted_answers"]` while rendering. This PR fixes that.
I considered removing the stricter check to be fully backwards compatible with the current question processor. However, this check lets us enable a key performance optimization: we can avoid copying the entire `data` object before each element is processed. This is valuable enough that I'm willing to enforce this stricter checking even if it will cause some problems in the meantime.

Ensure pl-order-blocks doesn't mutate submitted answers during render

---

apps/prairielearn/src/executor.js
apps/prairielearn/src/lib/code-caller/code-caller-native.js

This PR fixes two bugs with code caller initialization:
- The default options `CodeCallerNative` included `logger.error`. This needs to be `logger.error.bind(logger)` to ensure that the logger's `this` reference is set correctly. We already did this elsewhere:
https://github.com/PrairieLearn/PrairieLearn/blob/71d2178ab170731745146279ccc34f2cbf04db2a/apps/prairielearn/src/lib/code-caller/index.ts#L58
- The in-container executor was in some cases constructing a new code caller without setting the appropriate options.

Fix bugs with code caller initialization

---

apps/prairielearn/src/components/Navbar.html.ts
apps/prairielearn/src/server.js

This PR makes two improvements to the flash message system:
- `flashMiddleware` now runs as soon possible during the request lifecycle to maximize the chance that it'll have run when something else wants to either read or write flash messages.
- The `Navbar` component will now gracefully handle the case where the flash messages cannot be read. This ensures that we can render meaningful error pages even for errors that occur before the flash middleware runs, such as session store failures.
Closes #10745.

Fix flash message errors

---

apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css

On mobile, the text for pl-order-blocks overflows outside the blue box. This tiny change increases the height of the card header so that the "Construct your solution here" text can fit inside the box.  
Before: 
After:
For Desktop, this would look something like this:
Fixes #9861

Increase card header height for pl-order-blocks

---

apps/prairielearn/src/server.js

This is no longer necessary as of #10277.

Remove flash from res.locals

---

apps/prairielearn/src/ee/lib/lti13.ts
apps/prairielearn/src/tests/lti13.test.ts

The LTI 1.3 `fetchRetry` function now returns an array of responses if the response was paginated. The calling function must unpack that.
Replaces #10711 fixing some LTI 1.3 bugs we found with larger classes than in my test suite.

LTI 1.3 fetchRetry refactor for better pagination support

---

apps/prairielearn/src/lib/editors.ts

As reported by @MeiyingQin. Renaming an assessment's AID causes it to fail with an error. Debugging indicates the error was related to an attempt to delete empty preceding subfolders, which was being done with the wrong subdirectory structure, using the CIID instead of AID.
I believe the issue happened here because, in this course, we are using a subdirectory structure for the course instance (i.e., the CIID contains a /), which caused the problem. In the past this never caused a major issue because no parent directory was ever found, though the rename would fail to delete extraneous empty folders in the process, since the wrong directory structure was used to check for empty folders.
It seems this has been a bug since AID subdirectories were introduced 4 years ago.

Fix assessment rename process

---

apps/prairielearn/elements/pl-code/pl-code.py
exampleCourse/questions/element/code/question.html

This PR builds on the changes from #10759 to improve the performance of questions that use a lot of `pl-code` elements with the same language/style.
The following numbers are using the `matlab/practice assessment questions/sas_checkbox/image_manipulation/crop_and_highlight` question from UMich's ENGR 101 course. Testing was done with `process-questions-in-worker` feature enabled.
Master:
```
freeform.generate: 15.00ms
freeform.prepare: 505.75ms
freeform.render: 874.15ms
freeform.generate: 13.43ms
freeform.prepare: 480.76ms
freeform.render: 898.65ms
freeform.generate: 10.20ms
freeform.prepare: 476.02ms
freeform.render: 879.08ms
freeform.generate: 14.67ms
freeform.prepare: 479.53ms
freeform.render: 877.84ms
freeform.generate: 15.20ms
freeform.prepare: 475.83ms
freeform.render: 874.03ms
``` …

Cache expensive data in `pl-code` element

---

apps/prairielearn/elements/pl-integer-input/pl-integer-input.mustache
apps/prairielearn/elements/pl-integer-input/pl-integer-input.py

Fixes #10725. Restores the default placeholder from before #6980 for cases with base zero (i.e., base 10 with option of using a different base with a corresponding prefix).

Restore default placeholder for integer input with base 0

---

apps/prairielearn/elements/pl-checkbox/pl-checkbox.css
apps/prairielearn/elements/pl-checkbox/pl-checkbox.mustache
apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.css
apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.mustache

Closes #10645. Tested with the example from that issue, also adapted to test `<pl-checkbox>`.
Before:
After:
Before:
After:

Remove bottom padding on checkbox/multiple-choice answers

---

apps/prairielearn/src/ee/lib/ai-grading.ts

This is a simple modification to AI grading. In earlier versions, AI grading job information is logged once every 5 graded submissions to allow for higher IO performance. With more output information added in each iteration, and potentially more time needed for iterations for different models, I'm changing the logging to happen after each submission is graded. This would help instructors better keep track of the status of the grading tasks.

Log info in AI grading more frequently

---

apps/prairielearn/src/ee/lib/lti13.ts
apps/prairielearn/src/ee/pages/instructorInstanceAdminLti13/instructorInstanceAdminLti13.html.ts

- Changes to always send the graded timestamp as the current time so that Send Grades updates Canvas regardless of previous grades
- Fixes modal "Pick from existing assignments" to refresh a single div instead of repeating, added a refresh button
- Includes documentation about how to edit an existing Canvas assignment to show up in the line item list
- Adds error message display to the grade sync for the instructor
- Add instructions to the instructor LTI 1.3 admin page on how to refresh LTI metadata rather than erroring

Fix LTI 1.3 grade timestamps

---

apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.html.ts

This PR makes a couple of opinionated UI changes to the LTI 1.3 course instance linking flow.
Before:
After:

Refine LTI 1.3 linking flow

---

apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.html.ts

I broke this in #10668. The removal of the "Best submission" column only impacted the display for Exam-type assessments, but I accidentally changed the way Homework-type assessments displayed too.
Here's how things looked before that PR:
And here's how they looked after the PR:
After this PR, things should look as expected again:

Fix colspan attribute on homework assessment instance page

---

apps/prairielearn/src/components/QuestionContainer.html.ts

This PR fixes a bug reported by @trombonekenny: when a question is configured with `"showCorrectAnswer": false` and is used on an Exam assessment, we'd show an incorrect message in the question footer when the question is "complete" (has 100% credit or no more attempts):
This is because we were using `showTrueAnswer` to determine when the question is complete. However, when this is forced to false by `showCorrectAnswer`, we miss the early return and thus render with nonsensical data.
This PR changes the conditional to check `varianAttemptsLeft`, which is defined here:
https://github.com/PrairieLearn/PrairieLearn/blob/488fbcae1049e6235761719f4196386910e97f6a/apps/prairielearn/src/lib/question-render.js#L229-L264
AFAICT, this will in fact be reliably `0` when a question is complete. Here's …

Fix exam completion message when showCorrectAnswer is false

---

docs/installing.md
docs/lti13.md
docs/questionSharing.md

Minor nit I noticed while reviewing #10730.
This doesn't address the elements documentation, which is tracked by #10767.

Consistently use double quotes in docs

---

apps/prairielearn/src/lib/editors.ts
apps/prairielearn/src/schemas/schemas/infoQuestion.json
apps/prairielearn/src/sync/course-db.ts
apps/prairielearn/src/sync/fromDisk/questions.ts
apps/prairielearn/src/tests/sync/util.ts

This was briefly introduced in #10029 , but as no one has used it yet we should be safe to deprecate and remove immediately.

Disallow depracated property sharedSourcePublicly in JSON files

---

apps/prairielearn/elements/pl-drawing/mechanicsObjects.js

This PR fixes an issue that was reported on Slack. To reproduce on master, start with the following question:
```html
<pl-drawing width="500" height="500" gradable="true" answers-name="answer">
<pl-drawing-answer></pl-drawing-answer>
<pl-controls>
<pl-controls-group label="Write text">
<pl-drawing-button type="pl-text"></pl-drawing-button>
</pl-controls-group>
</pl-controls>
</pl-drawing>
```
- Click the button to add text to the canvas.
- Double click the text to edit.
- Change the text.
- Without making any other changes, click "Save" or "Save & Grade".
- Observe that after the page refreshes, the text has reverted to just "Text".

Persist changes to `pl-text` in `pl-drawing`

---

SECURITY.md

This brings this document into alignment with https://www.prairielearn.com/security. We don't care if someone discusses or discloses vulnerabilities in DMs.

Update security policy to only call out public Slack channels

---

docs/python-grader/index.md
docs/python-grader/sphinx-docs.md
graders/python/python_autograder/code_feedback.py

We might consider ways to make function disallowing more reliable in future versions of the Python autograder for now. In the meantime, we want to be upfront with instructors that this method is not fully secure and can be bypassed by students.

Document that `Feedback.not_allowed` is insecure

---

apps/prairielearn/package.json
apps/workspace-host/package.json
packages/compiled-assets/package.json
packages/session/package.json
workspaces/desktop/server/package.json
workspaces/desktop/server/yarn.lock
yarn.lock

This should keep Dependabot happy with some low-severity security alerts.

Upgrade cookie dependency

---

apps/prairielearn/src/components/Navbar.html.ts
apps/prairielearn/src/lib/authn.js
apps/prairielearn/src/lib/config.ts
apps/prairielearn/src/lib/question-render.js
apps/prairielearn/src/pages/authLogin/authLogin.html.ts
apps/prairielearn/src/pages/instructorAssessmentAccess/instructorAssessmentAccess.html.ts
apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.ts
apps/prairielearn/src/server.js

I realized while working on #10804 that we could clean this up a little bit.
It's not obvious from the actual changes here whether all usages of these values from `res.locals` have actually been removed. I'd recommend sitting down with grep or VSCode search to check my work, though I'm pretty sure I got them all.

Read some values directly from config instead of res.locals

---

apps/prairielearn/src/components/QuestionScore.html.ts
apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.html.ts
docs/assessment.md

This change will give us a little more breathing room for the long "saved for manual grading" badge that's coming in #10686. As discussed here: https://github.com/PrairieLearn/PrairieLearn/pull/10686#discussion_r1795922248
Before:
<br/>
After:
<br/>

Rename "Submission status" to "Status"

---

apps/prairielearn/src/components/InstructorInfoPanel.html.ts

This PR uses a [Bootstrap list group](https://getbootstrap.com/docs/5.3/components/list-group/) to render sections of the instructor question info panel, as discussed here: https://github.com/PrairieLearn/PrairieLearn/pull/10695#discussion_r1805219882
Public question preview context:
Student assessment context (as instructor):
Manual grading context:
Instructor question preview context:

Refine instructor info panel

---

exampleCourse/questions/demo/manualGrade/codeUpload/question.html
testCourse/questions/manualGrade/codeUpload/question.html

These questions are strictly manually-graded and aren't configured for external grading at all. This PR ensures that we don't show a "Grading failed" message after manual grading feedback has been added:

Remove unnecessary pl-external-grader-results elements

---

apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts
apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.sql
apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.ts
apps/prairielearn/src/tests/manualGrading.test.ts

This came up while working on #10800 (https://github.com/PrairieLearn/PrairieLearn/pull/10800#discussion_r1799980596). We ultimately decided we didn't need this functionality any more. I decided to remove this in a separate PR so we could better document this removal for our future selves.
Rationale from Matt:
> I think the original use case was that we’ve got many students doing their exams, and some students have extra time allocated to them. Now we want to give everyone some extra time for some reason, but we want to maintain extra-time-accommodations, so we give 10% extra time to everyone.
>
> I guess I just don’t think that this is a very common scenario. PT handles most such cases already, so it would have to be a very special set of circumstances in PL to trigger the need for this, …

Remove percent-based adjustments to assessment instance time limits

---

apps/prairielearn/src/server.js

Fixes #10838 
This was causing the Modules tab to not be shown active if selected after choosing a course instance.

Fix typo for modules navSubPage

---

apps/prairielearn/src/sync/course-db.ts
apps/prairielearn/src/tests/sync/assessmentsSync.test.ts

As suggested here: https://github.com/PrairieLearn/PrairieLearn/pull/10682#issuecomment-2420134966
I checked the production database for violations of this with the following query:
```sql
SELECT
aq.assessment_id,
aq.init_points,
aq.max_points,
a.course_instance_id,
ci.course_id,
MIN(ciar.start_date) AS start_date,
MAX(ciar.end_date) AS end_date
FROM
assessment_questions AS aq
JOIN assessments AS a ON (aq.assessment_id = a.id)
JOIN course_instance_access_rules AS ciar ON (ciar.course_instance_id = a.course_instance_id)
JOIN course_instances AS ci ON (ci.id = a.course_instance_id)
JOIN pl_courses AS c ON (c.id = ci.course_id)
WHERE
aq.init_points = 0
AND aq.max_auto_points > 0
AND aq.deleted_at IS NULL
AND a.deleted_at IS NULL
GROUP BY
aq.assessment_id,
aq.init_points,
aq.max_points, …
```

Warn when points == 0 and maxPoints > 0

---

docs/assessment.md

Based on confusion in multiple cases, including most recently on Slack: https://prairielearn.slack.com/archives/C266KEH9A/p1729720089108239. This change highlight the narrow set of cases where multiple-instance is suitable.

Clarify docs on multiple instance assessments

---

apps/prairielearn/src/tests/accessibility/index.test.ts

JSDOM is very verbose regarding unimplemented features (e.g., canvas) that make no difference from an accessibility point of view. These warnings polute the CI logs with irrelevant information. This PR changes the console of JSDOM to a virtual console that ignores all output.

Hide JSDOM warnings from accessibility tests

---

apps/prairielearn/assets/scripts/lib/questionsTable.js
apps/prairielearn/src/components/InstructorInfoPanel.html.ts
apps/prairielearn/src/models/questions.sql
apps/prairielearn/src/models/questions.ts
apps/prairielearn/src/pages/clientFilesQuestion/clientFilesQuestion.ts
apps/prairielearn/src/pages/elementFiles/elementFiles.sql
apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts
apps/prairielearn/src/pages/publicQuestionPreview/publicQuestionPreview.ts
apps/prairielearn/src/pages/submissionFile/submissionFile.ts

This PR improves the behavior when a question is shared for copying but not importing (that is, with `"sharePublicly": false, "shareSourcePublicly": true`). The following changes were made:
- Such questions are now displayed on the public questions page and viewable on the public question preview page. Note that these questions don't display the sharing name prefix on the QID. This is our stopgap solution to try to differentiate between "shared for importing" and "shared for copying".
- The "Sharing" column of the course questions table now displays a "Public source" badge for `"shareSourcePublicly": true` questions, to complement the existing "Public" badge. A similar change was made to the "Sharing" section of the question settings page.

Improve source-only sharing of questions

---

apps/prairielearn/src/lib/server-jobs.ts

Add internal batching so that server job outputs will be displayed at least 1 second apart to allow for better performance.

Internal batching using time for server job logging

---

apps/prairielearn/src/lib/workspace.ts
apps/prairielearn/src/tests/workspaceDynamicFiles.test.ts
docs/workspaces/index.md
exampleCourse/questions/demo/workspace/dynamicFiles/server.py
exampleCourse/serverFilesCourse/workspace_file.txt
testCourse/questions/workspace/server.py
testCourse/questions/workspaceInvalidDynamicFiles/server.py
testCourse/serverFilesCourse/workspace_file.txt

This came about from a Slack discussion, where an instructor needed the same file to be made available to workspaces and external graders in multiple questions. External graders already have support for serverFilesCourse. Workspaces can currently support server files by reading the content and adding it directly to params, but this causes params to become unnecessarily large if the file is large enough. This PR adds support for a `serverFilesCourseFile` to the dynamic workspace process, allowing these files to be referenced instead of copied to params.
Closes #10874.

Support adding course server files to workspaces

---

apps/prairielearn/src/cron/cleanUserSessions.sql
apps/prairielearn/src/cron/cleanUserSessions.ts
apps/prairielearn/src/cron/index.ts
apps/prairielearn/src/lib/config.ts

I discussed this in passing with Matt recently. We currently have millions of sessions that don't have an associated user and thus can be safely cleaned up.

Create a cron job to clean up user_sessions rows

---

docs/devElements.md
docs/elementExtensions.md
docs/externalGrading.md
docs/getStarted.md
docs/installing.md
docs/pl-drawing/index.md
docs/workshop/index.md
docs/workshop/lesson4.md
docs/workshop/lesson5.md

This fix was found through a local check using axe-linter, which has a [free version for local execution](https://marketplace.visualstudio.com/items?itemName=deque-systems.vscode-axe-linter) but unfortunately the CI version is not free.

docs: Fix invalid heading levels

---

apps/prairielearn/src/batched-migrations/20241018171312_questions__share_publicly__backfill.sql

This caused two big problems in production:
- This forced us to unnecessarily rewrite the entire `questions` table because the `WHERE` clause didn't exclude non-shared questions.
- More importantly, `FROM questions` caused us to compute and materialize the cross product of all the questions in the ID range and _all the questions_. In practice, this was 139 million rows per batch.
This PR drops the execution time of a batch of 1000 questions from 610596ms to ~1ms.

Remove useless JOIN from questions.share_publicly backfill

---

images/plbase/python-requirements.txt

See https://github.com/hgrecco/pint/commit/d592aff209a0eeae9383042368906dfb5edc5f54, this should fix the following error that we've been seeing in CI this morning:
```
ImportError while loading conftest '/home/runner/work/PrairieLearn/PrairieLearn/apps/prairielearn/python/conftest.py'.
apps/prairielearn/python/conftest.py:2: in <module>
from prairielearn import QuestionData
apps/prairielearn/python/prairielearn.py:28: in <module>
from pint import UnitRegistry
/opt/hostedtoolcache/Python/3.10.[15](https://github.com/PrairieLearn/PrairieLearn/actions/runs/11729274949/job/32674566763?pr=10906#step:16:16)/x64/lib/python3.10/site-packages/pint/__init__.py:18: in <module>
from .delegates.formatter._format_helpers import formatter
/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packag …
```

Upgrade Pint

---

apps/prairielearn/src/server.js

This minor change will allow PrairieLearn to run in Bun with the following:
```sh
cd apps/prairielearn
bun --watch src/server.js
```
This change will be necessary until Bun supports `Server#getConnections`: https://github.com/oven-sh/bun/issues/4459
In my local testing, starting/restarting with Bun was roughly 2x faster than in Node (~4s instead of ~8s).

Get PrairieLearn running in Bun

---

apps/prairielearn/assets/scripts/lib/questionsTable.js

Issue introduced in #10860. The questions table assessments filter relied on the badge class of each assessment to compare with the value of the filter. This is a bandaid solution to get a fix fast, a better way to handle it would probably require a more robust search that doesn't rely on the formatting of the data. This could be something like tabulator (see #8171), or an intermediate solution that reviews the use of filters in this page and others using bootstrap-table.

Fix filter by assessment in questions table

---

docs/lmsIntegrationInstructor.md
docs/lti13.md

We recently decided to use the term "public preview" instead of "early beta" to describe the availability of LTI 1.3 integration. This PR updates the admin-facing docs to use that same terminology. I also tweaked the instructor documentation a bit.

Clarify availability of LTI 1.3 integration

---

exampleCourse/questions/template/checkbox/feedback/info.json
exampleCourse/questions/template/checkbox/random-prompt/info.json
exampleCourse/questions/template/figure/dynamic/info.json
exampleCourse/questions/template/integer-input/random/info.json
exampleCourse/questions/template/matrix-component-input/random-graph/info.json
exampleCourse/questions/template/matrix-input/random/info.json
exampleCourse/questions/template/multiple-choice/images/info.json
exampleCourse/questions/template/multiple-choice/numeric/info.json
exampleCourse/questions/template/multiple-choice/random-prompt-true-false/info.json
exampleCourse/questions/template/multiple-choice/random-prompt/info.json
exampleCourse/questions/template/multiple-choice/random/info.json
exampleCourse/questions/template/number-input/multiple-answer-inputs/info.json
exampleCourse/questions/template/number-input/random-prompt/info.json
exampleCourse/questions/template/number-input/random/info.json
exampleCourse/questions/template/string-input/random/info.json
exampleCourse/questions/template/symbolic-input/random/info.json

These were already shared in the US production environment; we need to reflect that in the JSON. Note that they're currently configured with `share_publicly`; I'll change that to `share_source_publicly` in the database by hand so that this will sync.

Publicly share source of all example course template questions

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/lib/editors.ts
apps/prairielearn/src/pages/instructorFileTransfer/instructorFileTransfer.js
apps/prairielearn/src/pages/instructorFileTransfer/instructorFileTransfer.sql
apps/prairielearn/src/pages/instructorFileTransfer/instructorFileTransfer.ts

Resolves #10931. Changes the redirection target after a successful question copy operation to the question settings page instead of the question preview page. This change makes the operation consistent with a copy within a course, which already redirects to the settings page:
https://github.com/PrairieLearn/PrairieLearn/blob/35ecc8f9a8fbca79963bd13ef33394e860c618c2/apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts#L191

Redirect to question settings page after question copy between courses

---

apps/prairielearn/src/components/QuestionContainer.html.ts
apps/prairielearn/src/components/QuestionScore.html.ts

This is being done as part of the implementation of #10792. Unfortunately that change requires us to make changes gradually so as to not break clients.
This PR adds `id` attributes that will be used in future PRs to change which parts of the page are updated after external grading completes for a submission. The next PR will change the question client JS to be forwards-compatible with receiving these "content" bits of HTML.

Add IDs for dynamically-rendered elements

---

apps/prairielearn/src/pages/instructorCourseAdminStaff/instructorCourseAdminStaff.html.ts

I had to do a double take when adding a staff member because I was confused why the placeholder said student when I was adding staff. This should avoid confusion better.

Change student email placeholders to staff ones on the staff page

---

apps/prairielearn/src/sprocs/instance_questions_grade.sql

Fixes a regression introduced in #10840. The `issues_insert_for_variant` sproc now takes two separate user IDs, but this callsite wasn't updated to account for that.

Fix regression in instance_questions_grade sproc

---

apps/prairielearn/src/webhooks/terminate.ts

We want to fully trust the expiration date so we can adjust this without changes to PrairieLearn.

Trust token expiration date for termination webhook

---

apps/prairielearn/src/question-servers/freeform.js

This PR makes several optimizations to the way the `data` object is handled in freeform questions:
- Rather than deep coping the data with `JSON.parse(JSON.stringify(...))`, we now use `structuredClone`. This should generally be more efficient for large/complex objects, and crucially, it avoids creating copies of large strings like we might see in `raw_submitted_answers`/`submitted_answers` when large files are submitted. This will help minimize memory usage. `structuredClone` has been available since Node 17, so i's available in all our supported versions (v20+).
- `processQuestionHtml` now avoids unnecessary clones of data. Before, we were cloning an object and then essentially asserting that the clone was equal to the original, which was pointless.
- ~`checkData` now only does an …

Optimize handling of data in freeform questions

---

apps/prairielearn/src/lib/chunks.ts
apps/prairielearn/src/tests/chunks.test.ts

This was recently encountered in production. See the new test case and inline comments for details.

Fix chunk loading after question renamed to a parent directory

---

workspaces/vscode-python/settings.json

This has bugged me for a little bit, the font size seems unnaturally big compared to the rest of the UI:
This PR restores it to the default. The user can always adjust this as needed.

Use default font size for workspace-vscode-python image

---

apps/prairielearn/src/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.ts

This wasn't typed correctly in #10950. If a submission is ungraded, this will be `NULL`.

Fix type for correct field in assessment download Zod schema

---

apps/prairielearn/src/lib/externalGradingSocket.ts
apps/prairielearn/src/lib/question-render.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ts
apps/prairielearn/src/pages/instructorQuestionPreview/instructorQuestionPreview.ts
apps/prairielearn/src/pages/publicQuestionPreview/publicQuestionPreview.ts
apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ts

Part of #10792. Uses the new components introduced in #10942, which removes the need to have a CSRF token in this context. Because of the work done in #10936, this will be backwards-compatible with clients that are out there in the wild.

Render new contents for async panel rendering

---

apps/prairielearn/assets/scripts/question.ts
apps/prairielearn/src/components/SubmissionPanel.html.ts

Part of #10792. This teaches the question client to render results via an HTTP request. We can't yet remove the websocket rendering code since some clients may still be expecting to use it. Once this has been deployed, we can rip out the websocket rendering stuff.

Use HTTP to render external grading results

---

apps/prairielearn/src/components/QuestionContainer.html.ts
apps/prairielearn/src/lib/externalGradingSocket.ts
apps/prairielearn/src/tests/gradingMethods.test.ts

Second-to-last part of #10792. In the final PR, I'll update `renderPanelsForSubmission` to use the objects we get from middleware instead of the IDs that it currently uses, which will simplify the implementation.

Remove websocket rendering of question panels

---

apps/prairielearn/src/components/EditQuestionPointsScore.html.ts

A recent question on Slack prompted this solution. This is a proposal, and I won't be offended if it's rejected.
Currently, in the assessment instance page, an instructor can manually set the points/score for an instance question by using the edit (pencil) button beside the points/score for the question. However, the component that enables the update form blocks the update via the form if the question is set up to use rubrics. This makes sense, since we want to ensure some consistency in the grading of the question if rubrics are involved. The instructor still has the option of adding a manual adjustment to the score in the manual grading interface.
This workflow, however, causes problems in questions that were never opened by the student (thus have no variant), or that have no …

Override rubric requirement for instance questions without submission

---

apps/prairielearn/src/lib/group-update.ts
apps/prairielearn/src/pages/instructorAssessmentGroups/instructorAssessmentGroups.html.ts
apps/prairielearn/src/pages/instructorAssessmentGroups/instructorAssessmentGroups.ts
apps/prairielearn/src/tests/groupGenerateAndDelete.test.ts
docs/assessment.md

As discussed in https://github.com/PrairieLearn/PrairieLearn/pull/10985#discussion_r1873717565. The feature for random group generation in assessments was named "Auto", which is misleading and unclear. This PR changes the button and related labels to use the term "Random", as it more clearly indicates what the feature is about.
While the function name in the related library has been changed, the action name in the form was kept the same. This is mostly to avoid problems with old clients accessing new servers. This should not affect the general functionality of the code, since the action name is not generally visible to users.

Rename random group generation for clarity

---

apps/prairielearn/src/pages/home/home.sql

I noticed while testing https://github.com/PrairieLearn/PrairieLearn/pull/11003 that the example course disappeared from the homepage if I removed all the course instances from it. This PR changes that to match the behavior of other courses: it will still be shown even if there aren't any course instances.

Show example course without course instances on homepage

---

apps/prairielearn/src/tests/access.test.ts
apps/prairielearn/src/tests/activeAccessRestriction.test.ts
apps/prairielearn/src/tests/administratorQueries.test.ts
apps/prairielearn/src/tests/bonusPoints.test.ts
apps/prairielearn/src/tests/courseEditor.test.ts
apps/prairielearn/src/tests/fileEditor.test.ts
apps/prairielearn/src/tests/gradeRate.test.ts
apps/prairielearn/src/tests/groupRole.test.ts
apps/prairielearn/src/tests/helperAttachFiles.ts
apps/prairielearn/src/tests/helperClient.ts
apps/prairielearn/src/tests/helperExam.ts
apps/prairielearn/src/tests/instructorAssessmentSettings.test.ts
apps/prairielearn/src/tests/instructorCourseAdminSettings.test.ts
apps/prairielearn/src/tests/instructorQuestionSettings.test.ts
apps/prairielearn/src/tests/permissions/courseAdminAccess.test.ts
apps/prairielearn/src/tests/permissions/studentData.test.ts
apps/prairielearn/src/tests/realTimeGradingDisabled.test.ts
apps/prairielearn/src/tests/showClosedAssessment.test.ts
apps/prairielearn/src/tests/showClosedAssessmentScore.test.ts
apps/prairielearn/src/tests/testSequentialQuestions.test.ts

This PR standardizes us on using `body: new URLSearchParams({ ... })` to construct form data in our tests. This uses web standards with well-defined behavior instead of our custom JSON-based `form` property that doesn't reflect the way browsers will actually submit data from form submissions.

Refactor fetchCheerio to remove form property

---

yarn.lock

#10715 undid the update of path-to-regexp done in #10791. This re-updates the dependency and re-fixes https://github.com/PrairieLearn/PrairieLearn/security/dependabot/205.

Bump path-to-regexp again

---

docs/installingNative.md

The documentation currently assumes Linux has all the dependencies in packages, but that is not the case. For Ubuntu 24.04 in particular:
* d2 is not a package;
* nodejs uses version 18.19 (we need 20);
* redis uses version 5 (we need 6);
* yarn uses version 1.22 (this is not an actual issue since yarn defers to the release found in .yarn).
The PR also changes the link to Yarn to the newest version (it was still pointing to the 1.x version). While the installation of the proper version should not matter much (see above), it probably makes sense to point users to the docs version that matches what we're actually using.

Clarify documentation regarding Linux native installation

---

apps/prairielearn/src/ee/lib/lti13.ts

This broke with the update to 5.7.1 of `openid-client` in #10982. See inline comment for more details.

Fix fetching of LTI 1.3 access tokens

---

apps/prairielearn/src/server.ts
docs/dev-guide/index.md
docs/installingNative.md
images/plbase/plbase-install.sh
packages/postgres/src/pool.ts

We're now running with Postgres 16 in production; time to update our image to reflect that!
We didn't jump to Postgres 17 yet for two reasons:
- AWS Aurora Serverless v2 doesn't yet support it
- It's not present in the Amazon Linux 2023 package repository

Upgrade base image and docs to use Postgres 16

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/migrations/20241219173221_course_instances__ps_linked__drop.sql

This was called out as a remaining task in #3373. This column is no longer read anywhere.
We can't drop the column from the database until it's no longer being expected in the schema. Once this is deployed, we can land a PR that drops the column itself.

Drop course_instances.ps_linked column from Zod schema

---

apps/prairielearn/src/ee/pages/administratorInstitutionSso/administratorInstitutionSso.sql
apps/prairielearn/src/lib/question-render.sql
apps/prairielearn/src/lib/server-jobs.sql
apps/prairielearn/src/lib/workspaceHost.sql
apps/prairielearn/src/sprocs/assessment_instances_grade.sql
apps/prairielearn/src/sprocs/sync_assessment_modules.sql
apps/prairielearn/src/sprocs/sync_assessment_sets.sql
apps/prairielearn/src/sprocs/sync_assessments.sql
apps/prairielearn/src/sprocs/sync_course_tags.sql
apps/prairielearn/src/sprocs/sync_topics.sql
docs/dev-guide/index.md

Based on discussion in https://github.com/PrairieLearn/PrairieLearn/pull/11081#discussion_r1901168880. Replaces all cases where `UNNEST` is used to convert an array to a set to be used with `IN`, when the direct equivalent `= ANY` (or `!= ALL`) can be used instead. We had been slowly moving in this direction, this change updates both the docs and the remaining uses of the old pattern.

Standardize query check for array membership

---

apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.html.ts

This removes an extraneous space between the assessment number and the question mark.

Fix whitespace on the grade instances modals

---

graders/c/cgrader/cgrader.py

Reported by James Foster.
Always decode the output into a string, which avoids a bug where the empty bytestring is not decoded.

Fix bug in cgrader.py

---

docs/elements.md
exampleCourse/questions/demo/annotated/engLogic/question.html
exampleCourse/questions/demo/overlayMap/question.html
exampleCourse/questions/workshop/Lesson3_example4_v2/question.html
exampleCourse/questions/workshop/Lesson4_example2/question.html

#11097 reported that the `demo/overlayMap` question didn't work correctly at different screen sizes. This PR fixes that question and improves the documentation for `<pl-overlay>` to better reflect when an explicit width/height is needed.
Closes #11097.

Fix overlayMap example question; improve pl-overlay docs

---

apps/prairielearn/src/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql
apps/prairielearn/src/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.ts

Resolves #8599.
I only added it to the submissions download files (all/best/last). I didn't add it to instance question download since that file also doesn't include feedback or any other submission-specific info (note that rubric grading is attached to a submission and/or grading job). I also didn't add it to the manual grading download to avoid confusion, since manual grading upload does not currently support rubrics.
This is a feature I'll need myself this coming term.

Add rubric grading to assessment submission download

---

apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.html.ts

As of #10591, the question preview page is not accessible for users without previewer permission in the course. The assessment instance page still had links that pointed to the preview page even if the user had no access to it. This PR removes those links to avoid confusion.

Remove instructor links from assessment instance page if user has no access

---

apps/prairielearn/src/lib/question-render.ts

This was an unintentional behaviour change in #11089, where the answer panel used to be hidden in the instructor preview page until at least one submission was sent. #11089 made it always shown, so this PR restores the original behaviour to hide the answer panel.

Restore hiding answer panel in question preview when there are no submissions

---

Makefile

As suggested by @trombonekenny in #11125. `build-docs` will fail unless `d2` is installed, and it isn't installed in the `prairielearn/prairielearn` image. We don't want to install `d2` there since we don't want that to become part of the "API" we offer to questions.
Closes #11125.

Remove build-docs from ci Makefile target

---

apps/prairielearn/src/lib/editors.ts

Based off this suggestion: https://github.com/PrairieLearn/PrairieLearn/pull/11117#discussion_r1909369992
- Adjusted editors to use `formatJsonWithPrettier` and `writeFile` instead of using `writeJson`.

Update file editors to use formatJsonWithPrettier

---

apps/prairielearn/python/zygote.py
apps/prairielearn/src/question-servers/freeform.js

This was reported as an issue on Slack. In short, we weren't correctly seeding the random number generator when the `process-questions-in-worker` feature is turned on. This is because the RNG-seeding code assumes that the last thing in `args` will be the `data` object containing the `variant_seed`:
https://github.com/PrairieLearn/PrairieLearn/blob/ac67ff0eacefd4ed2ed730e72e758f2e6076f864/apps/prairielearn/python/zygote.py#L257-L267
However, when I implemented the experimental processor, I changed that convention and instead passed a different object as the last element in `args`.
For simplicity's sake, to fix this, I just swapped the order so that `data` would once again be the last thing.

Fix RNG seeding in experimental question processor

---

apps/prairielearn/elements/pl-integer-input/pl-integer-input.py
apps/prairielearn/elements/pl-python-variable/pl-python-variable.py
apps/prairielearn/python/prairielearn.py
apps/prairielearn/python/zygote.py
exampleCourse/questions/demo/annotated/LectureVelocity/1-Introduction/server.py
exampleCourse/questions/demo/annotated/LectureVelocity/4-KnowledgeTest/server.py
exampleCourse/questions/demo/randomPlot/server.py
exampleCourse/questions/gallery/includeFigure/complex/server.py
graders/python/python_autograder/pl_execute.py
graders/python/python_autograder/pl_unit_test.py
pyproject.toml
testCourse/questions/differentiatePolynomial/server.py

- Enforces imports of `pandas`, `matplotlib`, `numpy`.
- This PR also introduces the flake8-implicit-str-concat ruleset, which does not affect any of our code.
- All changes were automated

Ruff: flake8-import-conventions, flake8-implicit-str-concat

---

apps/prairielearn/python/prairielearn.py
graders/python/python_autograder/pl_unit_test.py
pyproject.toml

```
"YTT",
"ASYNC",
"DTZ",
"T10",
"LOG",
"PYI",
"SLOT",
"INT",
"FLY"
```
These rules barely affect us; but they felt useful to enable to catch future issues. Only `flake8-pyi` affects our codebase.

Ruff: misc ruff rules

---

workspaces/jupyterlab-python/README.md

Adding in the missing documentation from #10596 explaining how to launch a file automatically when opening this workspace.
Please let me know if anything else should be included here whilst I am adding this file.

Launch file documentation for jupyterlab-python

---

apps/prairielearn/src/middlewares/authnToken.ts
docs/api.md

Closes #5487. I confirmed via load balancer logs that no one has used this in the past month.

Remove ability to set API token via query parameter

---

docker/start_s3rver.sh

See the issue [123 in the amazonlinux repo](https://github.com/amazonlinux/container-images/issues/123) for context.  PR sets a `ulimit` in the one script `lsof` is called it, this unplugs an issue seen on Ubuntu 24.10 (and so far only on Ubuntu 24.10).

Use ulimit to avoid lsof hanging when Docker image runs on Ubuntu 24.10

---

graders/c/cgrader/cgrader.py

Tested with correctly tagged docker image.
`docker build --platform linux/amd64 -t cgrader .`

Revert bad type annotation in cgrader

---

apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js

Fixes a regression introduced in #11069, which caused the button to edit the rubric item explanation and grader note to not work if the original explanation was blank (which would cause the label to not exist.
Also fixes a reference to the event target to use `currentTarget`, since `event.target` may refer to a child of the button (e.g., the SVG image included in the button).

Fix handling of long text fields in rubric settings

---

graders/python/python_autograder/pl_execute.py

#11142 introduced a regression here. `matplotlib.pyplot` must be imported before one can read it. The original code was written like this:
```py
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot
plot_value = matplotlib.pyplot
```
However, that would cause some linter complaints, so I changed it slightly here. I think the new version is slightly clearer anyways.

Fix regression with plots in Python grader

---

apps/prairielearn/assets/scripts/behaviors/popover.ts
apps/prairielearn/assets/scripts/behaviors/tooltip.ts
apps/prairielearn/assets/scripts/navbarClient.ts
apps/prairielearn/public/stylesheets/local.css
apps/prairielearn/src/components/Navbar.html.ts
apps/prairielearn/src/pages/authLogin/authLogin.html.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts
docs/dev-guide/index.md
docs/elements.md

Part of #11088. This PR removes all code that made our application code backwards-compatible with Bootstrap 4. I tested these changes as follows:
- Popover changes were tested on the course instances page; there are two popover triggers in table headers, and I was able to test all the behavior with those (even focus traps, since they include focusable content).
- Tooltip changes were tested by opening an issue on a student instance of a question and then opening the manual grading page for that assessment question. There are tooltips to warn about the issue _and_ an open assessment instance, both of them work.
- Navbar changes were tested by navigating to a course and then opening the course and course instance switchers. Both work correctly.
- Table styling changes were tested on the …

Remove Bootstrap 4 backwards-compat

---

apps/prairielearn/assets/scripts/behaviors/bootstrap-compat.ts
apps/prairielearn/src/ee/pages/administratorInstitutionSaml/administratorInstitutionSaml.html.ts

This doesn't really matter, but I frequently use these pages to copy/paste things from, so I want to make sure they're demonstrating the right way to do things.
Before:
After:
I also updated the Bootstrap 5 compat script to avoid adding a `form-label` class to a `<label>` if the `form-check-label` class was already present.

Fix styling of SAML settings checkboxes

---

mkdocs.yml

Changes option on https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#options
> If a snippet declaration is processed, and the specified file cannot be found, then the markup will be removed.
To
> Make the build fail if a snippet can't be found.

enforce snippets exist

---

pyproject.toml

Closes #11092 
The remaining rules don't need to be enabled, and this just cleans up the remaining notes about it

finish up pyproject.toml

---

apps/prairielearn/src/pages/home/home.html.ts
apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.html.ts
docs/courseInstance.md
docs/getStarted.md

Per discussion with @mwest1066 and @mfsilva22, these docs could use some improvement. This PR makes several changes:
- Access control and enrollment control are now adjacent to each other in the docs since they're pretty related.
- There are now concrete examples for controlling access based on institution and UIDs.
- I updated the description of the enrollment process from the homepage; the button is now called "Add or remove courses", not "Enroll".
- This is unrelated to the main goal here, but I added an admonition to note that LTI 1.1 is deprecated and added a link to the LTI 1.3 docs.

Improve course instance access/enrollment docs

---

apps/prairielearn/python/python_helper_sympy/__init__.py
apps/prairielearn/python/zygote.py
pyproject.toml

- Enables `typeCheckingMode = "strict"`
- Silences most strict rules
- Allows for incremental type improvements
- Adds a separate `3.12` execution environment for the graders

Pyright: Invert rules, execution environments

---

apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.html.ts
apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.ts
apps/prairielearn/src/lib/db-types.ts

Lifting this out of #11184. Conventionally, these schemas/types should match the underlying table name.

Fix name of AiQuestionGenerationPromptSchema

---

apps/prairielearn/src/components/QuestionsTable.html.ts

Complements #11184 by providing a way to get to the draft questions page even when there are no other non-draft questions in the course.
This will also be useful once we turn this feature on more widely; people can create their very first question with AI!

Show AI question generation in questions table empty state

---

apps/prairielearn/elements/pl-code/pl-code.py
apps/prairielearn/python/prairielearn/core.py
pyproject.toml

- Makes pyright rules stricter
- pl-code change wasn't tested, but the constructor unpacks with `**options` so it seems unlikely to break it?

pyright: add rule improvements

---

apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.sql
apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.ts

Complements #11184, lifting this change out of that PR. This ensures that any courses that were dynamically inserted into the database are synced via the "Load from disk" button in local dev. Previously, only courses explicitly listed in `config.json` would have been loaded.

Merge database and config courses for dev load from disk

---

apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts

Lifting these changes out of #11184. From my testing, these changes improve two things:
- A `server.py` is much more likely to be generated when it's needed (though still not 100% of the time, which is why we have manual checks for that)
- It's much more likely to use our supported Mathjax delimiters.

Tweak AI question generation prompt

---

yarn.lock

Resolves https://github.com/PrairieLearn/PrairieLearn/security/dependabot/217.

Bump undici from 6.19.8 to 6.21.1

---

apps/prairielearn/python/prairielearn/internal/question_phases.py
apps/prairielearn/python/zygote.py

We have this same little snippet in `zygote.py`:
https://github.com/PrairieLearn/PrairieLearn/blob/65fb2c39a51c69508d94ff9149f324fb0f77969d/apps/prairielearn/python/zygote.py#L326-L335
We neglected to carry over this behavior into the new question processor, which caused problems with courses that were using ancient custom elements.
I tested this by changing the `pl-number-input` implementation to include the other parameter. I confirmed that it was broken without this change and worked correctly after this change.

Fix backwards compatibility with legacy question functions

---

apps/prairielearn/python/prairielearn/internal/question_phases.py

In the old question processor, we don't check `data` during either `render()` or `file()`:
https://github.com/PrairieLearn/PrairieLearn/blob/97a877d300df072c2c3dcd7c04f93c2cc503653f/apps/prairielearn/src/question-servers/freeform.js#L612-L647
This PR updates the new one to match this behavior for backwards compatibility.

Update new question processor data validation to match old one

---

apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts
apps/prairielearn/src/tests/accessibility/index.test.ts

This is needed to test pages that are unavailable in the example course (where editing is generally disabled).
This had the benefit of catching some genuine accessibility issues on the question settings page!

Use test course for accessibility tests

---

docs/assets/extra.css
docs/installingNative.md

Addresses my comment here: https://github.com/PrairieLearn/PrairieLearn/pull/11012#discussion_r1931238196. So far, this just adds a light border that matches that below the tabs.
Before:
After:
After (dark mode):

Refine styles of tabbed content in docs

---

apps/prairielearn/src/lib/editors.ts
apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.ts
apps/prairielearn/src/pages/instructorAssessments/instructorAssessments.ts
apps/prairielearn/src/pages/instructorCourseAdminInstances/instructorCourseAdminInstances.ts
apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ts
apps/prairielearn/src/pages/instructorFileBrowser/instructorFileBrowser.ts
apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.ts
apps/prairielearn/src/pages/instructorFileTransfer/instructorFileTransfer.ts
apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts
apps/prairielearn/src/tests/instructorAssessmentSettings.test.ts

Closes #11222.
As proposed in that issue, this PR introduces a new `MultiEditor` that itself can execute multiple editors.
As part of this, I removed some dead code related to a `change_id` action that was since removed. I also did some refactoring of editors as a whole to improve type safety.

Make multi-part file edits atomic

---

docker/start_redis.sh
docs/installingNative.md
images/plbase/plbase-install.sh

- resolves an inconsistency between `redis6`  / `redis`: almost all systems use `redis-cli` not `redis6-cli`, etc.
- updates package list to be valid

Update redis installation / WSL package list

---

apps/workspace-host/package.json

The current nodemon configuration on workspace-host uses the default settings for extensions, which does not include ts files. This means nodemon will not restart the workspace host if there are changes to interface.ts (the main file in workspace-host), which defeats the purpose of using nodemon in this context. This PR changes the settings of nodemon to use the same extensions as the prairielearn server.

Add TS files to nodemon watchlist in workspace host

---

apps/prairielearn/elements/pl-matrix-output/pl-matrix-output.py
apps/prairielearn/elements/pl-variable-output/pl-variable-output.py
apps/prairielearn/python/prairielearn/core.py
apps/prairielearn/python/test/core_test.py

Fixes regressions introduced in #11158. Incorrect runtime type checks were added that caused `string_from_numpy` to raise a `ValueError` when called with instances of `np.float64` and similar values.
I uncovered a second error while testing: `pl.string_from_number_sigfig(complex(1, 2))` would incorrectly produce a string like `1.0`. This was also due to incorrect runtime type checks.

Fix bugs in core.string_from_numpy(...)

---

apps/prairielearn/python/prairielearn/internal/traverse.py
apps/prairielearn/python/test/traverse_test.py

@ffund reported that the following example broke when rendered with the new question processor:
```html
<pre>&langle; something &rangle;</pre>
```
She used to see this:
```
⟨ something ⟩
```
But now saw this:
```
&langle; something &rangle;
```
This occurs because `libxml2` (and this `lxml`) only knows about HTML4 named entities, but `&langle;` and `&rangle;` were only defined in HTML5. See this issue: https://gitlab.gnome.org/GNOME/libxml2/-/issues/857
This wasn't a problem with the old question processor, which used `parse5` and properly supported these out of the box.
The easiest way to fix this was to eagerly resolve named entities to their actual Unicode characters, and then re-escape to just handle `&`, `<`, and `>`. We explicitly declare all our documents as being `utf-8`, so this …

Fix handling of HTML5 named entities in new question processor

---

apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.html.ts
apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.html.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts
apps/prairielearn/src/tests/fileEditor.test.ts

This PR updates the course instance settings (`instructorInstanceAdminSettings`) page to include form fields. This is a stepping stone to adding an editor to this page. As we have done with other settings pages, we are first converting the main card to include form fields. These will be updated to be editable in a future PR. I have used the course settings (`instructorCourseAdminSettings`) page as a template for the changes here.

Update course instance settings page

---

apps/prairielearn/elements/pl-number-input/pl-number-input.py
apps/prairielearn/python/prairielearn/core.py
apps/prairielearn/python/test/core_test.py

This was another regression introduced by recent changes to the `string_from_number_sigfig` function. Historically, it allowed and correctly handled strings, though this wasn't documented and thus didn't make its way into our types. This manifests as a problem when someone specifies a string correct answer for `<pl-number-input comparison="sigfig">`. We'd pass the string to `string_from_number_sigfig`, which would fail at the newly-added type assertion.
This PR makes two changes to make things work:
- It changes `string_from_number_sigfig` to support strings as the first argument.
- It changes the `format_true_ans` function in `pl-number-input` to support string correct answers. Previously, this was (maybe accidentally) allowed when `comparision="sigfig"`, but would otherwise fail. Now, …

Allow strings in string_from_number_sigfig

---

apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.ts

Resolves #11310. Ensures that directories that are listed as relative paths in the config for "courseDirs" (such as exampleCourse, testCourse and templateCourse)  are not loaded twice when "Load from disk" is invoked, by using the resolved path when comparing with existing courses.

Fix handling of relative paths in course directories config

---

apps/prairielearn/elements/pl-code/pl-code.py
apps/prairielearn/elements/pl-drawing/elements.py
apps/prairielearn/elements/pl-matching/pl-matching.py
apps/prairielearn/elements/pl-multiple-choice/pl-multiple-choice.py
apps/prairielearn/elements/pl-order-blocks/dag_checker.py
apps/prairielearn/elements/pl-units-input/pl-units-input.py
apps/prairielearn/elements/pl-units-input/unit_utils.py
apps/prairielearn/python/prairielearn/colors.py
apps/prairielearn/python/prairielearn/core.py
apps/prairielearn/python/prairielearn/internal/traverse.py
apps/prairielearn/python/prairielearn/internal/zygote_utils.py
apps/prairielearn/python/prairielearn/sympy_utils.py
apps/prairielearn/python/prairielearn/unicode_utils.py
pyproject.toml

This is going to help document our codebase in a consistent manner. Enforcing some of these rules will as a bonus, help us generate code documentation (see #11216 )
Applies:
- D200 One-line docstring should fit on one line
- D401 First line of docstring should be in imperative mood
- The rule about no function in docstring itself

ruff: start linting docstrings

---

apps/prairielearn/src/lib/db-types.ts

This is necessary to accurately reflect the database schema itself:
https://github.com/PrairieLearn/PrairieLearn/blob/975da6547c50b68a1afdbd3c78818cd89c7ac559/database/tables/enrollments.pg#L3

Mark enrollments.created_at as nullable in Zod schema

---

apps/prairielearn/src/pages/instructorGradebook/instructorGradebook.html.ts

This regressed in #11209. Before this change, the instructor course instance gradebook page wouldn't show the usual navigation tabs.

Ensure tabs are shown on the instructor gradebook

---

apps/prairielearn/src/migrations/20250210225102_tags__not_null_constraints__add.sql
apps/prairielearn/src/migrations/20250210225433_topics__not_null_constraints__add.sql
apps/prairielearn/src/migrations/20250211000848_assessment_modules__heading__nonnull.sql
database/tables/assessment_modules.pg
database/tables/tags.pg
database/tables/topics.pg

This is necessary for some upcoming improvements of tags/topics/modules syncing. We already did this for `assessment_sets` in #9972.

Add NOT NULL constraints for tags/topics/modules

---

apps/prairielearn/python/prairielearn/internal/traverse.py
apps/prairielearn/python/test/traverse_test.py

#11302 missed the case of trailing text. This PR adds test cases that failed with the previous implementation and fixes the underlying issue.
Closes #11326.

Fix escaping of trailing text in question HTML

---

apps/prairielearn/src/batched-migrations/20250212010945_variants__authn_user_id__backfill.sql
apps/prairielearn/src/batched-migrations/20250212010945_variants__authn_user_id__backfill.ts
apps/prairielearn/src/migrations/20250206202509_variants__authn_user_id__nonnull.sql
apps/prairielearn/src/migrations/20250212010945_variants__authn_user_id__backfill.ts
apps/prairielearn/src/migrations/20250212011728_variants__authn_user_id__backfill__finalize.ts
apps/prairielearn/src/migrations/20250212012249_variants__authn_user_id__nonnull.sql

#11314 failed in production. The entire database locked up, presumably because we tried to rewrite ~1.6 million rows at once. From what we can tell, locking wasn't involved, it was just the write load that killed us.
This PR does what we probably should have done in the first place: it adds a batched migration to backfill `variants.authn_user_id`, finalizes it, and then does the usual thing to actually mark the column as `NOT NULL`.

Correctly backfill `variants.authn_user_id` and add `NOT NULL` constraint

---

apps/prairielearn/src/migrations/20230523200759_variants__course_id__nonnull.sql
apps/prairielearn/src/migrations/20240111005800_group_users__group_config_id__not_null.sql
apps/prairielearn/src/migrations/20240111010531_groups__group_config_id__not_null.sql
apps/prairielearn/src/migrations/20250117000347_variants__variant_seed_nonnull.sql
apps/prairielearn/src/migrations/20250212012249_variants__authn_user_id__nonnull.sql

While trying to run the migration from #11351 that added a `NOT NULL` constraint to `variants.authn_user_id`, @mwest1066 and I observed that the migration would hold a lock on `variants` and block all reads/writes of the table. We confirmed that the issue is running all these statements in a transaction, which happens by default:
https://github.com/PrairieLearn/PrairieLearn/blob/81e6792bcf7c6b1b914d424396b9b7d59b865a0b/packages/migrations/README.md?plain=1#L26-L33
We confirmed that manually executing the steps one by one outside of a transaction avoid locks.
To help our future selves, we also updated all existing similar migrations to do the same. This ensures we can safely copy/paste from any one of them in the future.

Run all NOT NULL constraint addition migrations outside transactions

---

apps/prairielearn/src/migrations/20250212012249_variants__authn_user_id__nonnull.sql
apps/prairielearn/src/migrations/20250213014138_variants__authn_user_id__nonnull_constraint_add.sql
apps/prairielearn/src/migrations/20250213014139_variants__authn_user_id__nonnull_constraint_validate.sql

The change in #11357 wasn't enough to run the migration. We think we need to split it in half. Based on our observations, Postgres will run all parts of a multi-statement query as part of an implicit transaction.

Retry NOT NULL variants.authn_user_id migration

---

tools/api_download.py

As @mfsilva22 pointed out to me, `content-length` doesn't appear to be in the headers anymore. We were only using it for informational purposes so we can replace it with another measure of download size.

Fix `api_download.py` bug with `content-length`

---

yarn.lock

Dependeabot reported issues with `@octokit/plugin-paginate-rest` and `@octokit/endpoint`. While we aren't vulnerable, it was easy to upgrade to the latest versions anyways.

Resolve vulnerabilities in GitHub client libraries

---

mkdocs.yml

Currently in the docs tabs create odd numbered anchors.
This update automates named tabs based on the content of the tab title.

Make docs tabs named instead of numbered

---

docs/assets/extra.css
docs/developer-guide/index.md
docs/getting-started/index.md
docs/installingNative.md
docs/instructor-guide/index.md
mkdocs.yml

- Enables section indexes, and writes a small blurb for some.
Clickable/non-clickable indexes now differentiated by color.

docs: enable section indexes

---

images/plbase/python-requirements.txt

Adding this as a dependency to avoid keeping a local copy of this code for questions our course would like to share. Other courses have installed and used this library on their own as well, so I think this is worth adding. Also generally very light on dependencies we don't have installed already. Happy to answer any questions about this.

Add `automata-lib` dependency

---

apps/prairielearn/elements/pl-card/pl-card.mustache
docs/elements.md
exampleCourse/questions/element/card/question.html

This change allows HTML tags such as `<strong>` and `<code>` to be used inside of the pl-card `header` attribute.
It also updates the element question with an example showing this and changes the URL to a new website for the placeholder images due to the previous one being taken down.
Was
Now
Edit: update for footer - https://github.com/PrairieLearn/PrairieLearn/pull/11384#issuecomment-2661912711

Allow pl-card header and footer to use HTML tags

---

docs/elements.md

Added the missing link to make richTextEditor example link to GitHub from [the docs](https://prairielearn.readthedocs.io/en/latest/elements/#pl-rich-text-editor-element)

Add missing link for richTextEditor

---

apps/prairielearn/assets/scripts/instructorQuestionSettingsClient.ts
apps/prairielearn/elements/pl-number-input/pl-number-input.mustache
apps/prairielearn/elements/pl-string-input/pl-string-input.mustache
apps/prairielearn/src/components/SyncProblemButton.html.ts
apps/prairielearn/src/pages/instructorIssues/instructorIssues.html.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts

This PR addresses several of the bullet points in #11360 regarding issues with labeling for accessibility. In this PR I have addressed the following issues:
- The `pl-string-input` element and `pl-number-input` element were pointed to incorrect elements in `aria-describedby` and `aria-labelledby`.
- The "Warning" trying on the course instances page did not have a label.
- The "?" button on the issues page does not have a label.
- The "Topic" and "Tags" dropdowns on the question settings page did not have labels.

Fix accessibility labels

---

packages/workspace-utils/package.json
yarn.lock

This ensures that `turbo` builds things in the correct order. Without this, there's a race condition where `@prairielearn/workspace-utils` might be built before `@prairielearn/zod`. This would fail, since the expected types wouldn't be present. We observed this in the wild here: https://github.com/PrairieLearn/PrairieLearn/actions/runs/13400788552/job/37430902112

Add missing dependency to workspace-utils

---

apps/prairielearn/src/batched-migrations/20250214035153_course_instance_usages__submissions__backfill.sql
apps/prairielearn/src/batched-migrations/20250214035153_course_instance_usages__submissions__backfill.ts
apps/prairielearn/src/migrations/20250214035153_course_instance_usages__submissions__backfill.ts

Part of #11289, following on from #11298
Our strategy here is to delete all submission usage data older than `CUTOFF_DATE` and then regenerate it from submissions which are also older than `CUTOFF_DATE`.

Backfill usage data from submissions

---

apps/prairielearn/src/ee/auth/saml/index.ts

This came up during the integration process with UCSD, their integration folks noticed that our SAML metadata included the following:
```xml
<NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
```
This is added by default by the `@node-saml/node-saml` library that we use. Setting it to `null` will remove the property and help avoid confusion.

Remove NameIDFormat from SAML metadata

---

yarn.lock

This resolves a security vulnerability reported by Dependabot. We aren't actually vulnerable to it, but bumping to the latest version is cheap.

Upgrade @octokit/plugin-paginate-rest

---

apps/prairielearn/src/ee/lib/aiQuestionGeneration.sql
apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts
apps/prairielearn/src/lib/url.ts
apps/prairielearn/src/models/question.sql
apps/prairielearn/src/models/question.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts
apps/prairielearn/src/pages/instructorQuestions/instructorQuestions.ts
apps/prairielearn/src/server.ts
apps/prairielearn/src/tests/accessibility/index.test.ts
apps/prairielearn/src/tests/instructorQuestions.test.ts

This adds support for a route like `/pl/course/1/course_admin/questions/qid/demo/addHTMLtable`, which will redirect to the specified question based on its QID. This is designed primarily for automated testing use cases, where one wouldn't want to jump through hoops to try to get a database ID based on a QID on disk.

Add route to redirect to question based on QID

---

apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js

`event.target` would _not_ be an instance of `HTMLElement` if the click was actually on the icon; instead, it would be an `SVGElement`.

Fix click handlers on rubric modal buttons

---

apps/prairielearn/assets/scripts/lib/histmini.ts

When working on #11390, I did not realize I needed to add a role to `histmini` as well. This adds that role of `none` which will satisfy accessibility requirements for the SVGs.

Add role to mini histogram

---

apps/prairielearn/src/ee/lib/ai-grading.ts

In [our local testing of AI grading](https://arxiv.org/abs/2502.13337), a temperature of 0.2 is observed to result in a higher accuracy than 0.7 (default value).

Decrease temperature to api call for AI grading

---

workspaces/jupyterlab-python/Dockerfile

This change fixes some weirdness that we've observed when real-time collaboration is enabled.
To reproduce the issue (or lack of it):
- Find a question that uses the `prairielearn/workspace-jupyterlab-python` workspace image
- Enable real-time collaboration:
```json
{
"workspaceOptions": {
"environment": {
"ENABLE_REAL_TIME_COLLABORATION": "true"
}
}
}
```
- Launch the workspace and open the notebook.
- Edit and then execute any cell.
- Reload the webpage.
- **Broken**: the file opens as completely empty, without even showing editor UI.
- **Fixed**: the file open as normal.

Use new version of jupyter/minimal-notebook base image

---

apps/prairielearn/src/ee/lib/ai-grading.ts

When there is a current feedback to a manually graded question, ai grading again on the problem using a rubric would leave the current feedback as-is, is might not match the necessary feedback. This PR will remove the existing feedback when ai grading with rubric.

Remove existing feedback when grading with rubric

---

apps/prairielearn/src/ee/lib/ai-grading.ts

In the current setup of AI grading, a problem with both manual graded and autograded parts will be overwritten by the AI grade when using it, but AI grade should only modify the manual score. 
Note that this doesn't stop the AI from seeing the autograded parts and attempting to give scores. This will be dealt with in a later PR.

AI grading without rubric should only update manual score

---

yarn.lock

#11413 updated a dependency on v9, but another package depends on v11, which also has the same vulnerability issue.

Upgrade @octokit/plugin-paginate-rest v11

---

apps/prairielearn/src/models/course-instance-usages.sql

As reported on Slack, the previous code would error out if the grading job itself failed (for instance, if one forgot to mount the Docker socket into the PrairieLearn Docker container in local development):
> Error processing results for grading job 1 null value in column "duration" of relation "course_instance_usages" violates not-null constraint

Handle failed grading jobs when computing course instance usage

---

apps/prairielearn/assets/scripts/workspaceClient.ts
apps/prairielearn/src/pages/workspace/workspace.html.ts

Fixes #11120. If a workspace fails to load (e.g., the image is invalid), changes the spinning circle interface to an error message instead.

Improve interface when workspace fails to load

---

.eslintrc.cjs

Our existing config was causing problems in #11459 when we removed the `tsconfig.json` file from the root of the repo. As it turns out, we don't actually need any of these rules expect for `import-x/order` because TypeScript will check everything else for us.

Disable unnecessary esbuild-plugin-import-x rules

---

contrib/question_converters/canvas/canvas.py

Introduced in #11143. Not sure what I was thinking with that change, I hadn't tested it, and it will obviously fail on the basis of a `__init__` call.
Apologies for introducing a change without testing -- I was reminded about the unresolved comment on that PR when this was mentioned on Slack.
This also isn't tested, but this at least won't make things more broken (i.e. `course.quiz` and `self.get_course().quiz` might both throw an error).

Fix bug in Canvas question conversion script

---

contrib/question_converters/canvas/canvas.py

This was broken by #11148, which performed an incomplete removal of an unused argument.

Fix another bug in the Canvas conversion script

---

.github/workflows/main.yml

The image build process introduced in #11096 is broken if the `workspace-vscode-base` image didn't change. I hope this fixes it.

Only use local workspace-vscode-base image if it changed

---

packages/compiled-assets/src/index.ts

When the PrairieLearn dev server is running behind a reverse proxy, e.g. to serve it from a "real" domain on the internet, esbuild rejects requests because the host on the request doesn't match the host that the esbuild dev server is running on. This was changed in https://github.com/evanw/esbuild/releases/tag/v0.25.0 to prevent a security issue.
This would also impact people who are using local DNS overrides to serve from a non-localhost domain.
This PR fixes that by modifying the proxied request to make it seem like it came from localhost.

Ensure esbuild dev server works with proxied requests

---

.github/workflows/main.yml
Makefile

- CI currently wasn't caching turbo correctly: I suspect that the yarn cache wasn't playing nice. I moved the cache to a different location to avoid this problem. https://github.com/vercel/turborepo/issues/451#issuecomment-1191115427
- Use uv to shave some seconds
- Goes from 4:30 to 2:45 minutes

CI turbo build cache, uv build + cache, apt cache

---

apps/prairielearn/assets/scripts/workspaceClient.ts

Fix to #11440. In production, things are slow enough that the client actually witnesses the full `uninitialized` -> `stopped` -> `launching` sequence. This doesn't occur in local dev so wasn't caught during testing.

Don't show workspace failure message on initial transition to stopped

---

graders/c/cgrader/cgrader.py

The C grader was implemented to accept, in `exp_output` and `reject_output`, regular expressions instead of just strings, however in #11119, when types were added to the autograder code, these arguments did not have the appropriate types added to type annotation. Moreover, that PR changed a check if the argument was not a list to replace it with a check if the argument was a string, which left out regular expressions. This PR fixes this omission allowing regular expressions to be used in the grader.
This also resolves #11507.

C grader: fix types for expected output

---

apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/lib/question-render.sql
apps/prairielearn/src/sprocs/grading_jobs_insert.sql
apps/prairielearn/src/sprocs/grading_jobs_update_after_grading.sql
apps/prairielearn/src/sync/tests.md

Once this is deployed, we can remove this column entirely. It's currently not being used at all, and is just causing confusion for us.

Stop reading/writing `submissions.grading_method`

---

apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.html.ts
apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.html.ts

The use of `QRCodeModal` (which itself renders a `<form>`) inside another `<form>` resulted in an HTML document that parsed with the submit button outside of the form, which broke editing. Moving the modal outside of the form fixes this.
In another PR, I want to introduce an HTML validator that will help catch these things during automated testing. **Edit**: #11522

Fix submit button on settings forms

---

apps/prairielearn/src/components/ProgressCircle.html.ts

This PR fixes the following error that I observed in the browser dev tools when the course getting started page is shown:
```
Error: <svg> attribute viewBox: Expected number, "0 0 20px 20px".
```

Fix viewBox attribute of ProgressCircle svg

---

apps/prairielearn/src/components/Navbar.html.ts

Related to https://github.com/PrairieLearn/PrairieLearn/pull/11279#discussion_r1980328391. 
Added trigger that preloads navbar course and course instance dropdown elements on user hover/focus.

Load navbar dropdown options on mouseover or focus

---

apps/prairielearn/src/components/Navbar.html.ts
apps/prairielearn/src/components/ProgressCircle.html.ts
apps/prairielearn/src/components/SideNav.html.ts
apps/prairielearn/src/lib/navPageTabs.ts

Closes #11510. 
- Added issue count to enhanced navigation sidebar.
Here's what it looks like when the getting started sidebar tab is shown:
and when it is hidden:

Add issue count to enhanced navigation sidebar

---

apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.html.ts

While testing recent changes, I noticed that the course instance settings page had a different ordering of fields than the assessment and question settings pages, where the AID/QID fields came first. This PR reorders the fields on this page to match the others, which should make the UI more consistent and predictable.

Reorder fields on course instance settings editor

---

apps/prairielearn/elements/pl-external-grader-results/pl-external-grader-results.mustache

Closes #11549.
With normal-length titles:
With very long titles:

Fix alignment in pl-external-grader-results

---

apps/prairielearn/src/lib/navPageTabs.ts

Closes #2263 by linking the instance to the same heading as instructor instances page
Not sure if this will be handled elsewhere (https://github.com/PrairieLearn/PrairieLearn/issues/2263#issuecomment-2721927051) but created the PR if not

Add highlight of tab bar inside of instance

---

apps/prairielearn/assets/scripts/behaviors/popover.ts
apps/prairielearn/assets/scripts/behaviors/tooltip.ts
apps/prairielearn/public/stylesheets/local.css
apps/prairielearn/src/components/InstructorInfoPanel.html.ts
apps/prairielearn/src/components/QuestionContainer.html.ts
apps/prairielearn/src/components/SubmissionPanel.html.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.html.ts
apps/prairielearn/src/pages/instructorQuestionPreview/instructorQuestionPreview.html.ts
apps/prairielearn/src/pages/instructorQuestionPreview/instructorQuestionPreview.ts
apps/prairielearn/src/pages/publicQuestionPreview/publicQuestionPreview.html.ts

This will soon be an important part of AI question grading: we'll want to give instructors the ability to see what context is being sent to the LLM. Though that doesn't exist yet, this establishes the UI and backend conventions for that.
This is activated with a button that I put in the upper right of the question panel (open to alternative suggestions):
When the preview is active, a dismissible alert is shown to inform the user of the current setting, and they're given a link to return to the normal view.

Add ability to preview manual grading view from question preview page

---

apps/prairielearn/src/components/QuestionContainer.html.ts
apps/prairielearn/src/components/SubmissionPanel.html.ts
apps/prairielearn/src/lib/question-render.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ts
apps/prairielearn/src/pages/instructorQuestionPreview/instructorQuestionPreview.html.ts
apps/prairielearn/src/pages/instructorQuestionPreview/instructorQuestionPreview.ts

Any submissions but the three most recent aren't rendered until they're actually viewed. However, the routes that handled rendering those submissions previously weren't aware of if the panel was being rendered in the context of manual grading. This PR resolves that by propagating a value for `manualGradingInterface` into `renderPanelsForSubmission`.
When we force the instructor question preview to show the manual grading interface as implemented in #11528, we need to propagate the fact that we've been forced into that state back into the route that serves the submission HTML. This PR adds such a parameter to `QuestionContainer` and drills it down to `SubmissionPanel`.

Respect manual grading mode when async rendering submissions

---

apps/prairielearn/src/components/InstructorInfoPanel.html.ts
apps/prairielearn/src/lib/question-render.sql
apps/prairielearn/src/lib/question-render.ts
apps/prairielearn/src/middlewares/selectAndAuthzInstanceQuestion.sql
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.html.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.ts
apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.html.ts
apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ts

Resolves #11574. Adds the UID info to assigned grader and last grader information in the Staff information panel.
This PR also takes the opportunity to remove the assigned grader/last grader from res.locals, and move them to local variables computed when needed.
Only the instance question page has been updated. The assessment question list of instances still only shows the name.

Add grader UID to staff information panel

---

apps/prairielearn/src/components/FileBrowser.html.ts
apps/prairielearn/src/lib/instructorFiles.ts
apps/prairielearn/src/tests/fileEditor.test.ts

Fixes #11579. Shows all hidden files in the file browser.
Given the potential for issues if a user accesses files in the .git directory, this directory is also changed to become invalid, using the same mechanism that blocks direct access to e.g., question files from course admin. The directory is still visible, but no link it provided and access to it becomes blocked (it was previously allowed if the URL were typed with its name). An alternative would be to hide it altogether, which I'm happy to do if requested.
The test change has been tested in master, and it fails there, but succeeds in this branch.

Show hidden files in file browser

---

apps/prairielearn/src/pages/instructorIssues/instructorIssues.html.ts
apps/prairielearn/src/pages/instructorIssues/instructorIssues.sql
apps/prairielearn/src/pages/instructorIssues/instructorIssues.ts

Previously, searching for a QID in issues added implicit wildcards, e.g. searching for `foo` would match any question with `foo` in the QID. This caused problems if one QID was a substring of another. For instance, searching for `qid:graph` would show issues for `qid:graph-search` as well.
Now, it defaults to an exact match, with `*` supported as a wildcard character. This allows exact match to be the default, while still supporting wildcards when needed.
I removed `LIKE` matching for issues; searching for `user:foo@example.com` is now an exact match on the user UID. I couldn't see a good reason to either have substring matching be the default behavior, or to support wildcard matching at all.

Add explicit wildcard to issues QID search

---

apps/prairielearn/elements/pl-drawing/pl-drawing.js
apps/prairielearn/src/components/CourseRequestsTable.html.ts
apps/prairielearn/src/lib/github.ts
apps/prairielearn/src/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.ts
packages/sanitize/src/index.test.ts
packages/sanitize/src/index.ts

@jonatanschroeder called out in https://github.com/PrairieLearn/PrairieLearn/pull/11541#discussion_r1999095447 that I had used `String.prototype.replace` when I should have used `String.prototype.replaceAll`. I decided to check the rest of the codebase and found a few more places where I believe we were using the wrong one.

Use replaceAll instead of replace where appropriate

---

apps/prairielearn/src/components/SideNav.html.ts
apps/prairielearn/src/middlewares/authzCourseOrInstance.ts

Related to https://github.com/PrairieLearn/PrairieLearn/discussions/11550#discussioncomment-12480352.
Currently, when enhanced navigation is enabled, if a user is on a course page, they must navigate to the course instances page to select a course instance. They cannot do so directly through the side nav. 
This PR enables users to navigate to course instances directly from the side nav on course pages:
If a course has no course instances, the course instances switcher is hidden:

Side nav course instance switching from course pages

---

apps/prairielearn/src/models/course-instance-usages.sql
packages/workspace-utils/src/index.sql

This was the same bug that was fixed in https://github.com/PrairieLearn/PrairieLearn/pull/11437 for the backfill queries. Copy-paste meant that the bug was also in the real-time usage queries.
I'll follow up shortly with new backfill queries.

Fix course instance usage queries

---

apps/prairielearn/elements/pl-string-input/pl-string-input.mustache

This PR addresses a problem related to the recent changes in #11489. That PR displayed a message for an invalid string. However, we have had problems with using a standardized message if there are any parsing errors and displaying this rather than custom feedback. This PR simply removes that messaging so users are more likely to click "More info..." for help.
Here is a screenshot before the change:
And here is the updated version with the messaging removed:

Remove invalid string message

---

workspaces/jupyterlab-python/Dockerfile
workspaces/jupyterlab-python/pl-gosu-helper.sh

Jupyter changed their base image entrypoint formulation in a way that broke our assumptions. This caused the local behavior to break where we start as 0:0 and step down to 1001:1001 dynamically. With this fix, things behave as they did before.

fix Jupyter workspace entrypoint to reflect base image changes

---

apps/prairielearn/src/ee/lib/selectAndAuthz.ts

Related to https://github.com/PrairieLearn/PrairieLearn/pull/11583#discussion_r2001781822. 
When a global admin has admin access turned off but is explicitly listed as an institution admin independent of global admin access, they cannot access institution admin pages:
However, "turn on admin access" should only control global admin access, so institution admin pages should still be accessible in this case. 
This PR ensures that global admins with admin access turned off that are explicitly listed as institution admins have access to institution admin pages.

Institution admin page access for global admins with admin access disabled

---

apps/prairielearn/assets/scripts/question.ts
apps/prairielearn/src/components/Modal.html.ts
apps/prairielearn/src/components/QuestionContainer.html.ts

@echuber2 reported on Slack that when he went to copy a question from the public question preview page, the question was copied to the first course that was selected by default, not the one he changed it to.
This was caused by the changes I made to the `Modal` component in #11522. Because `<form>` now wraps the modal instead of being a child of it, the selector used here didn't work anymore. This PR updates the `Modal` component to allow adding a class to the `<form>`, which should be more robust than relying on element nesting.

Fix copying question from public preview page

---

apps/prairielearn/src/api/v1/endpoints/queries.sql

Closes #11547. This PR exposes the zone number and title on the instance question API endpoint.

Expose zone number and title in instance questions API

---

apps/prairielearn/src/lib/grading.ts
apps/prairielearn/src/question-servers/freeform.js

Closes #10770.
The reason this worked most of the time is because we typically got lucky and chunks were already present on servers by the time exams auto-closed. It's likely that things really only got bad for either tiny courses (where normal question HTTP requests wouldn't have reached _every_ server via the load balancer) or after deploys. We never would have seen issues from this during synchronous grading because `parse()` would have been run on the same machine before grading occurred, and `parse()` was always correctly loading all chunks.

Load question chunks when externally grading a variant after auto-close

---

apps/prairielearn/src/api/v1/endpoints/queries.sql

Adds the question tags to the output of courseInstanceSubmissions as per https://github.com/PrairieLearn/PrairieLearn/issues/1960#issuecomment-573070722
Given the associated issue of the above comment is quite old and links to another issue, this change may be preferred to be made in another way or in a different location.
Closes #1960.

Add tags to submissions API endpoint

---

apps/prairielearn/src/batched-migrations/20250318174636_course_instance_usages__submissions__backfill_v3.sql
apps/prairielearn/src/batched-migrations/20250318174636_course_instance_usages__submissions__backfill_v3.ts
apps/prairielearn/src/batched-migrations/20250318175247_course_instance_usages__external_grading_jobs__backfill_v3.sql
apps/prairielearn/src/batched-migrations/20250318175247_course_instance_usages__external_grading_jobs__backfill_v3.ts
apps/prairielearn/src/batched-migrations/20250318180548_course_instance_usages__workspaces__backfill_v3.sql
apps/prairielearn/src/batched-migrations/20250318180548_course_instance_usages__workspaces__backfill_v3.ts
apps/prairielearn/src/migrations/20250318174636_course_instance_usages__submissions__backfill_v3.ts
apps/prairielearn/src/migrations/20250318175247_course_instance_usages__external_grading_jobs__backfill_v3.ts
apps/prairielearn/src/migrations/20250318180548_course_instance_usages__workspaces__backfill_v3.ts

This PR backfills usage data that was incorrectly generated due to the bug in #11590. These backfills are identical to those in #11366/#11437, #11377, and #11378.

Backfill usage data v3

---

apps/prairielearn/src/components/InstructorInfoPanel.html.ts

This panel is used both in the sharing course and in any consuming course. When a question is previewed in the context of a consuming course, we must use the course ID of the question, not the course that's currently being viewed.

Fix public preview URL for shared question

---

.changeset/neat-experts-look.md
packages/flash/src/index.test.ts
packages/flash/src/index.ts

We recently discovered a memory leak that's very similar to the one that we fixed in https://github.com/PrairieLearn/PrairieLearn/pull/7092. In short: if a Docker code caller times out, the code caller pool will create a new one. This technically occurs in the context of the current request. Creating a new code caller creates a new `Socket` to talk to it, and Node's async-context-tracking system will keep a reference to any active `AsyncLocalStorage` instances for that new socket. The flash middleware uses `AsyncLocalStorage`, and indirectly retains a reference to the request object. That, in turn, references the response object, which includes `res.locals`, which can get very big (ironically, it's extra-likely to be big when a code caller times out since we're more likely dealing with …

Fix memory leak caused by flash middleware

---

apps/prairielearn/src/sync/course-db.ts
apps/prairielearn/src/tests/sync/assessmentsSync.test.ts

Updates the sync error for missing questions to include quotes to make whitespaces more obvious. Also updated test to match.
Closes #2933

Add quotes to QIDs in sync errors to highlight whitespace

---

docs/workspaces/index.md

This list won't be different from PrairieLearn as a whole; it's not clear why this was added to the workspace docs specifically.
I don't think we need to call out that Edge Legacy is untested, either here or anywhere. It hasn't seen a release in 4 years and per [caniuse.com](https://caniuse.com/usage-table), its usage is 0.09%.

Remove supported browsers list from workspace docs

---

.github/ISSUE_TEMPLATE/1-bug.yml
.github/ISSUE_TEMPLATE/2-enhancement.yml

I'm hoping this can help categorize issues as either bug or enhancement when instructors report them.
I am very aware and also dislike those verbose "Bug report" templates. All this template does is set the type field for triaging, and should otherwise look identical to the "Blank Issue" template.
My thinking is that this forces reporters to decide if they are reporting a bug, or requesting a feature, or neither so that we can prioritize. I think without this click, the odds that someone sets the type is low, which puts more burden on the maintainers.

Add issue templates that set the issue type

---

apps/prairielearn/package.json
yarn.lock

Resolves dependabot alert on an indirect dependency.

Bump @pyroscope/nodejs to 0.4.5

---

apps/prairielearn/src/lib/grading.ts

Workspace files can be very large; double storing them in both `submitted_answers` and `raw_submitted_answers` is wasteful and should be unnecessary. There's a very small chance that this impacts course code, but I think that's unlikely. I grepped for `raw_submitted_answers.*files` in all courses and there weren't any hits. If this breaks any questions, there's a simple fix: just use `sumbitted_answers` instead.

Don't store workspace files in raw_submitted_answer

---

apps/grader-host/package.json
apps/prairielearn/package.json
apps/workspace-host/package.json
yarn.lock

Resolves a dependabot alert on an indirect dependency.

Bump dockerode to 4.0.5

---

apps/prairielearn/src/ee/pages/administratorInstitutionGeneral/administratorInstitutionGeneral.ts
apps/prairielearn/src/lib/timezones.ts
apps/prairielearn/src/pages/administratorInstitutions/administratorInstitutions.ts
apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ts
apps/prairielearn/src/schemas/schemas/infoCourse.json
apps/prairielearn/src/schemas/schemas/infoCourseInstance.json

The institution/course/course instance timezone is used in different parts of the code, sometimes in conversions done via sprocs/queries (i.e., using Postgres), sometimes via the formatter package (i.e., using JS Intl). Postgres supports some timezones that are not supported by Intl. If a user selects one of these timezones, this can cause an issue in pages that use the formatter package (which will gradually be used more often, so this may happen more often for these timezones).
This PR changes the lib function that populates dropdowns for timezones to filter only those timezones supported by both Postgres and Intl.
AFAIK there is no restriction in sync currently that checks if the timezone is valid, and this PR does not attempt to add this restriction in sync. So this PR attempts to …

List only canonical timezones in timezone dropdowns

---

apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.css
apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js

Fixes #11653. Increases the Z index of the tooltip, and ensures it is always contained within the question container.
Before:
After:

UI tweaks to the formula tooltip in rich text editor

---

apps/prairielearn/src/pages/workspace/workspace.ts

This was a regression from #11630. Turns out that `question_qid` wasn't quite as unused as we thought it was!
Using `question.qid` will be safe because we'll have run `selectAndAuthzInstructorQuestion` by this point:
https://github.com/PrairieLearn/PrairieLearn/blob/984dc62b2bd67868670cd71f8683af3d6c2c40f9/apps/prairielearn/src/middlewares/authzWorkspace.ts#L80

Fix question link on instructor question preview workspaces

---

docs/PrairieDraw.md
docs/docker.md
docs/faq.md
docs/installing.md
docs/workspaces/index.md

Most people won't care about this; this explanation just gets in the way of the command they're looking for. This PR hides it in a collapsible section.

Hide explanation of local external grader and workspace setup

---

apps/prairielearn/python/zygote.py

This error was reported by Scott Spurlock on Slack. For posterity, here's the full error message:
```
Traceback (most recent call last):
File "/PrairieLearn/apps/prairielearn/python/zygote.py", line 429, in <module>
worker_loop()
File "/PrairieLearn/apps/prairielearn/python/zygote.py", line 337, in worker_loop
val = method(*args)
File "/course/questions/hw01/code_category_count_bar_plot/server.py", line 147, in file
plt.gcf().tight_layout(pad=2)
File "/usr/local/lib/python3.10/site-packages/matplotlib/figure.py", line 3640, in tight_layout
engine.execute(self)
File "/usr/local/lib/python3.10/site-packages/matplotlib/layout_engine.py", line 183, in execute
kwargs = get_tight_layout_figure(
File "/usr/local/lib/python3.10/site-packages/matplotlib/_tight_layout.py", line 266, in …
```

Fix rendering of LaTeX by matplotlib

---

apps/prairielearn/assets/scripts/tsconfig.json
apps/prairielearn/package.json
yarn.lock

I couldn't immediately identify any problems in [the changelog](https://github.com/js-temporal/temporal-polyfill/blob/main/CHANGELOG.md), and TypeScript didn't complain about anything, so I think we're good.

Upgrade Temporal API polyfill

---

.github/workflows/main.yml
workspaces/jupyterlab-python/install.sh

We heard from an instructor recently that the presence of this link caused them to worry that students could access any workspace if they knew the link. They tested this with a colleague (who was on course staff) and it "worked". This is of course by design: anyone with staff permissions can access any other staff workspace in the course. Nevertheless, this worried them a lot. Hiding the link doesn't change our (already safe) behavior, but it should hopefully help avoid additional confusion in the future.
"Copy shareable link" on the context menu for files:
Share button in the upper-right:

Disable shareable link copying in JupyterLab workspace

---

apps/prairielearn/src/middlewares/workspaceProxy.ts

This was a regression introduced by #11664. `pathRewrite` got a path without the `/pl/workspace/...` prefix, which broke workspaces like Jupyterlab that depended on that. I tested the changes in this PR with both the VSCode and Jupyterlab workspaces (the first uses rewriting, the second does not) and things are working well now.

Fix workspace proxy path rewriting

---

apps/prairielearn/src/lib/assets.ts

Resolves #11708. This simplifies the development of PL packages used client-side, but ensuring that their assets are never cached by the browser. We still need to `yarn build` the package before its change is seen in the browser, though.
There are currently no cases that I could find where this is used directly, since all PL packages used client-side are used indirectly, via imports in asset scripts. The main potential use case for this is in packages used in elements. The only current element using a PL package is pl-excalibur, and it uses a package outside the monorepo, so testing it becomes a bit tricky. The easiest way to test this code is to merge it with #10570, which uses a custom package in this manner. To test it in that PR, load a page using this package (e.g., …

Skip cachebuster process for prairielearn packages in local dev

---

docker-compose-production.yml
docker-compose.yml

Network config is missing in current docker compose file for development.  Consequently, one cannot launch workspace.
Ref: https://github.com/PrairieLearn/PrairieLearn/issues/9805

Add network config to Docker compose file

---

workspaces/jupyterlab-python/install.sh
workspaces/jupyterlab-python/requirements.txt

This is a fix for the issue described here: https://github.com/jupyterlab/jupyter-collaboration/issues/462
For posterity: `prairielearn/workspace-jupyterlab-python:90d9e5bef1c0950457a60a78d224f99e32339cee` and on were broken, whereas `prairielearn/workspace-jupyterlab-python:5cd46e341504107d342b6f95ad33515b8fee0b50` (built just a few days before that) worked fine. Neither the base image tag nor any dependencies were changed between those builds, so we really don't know what caused this to start happening.

Install jupyter-collaboration with conda in JupyterLab workspace

---

apps/prairielearn/package.json
apps/prairielearn/src/middlewares/workspaceProxy.ts
apps/prairielearn/src/server.ts
yarn.lock

Now that the changes from https://github.com/chimurai/http-proxy-middleware/pull/823 have been released, we can upgrade to that latest version and simplify our error handling.

Upgrade http-proxy-middleware

---

docs/java-grader/index.md

The [`-source` option is not enough](https://stackoverflow.com/questions/43102787/what-is-the-release-flag-in-the-java-9-compiler/43103038#43103038), as it restricts language features but not library availability. For example, `str.isBlank()` is not available in Java 8, but since the Java 21 library is available in the boot classpath, it would still be available if compiled with `-source 8`. The `--release` option also sets the library version accordingly.

Update recommendation for version compatibility in Java grader

---

workspaces/jupyterlab-python/Dockerfile
workspaces/jupyterlab-python/install.sh
workspaces/jupyterlab-python/requirements.txt

Now that the dependency has been fixed and `jupyter/minimal-notebook` uses `jupyterlab==4.4.0`, we should be able to undo the hacky fix from #11726.

Upgrade workspace-jupyterlab-python base image and collaboration dep

---

.github/workflows/upgrade-containers.yml

See discussion in https://github.com/PrairieLearn/PrairieLearn/pull/11732. In short: the action that creates the PR will use `github.actor` as the author, and because we use a merge queue, the actor will always be `github-merge-queue`.

Hardcode committer and author in container upgrade workflow

---

.github/workflows/main.yml

This makes the timeout consistent with the other place we run them:
https://github.com/PrairieLearn/PrairieLearn/blob/bc7bfc2f7ccd3fedba1169889a0621baaf94b631/.github/workflows/main.yml#L204-L206
I think this mismatch was just an oversight in #11393.

Fix timeout of Python tests

---

apps/prairielearn/src/lib/navPageTabs.ts

I saw a note about this on slack recently, I figured now is a good time to fix since sharing still isn't enabled by default anyway.

Put sharing tab in alphabetical order

---

apps/prairielearn/assets/scripts/lib/jobSequenceResults.ts
apps/prairielearn/src/components/JobSequenceResults.html.ts
apps/prairielearn/src/components/SyncErrorsAndWarnings.html.ts
apps/prairielearn/src/components/SyncProblemButton.html.ts
apps/prairielearn/src/lib/chalk.ts
apps/prairielearn/src/lib/server-jobs.ts
apps/prairielearn/src/pages/instructorFileEditor/instructorFileEditor.html.ts

Resolves #11613.
Adds a checkbox to the job sequence page that hides/shows verbose messages in the output. Verbose messages are determined by the use of `chalk.dim` based output. Hiding is done with the use of a custom CSS variable that is updated based on the checked status of the checkbox, and is used in the style for "faint" output.
To ensure consistency of formats, all references to AnsiUp have been moved to a library function, so that the same format is used in all cases (e.g., sync errors/warnings). This should also allow future changes to the style of individual message types to be consistent across pages (e.g., if we decide to use a different color/style for different errors/warnings). The checkbox was not added to other pages (though I should note that sync errors/warnings don't …

Add option to hide verbose messages in job outputs

---

apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.tsx

Fixes #11755. The process that changed the default behavior for deleting assessment instances (both individual and batch) assumed that the form was inside the modal, but recent changes moved that form to contain the modal instead.

Fix handling of delete assessment instance modals

---

apps/prairielearn/src/components/PageLayout.html.ts

This previously rendered as something like `hx-ext=&#34;loading-states&#34;`, which isn't valid. The change here mirrors how the attribute is set when enhanced navigation isn't enabled.

Fix hx-ext attribute on body

---

apps/prairielearn/elements/pl-file-preview/pl-file-preview.js
apps/prairielearn/elements/pl-file-preview/pl-file-preview.mustache
apps/prairielearn/elements/pl-file-upload/pl-file-upload.js
exampleCourse/questions/demo/fileDownloadUpload/question.html

This PR takes the place of #11138. It uses the suggestions from Jonatan: if a preview is not available after uploading, the preview remains collapsed by default, and instead of a red error message, a more neutral blue "info" alert is used instead.

Improve message when file cannot be previewed

---

apps/prairielearn/src/lib/features/index.ts
apps/prairielearn/src/sync/fromDisk/assessments.ts

From discussions with @nwalters512 and @mfsilva22, it would be nice if any course could consume public questions, without them necessarily needing to have sharing enabled for their course. This will allow us to enable consuming public question for everyone right away.
Currently, anyone can view publicly shared questions, but they will get an error if they actually try to import them, which is a bit odd. This will solve that problem as well.
Letting people consume questions by sharing set is a bit messier, because they need access to the Sharing settings page to do that. So, we can just launch that the same time we make all the sharing features public access.

Add feature to enable public question consuming only

---

apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.py

#10256 introduced a backward compatibility bug: pl-order-blocks variants that were created with the old version of the element could not be graded with the new version of the element due to the missing 'ordering_feedback' key in part of the `data` object. 
This fixes the problem. I also made the same change for the 'distractor_feedback' property, for consistency and because it should have been done that way in the first place as well.

pl-order-blocks: ordering-feedback backward compatibility fix

---

apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js
apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.mustache

We were previously abusing the list-group-item styles for color, but that doesn't work anymore with new bootstrap. Thankfully they have styles for background color now, easy drop in fix.

update pl-order-blocks for bootstrap 5.3

---

.github/dependabot.yml

As of #11772, we're once again running on the latest version of Bootstrap!

Unignore Bootstrap in Dependabot config

---

apps/prairielearn/public/stylesheets/local.css

This change improves accessibility for folks who are navigating PL with a keyboard.

Improve indication of active item in tom-select dropdowns

---

.github/workflows/main.yml
scripts/copy_docker_coverage_reports.sh

We were already running the Python tests in the (faster) `native-checks` job, we might as well use the coverage reports generated there. This should shave about a minute off the `test-prairielearn` job in the best case.

Use coverage report from native execution of Python tests

---

docs/elements.md
docs/python-grader/index.md
exampleCourse/questions/demo/annotated/MarkovChainGroupActivity/MarkovChains-Gambler/question.html
exampleCourse/questions/demo/annotated/MarkovChainGroupActivity/MarkovChains-Intro/question.html
exampleCourse/questions/demo/annotated/MarkovChainGroupActivity/MarkovChains-PageRank/question.html
exampleCourse/questions/demo/annotated/engMarkovBrewing/server.py
exampleCourse/questions/demo/autograder/codeEditor/question.html
exampleCourse/questions/demo/autograder/codeUpload/question.html
exampleCourse/questions/demo/autograder/python/leadingTrailing/server.py
exampleCourse/questions/demo/autograder/python/orderBlocksAddNumpy/server.py
exampleCourse/questions/demo/autograder/python/orderBlocksRandomParams/server.py
exampleCourse/questions/demo/autograder/python/pandas/question.html
exampleCourse/questions/demo/autograder/python/plots/question.html
exampleCourse/questions/demo/autograder/python/random/question.html
exampleCourse/questions/demo/autograder/python/randomFunctionName/server.py
exampleCourse/questions/demo/workspace/jupyterlab/question.html
exampleCourse/questions/demo/workspace/vscode-python/question.html

As of https://github.com/PrairieLearn/PrairieLearn/pull/11808, `names_for_user` is now optional. This updates our example questions to reflect that.
I also reworked the documentation around this to reflect the fact that `names_for_user` is optional, and the fact that `<pl-external-grader-variables>` can actually be used to set `names_for_user` and `names_from_user`.
Closes #11689.

Remove empty names_for_user values from Python grader examples

---

exampleCourse/questions/demo/annotated/engMarkovBrewing/question.html
exampleCourse/questions/demo/annotated/engMarkovBrewing/server.py

Removes an instance of names_for_user being set in Python files and moves this to using the external grader variables element. Follow-up to https://github.com/PrairieLearn/PrairieLearn/pull/11812. Other questions mentioned in https://github.com/PrairieLearn/PrairieLearn/pull/11812#issuecomment-2816333580 do not use this element or include additional logic so that setting the names within the element isn't really worth it.
Haven't tested this yet.

Remove setting of names_for_user

---

graders/python/python_autograder/code_feedback.py

This was a regression introduced in https://github.com/PrairieLearn/PrairieLearn/pull/9436. When using `check_numpy_array_allclose(...)`, the "looks good" feedback is printed twice:
To fix this, we just tell `check_numpy_array_features(...)` not to print anything in case of success.

Fix duplicate feedback with check_numpy_array_allclose

---

Makefile

Applies the same changes done for build-docs to also apply to preview-docs, i.e., install requirements and run mkdocs from venv.

Fix preview feature for docs in local dev

---

.github/workflows/main.yml

Not sure if this is worth doing, but this should save about half the docker rebuild time.

Use cache for image builds in test pipeline

---

apps/prairielearn/src/question-servers/freeform.js
apps/prairielearn/src/question-servers/types.ts

I pulled this out of #11053. My goal here was to add just enough types for force the type checker to recognize the need for nullish coalescing with defaults in the `data` object declarations.

Add more JSDoc typing to freeform code

---

apps/prairielearn/src/question-servers/calculation-subprocess.js
apps/prairielearn/src/question-servers/freeform.js
apps/prairielearn/src/question-servers/types.ts

Lifting this out of #11053.
Our validation on data coming back from workers only ensures that `partial_scores` is an object. It doesn't say anything about what type the object's values have. To improve the safety here, we're now representing `partial_scores` (and all other `data` dictionaries) as `Record<string, unknown>` to force ourselves to validate the values we're reading from it.

Refactor partial scores calculations in v3 questions

---

packages/preact-cjs-compat/README.md
packages/preact-cjs-compat/package.json
packages/preact-cjs-compat/src/index.ts
packages/preact-cjs-compat/src/jsx-dev-runtime.ts
packages/preact-cjs-compat/src/jsx-runtime.ts
packages/preact-cjs-compat/tsconfig.json
packages/preact-cjs/README.md
packages/preact-cjs/package.json
packages/preact-cjs/src/compat.ts
packages/preact-cjs/src/hooks.ts
packages/preact-cjs/src/index.ts
packages/preact-cjs/src/jsx-dev-runtime.ts
packages/preact-cjs/src/jsx-runtime.ts
packages/preact-cjs/tsconfig.json
yarn.lock

Preact dual-publishes CJS and ESM code, but they're unable or unwilling to fix the resulting bugs when Preact is used in a mixed ESM/CJS codebase: https://github.com/preactjs/preact/issues/4648
To work around this, we wrap `preact` and `@preact/compat` in our own packages, `@prairielearn/preact-cjs` and `@prairielearn/preact-cjs-compat`. These re-export _only_ the CJS versions of the Preact code.
I'm lifting this out of #10944 as these changes are easy to merge independently. Note that the packages are not yet used, nor are the necessary `overrides` in `package.json` set up yet. I'll introduce those in a future PR when we actually start using Preact to render UI.

Add CJS Preact packages

---

apps/prairielearn/src/admin_queries/course_instances_usage.json
apps/prairielearn/src/admin_queries/course_instances_usage.sql

This adds the ratio of in-term to total activity for course instance usages. It also adds cutoffs for the minimum such ratio (default: 0.5) and the minimum number of students (default: 5) for a course instance to count as "active" in the current term. The minimum number of students is hard to tune perfectly. With 5 we get zero false positives, but we do get a couple of false negatives (tested on UIUC Fa24).

Add in-term ratios for course instance usages

---

apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.py
apps/prairielearn/python/prairielearn/internal/check_data.py
apps/prairielearn/python/prairielearn/question_utils.py
apps/prairielearn/python/test/conftest.py
apps/prairielearn/python/test/misc_test.py
apps/prairielearn/src/question-servers/freeform.ts
apps/prairielearn/src/question-servers/types.ts

Closes #11558. Part of #11559.
This PR adds a new `ai_grading` key to the `data` object received by questions and elements during rendering. Its value is `True` when the question is being rendered for AI grading, either because it's actually being rendered or because the instructor is previewing how it'll look (see #11582).
As a test that this actually works, I updated `<pl-rich-text-editor>` to have specialized rendering for AI grading. Previously, it would render a script and a base64-encoded hidden input, neither of which mean anything to the AI. Now, it renders like this (taken from `element/richTextEditor` in the example course):
```html
<div data-file-name="meaning.html">
<p><span>$1+1=2$</span></p>
</div>
<div data-file-name="woodchuck.html">If a woodchuck could chuck wood,</div> …
```

Specialized rendering of pl-rich-text-editor for AI grading

---

.changeset/clean-planets-know.md
apps/prairielearn/src/server.ts
packages/node-metrics/src/index.ts

Previously the `node-metrics` CloudWatch logger was hardcoding `Namespace: 'PrairieLearn'`. This PR adds a `namespace` option so that we can use `node-metrics` in non-PL projects.
See https://github.com/PrairieLearnInc/PrairieTest/pull/2249#discussion_r2067730520 for the issue that triggered this PR.

Add required `namespace` option to `node-metrics`

---

apps/prairielearn/src/ee/lib/lti13.test.ts
apps/prairielearn/src/tests/lti13.test.ts

Since these are utility functions and pretty easily tested in isolation, we can put their tests next to the implementation and save the `tests/` directory for integration tests.
I rewrote them to use `withServer(...)` from `@prairielearn/express-test-utils` while I was at it.

Move fetchRetry tests adjacent to implementation

---

workspaces/vscode-python/Dockerfile

This started failing in recent builds:
```
The following arguments were not expected: bash init
Run with --help for more information.
```
I can't find any indication at all that this changed in Mamba's changelog 🤷 I did indeed run `mamba --help` and ended up with the change here, which does seem to work.

Fix mamba shell init in Python VSCode workspace

---

apps/prairielearn/src/pages/home/home.sql

As discussed on Slack
<details>
<summary>Slack Quotes</summary>
Zac:
> Given that a course instance could be created for the future with no access role, is it worth changing Older instances to be Inactive instances or is it just expected that future instances should have an access role with dates from the future and then would not be filtered under the older criteria?
Jonatan:
>only the end date is considered in this filtering, so a future course instance will not be "older" even if it's not yet active.
Nathan:
> What if we just don't put something in "older instances" if it doesn't have any access rules at all?
> untested, but it might be as simple as changing the coalesced value here to FALSE
</details>
Makes it so that course instances without an access role still show up as opposed to …

Tweak filtering for 'Older instances'

---

graders/python/python_autograder/pl_execute.py

This makes three improvements to tracebacks in the Python grader:
- We avoid adding extra newlines if `leading_code` and/or `trailing_code` aren't present. This keeps the line numbers more faithful in the case where `leading_code` isn't specified.
- This PR doesn't do anything to fix line numbers in situations where `leading_code` _is_ present. That's possible in theory, but is a lot of work for only marginal gain.
- We now use `compile(...)` before `exec(...)` to associate filenames with the executed code (see https://github.com/PrairieLearn/PrairieLearn/pull/1409).
- We now manually populate the `linecache` so that `traceback` can show the lines of code involved in the stack trace.
This is in response to a report from the student that line numbers in tracebacks were always off by one. …

Improve tracebacks in the Python grader

---

docs/faq.md

Closes #11888.
For easier review: https://prairielearn--11896.org.readthedocs.build/en/11896/faq/#when-uploading-grades-via-csv-the-upload-process-cannot-match-some-group-names-why

Add FAQ for grade uploads with zero-leading group names

---

apps/prairielearn/assets/scripts/workspaceClient.ts

In the wild, we witnessed the following sequence of events:
```
change:state (state=stopped)
joinWorkspace (state=uninitialized)
change:state (state=launching)
```
Our previous code didn't handle this well.
This is in some sense a continuation of #11504. Funnily enough, in https://github.com/PrairieLearn/PrairieLearn/pull/11504#discussion_r1981821478 we wondered about changing the conditional but decided that they were equivalent. As it turns out, they were not 🙂

Fix handling of unexpected workspace transitions

---

apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js
apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.mustache
apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.py

Fixes #11904. Mustache escape does not consider single quotes (apostrophe) as needing escaping. This PR changes the setting of quill options to be handled using JSON in a data attribute, which takes care of any necessary escaping.

Improve handling of escaped characters in rich text editor options

---

apps/prairielearn/src/components/Navbar.html.ts

This came out of discussion with UMich, who were concerned that it wasn't easy for students to discover the accessibility documentation. Adding it as a hidden link that becomes visible on keyboard focus seems like a good, unobtrusive way to make this link readily available.

Add hidden link to accessibility guide

---

apps/prairielearn/src/tests/issues.test.ts
apps/prairielearn/src/tests/newsItems.test.ts

We've seen several cases recently of CI failing due to timeout in these two tests. I'm not sure why they are failing so frequently (maybe slower hardware), but rerunning the test often causes it to pass, so the issue is volatile. This PR attempts to increase the timeout so that these errors happen less often.

Increase timeout for tests that take longer to run

---

apps/workspace-host/src/interface.ts

The workspace host code relies on the workspace job directory existing before the container is created, however it also tries to create the directory after checking for access. This latter process is unnecessary, as the code would have already thrown an exception if the directory did not exist. In other words: if the directory exists, it doesn't need to be created; if it doesn't, the previous call to `fs.access` would have caused an exception.
This seems to be a remnant from #6983, where the directory had to be created if the file content was stored in S3 format, which is no longer supported (in that case the directory would contain a local version of the data, if I understand the code correctly).
With that in mind: the use of `fs.access` before other file system operations is usually not …

Remove unnecessary workspace directory creation

---

apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.html.ts

Without this, element scripts and styles weren't being included, which resulted in elements that required them rendering and behaving strangely.

Include element assets on AI question generation preview

---

docs/accessControl/index.md

cc: @eliotwrobson 
Adding missing s.
Before: "Two level of access control for assessments"
After: "Two levels of access control for assessments"

Fixing Typo in Docs

---

Makefile
apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js
apps/prairielearn/elements/pl-drawing/mechanicsObjects.js
apps/prairielearn/elements/pl-drawing/pl-drawing.js
apps/prairielearn/elements/pl-excalidraw/pl-excalidraw.js
apps/prairielearn/elements/pl-file-editor/pl-file-editor.js
apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js
apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js
contrib/dump-anonymize.mjs
eslint.config.mjs

Previously, this was only enabled for TypeScript files; IMO, we want this rule enabled for all files.
The rule was also using the default of `destructuring: 'any'`, and also IMO, that was too restrictive.

Enable ESLint prefer-const rule for all files

---

apps/prairielearn/src/pages/instructorAssessments/instructorAssessments.sql
apps/prairielearn/src/pages/instructorAssessments/instructorAssessments.ts

These calls were needed back when access rules could be used to restrict TA access to certain assessments.
Now, everyone who can see the instructor assessments page at all should be able to see all the assessments that are on it.

Remove unneeded auth calls on Instructor Assessment Page

---

apps/prairielearn/src/ee/lib/validateHTML.test.ts
apps/prairielearn/src/ee/lib/validateHTML.ts
eslint.config.mjs

Rather than mucking around with regular expressions, it's more reliable to to use Mustache's built-in parser. It produces an AST that we can traverse and gather information from.

Refactor Mustache template extraction for AI question generation

---

apps/prairielearn/src/components/Navbar.html.ts
apps/prairielearn/src/components/SubmissionPanel.html.ts
apps/prairielearn/src/ee/pages/instructorInstanceAdminLti13/instructorInstanceAdminLti13.html.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessment/assessment.html.ts
apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/gradingPanel.html.ts

This PR replaces some uses of visually hidden text inside buttons, intended to be used for screen readers and accessibility tools, with `aria-label` properties. It also replaces a hidden label for an input box.

Replace hidden text with aria labels in buttons

---

.coderabbit.yaml

See https://github.com/PrairieLearn/PrairieLearn/pull/11943#discussion_r2087767974 and similar comments in that PR. We use ESLint; we don't need input from Biome.

Disable Biome in CodeRabbit config

---

apps/prairielearn/src/ee/auth/lti13/lti13Auth.ts
apps/prairielearn/src/ee/lib/lti13.ts

Ahead of LTI 1.3 placements in assignment selection, we needed to support a new LTI 1.3 message type. This PR changes the `LTI13ClaimSchema` to a `discriminatedUnion()` that combines a base LTI claim with specific objects for types `LtiResourceLinkRequest` and `LtiDeepLinkingRequest`.
~~Discriminated unions do not have `passthrough()` function so that was moved from `parse()` to their schema definitions.~~ `passthrough()` was removed in this PR so we `strip()` claims not validated.

LTI 1.3 schema extended to support deep linking

---

docs/question/accessibility.md

#11922 added some accessibility suggestions for instructors and question developers, including the suggestion to use screen readers to test a question. However, the provided list did not include links to these tools, which adds an extra burden on instructors searching for these tools (Googling NVDA returns the stock info for NVidia, and JAWS is a movie name). This PR adds links to the tools' official pages, as well as an indication of the OS associated to each tool. For completeness, it also adds a Linux tool.

Add links to screen reader suggestions in docs

---

apps/prairielearn/python/zygote.py

If the prairielearn server crashes during startup, but after creating the zygote child processes, some zombie zygote process can be left behind. Examining them with strace showed they were stuck in a loop repeatedly reading the empty string. This should solve the problem.

Prevent zombie zygote processes

---

apps/prairielearn/src/lib/grading.sql
apps/prairielearn/src/lib/manualGrading.sql
apps/prairielearn/src/lib/question-variant.sql
apps/prairielearn/src/lib/submissions-upload.sql
apps/prairielearn/src/migrations/20250513234929_variants__modified_at__add.sql
apps/prairielearn/src/migrations/20250513235033_submissions__modified_at__add.sql
apps/prairielearn/src/models/grading-job.sql
apps/prairielearn/src/models/variant.sql
apps/prairielearn/src/sprocs/grading_jobs_update_after_grading.sql
apps/prairielearn/src/sprocs/variants_update_after_grading.sql
database/tables/submissions.pg
database/tables/variants.pg
docs/dev-guide/guide.md
packages/postgres-tools/src/bin/pg-describe.ts

This is the first part of #11974. In future PRs, we'll backfill these columns, add a `NOT NULL` constraint, and then add a default of `NOW()`.
@mwest1066 while working on this change, I wasn't sure exactly when we should update `modified_at`. Should it be literally any time we have an `UPDATE` statement with these tables? That's simple but I wasn't sure exactly how we wanted this value to behave. For now, I just added `TODO` comments to the relevant locations in this PR to help with discussion.

Add modified_at column to variants and submissions tables

---

apps/prairielearn/assets/scripts/lib/mathjax.ts
apps/prairielearn/assets/scripts/question.ts

This is specifically relevant to `apps/prairielearn/src/pages/instructorAssessmentManualGrading/instanceQuestion/instanceQuestion.html.ts`, which loads `lib/mathjax.ts` twice on the same page: once from `apps/prairielearn/assets/scripts/instructorAssessmentManualGradingInstanceQuestion.js`, and once from `apps/prairielearn/assets/scripts/question.ts`. They'd both try to write `window.MathJax`, but only the last one to run before MathJax loaded would win, and thus only that one would ever have `mathjaxPromise` resolve.
The actual issue this caused could be reproduced by making a bunch of submissions to a question that rendered math in its submission panel. When asynchronously loading a submission on the instructor manual grading page, that math wasn't typeset. Now, it is.
While I was here, …

Fix MathJax when it's loaded multiple times on the same page

---

apps/prairielearn/src/lib/code-caller/code-caller-container.ts

We were running out of disk space in production because of these logs 😬

Disable logs in the code caller containers

---

apps/prairielearn/src/sync/course-db.ts
apps/prairielearn/src/tests/helperAttachFiles.ts
apps/prairielearn/src/tests/manualGrading.test.ts
apps/prairielearn/src/tests/sync/assessmentsSync.test.ts
apps/prairielearn/src/tests/sync/courseInstancesSync.test.ts

This was originally brought to our attention by @echuber2. After checking the prod database, it's clear this has impacted many more people (whether or not they realized it).
Relevant queries:
```sql
-- Find all access rules with either whitespace or a comma.
-- This yielded 578 access rules.
SELECT
COUNT(aar.id)
FROM assessment_access_rules aar
WHERE EXISTS (
SELECT 1
FROM unnest(aar.uids) AS uid
WHERE uid ~ '[\s,]'
);
-- Fine all access rules with either whitespace or a comma, AND an @.
-- This yielded 402 access rule.
SELECT
COUNT(aar.id)
FROM assessment_access_rules aar
WHERE EXISTS (
SELECT 1
FROM unnest(aar.uids) AS uid
WHERE uid ~ '[\s,]'
AND uid ~ '@'
);
```
I considered the second case separately because some people seemed to be using UIDs to store comments:
```json
["1.5X …
```

Add basic validation of access rule UIDs

---

apps/prairielearn/elements/pl-matching/pl-matching.mustache
apps/prairielearn/elements/pl-matching/pl-matching.py
exampleCourse/questions/element/matching/question.html

Resolves #11990. Adds a screen reader label to options, so that the screen reader announces the meaning of each option instead of its letter.

Add ARIA label to matching options

---

apps/prairielearn/src/components/CommentPopover.html.ts
apps/prairielearn/src/lib/comments.test.ts
apps/prairielearn/src/lib/comments.ts
apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/pages/instructorAssessmentAccess/instructorAssessmentAccess.html.ts
apps/prairielearn/src/pages/instructorAssessmentAccess/instructorAssessmentAccess.sql
apps/prairielearn/src/pages/instructorInstanceAdminAccess/instructorInstanceAdminAccess.html.ts
apps/prairielearn/src/tests/comments.test.ts

This will allow instructors to see comments on access rules from their JSON files. This uses the newly added JSON comment columns to render the access rules for course instances and assessments in the access rules tables.

Display access rule comments

---

apps/prairielearn/src/ee/lib/lti13.ts
docs/lmsIntegrationInstructor.md

- Adds documentation about Canvas courses being published for grade sending to work.
- Adds in-page troubleshooting to the grade sending page if results appear as though the Canvas page isn't published.
Closes #11292.

LTI 1.3: Document Canvas requirements for grade sync

---

yarn.lock

Resolves a dependabot alert on an indirect dependency.

Bump undici from 6.21.1 to 6.21.3

---

apps/prairielearn/src/models/assessment.sql
apps/prairielearn/src/models/assessment.ts
apps/prairielearn/src/models/course-instances.sql
apps/prairielearn/src/models/course-instances.ts
apps/prairielearn/src/tests/clientFiles.test.ts
apps/prairielearn/src/tests/manualGrading.test.sql
apps/prairielearn/src/tests/manualGrading.test.ts
apps/prairielearn/src/tests/permissions/institutionAdminAccess.test.ts
apps/prairielearn/src/tests/variantAccess.test.ts

#11770 introduced a new `public` course instance to `testCourse`. This broke the assumption in a number of tests that only a single course instance (`Sp15`) would be present in the test course. This PR updates tests that rely on that specific course instance to always query for it explicitly instead of hardcoding `course_instance/1`.
Note that there are still some tests that hardcode `course_instance/1`. Many of them use their own manually-constructed fixture, and others access subroutes that don't care which course instance is in use.

Use specific course instance in tests

---

apps/prairielearn/public/stylesheets/colors.css

I recently read this article: https://webkit.org/blog/16929/contrast-color/. It explains something that I think a lot of us have felt intuitively: even things that technically pass the WCAG 2.1 AA contrast requirements can _appear_ to have insufficient contrast. Long story short, human vision is weird, and the simple algorithm used in WCAG 2 doesn't match how we actually perceive things. WCAG 3 is proposing to use a new contrast algorithm, a calculator for which is available here: https://apcacontrast.com/.
I ran some of our most suspect color combinations and confirmed that yes, swapping the text color does provide more _perceptual_ contrast.
Before:
After:

Improve contrast on custom button/badge colors

---

apps/prairielearn/src/components/QuestionContainer.html.ts
apps/prairielearn/src/pages/instructorIssues/instructorIssues.html.ts

Students will sometimes use line breaks, e.g. in long regrade requests. We were correctly formatting this on the issues list page, but not when rendering issues on specific variants. This PR fixes that by adding `white-space: pre-wrap;` to the relevant containers.
Before:
After:

Consistently render linebreaks in issue student message

---

.github/workflows/main.yml

We recently had two CI failures that traced back to this action:
- https://github.com/PrairieLearn/PrairieLearn/actions/runs/15126128873/job/42518423527
- https://github.com/PrairieLearn/PrairieLearn/actions/runs/15126128873/job/42518423520
This issue is described here: https://github.com/awalsh128/cache-apt-pkgs-action/issues/82. It was closed as fixed, but clearly it's still happening.

Remove apt caching in GitHub Actions

---

apps/prairielearn/src/tests/clientFiles.test.ts

Similar to #12008, just with assessments, not course instances.
The issue here was manifesting as flakey tests, where these would fail when assessment with ID 1 didn't belong to the `Sp15` course instance.

Use consistent assessment in client files tests

---

apps/prairielearn/src/lib/assets.ts
apps/prairielearn/src/tests/helperServer.ts

This yields a small performance increase (~100ms/test) for suites like `src/ee/pages/instructorInstanceAdminBilling/instructorInstanceAdminBilling.test.ts` that repeatedly set up and tear down the testing server.

Skip reinitialization of assets in tests

---

apps/prairielearn/src/sync/fromDisk/courseInstances.ts

https://github.com/PrairieLearn/PrairieLearn/pull/11770 introduced a new `public` course instance to `testCourse` that's been causing us trouble ever since, as many tests hardcode course instance IDs to 1 since until recently, there was indeed only a single course instance.
We'd worked a bit to be explicit about which course instance is being used, see e.g. https://github.com/PrairieLearn/PrairieLearn/pull/12008 and https://github.com/PrairieLearn/PrairieLearn/pull/12017. However, @reteps found a bunch more tests that are still hardcoding the specific instance. I figured that fixing all those tests that used to work just fine was a poor use of our time, and that we could get away with this one little stupid hack to make sure they keep passing 😅

Deterministically order course instances in the test course

---

apps/prairielearn/src/lib/socket-server.ts
apps/prairielearn/src/tests/exam.test.ts
apps/prairielearn/src/tests/homework.test.ts
apps/prairielearn/src/tests/zoneGradingExam.test.ts
apps/prairielearn/src/tests/zoneGradingHomework.test.ts

We recently observed some failed tests in https://github.com/PrairieLearn/PrairieLearn/actions/runs/15173871436/job/42670115274?pr=12012:
```
@prairielearn/prairielearn:test: ⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
@prairielearn/prairielearn:test: 
@prairielearn/prairielearn:test: Vitest caught 2 unhandled errors during the test run.
@prairielearn/prairielearn:test: This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
@prairielearn/prairielearn:test: 
@prairielearn/prairielearn:test: ⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
@prairielearn/prairielearn:test: Error: Connection is closed.
@prairielearn/prairielearn:test:  ❯ close ../../node_modules/ioredis/built/redis/event_handler.js:189:25
@prairielearn/prairielearn:test:  ❯ Socket.<anonymous> …
```

Propertly shut down Socket.io to reduce test flakiness

---

apps/prairielearn/src/sprocs/sync_course_instances.sql

Followup to https://github.com/PrairieLearn/PrairieLearn/pull/12039. Postgres doesn't use a consistent collation by default, so we force it to use `C`.

Use C collation to order course instances during sync

---

.coderabbit.yaml

Having coderabbit add a comment saying "I won't review because (it's draft | base is not master | it's a bot | etc.)" is noise that doesn't actually help.

Disable coderabbit review status comments

---

apps/prairielearn/assets/scripts/lib/saveButtonEnabling.ts

In the AI question generation draft editor, even after a user would type in a revision prompt, the revise question button remained disabled, preventing the user from submitting question revisions. 
This PR resolves that issue:
https://github.com/user-attachments/assets/62e5580c-1c5d-4a93-ac98-e5237749fb1c
The problem was that the question revision input was a `textarea`, but `saveButtonEnabling` checked that text inputs were `input` elements:
https://github.com/PrairieLearn/PrairieLearn/blob/f8f93a5caea6d49d72752062a5d119aa55df05f4/apps/prairielearn/assets/scripts/lib/saveButtonEnabling.ts#L27-L40
This is now fixed.

Permanently disabled revise question button patch

---

apps/prairielearn/src/components/SubmissionPanel.html.ts

Resolves #11883. Hides the UID from the main view of the submission panel. This focuses on reducing grading bias, to allow a grader to make grading decisions that are not affected by the identity of the student.
In order to allow a grader to still see the submitter as necessary, the submission info modal has been modified to include the submitter UID. Since this information was previously only available for graded submissions the modal has also been modified to show useful information for submissions that are not graded (either save-only or ungradable).
This PR has conflicts with #12060. I decided to work on both issues separately to allow more targeted discussion on their merits, but I'm happy to handle any merge conflicts once one of the PRs is merged.
Best reviewed ignoring …

Hide submitter UID in submission panel for manual grading interface

---

.changeset/three-carrots-hide.md
apps/prairielearn/assets/scripts/instructorQuestionSettingsClient.ts
apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts
packages/zod/src/index.test.ts
packages/zod/src/index.ts

#12096 still didn't completely fix the handling of this. After that, it was actually impossible to disable URL rewriting from the GUI settings editor. This was caused by us calling `.optional()` on `BooleanFromCheckboxSchema`, which caused it to treat a missing value as `undefined` instead of `false`.
There are a few changes to help address this in this PR:
- I wrapped the `BooleanFromCheckboxSchema` schema in a TypeScript helper that forbids calling `.optional()`. IMO it makes sense to bake in this behavior.
- I updated the form validation for workspace settings to be simpler: if workspace settings are shown, image/port/home will all be required. This is a change from the old behavior, where they'd only be marked as required if any of the workspace settings inputs had a value. This was …

Fix handling of workspace URL rewrite checkbox

---

apps/prairielearn/assets/scripts/lib/questionsTable.ts

As discussed in https://github.com/PrairieLearn/PrairieLearn/pull/11989#discussion_r2103169901, we want to standardize on this new icon for AI functionality.
I also took the opportunity to standardize on sentence case for these button labels.
Before:
After:

Update icon for AI question generation

---

docs/question/server.md
docs/question/template.md

Following this conversation:
I figured the documentation could be more explicit.

More details on server.py + mustache rendering

---

apps/prairielearn/src/executor.ts

This makes testing the `prairielearn/executor` image easier by actually making it possible to kill the process when running it as follows:
```
docker run --rm -it prairielearn/executor
```

Handle SIGINT and SIGTERM in executor image

---

apps/prairielearn/src/lib/code-caller/code-caller-container.ts

On a recent attempted deploy of revision `2578ecc57a91e8e5b0c7087d48cd5626a6f2360b`, I observed that the code callers were failing to start properly. After some investigation, it appeared that the Node process running inside the executor container wasn't receiving data over stdin. Adding `hijack: true` fixed that locally; I'm going to try to deploy from this branch to see if it works in production environments too. I don't know why this changed anything, and I also don't know why this ever worked in the first place.
See here for more details on connection hijacking: https://docs.docker.com/reference/api/engine/version/v1.45/#tag/Container/operation/ContainerAttach

Fix CodeCallerContainer stdin handling

---

apps/prairielearn/python/prairielearn/html_utils.py
apps/prairielearn/python/test/misc_test.py
docs/devElements.md

As discussed on Slack. Attributes treated by libxml as boolean attributes can cause weird behaviour, such as changing the value during processing. This PR ensures that:
Still testing to ensure this won't break any regular elements.

Docs: warn about the use of boolean attributes

---

workspaces/jupyterlab-python/requirements.txt

Matches the changes in #12151 and #12147, but in the jupyterlab-python workspace, which for some reason dependabot wasn't able to create yet.

Bump requests to 2.32.4 in jupyterlab-python workspace

---

.github/workflows/main.yml

The bug fix for modified timestamps (https://github.com/prettier/prettier/issues/17278) was upstreamed, so this removes the workaround. This can technically be merged ahead of time, for slightly-slower CI builds.
Closes #12064

Undo modified time workaround for prettier

---

apps/prairielearn/assets/scripts/instructorAssessmentManualGradingAssessmentQuestionClient.ts

As suggested in the dev meeting, disagreements between AI and human might not necessarily mean inaccurate AI grading. We are now renaming the `AI accuracy` column to `AI agreement` to reflect this.

Rename column for human-AI agreement when displaying AI grading stats

---

packages/session/src/index.test.ts

I don't love not knowing what's going on here, but I hate inactionable CI failures even more, so hopefully this is a reasonable compromise.

Configure flaky session test to retry a few times

---

.changeset/early-hats-thank.md
packages/preact-cjs/src/hooks.ts
packages/preact-cjs/src/jsx-runtime.ts

- Imports aren't handled correctly in ESM otherwise

Explicit re-exports for Preact

---

Makefile
docs/dev-guide/installingNative.md

Closes #12217; I suspect even though the bug itself is different, the root cause is fixed the same way.
Resolves a bug where the zygote cannot call subprocesses in a forked process. See https://github.com/astral-sh/python-build-standalone/issues/146#issuecomment-2981797869 for more context.

Update native install instructions for installing python

---

apps/grader-host/.mocharc.cjs
apps/workspace-host/.mocharc.cjs
packages/compiled-assets/.mocharc.cjs
packages/config/.mocharc.cjs
packages/csv/.mocharc.cjs
packages/docker-utils/.mocharc.cjs
packages/error/.mocharc.cjs
packages/eslint-plugin-prairielearn/.mocharc.cjs
packages/express-list-endpoints/.mocharc.cjs
packages/flash/.mocharc.cjs
packages/formatter/.mocharc.cjs
packages/html-ejs/.mocharc.cjs
packages/html/.mocharc.cjs
packages/markdown/.mocharc.cjs
packages/marked-mathjax/.mocharc.cjs
packages/migrations/.mocharc.cjs
packages/opentelemetry/.mocharc.cjs
packages/path-utils/.mocharc.cjs
packages/postgres/.mocharc.cjs
packages/run/.mocharc.cjs
packages/sanitize/.mocharc.cjs
packages/session/.mocharc.cjs
packages/zod/.mocharc.cjs

After the move to Vitest, these are unused. I missed these in the earlier conversion PRs.

Remove Mocha configs

---

apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.ts

When using the "Load from disk" button in dev mode, the log displays the results of all course syncs, separated by blank lines. To make the log slightly cleaner the last course is not followed by a blank line. However, when this process was updated to also sync courses in the DB that are not in the config file in #11200 and #11311, the identification of the "last course" was not properly updated, causing the blank line to be missing between the config courses and the DB-only courses.

Fix spacing between courses in load from disk log

---

apps/prairielearn/src/lib/editors.sql
apps/prairielearn/src/lib/editors.ts

Currently, when adding a new assessment using the UI, the assessment number defaults to 1, even if there is an assessment with that number in the set. This PR changes that default to the next numeric value based on assessments on the same set (e.g., if there is an assessment with number 3 in the same set, the default for the new assessment is 4). Assessments with non-integer or non-numeric values are ignored.
This also replaces the query used to retrieve all assessments with a call to the corresponding model function.

Use next available number as default when creating assessments

---

apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.html.ts

Per offline discussion, we want to emphasize that this is a very early preview and doesn't even really meet the bar for "beta".

Use "alpha preview" as label on AI question generation toggle

---

apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.sql

JOINs always need an ON clause.

Fix query to delete AI gradings

---

eslint.config.mjs

I commonly do this to omit a field from an object.
```ts
const foo = { a: 1, b: 2, c: 3, d: 4 }
const { a: _a, ...bar } = foo
```

Ignore vars that start with an underscore

---

apps/prairielearn/src/lib/preact.tsx

We can't rely on `Component.name` because for production builds, this is a mangled/minified value that isn't useful to us.

Require display name for hydrated Preact components

---

docs/dev-guide/installingNative.md

Running question `demo/annotated/LectureVelocity/1-Introduction` locally in an environment where latex is not installed caused a few issues with dependencies. While installing `texlive` was indeed required, it was not sufficient.

Update needed packages for Latex installation in documentation

---

docs/assessment/index.md

I was recently unsure whether students were really seeing the "invalid: why?" banners during `allowRealTimeGrading=False` exams.
After a discussion on `pl-help` we felt it might be nice to document that `parse` in fact happens as usual (as one would expect, but in contradiction to what some students told me happened in practice).
Here's such an edit.  Further edits/suggestions welcome!

Document that `parse` runs when real-time grading is disabled

---

apps/prairielearn/src/components/Navbar.html.ts

As noted in feedback about the new nav experience (https://github.com/PrairieLearn/PrairieLearn/discussions/12230#discussioncomment-13565161), it's impossible to tell what course instance you're looking at if the sidebar is collapsed. This PR adds a link to the navbar with the selected course instance ("SectionA" in the following screenshot):

Show selected course instance in navbar

---

apps/prairielearn/assets/scripts/instructorAiGenerateDraftsSampleQuestions.tsx
apps/prairielearn/src/ee/pages/instructorAiGenerateDrafts/SampleQuestionDemo.tsx

- Since Preact doesn't need to abide by the `React` className rules, I would prefer to use class instead.

Switch to class instead of className

---

apps/prairielearn/src/pages/instructorAssessmentInstance/instructorAssessmentInstance.html.ts

Resolves #12273. 
Added horizontal scrolling to assessment instance tables using the `table-responsive` Bootstrap class. 
Question: On smaller viewports, the percentage score and manual grading cell content is centered, while the other cells' content is not. This is not a regression. Is this okay, or would you like to also have these towards the top of their cells?

Add horizontal scroll to assessment instance tables

---

apps/prairielearn/src/lib/client/page-context.ts

- short_name is required on context that comes from res.locals

Narrow getCourseInstanceContext

---

apps/prairielearn/python/prairielearn/question_utils.py
apps/prairielearn/python/test/misc_test.py
docs/question/server.md
exampleCourse/questions/demo/autograder/python/fillBlankLastElement/info.json
exampleCourse/questions/demo/autograder/python/fillBlankLastElement/question.html
exampleCourse/questions/demo/autograder/python/fillBlankLastElement/server.py
exampleCourse/questions/demo/autograder/python/fillBlankLastElement/tests/ans.py
exampleCourse/questions/demo/autograder/python/fillBlankLastElement/tests/test.py

Includes a simplified interface for instructors to create files in the `parse()` function of a question. Also creates an example question using this method, as well as basic documentation for this use. Based on discussion in #12279.

Simplify creation of submitted files in parse function

---

packages/preact-cjs-compat/src/jsx-runtime.js

As reported by @reteps in https://github.com/PrairieLearn/PrairieLearn/pull/12211#issuecomment-3013862776. This all of course needs to be CJS.

Fix @prairielearn/preact-cjs-compat/jsx-runtime

---

pyproject.toml

Without this setting, editing a test.py file for a question in example course in VSCode would cause Pylance to complain about missing imports for autograder files.
I also removed the extra paths in the graders/* files since they don't get access to the prairielearn.py content, so using the default extra paths would not give a proper type check.
I know this is an imperfect solution, since it would not distinguish Python files for server.py and tests/ directory, or files used in other graders, but this is the most common autograder language in the example course. If you don't agree with this change please feel free to reject it.

Ignore pyright errors in test files in example course

---

apps/prairielearn/python/test/traverse_test.py

This is relevant for #12304, where this is causing a test failure.

Fix malformed HTML in Python test

---

.github/dependabot.yml

See the note, these changes are blocked on Sentry: https://github.com/getsentry/sentry-javascript/issues/15737 and https://github.com/getsentry/sentry-javascript/issues/15213

Ignore OpenTelemetry package upgrades

---

.github/dependabot.yml

See inline comment for details. This will prevent PRs like #12330 in the future.

Configure Dependabot to ignore React dependencies

---

docs/api.md

I'm throwing some ideas out there based on conversations from #12318.
Notable changes:
- Endpoints are grouped by resource.
- Endpoints include an HTTP method (currently all `GET`, but we'll have some `POST` ones too)
- The endpoint is documented in a code block to prevent strange wrapping.
- The descriptions are removed; I felt they were basically redundant given the names for the endpoints themselves.
Here's how things look now:

Rework API docs

---

eslint.config.mjs

As discussed in other PRs, we want rules to either be 'error' or 'off'.

Enable errors on all eslint-react rules

---

apps/prairielearn/src/pages/instructorRequestCourse/instructorRequestCourse.html.ts
docs/installing.md

As discussed on Slack. Adds language that encourages users to provide GitHub username in course requests when complex questions are planned.

Extend help text for GitHub username in request course page

---

apps/prairielearn/src/lib/externalGraderLocal.ts
apps/prairielearn/src/lib/externalGraderSqs.ts
apps/prairielearn/src/pages/publicAssessments/publicAssessments.ts
apps/prairielearn/src/schemas/jsonSchemas.ts
apps/prairielearn/src/tests/groupExamRolePermissions.test.ts
eslint.config.mjs

Most cases of duplicate imports are done by mistake, and we don't have any case of legitimate duplicate imports on purpose.
The rule also has an option for no duplicate exports. It would catch this case:
https://github.com/PrairieLearn/PrairieLearn/blob/365920394d8ac7d1e0e63439804b7e1ce9607ac3/packages/sentry/src/index.ts#L87-L136
If you're ok with either joining these or using an eslint-ignore comment I can enable this option.
This rule does not have autofix, but vscode is usually pretty good at reusing existing imports when possible, so autofix should not be a big deal. If autofix is required we can consider using [`import/no-duplicates` from the eslint-plugin-import plugin](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/no-duplicates.md) (which would require a …

Enable no-duplicate-imports eslint rule

---

.changeset/neat-cougars-grow.md
packages/compiled-assets/src/index.ts

While testing #12446 I noticed that preloads were using a bad URL like `http://localhost:3000/assets/build/public/build/chunk-NYHNC5ZV.js`, which would 404. This PR fixes them to use something like `http://localhost:3000/assets/build/chunk-NYHNC5ZV.js`, which is correct.

Fix paths for compiled asset preloads

---

apps/prairielearn/src/models/assessment-question.sql
apps/prairielearn/src/models/assessment-question.ts

Pulled out of https://github.com/PrairieLearn/PrairieLearn/pull/12402#discussion_r2223337873.
To test this, I added `.omit({ number: true })` to the schema and verified that things still built (and thus that nothing was relying on that column).
The `number` column will still exist on the resulting type, it just comes directly from the `assessment_questions` table.

Drop unused number column from assessment questions query

---

apps/prairielearn/src/tests/sync/assessmentsSync.test.ts

I witnessed some flaky tests on #12475 that I'm pretty sure were due to the un-awaited `features.enable('question-sharing');` call here. As it turns out, `question-sharing` doesn't even have to be enabled for this test to pass!

Fix flaky sync tests

---

apps/prairielearn/elements/pl-image-capture/pl-image-capture.js
apps/prairielearn/elements/pl-image-capture/pl-image-capture.mustache

Closes #12481. 
- When the user captures an image, they are no longer prompted to use or retake their image:
- The "Use webcam" and "Use phone" text updates to "Retake with webcam" and "Retake with phone" once an image is captured or if an image was previously captured.

Remove image capture confirmation phase

---

package.json
yarn.lock

#12493 left an unused version of `react-bootstrap` around.

Remove unused version of react-bootstrap

---

apps/prairielearn/src/tests/testAssessmentOrdering.test.sql
apps/prairielearn/src/tests/testAssessmentOrdering.test.ts

I noticed that we could remove this query (which already was poorly named) while looking at #12500.

Remove bespoke query from assessment ordering tests

---

packages/sentry/package.json
yarn.lock

This just came out! This shouldn't impact us.
- https://docs.sentry.io/platforms/javascript/migration/v9-to-v10/
- https://github.com/getsentry/sentry-javascript/releases/tag/10.0.0

Upgrade to Sentry 10

---

apps/prairielearn/src/pages/assessmentsSwitcher/assessmentsSwitcher.html.ts

The assessment switcher was using `plainUrlPrefix` in place of `urlPrefix`, which in the context of the issue badge component was an incorrect assumption. The issue badge assumes that the `urlPrefix` will have the instructor prefix for either the course or course instance, but the assessment switcher does not have that value in `urlPrefix`, since it does not lie under a route that includes that update. In this context the PR updates the call to the issue badge to include the `urlPrefix` in the format expected by that component.

Fix link to issues page in assessment switcher

---

packages/actions-report-image-sizes/src/index.ts

While reviewing #12501, I noticed we had some alternatives to using `console.*` directly.

Use GitHub Actions core API instead of console

---

apps/prairielearn/elements/pl-image-capture/pl-image-capture.css
apps/prairielearn/elements/pl-image-capture/pl-image-capture.js
apps/prairielearn/elements/pl-image-capture/pl-image-capture.mustache

Closes #12560
- Added rotate clockwise button for viewing submitted images captured with `pl-image-capture`

`pl-image-capture` Submitted image rotation

---

apps/prairielearn/src/executor.ts

#12501 brought this to my attention. IMO using something more low-level like this is more appropriate here.

Use process.stdout.write in executor

---

requirements.txt

Follow up to #12572 . This would _actually_ remove Sphinx as a dep.
In addition to the analysis done there, I also did the same for `recommonmark` with `rg 'import recommonmark' -g '*.py'`. There were no mentions.

Remove recommonmark

---

apps/prairielearn/src/ee/lib/lti13.sql
apps/prairielearn/src/ee/lib/lti13.ts
apps/prairielearn/src/pages/instructorGradebook/instructorGradebook.sql

Refactors the LTI 1.3 SQL to send the highest score of multiple-instance assessments, similar to code from the gradebook.
Refactored to return a row for each group-assessment-instance instead of looping inside of it like the previous version did. This removed a loop in the typescript, so it might be better reviewed with whitespace ignored.
The review discussion identified we could fix the SQL to choose the latest assessment instance with the highest score, so that change was pushed to the gradebook too.
Closes #12520

Refactor LTI 1.3 grade push to support multiple-instance assessments

---

apps/prairielearn/src/server.ts

Tiny drive-by improvement. This makes these consistent with the `public` pages, which use just a single middleware.

Simplify navbarType and urlPrefix middlewares

---

apps/prairielearn/src/components/QuestionContainer.tsx
apps/prairielearn/src/pages/instructorAssessmentGroups/instructorAssessmentGroups.html.tsx
apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.html.tsx
apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessment/assessment.html.tsx
apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/assessmentQuestion.html.tsx
apps/prairielearn/src/pages/instructorAssessmentQuestionStatistics/instructorAssessmentQuestionStatistics.html.tsx
apps/prairielearn/src/pages/instructorStudents/instructorStudents.html.tsx

As discussed in https://github.com/PrairieLearn/PrairieLearn/pull/12512#discussion_r2255404763, we are ensuring spacing between elements in the card header in all viewport sizes.

Add gap between elements of manual grading assessment question header

---

apps/prairielearn/src/sync/course-db.ts
apps/prairielearn/src/sync/syncFromDisk.ts
contrib/verify_course_repo.mjs

This makes all the sync output use the same consistent colors (the "bright" variants of red and yellow) that the server job logger is using:
https://github.com/PrairieLearn/PrairieLearn/blob/00b0752bfad75616ce066e375262e7782b7f65e4/apps/prairielearn/src/lib/server-jobs.ts#L102-L108

Use consistent colors for sync output

---

apps/prairielearn/src/sprocs/instance_questions_points_homework.sql

[As discussed on Slack](https://prairielearn.slack.com/archives/C266KEH9A/p1755700073734889). At some point in the past, the logic for the status was to retain it if the current variant did not achieve 100% score. This was mainly to ensure that, if an instance question was tagged as correct or complete, that an incorrect answer afterwards did not replace that status. However, in #12339 the grading status was re-introduced, causing the logic to check for previous status to fail.
This PR changes the logic to perform the full evaluation of what constitutes each status, instead of relying on the previous status. All relevant information was already precomputed anyway, so this has the secondary advantage of making the status logic easier to understand.

Fix instance question status logic for homeworks

---

apps/prairielearn/src/components/AssessmentNavigation.tsx
apps/prairielearn/src/components/PageLayout.tsx
apps/prairielearn/src/ee/routers/administratorInstitution.ts
apps/prairielearn/src/ee/routers/institutionAdmin.ts
apps/prairielearn/src/lib/features/index.ts
apps/prairielearn/src/middlewares/authzCourseOrInstance.ts
apps/prairielearn/src/pages/userSettings/userSettings.html.ts
apps/prairielearn/src/pages/userSettings/userSettings.ts
apps/prairielearn/src/server.ts

We'd like to turn the new navigation on globally before the semester begins at most universities. We've now been running it for the whole summer and have ironed out all the kinks that we're aware of.
This PR inverts the feature flags: enhanced navigation is now enabled by default but can be turned off for individual users, either by a global admin or if the `legacy-navigation-user-toggle` flag is enabled. We plan to only turn on the user toggle for specific users if it proves to be absolutely necessary (e.g. because there's a bug that's impacting their ability to access their course).
I'm thinking we'll leave these feature flags in place until the end of the year, at which point we can rip out both the old code and the feature flags.
This was written by GPT-5 with Copilot with some minor …

Replace enhanced-navigation feature flag with legacy-navigation

---

.github/workflows/test.yml

We somewhat regularly get transitive test failures. Many times they're simply retriable. One can do that from the GitHub UI, but that doesn't work if the failure of a given test shard causes the others to be canceled mid-execution.
Setting `fail-fast: false` ensures that other shards will continue executing even if one of them fails.
Docs for this option: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstrategyfail-fast

Disable fail-fast behavior for sharded tests

---

apps/prairielearn/src/tests/sprocs/ip_to_mode.test.ts

This test keeps timing out in CI, but we can't figure out why and can't reproduce the issue locally. I'm hoping these logs will give us some kind of indication as to where things are getting stuck.

Add logs to try to diagnose root cause of flaky test

---

vitest.config.ts

When running `yarn test` in the root of the repository, the following warnings were printed:
```
DEPRECATED  `poolMatchGlobs` is deprecated. Use `test.projects` to define different configurations instead.
DEPRECATED  "cache.dir" is deprecated, use Vite's "cacheDir" instead if you want to change the cache director. Note caches will be written to "cacheDir/vitest"
DEPRECATED  "environmentMatchGlobs" is deprecated. Use `test.projects` to define different configurations instead.
```
This is because `resolveConfig()` produced configs with those values.
~This PR changes things to directly import the config and instantiate it. This uses the raw config, which doesn't contain any deprecated properties.~
As @reteps pointed out, we no longer rely on `mode` being propagated down from the root config, …

Fix Vitest deprecation warnings

---

apps/prairielearn/elements/pl-order-blocks/order_blocks_options_parsing.py
testCourse/questions/orderBlocks/question.html

This is returning functionality lost in the refactor in #12441. 
If anyone has added comments nested inside a pl-block-group tag, those questions will throw an error on the current master, so this should be merged/deployed ASAP.

Add functionality back to ignore comments in pl-block-groups.

---

docs/python-grader/index.md

The wrong line was highlighted:
After:

Fix highlighted line in serverFilesCourse example for Python grader

---

.changeset/twelve-kids-fetch.md
apps/prairielearn/src/api/v1/endpoints/courseInstanceAssessmentInstances/index.ts
apps/prairielearn/src/middlewares/authnToken.ts
apps/prairielearn/src/middlewares/workspaceProxy.ts
apps/prairielearn/src/sync/fromDisk/courseInfo.ts
apps/prairielearn/src/tests/accessAsStudent.test.ts
apps/prairielearn/src/tests/courseElementExtension.test.sql
apps/prairielearn/src/tests/courseElementExtension.test.ts
apps/prairielearn/src/tests/gradingMethods.test.ts
apps/prairielearn/src/tests/groupGenerateAndDelete.test.ts
apps/prairielearn/src/tests/helperQuestion.sql
apps/prairielearn/src/tests/helperQuestion.ts
apps/prairielearn/src/tests/issues.test.ts
apps/prairielearn/src/tests/manualGrading.test.ts
apps/prairielearn/src/tests/questionSharing.test.ts
apps/prairielearn/src/tests/workspaceAccess.test.ts
packages/postgres/src/default-pool.ts
packages/postgres/src/pool.ts

- Cleans up some missed conversions to typed SQL
- Helpers pulled out of https://github.com/PrairieLearn/PrairieLearn/pull/12627

Add execute and executeRow helpers, cleanup SQL that isn't using models

---

apps/prairielearn/src/middlewares/authzAuthnHasCoursePreviewOrInstanceView.ts
apps/prairielearn/src/pages/instructorEffectiveUser/instructorEffectiveUser.ts

#12496 introduced a better view when an instructor with overrides accesses a page that the effective user/role does not have access to. However, this was applied to pages that have permissions based on the authenticated user, not the effective user; namely, the effective user customization page. This means, in practice, that once an instructor switches to student view (or customizes the course/course instance roles to None/None), they can no longer customize further (e.g., switch only one of the roles back to not None, or change the effective date). This PR restores the previous functionality for the effective user page to be based on the authenticated role, not the effective role. Both the page and the corresponding middleware are restored to their status before #12496, just adding a …

Restore ability for instructor in student view to customize overrides

---

apps/prairielearn/src/pages/enroll/enroll.ts

Tiny drive-by fix. This was the only thing that a grep for `locals\.__[^c]` yielded.

Fix unknown action error message

---

apps/prairielearn/src/lib/submissions-upload.sql
apps/prairielearn/src/lib/submissions-upload.ts

After using the assessment "Upload submissions" option, I noticed that I couldn't report an issue from the manual grading page because this check was failing:
https://github.com/PrairieLearn/PrairieLearn/blob/dd7f0eee78673b253cb866de099e313b5ac5fd1f/apps/prairielearn/src/models/variant.ts#L195
This PR sets the course instance ID so that our usual invariant will hold.

Set course instance ID when uploading submissions

---

apps/prairielearn/src/ee/auth/saml/router.ts

This came out of discussion with a university today where I was setting up SAML auth. They clarified that some users with various types of protections may be missing email addresses. I wanted to bake this into a comment so that we don't start failing to authenticate users that are missing an email in the future.

Clarify that SAML cannot require email addresses

---

apps/prairielearn/src/lib/groups.ts

In https://github.com/PrairieLearn/PrairieLearn/pull/12065, the ability to allow PL to generate group names was introduced. Originally this was based on the largest group number in the form of group[0-9]+, but this can cause problems if a user-defined group name has a number that is too big for an integer (e.g., a number with more than 10 digits). Increasing it to bigint only defers the problem.
This PR blocks user-specified group names to use this format, with a conservative limit of 7 digits to keep enough space for future system-generated group names to still be created using the same method.
Alternative to #12747. If this PR is merged then #12747 may become unnecessary (and vice-versa), though there's nothing blocking them from both being used.

Block user-specified group names with system-generated format

---

apps/prairielearn/src/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.ts

This PR fixes two independent issues:
- https://github.com/PrairieLearn/PrairieLearn/pull/12402 added a schema for the `group_configs` query that incorrectly used a `group_name` property; the column is named `name` in the query: https://github.com/PrairieLearn/PrairieLearn/blob/9bc08384fe83bb97b6175eed489fb97d9e2dc069/apps/prairielearn/src/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql#L366-L368
- #11300 added zone number/title to CSV exports, but didn't add it to the `ManualGradingSubmissionRowSchema` schema. This wasn't a problem, as the schema wasn't used in that particular query at the time. In this PR, I opted to actually use the schema, which required adding `zone_number` and `zone_title` to it.
I used Copilot with Claude Sonnet 4 to check for differences. I …

Fix Zod schemas for instructor assessment downloads

---

apps/prairielearn/src/tests/sprocs/ip_to_mode.test.ts

> That flaky test is really annoying... can we just increase the timeout?
> Definitely worth a try. It seems like it's taking just slightly more than 10s to complete? @nwalters512 
This tries to resolve the flaky test by increasing the timeout which has been causing failing CI status checks recently.
None

Increase timeout for ip_to_mode

---

apps/prairielearn/src/lib/client/page-context.test.ts
apps/prairielearn/src/lib/client/page-context.ts
apps/prairielearn/src/lib/features/index.ts
apps/prairielearn/src/lib/features/manager.ts
apps/prairielearn/src/pages/administratorFeatures/administratorFeatures.html.ts
apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.html.tsx
apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.ts

#12655 was merged, but it adds features that aren't available yet. I had a similar story in #12604, but that PR is still in review. In order to deploy correctly, we should gate #12655 behind a feature flag and local development. This will ensure that instructors don't get confused.
This PR does three things:
- Adds a feature flag (and fixes some associated typing)
- Uses that feature flag to hide the self-enrollment settings
- Uses the res.locals helpers for better type safety on this page.
AI tab completion was used when switching to the res.locals helpers.
I ran this locally. The first screenshot is before turning on the `enrollment-management` toggle. The second screenshot is after turning on the `enrollment-management` toggle.

Add enrollment management feature flag

---

.github/workflows/check.yml

Follow-up to #12783. The CI job that checks for changesets has a condition that it doesn't run if github.actor is dependabot. From what I could gather, github.actor is the user that triggered the action, which in the case of PRs is the user that pushed the latest commit. So this will likely not run when dependabot creates the PR, but might run if anyone adds a commit to a dependabot PR (e.g., yarn dedupe or merge with master). This PR changes the check for the PR author, not the commit author.

Fix check for pull request user in changeset CI

---

apps/prairielearn/src/ee/lib/billing/plan-grants.ts
apps/prairielearn/src/ee/middlewares/checkPlanGrantsForQuestion.ts

Peter called out in https://github.com/PrairieLearn/PrairieLearn/pull/12746#discussion_r2310539064 something that looked suspicious, and ended up being a pretty bad bug.
The `userHasRole` helper function expects an `authz_data` object:
https://github.com/PrairieLearn/PrairieLearn/blob/74e462e62ae98e4ff3cd2088de46ddb12496add7/apps/prairielearn/src/ee/lib/billing/plan-grants.ts#L23-L32
But we were passing the entire `res` object to it:
https://github.com/PrairieLearn/PrairieLearn/blob/74e462e62ae98e4ff3cd2088de46ddb12496add7/apps/prairielearn/src/ee/lib/billing/plan-grants.ts#L79
`res.course_role` is of course not `'None'`, so we'd incorrectly assume the user has some kind of permission in the course.
This could in theory break production courses that were relying on external grader or …

Fix checking of plan grants on student instance questions

---

apps/prairielearn/src/pages/home/home.html.tsx

Before this change:
After this change:
This was a regression from #12728.
This is only reproducible in production mode, where we're not rendering "pretty" JSX. The simplest way to reproduce this is to edit this to `pretty = false`:
https://github.com/PrairieLearn/PrairieLearn/blob/d6f506ef590d274fd6f80147c4994cd0abab7bd3/apps/prairielearn/src/lib/preact-html.ts#L24
Note that `renderHtmlDocument` unconditionally uses pretty rendering:
https://github.com/PrairieLearn/PrairieLearn/blob/d6f506ef590d274fd6f80147c4994cd0abab7bd3/apps/prairielearn/src/lib/preact.tsx#L39-L42
We should probably make `renderHtml` and that both behave the same way. I stand by the fact that "pretty" HTML is much easier to debug and that we should keep using it in dev mode, even if there are inconsistencies like this …

Fix course instance link spacing on homepage

---

.github/workflows/check.yml

The new CI test for the existence of changesets has a condition that causes it not to run for dependabot and "Version packages" PRs. For the latter, the check is done using the head_ref variable. The problem is that, in merge commit checks, this variable will have the branch name of the merge group, not the original branch, which causes it to fail in "Version packages" PRs (see https://github.com/PrairieLearn/PrairieLearn/actions/runs/17480060088/job/49648594444).
The PR is an attempt to change this check so that the identification of "Version packages" PRs is based on the head ref of the pull request, not the current branch.
I don't see a way to test this other than to merge it and then try to merge #12800.

Change condition for changeset check in version packages PR

---

.github/workflows/check.yml

Follow-up to #12822, which didn't resolve the issue. After changing ideas with @nwalters512, we decided that it should be ok to skip this test altogether in merge CI.
Again, we can only test it by merging it and then merging #12800.

Skip changeset check in merge CI

---

apps/prairielearn/assets/scripts/tsconfig.json

This bumps the version for `assets/scripts` from ES2021 to ES2022 so that I can use [`Intl.supportedValuesOf('timeZone')`](https://github.com/microsoft/TypeScript/issues/49231#issuecomment-1740901574) in #12835.
No testing done.

Upgrade from ES2021 to ES2022

---

apps/prairielearn/src/middlewares/clientFingerprint.ts
apps/prairielearn/src/pages/studentAssessment/studentAssessment.ts
apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.ts
apps/prairielearn/src/pages/studentAssessmentInstanceFile/studentAssessmentInstanceFile.ts
apps/prairielearn/src/pages/studentAssessments/studentAssessments.ts
apps/prairielearn/src/pages/studentGradebook/studentGradebook.ts
apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ts
apps/prairielearn/src/server.ts

An instructor recently noticed an assessment instance that had a high fingerprint change count (~35) despite only ever seeing one fingerprint in the logs. There are two related reasons for this:
- We're (accidentally IMO) including the fingerprint change tracking middleware on requests for things like `clientFileQuestion`. If those pages see a different fingerprint, they'd increment the change count and update the latest seen fingerprint ID, but there wouldn't be a corresponding log event. Normally this wouldn't be a problem. However...
- Safari (and possibly other browsers) seem to send reduced user agent strings on subrequests (e.g. loading images from `clientFilesQuestion`. For instance, a request for the main page might have `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) …

Fix inflated fingerprint change count

---

.changeset/dark-radios-punch.md
apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts
apps/prairielearn/src/ee/lib/billing/stripe.ts
packages/cache/src/index.ts

Noticed in #12818 that cache accesses are typed as any, which makes downstream types incorrect
None.

Require type parameter when fetching from the cache

---

apps/prairielearn/src/lib/externalGraderCommon.ts

I noticed this logic bug while working on something else. If the score provided passes `!Number.isNaN` (which is almost everything), it doesn't need to be a number.
No testing was done.
```ts
Number.isNaN('WHAT')
// false
```

Fix external grader accepting scores without number validation

---

apps/prairielearn/src/pages/home/home.html.tsx

This PR adds an empty state for PrairieLearn. It should let us remove the action header in future PR.
When we move the enrollment page to a modal, we will want to remove that action header.
This PR was initially created with this prompt:
> Add a new 'EmptyStateCards' component. It should render two cards side by side on desktop, and vertically on mobile. One card should be for if the user is a student, and the other if the user is an instructor. It should mirror the content of 'ActionsHeader' -- except it should make the call to action buttons a little larger with some nice bootstrap-icons.
See attached image:
To try yourself, set `hasCourses` to `false`.

Add new cards for empty state

---

apps/prairielearn/src/middlewares/AuthzAccessMismatch.tsx
apps/prairielearn/src/middlewares/authzHelper.tsx

One usage of `<AuthzAccessMismatch>` doesn't include an `errorExplanation`:
https://github.com/PrairieLearn/PrairieLearn/blob/1f29c43893bdf90db6b6194d81ae47e88063088c/apps/prairielearn/src/middlewares/authzHasCoursePreviewOrInstanceView.tsx#L44-L52
This PR ensures that one is always generated if one is defined.
- In one browser, auth as `student@example.com` and enroll in a course instance inthe test course.
- In a different browser, as an instructor, view the course instance as an instructor.
- Open the user menu in the upper-right and enter `student@example.com` as the UID.
On `master`, there's no error explanation given. On this branch, there is.

Always show error explanation for authz helper

---

apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ts

Closes #12935.
This regressed in #12582. After the first submission to a given question, the URL would be something like `.../instance_question/12345?variant_id=54321`. In this middleware, `req.url` would then be `/?variant_id=12345`, which would obviously pass the `!== '/'` check.
See https://github.com/PrairieLearn/PrairieLearn/pull/12582#discussion_r2258562258: over and over again we've proven to ourselves that using middleware for fingerprints is a Bad Idea. This PR is making the minimal change to get things working again until we can do a comprehensive refactor.
- Open a homework as a student; open a question.
- Make a submission; the URL should now have a `?variant_id=...` query param.
- Make another submission.
On `master`, only the first "view variant" and "submission" events will …

Fix fingerprint tracking when URL contains variant ID

---

apps/prairielearn/src/lib/editors.sql
apps/prairielearn/src/lib/editors.ts
apps/prairielearn/src/pages/instructorFileTransfer/instructorFileTransfer.ts

Extracted from #12981. These issues can be a problem if there are sync errors in the questions/assessments being copied.
To test, add a sync issue in a course (e.g., a question directory without info.json), then try to copy some question or course instance from the example course to the course that has the sync error. In master this will both cause a zod error and crash the server (since there are two redirects in the same response). In this PR it will cause the error page to properly be called with a reasonable error message.

Fix handling of question/instance copy in case of sync errors

---

apps/prairielearn/src/lib/score-upload.ts
eslint.config.mjs

The check for unused variables wasn't detecting lodash, since it technically starts with `_`. This updates the rules so that `_` is only used for ignoring if it is followed by any other character. `_` by itself is still allowed in arguments.
As I was updating this I also noticed that some comments in the eslint config file were in the wrong place. This also caused a few issues with the auto-fix for key ordering. The comments should now be in their proper places.
Eslint now detects an unused lodash import.

Update eslint rules to detect unused lodash

---

apps/prairielearn/src/components/RubricSettings.tsx

The current Preact component has width 4rem for point input, which seem too narrow for a point with two decimal places (or negative and one decimal place). I'm changing from 4rem to 5rem, which is also consistent with what the rubric editing modal uses. 
Now displays correctly without overflow.

Increase width for point input element

---

contrib/api_download.py

The use of sessions means that the same TCP connection can be reused across calls. Since all calls go to the same server, this is considerable. I haven't measured, but the performance improvement is noticeable, and the incidence of errors that interrupt the download is reduced considerably.
Functionally it remains the same, but code runs significantly faster for a large enough course instance.

Use request sessions in API download script

---

apps/prairielearn/src/components/RubricSettings.tsx
apps/prairielearn/src/lib/points.test.ts
apps/prairielearn/src/lib/points.ts

We recently got a report of an unexpected warning when configuring rubric points:
Floating point math is tricky! See #10928 for other examples of this.
This PR uses the approach suggested in https://github.com/PrairieLearn/PrairieLearn/issues/10928#issuecomment-2815809010 to avoid that.
Here's a somewhat simplified test case:
Here's how things look after this PR:

Handle floating-point error in rubric total points warning

---

apps/prairielearn/src/pages/instructorCourseAdminTopics/components/InstructorCourseAdminTopicsTable.tsx

This fixes a bug from #12292. The temporary ID generated was being generated too early and  was setting the same temporary ID for all new topics. This moves that function downstream so each new topic gets it's own temporary ID. 
To test the bug, on master try adding two new topics and then deleting one. Both will be deleted rather than the intended one to be deleted. Now trying the same process on this branch should result in only the desired target to be deleted.

Fix temporary ID generation for new topics

---

apps/prairielearn/src/lib/regrading.sql

Resolves #13020. Updates the status and requires_manual_grading flag so that, after a forced regrading to full score, grades are no longer listed as pending, as per discussion in the original issue.
Tested with the same sequence of events listed in the original issue.

Update status and manual grading flag on regrading process

---

apps/prairielearn/package.json
apps/prairielearn/src/cron/index.ts
apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts
apps/prairielearn/src/lib/assets.ts
apps/prairielearn/src/lib/chunks.ts
apps/prairielearn/src/lib/code-caller/code-caller-container.ts
apps/prairielearn/src/lib/code-caller/code-caller-native.ts
apps/prairielearn/src/lib/code-caller/index.ts
apps/prairielearn/src/lib/copy-content.ts
apps/prairielearn/src/lib/editors.ts
apps/prairielearn/src/lib/file-store.ts
apps/prairielearn/src/lib/github.ts
apps/prairielearn/src/lib/ltiOutcomes.ts
apps/prairielearn/src/lib/workspace.ts
apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ts
apps/prairielearn/src/pages/instructorCourseAdminTopics/components/InstructorCourseAdminTopicsTable.tsx
apps/prairielearn/src/pages/userSettings/userSettings.ts
apps/prairielearn/src/server.ts
apps/prairielearn/src/tests/courseEditor.test.ts
apps/prairielearn/src/tests/sync/assessmentsSync.test.ts
apps/prairielearn/src/tests/sync/courseInstancesSync.test.ts
apps/prairielearn/src/tests/sync/questionsSync.test.ts
apps/prairielearn/src/tests/testAssessmentOrdering.test.ts
apps/prairielearn/src/tests/workspaceHost.test.ts
apps/workspace-host/package.json
apps/workspace-host/src/interface.ts
contrib/dump-anonymize.mjs
yarn.lock

[`crypto.randomUUID()`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) is now considered baseline available in both Node and browsers. Let's use it!
This was implemented by GPT-5-Codex while I was doing other things. I did some manual cleanup to change it to use the `crypto` global.
None; let's let the test suite do its thing.

Use `crypto.randomUUID()` for UUID generation

---

docs/installing.md
docs/saml.md

`ca.prairielearn.com` is dead. This PR removes the remaining references to it.
None.

Remove references to ca.prairielearn.com

---

apps/prairielearn/src/lib/client/page-context.test.ts
apps/prairielearn/src/lib/client/safe-db-types.test.ts
apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/pages/instructorInstanceAdminSettings/components/SelfEnrollmentSettings.tsx
apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.html.tsx
apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.tsx
apps/prairielearn/src/pages/instructorInstanceAdminSettings/instructorInstanceAdminSettings.types.ts
apps/prairielearn/src/schemas/infoCourseInstance.ts
apps/prairielearn/src/schemas/schemas/infoCourseInstance.json
apps/prairielearn/src/sprocs/sync_course_instances.sql
apps/prairielearn/src/sync/course-db.ts
apps/prairielearn/src/sync/fromDisk/courseInstances.ts
apps/prairielearn/src/tests/sync/courseInstancesSync.test.ts

Originally we thought it'd be nice to persist settings values even when a given setting was disabled, which led to the introduction of this `self_enrollment_enabled_before_date_enabled` boolean (and the corresponding `selfEnrollment.beforeDateEnabled` value in JSON). However, after further discussion with @reteps and @mwest1066, we're going to stop storing these "enabled" booleans and stop trying to persist form state through an enabled -> disabled -> enabled transition.
Note that we still persist values during the lifetime of a page on the client, so if you set a "before date", disable self-enrollment, and then enable it again (all without refreshing the page), the "before date" won't be lost. It'll only potentially be lost on form submission if either self-enrollment as a whole is …

Begin work to remove self_enrollment_enabled_before_date_enabled

---

apps/prairielearn/src/lib/client/page-context.test.ts
apps/prairielearn/src/lib/client/safe-db-types.test.ts
apps/prairielearn/src/lib/db-types.ts
apps/prairielearn/src/migrations/20251007223022_course_instances__self_enrollment_enabled_before_date_enabled__drop.sql
database/tables/course_instances.pg

Continuation of #13063. Should not be merged until after that PR is deployed.
None.

Completely drop self_enrollment_enabled_before_date_enabled column
